### PR TITLE
Reduce shimming of GpuFlatMapGroupsInPandasExec [databricks]

### PR DESCRIPTION
**Pull request by gerashegalov**
Dedupe one of the results reported by #7860

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by gerashegalov** [comment]
CI indicates that the databricks side still needs work, marking as draft for now

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
