### PR TITLE
Updates for google analytics [skip ci]

### PR DESCRIPTION
**Pull request by Salonijain27**
Updates _config.yml file and adds _include/analytics.html file to set up google analytics tracker

### CODE REVIEW

**Review by sameerz — APPROVED** [review]

**Review by sameerz — DISMISSED** [review]

**Comment by sameerz** [comment]
build

**Comment by Salonijain27** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by sameerz — APPROVED** [review]

**Pull request merged**
