### PR TITLE
Init 23.02 changelog and move 22 changelog to archives [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

init changelog for 23.02 release, w/ 
```
GITHUB_TOKEN=<> scripts/generate-changelog --releases=23.02
```

move 22-related changelogs to doc archive folder w/
```
GITHUB_TOKEN=<> scripts/generate-changelog --releases=22.02,22.04,22.06,22.08,22.10,22.12 --path=docs/archives/CHANGELOG_22.02_to_22.12.md
```

for preview:
https://github.com/pxLi/spark-rapids/blob/ini-2302-changelog/CHANGELOG.md
https://github.com/pxLi/spark-rapids/blob/ini-2302-changelog/docs/archives/CHANGELOG_22.02_to_22.12.md

### CODE REVIEW

**Comment by sameerz** [comment]
Reviewed the changelog, made some changes to issues.

**Comment by pxLi** [comment]
build

**Review by revans2 — APPROVED** [review]
This looks fine to me. My only question wold be if we really want to only have 23.02 in the latest changelog. Or if we want to try and add a link to the older changelong. Both are minor and I am fine with it as is.

**Comment by pxLi** [comment]
> This looks fine to me. My only question wold be if we really want to only have 23.02 in the latest changelog. Or if we want to try and add a link to the older changelong. Both are minor and I am fine with it as is.

> My only question wold be if we really want to only have 23.02 in the latest changelog
I think we can keep more (like recent 3 releases) in latest changelog if needed, this time I make it separate is that 23.02 is the first version that we fully use github projectV2 https://github.com/orgs/NVIDIA/projects/4 to manage, so we could speed up the generation speed for if this release or later one only (w/o compatibility support for previous ones using projectV1)

 > Or if we want to try and add a link to the older changelong
We have the link at the bottom which link to the archived changelogs https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/CHANGELOG.md#older-releases

**Comment by pxLi** [comment]
Going to merge this one and will file an update before release candidate build

**Pull request merged**
