### PR TITLE
Fixing conflicts in branch-0.3

### PR DESCRIPTION
**Pull request by abellina**
Fixes some issues that could not be auto merged into 0.3.

Unit tests pass locally.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
NOTE: This must be merged with a merge-commit, not a squash commit!

**Comment by abellina** [comment]
The breaking change was a conflict where `GpuShuffleEnv.getDeviceStorage` was removed by @revans2 in a refactor. I had added an accessor next to it (for the shuffle timeout feature). So I just cleared that conflict, leaving the timeout accessor there.

**Comment by abellina** [comment]
build

**Pull request merged**
