### PR TITLE
Fix regression in AQE optimizations

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

Closes https://github.com/NVIDIA/spark-rapids/issues/4351

### CODE REVIEW

**Comment by andygrove** [comment]
build

**Comment by jlowe** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by andygrove** [comment]
Sign-off commit was intended for a different PR. I will start the build again.

**Comment by andygrove** [comment]
build

**Pull request merged**
