### PR TITLE
Optimize and fix Api validation script

### PR DESCRIPTION
**Pull request by nartal1**
Signed-off-by: Niranjan Artal <nartal@nvidia.com>

This closes https://github.com/NVIDIA/spark-rapids/issues/240.
Updated the Api validation script to fix package names after shim layer was introduced. As of now the script audits Spark 3.0 version.  Have filed follow-on issue https://github.com/NVIDIA/spark-rapids/issues/465 to support multiple Spark versions.

### CODE REVIEW

**Comment by nartal1** [comment]
build

**Comment by tgravescs** [comment]
can we have the title and description state which script is being updated?

**Comment by nartal1** [comment]
@tgravescs Sorry it was too vague. Have updated the title and description. Please take another look.

**Comment by razajafri** [comment]
Looks good

**Pull request merged**
