### PR TITLE
Init 23.12 changelog [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
init changelog 23.12,

1. init changelog with
```
GITHUB_TOKEN=<> scripts/generate-changelog --releases=23.10,23.12
```
2. move 23.08 content to archives folder

### CODE REVIEW

**Comment by sameerz** [comment]
I reviewed and made some label changes.

**Comment by pxLi** [comment]
build

**Review by NvTimLiu — APPROVED** [review]

**Comment by pxLi** [comment]
Going to merge this one to start building RC 
If any following updates, we could re-generate and merge to main without re-build release candidate as no code change.

**Comment by pxLi** [comment]
build

**Review by NvTimLiu — APPROVED** [review]

**Review by YanxuanLiu — APPROVED** [review]

**Pull request merged**
