### PR TITLE
Merge branch-24.08 into main [skip ci]

### PR DESCRIPTION
**Pull request by nvauto**
Change version to 24.08.0

Note: merge this PR with **Create a merge commit to merge**

### CODE REVIEW

**Comment by NvTimLiu** [comment]
This PR is for in-advance review, will up-merge the following changes if needed.

**Review by pxLi — APPROVED** [review]

**Comment by nvauto** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
internal artifactory is suffering from unknown issue. let [skip ci] to avoid docker build&push which would keep blocking the CI build

**Comment by pxLi** [comment]
build

**Pull request merged**
