### PR TITLE
Fix Spark 340 build error due to change in KeyGroupedPartitioning

### LINKED ISSUE #7537: [AUDIT] [SPARK-42039][SQL] SPJ: Remove Option in KeyGroupedPartitioning#partitionValuesOpt
**Describe the bug**
Spark 340 compile failed due to this commit:
https://github.com/apache/spark/pull/39540

**Steps/Code to reproduce bug**
Compile error:
```
[ERROR] [Error] spark-rapids/sql-plugin/src/main/
330+/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala:83: 
value partitionValuesOpt is not a member of 
org.apache.spark.sql.catalyst.plans.physical.KeyGroupedPartitioning
```

### PR DESCRIPTION
**Pull request by res-life**
Closes #7537 

The Spark change is a refactor, so simply change the function name according to the change.

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Review by nartal1 — APPROVED** [review]
LGTM

**Review by mythrocks — APPROVED** [review]
@res-life, thank you for the fix. LGTM.

**Pull request merged**
