### PR TITLE
XFail pos_explode tests until final fix can be put in

### PR DESCRIPTION
**Pull request by revans2**
This is here to mark some tests as xfail until #953 can be addressed

### CODE REVIEW

**Comment by revans2** [comment]
not going to do a build until we get the precommit build passing again.

**Review by abellina — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by jlowe** [comment]
The CI failed again with this:
```
10:50:01  [32mGpuDeviceManagerSuite:[0m
10:50:02  [31m- RMM pool limit *** FAILED ***[0m
10:50:02  [31m  java.lang.UnsupportedOperationException: Not allowed to modify active Spark session.[0m
10:50:02  [31m  at org.apache.spark.sql.SparkSession$.clearActiveSession(SparkSession.scala:1011)[0m
10:50:02  [31m  at com.nvidia.spark.rapids.TestUtils$.withGpuSparkSession(TestUtils.scala:137)[0m
10:50:02  [31m  at com.nvidia.spark.rapids.GpuDeviceManagerSuite.$anonfun$new$1(GpuDeviceManagerSuite.scala:40)[0m
10:50:02  [31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m
```
I think this needs to merge up to the latest on branch-0.3 to get the fix.

**Comment by revans2** [comment]
build

**Pull request merged**
