### PR TITLE
Use parse_url kernel for QUERY parsing

### PR DESCRIPTION
**Pull request by thirtiseven**
This PR adds plugin support for QUERY parsing in parse_url (returning the entire query).

Contributes to https://github.com/NVIDIA/spark-rapids/issues/8963

Depends on: https://github.com/NVIDIA/spark-rapids-jni/pull/1652

All cases from the kaggle dataset passed.

**Perf test results**

dataset: kaggle dataset repeated 10 times.

```scala
spark.time(df.selectExpr("COUNT(parse_url(url, 'QUERY')) as pr1", "COUNT(parse_url(url, 'QUERY')) as pr2", "COUNT(parse_url(url, 'QUERY')) as pr3", "COUNT(parse_url(url, 'QUERY')) as pr4", "COUNT(parse_url(url, 'QUERY')) as pr5", "COUNT(parse_url(url, 'QUERY')) as pr6", "COUNT(parse_url(url, 'QUERY')) as pr7", "COUNT(parse_url(url, 'QUERY')) as pr8", "COUNT(parse_url(url, 'QUERY')) as pr9", "COUNT(parse_url(url, 'QUERY')) as pr0").show())
```

 | GPU Time (ms) | CPU Time (ms) | Speed up |
|-|-|-|
| 966 | 14,583 | 15.09x |

### CODE REVIEW

**Comment by thirtiseven** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by revans2 — CHANGES_REQUESTED** [review]
Sorry I did some manual testing and this falls over badly if I include the third parameter for query.

```
spark.time(spark.range(0, 300000000L, 1, 24).selectExpr("CONCAT('http://a.com?foo=', CAST(id AS STRING)) as h").selectExpr("SUM(length(parse_url(h, 'QUERY', 'foo'))) as q").show())
```

```
Caused by: java.lang.UnsupportedOperationException: parse_url(input[0, string, false](h#340), QUERY, foo) is not supported partToExtract=QUERY. Only PROTOCOL and HOST are supported
  at org.apache.spark.sql.rapids.GpuParseUrl.doColumnar(GpuParseUrl.scala:85)
  at org.apache.spark.sql.rapids.GpuParseUrl.$anonfun$columnarEval$5(GpuParseUrl.scala:111)
  at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:74)
  at org.apache.spark.sql.rapids.GpuParseUrl.$anonfun$columnarEval$4(GpuParseUrl.scala:108)
  at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:74)
  at org.apache.spark.sql.rapids.GpuParseUrl.$anonfun$columnarEval$3(GpuParseUrl.scala:107)
  at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:74)
```

Can we please add tests that verify that we fall back to the CPU if we see the extra parameter for 'QUERY'?

**Comment by thirtiseven** [comment]
> Sorry I did some manual testing and this falls over badly if I include the third parameter for query.
> 
> ```
> spark.time(spark.range(0, 300000000L, 1, 24).selectExpr("CONCAT('http://a.com?foo=', CAST(id AS STRING)) as h").selectExpr("SUM(length(parse_url(h, 'QUERY', 'foo'))) as q").show())
> ```
> 
> ```
> Caused by: java.lang.UnsupportedOperationException: parse_url(input[0, string, false](h#340), QUERY, foo) is not supported partToExtract=QUERY. Only PROTOCOL and HOST are supported
>   at org.apache.spark.sql.rapids.GpuParseUrl.doColumnar(GpuParseUrl.scala:85)
>   at org.apache.spark.sql.rapids.GpuParseUrl.$anonfun$columnarEval$5(GpuParseUrl.scala:111)
>   at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:74)
>   at org.apache.spark.sql.rapids.GpuParseUrl.$anonfun$columnarEval$4(GpuParseUrl.scala:108)
>   at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:74)
>   at org.apache.spark.sql.rapids.GpuParseUrl.$anonfun$columnarEval$3(GpuParseUrl.scala:107)
>   at com.nvidia.spark.rapids.Arm$.withResourceIfAllowed(Arm.scala:74)
> ```
> 
> Can we please add tests that verify that we fall back to the CPU if we see the extra parameter for 'QUERY'?

Done, thanks!

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Pull request merged**
