### PR TITLE
Skip test_hash_groupby_collect_partial_replace_with_distinct_fallback for #7092 [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

workaround for #7092 

~~lower the parallelism while we are still investigating the issue~~
turns out test_hash_groupby_collect_partial_replace_with_distinct_fallback is the case that actually fail the executor, skip for now.

also found new string_test error and filed #7104 to xfail for now

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
the case could also hanging there and timeout the test, xfail does not workaround in this case
lets skip the test for now

**Comment by pxLi** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Comment by pxLi** [comment]
also found new case error when run premerge filed https://github.com/NVIDIA/spark-rapids/issues/7104 to xfail first

**Comment by pxLi** [comment]
build

**Review by zhanga5 — APPROVED** [review]

**Pull request merged**
