### PR TITLE
[WIP] Add EEP Spark shim layer

### PR DESCRIPTION
**Pull request by ekrivokonmapr**
Adding the EEP Spark shim layer to support the rapids plugin for EEP-version of spark starting from Spark-3.1.2.

### CODE REVIEW

**Comment by tgravescs** [comment]
thanks for the contribution, what is EEP? I'm inferring its MAPR product but can you provide some more details and possibly links to find more info?

Also I assume the jars are all public to be able to build?  I see you added             <url>http://repository.mapr.com/maven/</url> as repo but want to double check

**Comment by Agirish** [comment]
@tgravescs EEP stands for Ezmeral Ecosystem Pack. It's an upcoming rebrand of MapR Ecosystem Pack (MEP). 
Doc links: 
MEP - https://docs.datafabric.hpe.com/62/InteropMatrix/Component_versions_all_MEPs.html
Ezmeral - https://www.hpe.com/us/en/software/data-fabric.html

**Comment by ekrivokonmapr** [comment]
Thanks for the response.
Currently there are no Spark-3.1.2 jars in http://repository.mapr.com/maven/ and work on this PR is in progress.

**Comment by jlowe** [comment]
Thanks for the contribution, @ekrivokonmapr!  You will need to signoff on the commits per [the instructions in the contributor's guide](https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/CONTRIBUTING.md#sign-your-work).  At least one commit in the PR needs a signoff.

Can you elaborate a bit more in the description what was needed for this shim to help reviewers?  Is this just a copy of the 3.1.2 shim with a different version number, or were there additional changes that were necessary?  If there were EEP-specific changes beyond the version number, it would be good to document those here to help focus the review on that new code as well as provide a reference for future maintainers.

> Currently there are no Spark-3.1.2 jars in http://repository.mapr.com/maven/ and work on this PR is in progress.

Converting this PR to a draft until the requisite jars are made public and this is ready to go.

**Comment by razajafri** [comment]
I would like to echo @jlowe 's comment about perhaps adding to the description if possible to have a more focused review. That will also expedite the review process. 

In the meanwhile, can you answer why you need a separate copy of the `ParquetCachedBatchSerializer`? Have you made changes to it?

**Comment by sameerz** [comment]
Updating base branch while this PR is under discussion.

**Comment by sameerz** [comment]
As we've entered burndown for 21.12, retargeting to 22.02.

**Comment by sameerz** [comment]
I believe Ezmeral already implemented a shim internally per https://www.hpe.com/psnow/doc/a00118445enw?jumpId=in_videogallery_6c5236cc-41e9-4a3c-b3b3-a18ffbe9a219_gaiw .  If we can help you upgrade your shim to a newer version please let us know (open an issue).  Closing this PR for now.

**Pull request closed without merging**
