### PR TITLE
Merge 22.08 to main

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge branch 'branch-22.08' into main, prepare for v22.08.0 release

Merge this PR with "Create a merge request" instead of squash merge

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
Please help review the commit history in advance, thanks

We will merge https://github.com/NVIDIA/spark-rapids/pull/6348 when the jni is released and do a final update of changelog later

**Review by jlowe — COMMENTED** [review]
What's here so far looks good to me.  Will #6348 be added to this PR when it is merged to 22.08 or will there be a separate PR for that?

**Comment by pxLi** [comment]
> What's here so far looks good to me. Will #6348 be added to this PR when it is merged to 22.08 or will there be a separate PR for that?

cudf has tagged v22.08.00, we are working on releasing cudf jni and plugin jni. I think we can use the same PR

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]
LGTM

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
