### PR TITLE
Do not replace TableCacheQueryStageExec

### PR DESCRIPTION
**Pull request by andygrove**
Spark 3.5.0 adds a new TableCacheQueryStageExec. We should never try and replace a query stage exec, so this PR adds a `neverReplace` rule for this new exec.

I manually tested with the example in https://issues.apache.org/jira/browse/SPARK-45592 and it stops the following warning from being displayed:

```
! <TableCacheQueryStageExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.adaptive.TableCacheQueryStageExec
```

### CODE REVIEW

**Review by gerashegalov — APPROVED** [review]
LGTM

**Review by razajafri — APPROVED** [review]
LGTM

**Comment by razajafri** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Pull request merged**
