### PR TITLE
Merge branch 'branch-23.04' to main

### PR DESCRIPTION
**Pull request by NvTimLiu**
As the title,

Note : merge this PR with `Create a merge commit`

### CODE REVIEW

**Comment by pxLi** [comment]
wait for #8109 to re-trigger CI.

Please help review the commit history, thank!

**Review by jlowe — COMMENTED** [review]
This is building with snapshot dependency, spark-rapids-jni in this case, and that's something a mainline build should never do.  It's missing #8109.

**Comment by NvTimLiu** [comment]
> This is building with snapshot dependency, spark-rapids-jni in this case, and that's something a mainline build should never do. It's missing #8109.

Yes, this PR is for commit history reviewing, and we will do a final update to include https://github.com/NVIDIA/spark-rapids/pull/8109 https://github.com/NVIDIA/spark-rapids/pull/8092 before RC build

**Comment by NvTimLiu** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
