### PR TITLE
Add support for Spark 3.5.3 [databricks]

### LINKED ISSUE #11419: [FEA] Support Spark 3.5.3 release
**Is your feature request related to a problem? Please describe.**

Apache Spark is going to do a 3.5.3 release to fix correctness bug -  https://github.com/apache/spark/pull/43938

we should add support for it when its available.

### PR DESCRIPTION
**Pull request by razajafri**
This PR adds support for Spark 3.5.3 

fixes #11419

### CODE REVIEW

**Review by jlowe — COMMENTED** [review]
Need to generate scala2.13 pom files

**Review by jlowe — DISMISSED** [review]

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
This will have to wait until the private repo is merged

**Comment by razajafri** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by jlowe — COMMENTED** [review]
CI failed, looks like RapidsErrorUtils340PlusBase is missing 353 shim

**Review by jlowe — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Pull request merged**
