### PR TITLE
Update rapids JNI and private dependency to 24.08.0

### PR DESCRIPTION
**Pull request by nvauto**
Wait for the pre-merge CI job to SUCCEED

### CODE REVIEW

**Comment by NvTimLiu** [comment]
Draft this PR until rapids JNI and private v24.08.0 dependency jars get released

**Review by pxLi — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
please ignore spark400 failure, it will be taken care of in 24.10 thanks

**Comment by NvTimLiu** [comment]
> please ignore spark400 failure, it will be taken care of in 24.10 thanks

Sounds good to me, let me merge it

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
