### PR TITLE
Remove unsupported format when converting dates/timestamps to strings [skip ci]

### PR DESCRIPTION
**Pull request by ttnghia**
This fixes the documentation to remove the `SSS` format when converting dates/timestamps to strings, which has already been implemented in https://github.com/NVIDIA/spark-rapids/pull/6271.

Should be merged into 22.10 release since #6271 was merged into it.

### CODE REVIEW

**Comment by sameerz** [comment]
I think this is minor enough that it can go into 22.12.

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
Change looks fine to me, but if @sameerz wants it in 22.12 we can point the PR to that branch instead.

**Comment by ttnghia** [comment]
I forgot to create a new branch on my local repo so this PR was created from my local 22.10 branch. But merging just one file from it should not be a problem.

**Comment by ttnghia** [comment]
build

**Pull request merged**
