### PR TITLE
Fix merge conflict with 22.08

### PR DESCRIPTION
**Pull request by jlowe**
Fixes a small conflict in spark2-sql-plugin's RapidsConf as noted by #6245.

**NOTE: This must be merged as a merge commit, not squashed!**

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by tgravescs — DISMISSED** [review]

**Comment by jlowe** [comment]
branch-22.10 is currently not buildable due to an incompatibility between #6110 and #6161, the latter was auto-bot merged from 22.08.  Will add a fix to this PR.

**Comment by jlowe** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by jlowe** [comment]
CI is failing due to #6243

**Review by revans2 — APPROVED** [review]

**Comment by anthony-chang** [comment]
build

**Comment by jlowe** [comment]
Updated to add more commits that were pushed to 22.08 today.  Those came in clean.

**Comment by jlowe** [comment]
build

**Review by pxLi — APPROVED** [review]
LGTM. Going to merge this as a merge commit

**Pull request merged**
