### PR TITLE
Fix merge conflict with branch-21.10

### PR DESCRIPTION
**Pull request by jlowe**
Resolves the merge conflict reported at #3721.  Conflict was a deletion of `totalTime` metric in `GpuBroadcastToCpuExec`.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by tgravescs** [comment]
build

**Comment by jlowe** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
sorry I shouldn't have squashed that commit.

**Comment by jlowe** [comment]
Working on a new PR to fix.

**Pull request merged**
