### PR TITLE
[auto-merge] branch-0.3 to branch-0.4 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
auto-merge triggered by github actions on `branch-0.3` to create a PR keeping `branch-0.4` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.

### CODE REVIEW

**Comment by nvauto** [comment]
**FAILURE** - Unable to auto-merge. Manual operation is required.
```
{'message': 'Pull Request is not mergeable', 'documentation_url': 'https://docs.github.com/rest/reference/pulls#merge-a-pull-request'}
```

**Comment by jlowe** [comment]
I don't see any merge conflict here, it merges cleanly.  As such I'm going to merge (not squash!) this.

@pxLi please investigate why the automerge workflow failed in this instance.

**Comment by pxLi** [comment]
> I don't see any merge conflict here, it merges cleanly. As such I'm going to merge (not squash!) this.
> 
> @pxLi please investigate why the automerge workflow failed in this instance.

yeah, looks like https://github.com/NVIDIA/spark-rapids/runs/1527272657 failed the auto-merge. I will take a look later

**Comment by pxLi** [comment]
@jlowe I found the what happened here, so this PR was created w/ one sha, and as expected it would wait for 10s to auto-merge the PR. and https://github.com/NVIDIA/spark-rapids/pull/1342 was closed right inside the 10s period and updated this PR's sha value, so the auto-merge fail to merge this one w/ previous sha. I could remove [sleep 10s](https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/.github/workflows/auto-merge/automerge#L118) to get an instant auto-merge here, any idea?

**Pull request merged**
