### PR TITLE
Add BinaryType support to operations that already support arrays

### LINKED ISSUE #6267: [FEA] Support ShuffleExchangeExec with BinaryType as input and output
I wish we can support ShuffleExchangeExec with BinaryType as input and output.

This can be triggered when you do a percentile in a group by context.
Eg:
```
select ss_cdemo_sk,percentile(ss_wholesale_cost,0.1) from tpcds.store_sales group by ss_cdemo_sk limit 10;
```

The not-supported-message is:

```
    !Exec <ShuffleExchangeExec> cannot run on GPU because unsupported data types in output: BinaryType [buf#57]; Columnar exchange without columnar children is inefficient; unsupported data types in input: BinaryType [buf#57]
      @Partitioning <HashPartitioning> could run on GPU
        @Expression <AttributeReference> ss_cdemo_sk#32 could run on GPU
      !Exec <ObjectHashAggregateExec> cannot run on GPU because not all expressions can be replaced
        @Expression <AttributeReference> ss_cdemo_sk#32 could run on GPU
        @Expression <AggregateExpression> partial_percentile(ss_wholesale_cost#39, 0.1, 1, 0, 0) could run on GPU
          ! <Percentile> percentile(ss_wholesale_cost#39, 0.1, 1, 0, 0) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.aggregate.Percentile
```

As you can see, besides the `Percentile` related messages, it also generates the `ShuffleExchangeExec` related message which has BinaryType as input and output.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #6267.  Adds support for BinaryType to many expressions and operations by simply allowing the type check to pass and adding tests to verify the functionality.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — COMMENTED** [review]
This looks good to me. We might want to file a follow on issue to go back through the operators and see what else we are missing on Binary support and see how to add them in.

**Review by revans2 — DISMISSED** [review]

**Comment by jlowe** [comment]
> This looks good to me. We might want to file a follow on issue to go back through the operators and see what else we are missing on Binary support and see how to add them in.

Filed #6299 as a followup.

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
