### PR TITLE
Update rapids plugin version to 21.06.2 [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
1, Update rapids plugin version to 21.06.2-SNAPSHOT in pom.xml files
2, Update rapids plugin version to 21.06.2 in doc files

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Review by zhanga5 — DISMISSED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
missed udf-examples/src/main/cpp/CMakeLists.txt

**Review by GaryShen2008 — APPROVED** [review]

**Review by pxLi — CHANGES_REQUESTED** [review]
missed udf-examples/src/main/cpp/CMakeLists.txt
tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala
tools/README.md
changes comparing to #3123

**Review by pxLi — DISMISSED** [review]

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]

**Pull request merged**
