### PR TITLE
Improve JSON and CSV support for boolean values

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

Closes https://github.com/NVIDIA/spark-rapids/issues/2071 and https://github.com/NVIDIA/spark-rapids/issues/4763

This PR improves support for reading boolean values from JSON and CSV by reading the values as strings in cuDF and then applying a CAST operation to parse the string as boolean with compatibility with Spark.

This does not work correctly for JSON where there are strings as input (such as `"true"` rather than `true`) and there is a follow-on issue https://github.com/NVIDIA/spark-rapids/issues/4779 to fix this

### CODE REVIEW

**Review by revans2 — DISMISSED** [review]

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
I found some edge cases that are not handled correctly so I am moving this back to draft / WIP for now

**Comment by andygrove** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
