### PR TITLE
Append new authorized user to blossom-ci whitelist [skip ci]

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: Yuan Li yuali@nvidia.com

Append new authorized user to blossom-ci whitelist

### CODE REVIEW

**Comment by pxLi** [comment]
why we have 8 commits here, can you rebase you commit to upstream? thx~

**Comment by jlowe** [comment]
> why we have 8 commits here, can you rebase you commit to upstream?

Curious, what's the concern with the number of commits here?  We normally squash commits when merging to the regular development branches to avoid the concerns with commit count on a PR.

**Comment by nvliyuan** [comment]
I mis-involved other pr's commits into this pr. I just create a new pr and it is merged(https://github.com/NVIDIA/spark-rapids/pull/2837), so I closed this pr.

**Comment by jlowe** [comment]
Ah, got it, there were _unrelated_ commits on the PR.  Makes sense, thanks for the clarification, @nvliyuan!

**Pull request closed without merging**
