### PR TITLE
Add databricks 10.4 build in pre-merge [databricks]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
Abort current pre-merge run. 
Need to update the Jenkinsfile to add 10.4 stage instead of replace. After merge, please trigger test build to verify change

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Pull request merged**
