### PR TITLE
Add in support for zorder operators on databricks [databricks]

### PR DESCRIPTION
**Pull request by revans2**
This adds in support to accelerate the zorder optimization on databricks.  The implementation is different from open source deltalake.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
Something changed with databricks and the test started to fail because some metadata operations was still on the CPU. I'll try to update the tests.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe please take another look I had to modify the test.

**Review by jlowe — APPROVED** [review]

**Pull request merged**
