### PR TITLE
Fix nullability issues for some decimal operations[databricks]

### LINKED ISSUE #9108: [BUG] nullability on some decimal operations is wrong
**Describe the bug**
There are some expressions where we set nullable incorrectly.

`CheckOverflow` always has it set to true, but we have it set to `child.nullable` an inherited by unary.

In https://issues.apache.org/jira/browse/SPARK-39316 which made some changes to how arithmetic operations are calculated for decimal in changed the default nullable implementation for BinaryArithmatic

https://github.com/apache/spark/blob/ce12f6dbad2d713c6a2a52ac36d1f7a910399ad4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/arithmetic.scala#L253-L263

Ours no longer matches this and still does `left.nullable || right.nullable`. This can result in crashes if we do a ColumnarToRow operation and it is not expected to be null.

We should probably audit this for all expressions and see if we are setting it correctly.

**Steps/Code to reproduce bug**
The good news is that it is kind of hard to reproduce. You need to overflow the decimal operation on one of these, and have the input marked as not-nullable. But Spark tends to mark all inputs as nullable unless it is a constant or comes from `spark.range` so it would be good to come up with a way to test this generally, but I don't know of one right now.

### PR DESCRIPTION
**Pull request by firestarman**
fixes #9108 

We need to audit the correctness of nullability for at least the following 7 binary operators due to the Spark change [SPARK-39316](https://issues.apache.org/jira/browse/SPARK-39316).

1.   Add
2.   Subtract
3.   Multiply
4.   Divide
5.   IntegralDivide
6.   Remainder
7.   Pmod 

But in fact, only the first 3 ones (`Add`, `Sbutract` and `Multiply`) are affected, and the `nullable` of the other 4 operators are always `true` regardless of this Spark change. 

Therefore, this PR fixes the nullability of GPU version of `Add`, `Subtract` and `Multiply` for Spark 340+. And it also fixes the nullablity for `GpuCheckOverflow` and `GpuDecimalMultiply`.

Main change of this PR:
- Override the `nullable` for `GpuCheckOverflow`.
- In the shim class `CudfBinaryArithmetic`, add an abstarct field `failOnError`, and override the `nullable` method for all the shims to align with different Spark versions.
- Removed the `nullable` implementation from `GpuDecimalMultiplyBase`. And override the `nullable` in `GpuDecimalMultiply` individually for different shims.
- Some refactor on the `failOnError`.

- [x] add tests

### CODE REVIEW

**Comment by firestarman** [comment]
It is not easy to test this, tried several cases, but not work.

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
build

**Review by revans2 — COMMENTED** [review]
This looks good, but I would like to see some tests added to cover these cases. I was able to get some data corruption to happen. See: https://github.com/NVIDIA/spark-rapids/issues/9108#issuecomment-1790779490

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
>This looks good, but I would like to see some tests added to cover these cases. I was able to get some data corruption to happen. See: https://github.com/NVIDIA/spark-rapids/issues/9108#issuecomment-1790779490

I'v added your cases as tests.

**Review by revans2 — APPROVED** [review]

**Pull request merged**
