### PR TITLE
Update version to 24.06.1-SNAPSHOT [databricks]

### PR DESCRIPTION
**Pull request by nvauto**
Wait for the pre-merge CI job to SUCCEED

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Review by GaryShen2008 — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
failed fastparquet cases only which has been fixed in 24.08

**Comment by pxLi** [comment]
@NvTimLiu this may fail following the release test, I would recommend to 
cherry-pick the WAR https://github.com/NVIDIA/spark-rapids/pull/11072/files only

**Review by pxLi — CHANGES_REQUESTED** [review]
please include fastparquet workaround to pass the cases on DB thanks

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
Cherry-picked 11138

**Review by pxLi — APPROVED** [review]
thanks!

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
