### PR TITLE
Disable 340 for premerge and nightly

### PR DESCRIPTION
**Pull request by firestarman**
Spark 340 has removed the `AnsiCast` by https://github.com/apache/spark/commit/5f0bae7af3c39919efd4bf68b1b6f467f0e1b20b, which will probably lead to much work in plugin.
So disable 340 for premerge and nightly temporarily. But need to add it back when the issue #5688 is fixed.

### CODE REVIEW

**Review by pxLi — APPROVED** [review]
+1 for CI

**Review by res-life — APPROVED** [review]
LGTM

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
