### PR TITLE
[DOC] update release version from v2308.0 to 2308.1 [skip ci]

### PR DESCRIPTION
**Pull request by nvliyuan**
update release version from v2308.0 to 2308.1

### CODE REVIEW

**Comment by pxLi** [comment]
can you also help update https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/docs/get-started/getting-started-databricks.md#start-a-databricks-cluster in this change? thanks

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Comment by nvliyuan** [comment]
build

**Pull request merged**
