### PR TITLE
Support map type in case when expression

### LINKED ISSUE #3139: [BUG] case when on some nested types can produce a crash
**Describe the bug**
```
Caused by: ai.rapids.cudf.CudfException: cuDF failure at: /home/roberte/src/cudf/cpp/src/reshape/interleave_columns.cu:38: Called `interleave_columns` on none-supported data type.
E                   	at ai.rapids.cudf.ColumnVector.makeList(Native Method)
E                   	at ai.rapids.cudf.ColumnVector.makeList(ColumnVector.java:441)
E                   	at ai.rapids.cudf.ColumnVector.makeList(ColumnVector.java:410)
E                   	at ai.rapids.cudf.ColumnVector.empty(ColumnVector.java:1623)
E                   	at ai.rapids.cudf.ColumnVector.empty(ColumnVector.java:1630)
E                   	at ai.rapids.cudf.Scalar.listFromNull(Scalar.java:357)
E                   	at com.nvidia.spark.rapids.GpuScalar$.from(literals.scala:221)
E                   	at com.nvidia.spark.rapids.GpuScalar.getBase(literals.scala:442)
E                   	at com.nvidia.spark.rapids.GpuConditionalExpression.$anonfun$computeIfElse$3(conditionalExpressions.scala:42)
```

This happens when you do a case when statement and no default value is given.  The types involved are.

```
Array(Struct(key: String(not_null), value: Array(Struct(key: String(not_null), value: String))))
```

This is the same as a

```
Map(String(not_null),Map(String(not_null),String))
```

but we don't support maps on case when yet. I was trying to add them and ran into this.

### LINKED ISSUE #3140: [FEA] Support Map type on case when
**Is your feature request related to a problem? Please describe.**
We already support structs and arrays on case when statements, so we should be able to support maps as well.  It is relatively simple to add them it, but I ran into https://github.com/NVIDIA/spark-rapids/issues/3139 when trying to do it.  When it is fixed we should be able to extend case when support.

### PR DESCRIPTION
**Pull request by res-life**
Support map type in case when expression.
This fixes #3140; This fixes #3139 

Signed-off-by: res-life res_life@163.com

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by firestarman** [comment]
LGTM

**Comment by firestarman** [comment]
Seems you can also link to the issue https://github.com/NVIDIA/spark-rapids/issues/3139 if it will be fixed by this PR.

**Review by revans2 — APPROVED** [review]
Looks great.

**Pull request merged**
