### PR TITLE
Fix race condition in batch creation

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

In `GpuBroadcastNestedLoopJoinExecBase#doExecuteColumnar` the following code computes the number of rows the join will output by multiplying each batch row count by the `buildCount` which is the row-count of the broadcast side of the relation.

```scala
val counts = streamed.executeColumnar().map(getRowCountAndClose)
GpuNoColumnCrossJoin.divideIntoBatches(
  counts.map(s => s * buildCount),
  targetSizeBytes,
  numOutputRows,
  numOutputBatches)
```

`buildCount` is a lazy val, defined as follows:

```scala
lazy val buildCount: Int = computeBuildRowCount(broadcastRelation, buildTime, buildDataSize)
```

The method called when instantiating `buildCount` contains the following code:

```scala
broadcastRelation.value.batch.numRows()
```

This reference to `batch` calls code that will create the batch if it does not already exist. 

```scala
def batch: ColumnarBatch = {
  if (batchInternal == null) {
    .... 
    batchInternal = readObject(...)
  }
  batchInternal
}

```

Through adding some debug code I was able to prove that multiple threads are following the code path from `counts.map(s => s * buildCount)` and trying to instantiate an instance of the `lazy val` at the same time (note that they all have a distinct `lazy val` and are not referencing a shared instance because this `lazy val` is local within the code block).

The result is that multiple batches get created and references are lost to all but one of them and this will cause leaks.

This PR fixes the issue by synchronizing the batch creation logic.

This closes https://github.com/NVIDIA/spark-rapids/issues/1179

### CODE REVIEW

**Comment by andygrove** [comment]
I am now wondering what is different between this and the PR we had to revert [1]. They are almost identical.

[1] https://github.com/NVIDIA/spark-rapids/pull/1165

**Comment by jlowe** [comment]
> I am now wondering what is different between this and the PR we had to revert

I am assigned to #1179 and was just about to ask you what it was about #1165 that cause so much havok.

To me the race is clearly there, as we're directly calling `.batch` on the broadcast variable in task execution code, so if there's more than one concurrent task then more than one thread will try to create the broadcast batch instance at the same time.  What's a mystery is why adding locking in #1165 was bad -- all I heard is we had to revert it, not what it did or why.

**Comment by andygrove** [comment]
I've updated the issue with an example stack trace that we saw in the integration test failures that led to this being reverted.

Sorry, I thought you knew I was looking into this. I mentioned at standup that I'd look at at this afternoon but there is more to it than I thought so probably best to hand it back to you. Let me know if I can help though.

**Review by jlowe — APPROVED** [review]

**Comment by andygrove** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by revans2** [comment]
build

**Pull request merged**
