### PR TITLE
Fix merge conflict with branch-0.4

### PR DESCRIPTION
**Pull request by jlowe**
Fixing the merge conflict flagged in #1833.  In this case there's no files we want to change, just recording a merge commit.

**NOTE: This must be merged with a merge commit, not squashed!**

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
Updating to resolve merge conflicts from #1826

**Comment by jlowe** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Pull request merged**
