### PR TITLE
Workaround for cudf setup in databricks 11.3 runtime [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

fix https://github.com/NVIDIA/spark-rapids/issues/7639

root cause is https://github.com/rapidsai/cudf/issues/12764

also error out the script if fail execution during cluster creation by adding `-e`

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Comment by pxLi** [comment]
Verified workaround works for 11.3 environment. 
Going to merge this to unblock premerge and nightly CI,
all following-ups would be discussed in https://github.com/NVIDIA/spark-rapids/issues/7643 thx~

**Comment by pxLi** [comment]
this one resolved the db 11.3 py env setup issue. Also found a new pandas dependency issue at https://github.com/NVIDIA/spark-rapids/issues/7739

**Pull request merged**
