### PR TITLE
Support Ascii function for ascii and latin-1 [databricks]

### LINKED ISSUE #9585: [FEA] support ascii function
I wish we can support ascii function.

eg.
```
scala> spark.sql("select ascii(col4) from datavalid3").show
23/10/31 09:34:43 WARN GpuOverrides:
!Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
  @Partitioning <SinglePartition$> could run on GPU
  !Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced
    @Expression <Alias> cast(ascii(col4#85) as string) AS ascii(col4)#94 could run on GPU
      !Expression <Cast> cast(ascii(col4#85) as string) cannot run on GPU because Only UTC zone id is supported. Actual default zone id: Africa/Cairo; Only UTC zone id is supported. Actual session local zone id: Africa/Cairo
        ! <Ascii> ascii(col4#85) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.Ascii
          @Expression <AttributeReference> col4#85 could run on GPU
    *Exec <FileSourceScanExec> will run on GPU
```

### PR DESCRIPTION
**Pull request by thirtiseven**
Closes #9585 

This PR part supported ascii function for strings starting with ASCII and Latin-1 supplement, returning results from 0 to 255. The function is disabled by default.

This PR uses `cudf::code_points` to get the utf-8 code points of the first letter in a string, and converts to ASCII using the following rules:

|ascii|utf-8 dec| workaround |
|---|---|----|
|0~127|0~127| cudf::code_points|
|128~191|49792~49855|code_points - 49,664|
|192~255|50048~50111|code_points -49,856|

It is good enough for customer, we can file another issue to fully support it when needed.

**perf test results**

data: 50000000 string from big datagen:

```
spark.time(df.selectExpr("COUNT(ascii(a)) as asc0", "COUNT(ascii(a)) as asc1", "COUNT(ascii(a)) as asc2", "COUNT(ascii(a)) as asc3", "COUNT(ascii(a)) as asc4", "COUNT(ascii(a)) as asc5", "COUNT(ascii(a)) as asc6", "COUNT(ascii(a)) as asc7", "COUNT(ascii(a)) as asc8", "COUNT(ascii(a)) as asc9").show())
```

 | GPU Time (ms) | CPU Time (ms) | Speed up |
|-|-|-|
| 1,653 | 2,787 | 69% |

### CODE REVIEW

**Comment by thirtiseven** [comment]
Did some perf tests, and gpu is slightly faster than cpu (12%). I plan to refine my implementation to reduce times of cuDF API calling, but the undefined values will be *more undefined*, which doesn't matter for now.

**Comment by thirtiseven** [comment]
Ok, I refined the implementation and it now runs faster, about 69% speedup over cpu.

**Comment by thirtiseven** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by thirtiseven** [comment]
Test failed in CI because Latin-1 support in Spark is from 3.3.1, will add shim for it so ascii under 3.3.1 will be faster and (maybe) fully supported.

**Comment by thirtiseven** [comment]
build

**Review by revans2 — DISMISSED** [review]
Just need to be sure that we test this on databricks

**Comment by thirtiseven** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by thirtiseven** [comment]
build

**Comment by revans2** [comment]
Looks like we need to fix this for 3.5.1 too

**Comment by thirtiseven** [comment]
build

**Comment by thirtiseven** [comment]
perf test results on the byte-based solution (in lower version shims):

 | GPU Time (ms) | CPU Time (ms) | Speed up |
|-|-|-|
| 541.4 | 2,020.6 | 3.73x |

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
The previous tests timed out trying to run on databricks.  Trying again.

**Comment by revans2** [comment]
build

**Pull request merged**
