### PR TITLE
Drop the in-range check at INT96 output path [databricks]

### LINKED ISSUE #8625: [FEA] Support outputTimestampType being INT96
**Is your feature request related to a problem? Please describe.**

a customer reported jobs failing with the following error:

`Caused by: java.lang.IllegalArgumentException: requirement failed: INT96 column contains one or more values that can overflow and will result in data corruption. Please set `spark.rapids.sql.format.parquet.writer.int96.enabled` to false so we can fallback on CPU for writing parquet but still take advantage of parquet read on the GPU.`

Spark currently defaults spark.sql.parquet.outputTimestampType to INT96 so I think many users just end up here.  My guess is the timestamp in this case is bogus but its still an interruption to their current pipeline.

Investigate if we can add support to this in the plugin and cudf.

### PR DESCRIPTION
**Pull request by gerashegalov**
- Remove INT96 check for being in the Long.Min:Max range. 
- Update docs and tests

Fixes #8625 

Depends on  rapidsai/cudf#8070, rapidsai/cudf#13776
 
Verified with the [notebook](https://github.com/gerashegalov/rapids-shell/blob/9cb4598b0feba7b71eb91f396f4b577bbb0dec00/src/jupyter/int96.ipynb) and 
 
 ```bash
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 TEST_PARALLEL=0 SPARK_HOME=~/dist/spark-3.3.2-bin-hadoop3 ./integration_tests/run_pyspark_from_build.sh -k test_fix_for_int96_overflow
```

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Review by revans2 — DISMISSED** [review]

**Review by revans2 — DISMISSED** [review]
Still looks great

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
