### PR TITLE
Drop redundant total time metric from scan

### LINKED ISSUE #972: [BUG] total time metric is redundant with scan time
**Describe the bug**
As indicated in #952 the `total time` metric for GPU scan nodes is not very useful since there's already a Spark standard `scan time` metric.  More confusingly, `total time` is almost always going to be slightly smaller than `scan time` implying it isn't really a total.

**Steps/Code to reproduce bug**
Run a query that uses `GpuFIleSourceScanExec` and examine the metrics on the SQL UI.

**Expected behavior**
We probably should just remove the total time from the node.  If we keep both for some reason, total time should not be less than scan time as it is today.

### PR DESCRIPTION
**Pull request by revans2**
This fixes #972 

I am happy to add in documentation for the metrics too if that is what we want #971

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
it would be nice to have documentation for the metrics but I would think that would be across the board not just for scan so a separate issue.

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by sameerz** [comment]
build

**Pull request merged**
