### PR TITLE
Stop showing internal details of ternary expressions in SparkPlan.toString

### PR DESCRIPTION
**Pull request by andygrove**
Closes https://github.com/NVIDIA/spark-rapids/issues/7924

When printing a physical Spark plan with `toString`, the `GpuRegexpExtract` expression differed from Spark's representation because it also included the transpiled cuDF pattern. As described in issue #7924 , this pattern can contain newlines, and this causes the string representation of the plan to contain newlines and produce confusing output.

We did not intentionally choose to include the cuDF pattern in the output. It is picked up automatically because Spark's `stringArgs` method uses Scala's product iterator to discover fields in a class. Generally, we probably don't want all attributes displayed, so this PR overides `stringArgs` for ternary expressions and just returns the original three arguments.

### CODE REVIEW

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Review by jlowe — COMMENTED** [review]
Note that another alternative to trying to keep Spark/Catalyst from trying to mess with the case class parameters is to put the parameter in a second list of parameters.  See GpuSortExec where we track the cpuSortOrder as an extra argument or GpuShuffledHashJoinExec for examples.  Note that using an extra parameter list requires overriding `otherCopyArgs` but it's straightforward to do.

**Comment by andygrove** [comment]
> Note that another alternative to trying to keep Spark/Catalyst from trying to mess with the case class parameters is to put the parameter in a second list of parameters. See GpuSortExec where we track the cpuSortOrder as an extra argument or GpuShuffledHashJoinExec for examples. Note that using an extra parameter list requires overriding `otherCopyArgs` but it's straightforward to do.

Thanks. That is much better. I switched to this approach and have now implemented it for all regexp expressions.

**Comment by andygrove** [comment]
build

**Review by jlowe — DISMISSED** [review]

**Review by revans2 — DISMISSED** [review]

**Comment by andygrove** [comment]
The newly added test failed in CI when running against Spark 3.2.0:

```
[2023-03-27T16:30:35.144Z] RegularExpressionSuite:
[2023-03-27T16:30:36.517Z] - Plan toString should not leak internal details of ternary expressions *** FAILED ***
[2023-03-27T16:30:36.518Z]   java.lang.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.ProjectExec
[2023-03-27T16:30:36.518Z] Project [_c0#32529, regexp_extract(_c0#32529, (.*) (.*) (.*), 2) AS regexp_extract(_c0, (.*) (.*) (.*), 2)#32533]
[2023-03-27T16:30:36.518Z] +- GpuColumnarToRow false
[2023-03-27T16:30:36.518Z]    +- GpuFileGpuScan csv ...
```

I have not been able to reproduce locally yet, but I am investigating.

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
The test is failing in CI due to the regexp_extract falling back to the CPU due to:

```
regular expression support is disabled because the GPU only supports the UTF-8 charset when using regular expressions
```

**Comment by andygrove** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
New test failures:

```
2023-03-30T20:57:03.8723514Z [2023-03-30T20:55:20.114Z] ^[[31mFAILED^[[0m ../../src/main/python/regexp_test.py::^[[1mtest_re_replace_backrefs[INJECT_OOM]^[[0m - AssertionError: GPU and CPU string values are different at [0, 'regexp_replace(a, (TEST), [$0], 1)']
2023-03-30T20:57:03.8724332Z [2023-03-30T20:55:20.114Z] ^[[31mFAILED^[[0m ../../src/main/python/regexp_test.py::^[[1mtest_re_replace_anchors[INJECT_OOM]^[[0m - AssertionError: GPU and CPU string values are different at [0, 'regexp_replace(a, TEST$, PROD, 1)']
```

**Comment by andygrove** [comment]
build

**Review by gerashegalov — APPROVED** [review]

**Pull request merged**
