### PR TITLE
Test utility to compare SQL query results between CPU and GPU

### LINKED ISSUE #317: [FEA] Write test wrapper to run SQL queries via pyspark
There are Python integration tests that construct data sources and run SQL queries. Consider this [window-function test](https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/integration_tests/src/main/python/window_function_test.py#L79):
```python
https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/integration_tests/src/main/python/window_function_test.py#L79
def test_window_aggs_for_ranges(data_gen):
    df = with_cpu_session(
        lambda spark : gen_df(spark, data_gen, length=2048))
    df.createOrReplaceTempView("window_agg_table")
    assert_gpu_and_cpu_are_equal_collect(
        lambda spark: spark.sql(
            'select '
            ' sum(c) over '
            '   (partition by a order by cast(b as timestamp) asc  '
            '       range between interval 1 day preceding and interval 1 day following) as sum_c_asc '
            # ...
            'from window_agg_table'))
```

It would be good to have a `pytest` wrapper that does the following:
1. Takes a test input `data_gen`, and a SQL string.
1. Constructs an input DataFrame, and a corresponding input table.
1. Runs the supplied SQL on CPU and GPU, and compares results.

Should be a tiny utility.

### PR DESCRIPTION
**Pull request by mythrocks**
Closes #317.

Here is a test utility to run the specified SQL query on CPU and GPU, and verifies that the results are equal.

`window_function_test.py` demonstrates how this may be used.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by mythrocks** [comment]
> I think hash aggregate tests had some occurrences of this as well and it would be good to cover those in this PR as well.

I have now changed `hash_aggregate_test.py` to use this utility, also.

**Comment by mythrocks** [comment]
build

**Comment by mythrocks** [comment]
Thank you for the reviews, @revans2, @kuhushukla.

**Pull request merged**
