### PR TITLE
Disable Integration Test:`test_get_json_object_single_quotes`  on DB 10.4

### PR DESCRIPTION
**Pull request by SurajAralihalli**
This PR skips `test_get_json_object_single_quotes ` test on Databricks 10.4 as it shows incorrect behavior when single quotes are used in the input.  

Resolved [10422](https://github.com/NVIDIA/spark-rapids/issues/10422)

### CODE REVIEW

**Review by revans2 — CHANGES_REQUESTED** [review]
I don't think this is the right fix and we need to do more testing here.

First of all in your testing ` [r'''{'key':'A'}'''],` was parsed correctly. If we disable single quotes in our code is it still going to be parsed correctly?  Second this feels like it is a bug in databricks, and we might want to contact them and report it instead.

We also have no tests to cover json_tuple with single quotes and I am not sure if the same issue exits there or not. I would like to see us first gather come information about what each version of databricks does that we support for both get_json_object, from_json, and json_tuple, when dealing with single quotes for the test cases you listed. After that we can decide what is the best course of action.  In the short term if you want to disable the test for databricks feel free to do that with a reason pointing to the test failures that we are seeing.

**Comment by SurajAralihalli** [comment]
You're right! Thanks for pointing it out Bobby. I'll drop these changes and update this PR to skip this test on DB `10.4`.

**Review by revans2 — APPROVED** [review]

**Comment by SurajAralihalli** [comment]
build

**Comment by revans2** [comment]
build

**Pull request merged**
