### PR TITLE
Update aggregator jar name in databricks deploy script [databricks]

### LINKED ISSUE #3977: [BUG] databricks aggregator jar deployed failed
**Describe the bug**
After #3923 aggregator build do not produce artifacts w/ `-<spark_version_classifier>` which failed deploy script

```
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy-file (default-cli) on project rapids-4-spark-parent: /home/jenkins/agent/workspace/rapids_databricks_nightly-dev-github-301-198/deploy/spark-rapids/aggregator/target/spark301db/rapids-4-spark-aggregator_2.12-21.12.0-SNAPSHOT-spark301db.jar not found.
```

### PR DESCRIPTION
**Pull request by pxLi**
fixes #3977

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
timeout creating db cluster, try retrigger

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]
LGTM

**Pull request merged**
