### PR TITLE
Update to pull the rapids spark extra plugin jar

### PR DESCRIPTION
**Pull request by tgravescs**
This adds the spark rapids private jar to the Aggregator jar.  This means we have to have this jar published for the build to work so we shouldn't merge this until that is ready, or users manually install that jar in their .m2.  Marking this as draft until that jar has been deployed.

We look for a file with extra plugins and then we load those and call the corresponding functions from our RapidsDriverPlugin and RapidsExecutorPlugin.  

NOTE: We may want to find easy way for devs to point to internally pushed extra jar until it gets published externally.

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
the rapids-private jar is available on OSS snapshots repo: https://oss.sonatype.org/content/repositories/snapshots/com/nvidia/rapids-4-spark-private_2.12/23.04.0-SNAPSHOT/

trigger premerge build to verify

**Comment by NvTimLiu** [comment]
pre-merge CI PASS

**Comment by NvTimLiu** [comment]
NOTE: We may want to find easy way for devs to point to internally pushed extra jar until it gets published externally.
  --> the private jar is published to the [OSS snapshots repo](https://oss.sonatype.org/content/repositories/snapshots/com/nvidia/rapids-4-spark-private_2.12/23.04.0-SNAPSHOT/), which is available for external user.

**Comment by andygrove** [comment]
I am testing this now and running into issues. I can see that the final jar includes the classes from the private jar, but when I try and enable the plugin, I am getting a `ClassNotFoundException`. I'm debugging this now and will post an update once I understand more.

**Comment by andygrove** [comment]
> I am testing this now and running into issues. I can see that the final jar includes the classes from the private jar, but when I try and enable the plugin, I am getting a `ClassNotFoundException`. I'm debugging this now and will post an update once I understand more.

I understand now. I was explicitly adding the private plugin to `spark.plugins` but this is not necessary since the main plugin automatically loads it based on the `spark-rapids-extra-plugins` text file from the private jar.

**Review by andygrove — CHANGES_REQUESTED** [review]
Merging this PR will enable the new plugin by default, and also enable join reordering by default on all platforms, which is not what we want, so requesting changes so we don't accidentally merge this just yet.

**Review by andygrove — APPROVED** [review]
I tested locally with latest build of extra jar and LGTM

**Comment by andygrove** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Review by GaryShen2008 — APPROVED** [review]

**Comment by mimaomao** [comment]
From [here](https://oss.sonatype.org/content/repositories/snapshots/com/nvidia/rapids-4-spark-private_2.12/), it seems that only `23.04.0-SNAPSHOT` and `23.06.0-SNAPSHOT` were published. Any plan to publish `23.04.0` and other official releases in the future? Otherwise, the teams outside NVIDIA have to point to SNAPSHOT ones when they build from source for a specific release.

**Comment by tgravescs** [comment]
we publish official release to sonatype, there is a 23.04.0 release of this and when we release 23.06.0 there will be a version of that as well.

https://oss.sonatype.org/content/repositories/staging/com/nvidia/rapids-4-spark-private_2.12/23.04.0/

**Comment by gerashegalov** [comment]
Also easy to see how replacing `snapshots` to `releases` in the link in question redirects 
```diff text
- https://oss.sonatype.org/content/repositories/snapshots/com/nvidia/rapids-4-spark-private_2.12/
+ https://oss.sonatype.org/content/repositories/releases/com/nvidia/rapids-4-spark-private_2.12/
```
https://oss.sonatype.org/content/repositories/releases/com/nvidia/rapids-4-spark-private_2.12/ redirects to the URL Tom shows

**Comment by mimaomao** [comment]
Thanks for the reply! However, it seems there is not a one built against Spark 3.4.0 (332 at most). For SNAPSHOT ones, there is a one with Spark 3.4.0 indeed: https://oss.sonatype.org/content/repositories/snapshots/com/nvidia/rapids-4-spark-private_2.12/23.04.0-SNAPSHOT/rapids-4-spark-private_2.12-23.04.0-20230414.041020-2-spark340.jar. Any ideas why 23.04.0 with Spark 3.4.0 was not published? Ideally, I'd expect official ones and SNAPSHOT ones can have the same sets of SPARK support. BTW, maybe this is out of scope, but is there any plan/way the team outside NVIDIA can build this private artifact by ourselves?

**Comment by gerashegalov** [comment]
The released plugin jar supports only released versions of Spark.

3.4.0 was released when 23.04 was already finalized, and as a FEATURE release hard to accommodate for last minute.    

> BTW, maybe this is out of scope, but is there any plan/way the team outside NVIDIA can build this private artifact by ourselves?

It's not something I can answer. On the flip side I have filed #7981 for making the private dependency optional but it hasn't been prioritized one way or another.

**Pull request merged**
