### PR TITLE
Consolidate deps switching in an intermediate pom [databricks]

### LINKED ISSUE #9552: [BUG] Inconsistent CDH dependency overrides across submodules
|  Submodule    |  CDH overrides |
| ---------------     | -------------------- |
| api_validation | 321cdh              |
| datagen          | 321cdh, 330cdh |
| integration_tests | 321cdh, 330cdh, 332cdh |
| shuffle-plugin  | 321cdh |
| sql-plugin        |  321cdh, 330cdh, 332cdh |
| sql-plugin-api | N/A |
| tests | 321cdh, 330cdh. 332cdh |
| udf-compiler |  321cdh, 330cdh. 332cdh |

Proof of the difference:

Execute on the branch-23.12
```bash
mvn package dependency:list -Dbuildver=321cdh -DskipTests -DoutputFile=target/deps-321cdh.txt
mvn package dependency:list -Dbuildver=332cdh -DskipTests -DoutputFile=target/deps-332cdh.txt
```

Then execute the same commands in a work tree for #9508 

And check the difference between the dependency lists. For 321cdh the only difference is in sql-plugin-api which is expected because the CDH overrides are completely missing there.

```
$ find . -name deps-321cdh.txt | xargs -n 1 bash -c 'git diff --numstat -w $1 ../spark-rapids.worktrees/shimDepsSwitcherP
arent/$1' _
16      14      {. => ../spark-rapids.worktrees/shimDepsSwitcherParent/.}/sql-plugin-api/target/deps-321cdh.txt
```

but for 332cdh significant differences can be also seen for shuffle-plugin and datagen

```bash
$ find . -name deps-332cdh.txt | xargs -n 1 bash -c 'git diff --numstat -w $1 ../spark-rapids.worktrees/shimDepsSwitcherP
arent/$1' _
15      14      {. => ../spark-rapids.worktrees/shimDepsSwitcherParent/.}/sql-plugin-api/target/deps-332cdh.txt
99      12      {. => ../spark-rapids.worktrees/shimDepsSwitcherParent/.}/shuffle-plugin/target/deps-332cdh.txt
86      4       {. => ../spark-rapids.worktrees/shimDepsSwitcherParent/.}/datagen/target/deps-332cdh.txt
```

Compiling with incorrect dependencies may cause false bitwise identity results and/or wrong classes pulled into aggregator. 

_Originally posted by @gerashegalov in https://github.com/NVIDIA/spark-rapids/issues/9541#issuecomment-1780002116_

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #9552 

- Factor out dependency switching profiles for different Spark builds into a single intermediate parent pom

Signed-off-by: @gerashegalov

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
