### PR TITLE
Add shim for Spark 3.1.2

### PR DESCRIPTION
**Pull request by jlowe**
Apache Spark has started publishing Spark 3.1.2 snapshots, so this adds a shim to support that version.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by tgravescs — DISMISSED** [review]

**Review by gerashegalov — DISMISSED** [review]
LGTM

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Pull request merged**
