### PR TITLE
update changelog for 0.4 [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

generated changelog for 0.4 w/
```
GITHUB_TOKEN=xxxx  scripts/generate-changelog --releases=0.4,0.3,0.2,0.1
```

this could be updated at any time

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by sameerz** [comment]
I updated the labels on many issues that were tagged as feature requests but were more likely tasks, tests or performance related.

**Review by sameerz — CHANGES_REQUESTED** [review]
Please rerun the changelog script once more

**Comment by jlowe** [comment]
This was superceded by #1849

**Pull request closed without merging**
