### PR TITLE
Force datagen_seed for 9781 and 9784 [skip ci]

### PR DESCRIPTION
**Pull request by gerashegalov**
Relates to #9781 and #9784

Unblocking pre-merge and nightly tests 

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]

**Pull request merged**
