### PR TITLE
Add OOM retry handling for existence joins

### LINKED ISSUE #8023: [FEA] Existence Join should handle RetryOOM exceptions
**Is your feature request related to a problem? Please describe.**
This is a follow-on to the work done for #7255.  The `ExistenceJoinIterator` does not derive from `AbstractGpuJoinIterator` or from `SplittableJoinIterator`, so the work done for that issue does not apply.
We should add OOM retries where appropriate for `ExistenceJoinIterator`.

**Describe the solution you'd like**
This work should be very similar to what was done for #7255.  Add `withRetry` blocks to handle cases where we may be doing large allocations.

### PR DESCRIPTION
**Pull request by jbrennan333**
Closes #8023.

This adds a simple top-level retry without splits loop for existence joins, following the pattern used for other joins.
I tested this by running the integration tests with injected OOMs and also ran NDS on my desktop at scale 100.
I did not run a performance benchmark at 3TB for this one yet, but I can if desired.

### CODE REVIEW

**Comment by jbrennan333** [comment]
build

**Comment by jbrennan333** [comment]
build

**Comment by jbrennan333** [comment]
@revans2, @abellina I think this one is ready for review.  I don't think the markdown link check nor the 3.4 build failure are related.

**Review by abellina — APPROVED** [review]

**Comment by jbrennan333** [comment]
Thanks for the reviews @revans2 and @abellina!

**Pull request merged**
