### PR TITLE
Auto merge PRs to branch-24.10 from branch-24.08 [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
As the title

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
try `git commit --amend` to re-generate the hashcode and force push to see if retrigger. Github action is buggy..

**Comment by NvTimLiu** [comment]
> try `git commit --amend` to re-generate the hashcode and force push to see if retrigger. Github action is buggy..

Yes, should be GitHub bug , found similar issue reported : https://github.com/orgs/community/discussions/49257

**Comment by pxLi** [comment]
> > try `git commit --amend` to re-generate the hashcode and force push to see if retrigger. Github action is buggy..
> 
> Yes, should be GitHub bug , found similar issue reported : https://github.com/orgs/community/discussions/49257

this is a different case...do you want me to force merge this one?

**Comment by NvTimLiu** [comment]
> > > try `git commit --amend` to re-generate the hashcode and force push to see if retrigger. Github action is buggy..
> > 
> > 
> > Yes, should be GitHub bug , found similar issue reported : https://github.com/orgs/community/discussions/49257
> 
> this is a different case (open a PR via actions/github-script@v6)...do you want me to force merge this one?

`commit --amend` to upload a new hash commit ID but without file changes seems not working, either. 

Yes, please help force merge it.

**Pull request merged**
