### PR TITLE
Update changelog for v0.3.0 release [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Update changelog for 0.3.0 release [Skip CI]

Update changelog for 0.3 release w/ GITHUB_TOKEN= scripts/generate-changelog --releases=0.3,0.2,0.1

To preview the CHANGELOG: https://github.com/pxLi/spark-rapids/blob/changelog-0.3/CHANGELOG.md.

### CODE REVIEW

**Review by GaryShen2008 — DISMISSED** [review]

**Review by revans2 — DISMISSED** [review]

**Comment by revans2** [comment]
This is targeted to branch-0.4 is that what is expected?

**Comment by NvTimLiu** [comment]
build

**Comment by jlowe** [comment]
Agree with @revans2, the PR is marked for project 0.3 but branch is targeting 0.4.  One of those is wrong.

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Comment by revans2** [comment]
Looks good thanks for changing the target. Still +1 @jlowe are you OK with this?

**Comment by jlowe** [comment]
> Still +1 @jlowe are you OK with this?

Yes, although apparently I wasn't fast enough.  :smile:

**Pull request merged**
