### PR TITLE
Updated GCP Dataproc Mortgage-ETL-GPU.ipynb

### PR DESCRIPTION
**Pull request by aroraakshit**
Description of changes:
- `from pyspark import SparkConf`
- `if sc: sc.stop()`
- Added instructions to download and organize the dataset in a GCP bucket.

### CODE REVIEW

**Comment by jlowe** [comment]
Thanks for the contribution, @aroraakshit!  As reported by the CI checks, you will need to sign-off on your contribution per [the instructions in the contribution guide](https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/CONTRIBUTING.md#sign-your-work).  Easiest would be to perform a `git commit --amend -s` and then force-pushing your branch back up to github.

**Review by aroraakshit — COMMENTED** [review]
`if sc: sc.stop()` will fail if 'sc' variable does not exist. So changed to `if 'sc' in globals()`.

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]
The pre-commit build is failing because of the 3.1 changes to parquet.  Either this needs to be upmerged or we can ignore the build failure and merge it in because this is not executed by the pre-commit build at all.

**Comment by jlowe** [comment]
Merging since the CI failure is unrelated to the notebook change.

**Pull request merged**
