### PR TITLE
Update spark-rapids version to 22.04.0

### PR DESCRIPTION
**Pull request by NvTimLiu**
As the title

Note: merge this PR via `Create a merge request`

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by jlowe — COMMENTED** [review]
Diffing this against branch-22.04, I see there are files left in the top-level `shims` directory which was removed back in branch-22.02.  It appears these were (inadvertently?) restored in f5c62560b521514b16792.  These shims directories should be removed.  The only differences between main and branch-22.04 at this point should be the version string changes.

**Comment by NvTimLiu** [comment]
> Diffing this against branch-22.04, I see there are files left in the top-level `shims` directory which was removed back in branch-22.02. It appears these were (inadvertently?) restored in [f5c6256](https://github.com/NVIDIA/spark-rapids/commit/f5c62560b521514b1679238d8e125194ae8baf4c). These shims directories should be removed. The only differences between main and branch-22.04 at this point should be the version string changes.

Correct, this should be the side-effect of git merge.

Let me close this PR, and create a new PR instead.

**Comment by jlowe** [comment]
Closing this PR won't fix the merge problem, the merge was correct in terms of a pure git merge.  That's because the merge problem happened back in 22.02, not this 22.04 merge.  There needs to be an explicit fixup of that bad merge, either as part of the merge commit or as a separate commit on `main` as part of a PR (this or another).

**Comment by NvTimLiu** [comment]
> 

Thanks for your reminding @jlowe , I found the root cause: When fixing merge conflicts on my local side, my merge script only fixed `both modified : xxx` files, but not handled those `deleted by them : xxx` as below: 

```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        both modified:   README.md
        both modified:   aggregator/pom.xml
        both modified:   api_validation/pom.xml
        both modified:   dist/pom.xml
        both modified:   docs/configs.md
        both modified:   docs/get-started/getting-started-on-prem.md
        both modified:   integration_tests/README.md
        both modified:   integration_tests/pom.xml
        both modified:   jenkins/databricks/create.py
        both modified:   jenkins/version-def.sh
        both modified:   pom.xml
        deleted by them: shims/pom.xml
        deleted by them: shims/spark301/pom.xml
        deleted by them: shims/spark301db/pom.xml
        deleted by them: shims/spark302/pom.xml
        deleted by them: shims/spark303/pom.xml
        deleted by them: shims/spark304/pom.xml
        deleted by them: shims/spark311/pom.xml
        deleted by them: shims/spark311cdh/pom.xml
        deleted by them: shims/spark312/pom.xml
        deleted by them: shims/spark312db/pom.xml
        deleted by them: shims/spark313/pom.xml
        deleted by them: shims/spark320/pom.xml
        deleted by them: shims/spark321/pom.xml
        deleted by them: shims/spark322/pom.xml
        deleted by them: shims/spark330/pom.xml
        both modified:   shuffle-plugin/pom.xml
        both modified:   spark2-sql-plugin/pom.xml
        both modified:   spark2-sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
        both modified:   sql-plugin/pom.xml
        both modified:   sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala
        both modified:   tests-spark310+/pom.xml
        both modified:   tests/pom.xml
        both modified:   tools/pom.xml
        both modified:   udf-compiler/pom.xml
        deleted by them: udf-examples/pom.xml

```

**Pull request closed without merging**
