### PR TITLE
Update docs for 24.06.1 release [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
This PR updates download docs for 24.06.1 release.

Refer to : https://github.com/NVIDIA/spark-rapids/pull/10984

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
should target `branch-24.06`?

**Comment by NvTimLiu** [comment]
> should target `branch-24.06`?

Re-target to branch-24.06

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by NvTimLiu** [comment]
Looks like something went wrong after my forked repo, it merged get branch-24.08
Close this one, and  file another  PR

**Pull request closed without merging**
