### PR TITLE
Update title of configs.md page

### PR DESCRIPTION
**Pull request by sameerz**
1. Please write a description in this text box of the changes that are being
   made.

Update title of configs.md to be more in line with other page titles. 

2. Please ensure that you have written units tests for the changes made/features
   added.

Ran the build to generate configs.md from RapidsConf.scala

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by abellina** [comment]
Could be done in follow up but, the developer guide is also not consistent with the titles. Let us know @sameerz

**Comment by sameerz** [comment]
@abellina will do those updates in a followup doc change.

**Comment by tgravescs** [comment]
build

**Pull request closed without merging**
