### PR TITLE
Add test case for ORC statistics test [databricks]

### LINKED ISSUE #8763: Statistics tests for ORC files written by GPU
When the GPU writes an ORC file, it's important to get the file, row group, and page statistics correct. We should have better tests, ideally including tests at larger scale than a few thousand rows typical for unit/integration tests, for verifying the statistics written to the ORC file are correct.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #8763.  This restores the OrcSuite test that was reverted in #8983 by adding the new datagen module as a dependency and moving the test from the integration_tests module to the tests module.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by res-life** [comment]
Found build error:
```
Error: 8-11T01:02:46.563Z] [2023-08-11T01:02:35.710Z] [ERROR] /home/ubuntu/spark-rapids/tests/src/test/scala/com/nvidia/spark/rapids/OrcSuite.scala:183: Class org.apache.hadoop.hive.common.type.HiveDecimal not found - continuing with a stub.
```

Pushed a new commit to add hive-storage-api dependency.

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
The reason why I caused this issue is: I used `-DallowConventionalDistJar` argument to fast the compile.
```
mvn clean install -DallowConventionalDistJar=true -Dbuidver=330
```
So I compiled successfully locally.

**Review by res-life — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Pull request merged**
