### PR TITLE
Add nested type support to MetaUtils

### PR DESCRIPTION
**Pull request by jlowe**
This adds support for nested type columns to the RAPIDS shuffle.  This also updates `TestUtils` to compare nested type columns which was needed for the unit tests.

This PR is based on #1133 and should go in only after that does.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]
Looks good to me

**Review by abellina — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by jlowe** [comment]
I needed to resolve merge conflicts in TestUtils and MetaUtils when merging to latest on branch-0.3.

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by sameerz** [comment]
build

**Comment by abellina** [comment]
I ran a few queries using UCX and this patch and I haven't seen issues. We can't test nested types just yet, but for the old case it works correctly.

**Review by abellina — APPROVED** [review]

**Pull request merged**
