### PR TITLE
Bump up dependency version to 24.04.0-SNAPSHOT[databricks]

### PR DESCRIPTION
**Pull request by NvTimLiu**
To fix: https://github.com/NVIDIA/spark-rapids/issues/10256

Bump up dependency version to 24.04.0-SNAPSHOT

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
Will re-trigger the GitHub and pre-merge CIs after the spark-rapids-jni jars get updated by today's nightly build.

**Review by jlowe — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
Pre-merge CI failed with standalone application SparkUI, let me re-trigger a new pre-merge
```
[2024-01-30T17:27:44.475Z] To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-01-30T17:27:45.035Z] 24/01/31 01:27:44 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-01-30T17:27:45.035Z] 24/01/31 01:27:44 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-01-30T17:27:45.035Z] 24/01/31 01:27:44 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
...
```

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
