### PR TITLE
Rename 311until320-apache to 311until320-noncdh

### LINKED ISSUE #3613: [BUG] release312db profile pulls in 311until320-apache
**Describe the bug**
somehow 311until320-apache got added into the release312db profile for databricks.  I take apache as meaning all Apache release which wouldn't include databricks, cdh, or other vendor specific implementation, we should remove that and move files as needed.

### PR DESCRIPTION
**Pull request by res-life**
Rename "311until320-apache" directory  to "311until320-noncdh"
This fixes #3613 

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
@pxLi  3 tests failed in ParseDateTimeSuite, seems it's not introduced by this PR.
```
- to_date yyyy-MM-dd *** FAILED ***
  Mismatch between CPU and GPU for the following rows:
  
  [#40] CPU: [1999-12-29
  ,null]
  [#40] GPU: [1999-12-29
  ,1999-12-29] (ParseDateTimeSuite.scala:302)
- to_date yyyy-MM-dd LEGACY
- to_date yyyy/MM/dd LEGACY
- to_date dd/MM/yyyy
- to_date dd/MM/yyyy LEGACY
- to_date parse date
- to_date parse timestamp
- to_timestamp yyyy-MM-dd *** FAILED ***
  Mismatch between CPU and GPU for the following rows:
  
  [#35] CPU: [1999-12-29
  ,null]
  [#35] GPU: [1999-12-29
  ,1999-12-29 00:00:00.0] (ParseDateTimeSuite.scala:302)
- to_timestamp dd/MM/yyyy
- to_date default pattern
- unix_timestamp parse date *** FAILED ***
  Mismatch between CPU and GPU for the following rows:
  
  [#35] CPU: [1999-12-29
  ,null]
  [#35] GPU: [1999-12-29
  ,946425600] (ParseDateTimeSuite.scala:302)
- unix_timestamp parse yyyy/MM

```

**Review by jlowe — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]

**Comment by pxLi** [comment]
> @pxLi 3 tests failed in ParseDateTimeSuite, seems it's not introduced by this PR.
> 
> ```
> - to_date yyyy-MM-dd *** FAILED ***
>   Mismatch between CPU and GPU for the following rows:
>   
>   [#40] CPU: [1999-12-29
>   ,null]
>   [#40] GPU: [1999-12-29
>   ,1999-12-29] (ParseDateTimeSuite.scala:302)
> - to_date yyyy-MM-dd LEGACY
> - to_date yyyy/MM/dd LEGACY
> - to_date dd/MM/yyyy
> - to_date dd/MM/yyyy LEGACY
> - to_date parse date
> - to_date parse timestamp
> - to_timestamp yyyy-MM-dd *** FAILED ***
>   Mismatch between CPU and GPU for the following rows:
>   
>   [#35] CPU: [1999-12-29
>   ,null]
>   [#35] GPU: [1999-12-29
>   ,1999-12-29 00:00:00.0] (ParseDateTimeSuite.scala:302)
> - to_timestamp dd/MM/yyyy
> - to_date default pattern
> - unix_timestamp parse date *** FAILED ***
>   Mismatch between CPU and GPU for the following rows:
>   
>   [#35] CPU: [1999-12-29
>   ,null]
>   [#35] GPU: [1999-12-29
>   ,946425600] (ParseDateTimeSuite.scala:302)
> - unix_timestamp parse yyyy/MM
> ```

https://github.com/NVIDIA/spark-rapids/issues/4176 those tests have been disabled, and cudf issue has also been created. plz retrigger the build

**Comment by gerashegalov** [comment]
build

**Pull request merged**
