### PR TITLE
Update latest changelog [skip ci]

### PR DESCRIPTION
**Pull request by nvauto**
Update change log with CLI: 

   scripts/generate-changelog --token=<GIT_TOKEN> --releases=24.02,24.04

### CODE REVIEW

**Comment by sameerz** [comment]
Reviewed and made some changes to issue labels.  I am good once the changelog is regenerated.

**Comment by NvTimLiu** [comment]
> Reviewed and made some changes to issue labels. I am good once the change log is regenerated.

Update after review: https://github.com/NVIDIA/spark-rapids/pull/10683/commits/8a57f2404c2e8496730fcd5335ef839fc0df5883

@sameerz  Can you help check if we need add project 24.04 for below PRs? Thanks!

NOTE: Merged Pull Requests w/o Project:
branch-24.04 #10575 Update JsonToStructs and ScanJson to have white space normalization https://github.com/NVIDIA/spark-rapids/pull/10575
branch-24.04 #10615 Turn off state logging in HostAllocSuite https://github.com/NVIDIA/spark-rapids/pull/10615
branch-24.04 #10616 Pass metadata extractors to FileScanRDD [databricks] https://github.com/NVIDIA/spark-rapids/pull/10616
branch-24.04 #10625 Pin to 3.1.0 maven-gpg-plugin in deploy script [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10625
branch-24.04 #10667 Update rapids private dependency to 24.04.1 https://github.com/NVIDIA/spark-rapids/pull/10667
branch-24.04 #10676 [DOC] Update docs for 24.04.0 release [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10676
branch-24.02 #9470 Use float to string kernel https://github.com/NVIDIA/spark-rapids/pull/9470
branch-24.02 #9481 Use parse_url kernel for PROTOCOL parsing https://github.com/NVIDIA/spark-rapids/pull/9481
branch-24.02 #9716 Initiate project version 24.02.0-SNAPSHOT [databricks] https://github.com/NVIDIA/spark-rapids/pull/9716
branch-24.02 #9833 Fix a hang for Pandas UDFs on DB 13.3[databricks] https://github.com/NVIDIA/spark-rapids/pull/9833
branch-24.02 #9889 Fix test_cast_string_ts_valid_format test https://github.com/NVIDIA/spark-rapids/pull/9889
branch-24.02 #10069 Revert "Support split broadcast join condition into ast and non-ast [… https://github.com/NVIDIA/spark-rapids/pull/10069
branch-24.02 #10384 [DOC] Update docs for 23.12.2 release [skip ci]  https://github.com/NVIDIA/spark-rapids/pull/10384

**Comment by sameerz** [comment]
> > Reviewed and made some changes to issue labels. I am good once the change log is regenerated.
> 
> Update after review: [8a57f24](https://github.com/NVIDIA/spark-rapids/commit/8a57f2404c2e8496730fcd5335ef839fc0df5883)
> 
> @sameerz @GaryShen2008 Can you help check if we need to add project 24.04 for below PRs? Thanks!
> 
I updated these to either 24.02 or 24.04, per the PRs.

**Comment by NvTimLiu** [comment]
> > > Reviewed and made some changes to issue labels. I am good once the change log is regenerated.
> > 
> > 
> > Update after review: [8a57f24](https://github.com/NVIDIA/spark-rapids/commit/8a57f2404c2e8496730fcd5335ef839fc0df5883)
> > @sameerz @GaryShen2008 Can you help check if we need to add project 24.04 for below PRs? Thanks!
> 
> I updated these to either 24.02 or 24.04, per the PRs.

Thanks @sameerz , updated change log to latest, and included your updating.

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Review by sameerz — APPROVED** [review]

**Pull request merged**
