### PR TITLE
verify "Add array support to union by name " by adding an integration test

### LINKED ISSUE #3953: [FEA] Audit: Add array support to union by name
**Is your feature request related to a problem? Please describe.**
https://issues.apache.org/jira/browse/SPARK-36546
https://github.com/apache/spark/commit/5241d98800

I think this should just work out of the box for us, but we should add some tests and verify that it works properly.

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: HaoYang670 <13716567376yh@gmail.com>

Closes #3953

Add an integration test for https://github.com/NVIDIA/spark-rapids/issues/3953

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
The precommit tests don't run against 3.3+, but I assume that you did run this test against it?

**Comment by HaoYang670** [comment]
Hi Bobby, I have successfully run this test on local with spark 3.3.0 snapshot

**Comment by HaoYang670** [comment]
Signed-off-by: HaoYang670 13716567376yh@gmail.com

Closes #3953

verify "Add array support to union by name " by adding an integration test

**Pull request merged**
