### PR TITLE
Update SnakeYaml version for bug fixes

### PR DESCRIPTION
**Pull request by tgravescs**
Pick up bug fixes in SnakeYaml.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by jlowe — COMMENTED** [review]
Not sure what the empty file is for?

**Review by jlowe — APPROVED** [review]

**Comment by tgravescs** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by tgravescs** [comment]
build failure was unrelated and hsould be fixed now, rekicking

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Pull request merged**
