### PR TITLE
fix the non-consistency for `spark.rapids.sql.format.parquet.multiThreadedRead` in RapidsConf.scala

### PR DESCRIPTION
**Pull request by JustPlay**
for `spark.rapids.sql.format.parquet.multiThreadedRead.enabled` it is said

When set to true, reads multiple small files within a partition more efficiently by reading each file in a separate thread in parallel on the CPU side before sending to the GPU. Limited by spark.rapids.sql.format.parquet.multiThreadedRead.numThreads and `spark.rapids.sql.format.parquet.multiThreadedRead.maxNumFileProcessed`

but it shoud be `spark.rapids.sql.format.parquet.multiThreadedRead.maxNumFilesParallel`

### CODE REVIEW

**Comment by JustPlay** [comment]
fix: https://github.com/NVIDIA/spark-rapids/issues/874

**Comment by svcngcc** [comment]
Can one of the admins verify this patch?

**Comment by tgravescs** [comment]
build

**Review by tgravescs — APPROVED** [review]
thanks for the fix @JustPlay

**Review by revans2 — APPROVED** [review]

**Comment by JustPlay** [comment]
why CI error?

**Comment by tgravescs** [comment]
it was from a build timeout, probably due to busy nodes

**Comment by tgravescs** [comment]
build

**Pull request merged**
