### PR TITLE
update 21.08 gh-pages doc

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: Yuan Li yuali@nvidia.com
Update gh-pages for 21.08 release #3030

### CODE REVIEW

**Comment by nvliyuan** [comment]
@jlowe please refer to this one

**Review by jlowe — APPROVED** [review]
Similar to my comment in the previous PR, there are interactively edited files on this branch, specifically in:
- compatibility.md
- additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma
- additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma

This means it wasn't cherry-picked from branch-21.08 as it should have been.  I'm fine with this going in, but these fixes need to be made on branch-21.08 (or at least branch-21.10) so those browsing the docs on the dev branch see the same fixes.

**Comment by nvliyuan** [comment]
After cherry-picked from branch-21.08, there are typos in these three files, so I directly fix them in this pr. If this pr was merged, I should draft another pr to fix the same issue on branch-21.08. Following are the changes in these three files:

- compatibility.md: line 417: change "...the hybrid Julian+Gregorian calender" to "...the hybrid Julian+Gregorian calendar"
- additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma: line 20 change "... a package matchin a specific" to "... a package matching a specific"
- additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma: line 23 change "... a package matchin a specific" to "... a package matching a specific"

**Comment by jlowe** [comment]
> If this pr was merged, I should draft another pr to fix the same issue on branch-21.08.

Correct.  In the future, it's preferable to fix these changes on the dev branch so these types of PRs are straightforward merges/cherry-picks of the doc changes from the dev branch without interactive edits.

**Comment by nvliyuan** [comment]
OK, I got it

**Comment by sameerz** [comment]
> After cherry-picked from branch-21.08, there are typos in these three files, so I directly fix them in this pr. 
> 
    compatibility.md: line 417: change "...the hybrid Julian+Gregorian calender" to "...the hybrid Julian+Gregorian calendar"
    additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_no_rdma: line 20 change "... a package matchin a specific" to "... a package matching a specific"
    additional-functionality/shuffle-docker-examples/Dockerfile.ubuntu_rdma: line 23 change "... a package matchin a specific" to "... a package matching a specific"


@nvliyuan thank you for the fixes.  At this point it is late for 21.08.  Would you mind opening a PR in branch-21.10 to make these changes in our dev branch going forward?

**Comment by nvliyuan** [comment]
> opening a PR in branch-21.10

ok, I will do that

**Pull request merged**
