### PR TITLE
Merge from branch 0.2

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge remote-tracking branch 'nvspark/branch-0.2' into main

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
NOTE: This must be merged with a merge commit, not squash commit.

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
> NOTE: This must be merged with a merge commit, not squash commit.

@jlowe  Thanks for reminding

**Comment by jlowe** [comment]
build

**Pull request merged**
