### PR TITLE
Branch 0.5 doc remove numpartitions

### LINKED ISSUE #1853: [DOC] Getting started docs sets numpartitions
## Report incorrect documentation

our getting started docs (https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#local-mode) have   --conf spark.sql.shuffle.partitions=10, we should either remove that or comment on it to explain it as some users just copy it.

### PR DESCRIPTION
**Pull request by sameerz**
Fixes #1853 

The `spark.sql.shuffle.partitions` default is 200, we should let uses modify if they need rather than put in a setting.  We have information about tuning this in https://nvidia.github.io/spark-rapids/docs/tuning-guide.html .

### CODE REVIEW

**Review by jlowe — COMMENTED** [review]
Note that we also have a shuffle partition setting in [the AWS EMR guide](https://github.com/NVIDIA/spark-rapids/blob/branch-0.5/docs/get-started/getting-started-aws-emr.md) which should probably be removed as well.

**Comment by sameerz** [comment]
Removed from AWS EMR getting started guide as well.

**Review by jlowe — APPROVED** [review]
This will need to be upmerged to branch-0.5 after https://github.com/NVIDIA/spark-rapids/pull/1889 is merged to get the premerge CI to pass.  Not worth performing a premerge CI build until that happens.  Assuming the merge of branch-0.5 goes in clean, this approval should "stick."

**Comment by sameerz** [comment]
build

**Comment by jlowe** [comment]
This will likely need to upmerge with branch-0.5 to get premerge CI to pass.

**Comment by sameerz** [comment]
build

**Comment by sameerz** [comment]
build

**Pull request merged**
