### PR TITLE
Change the assert to require for handling TIMESTAMP_MILLIS in isDateTimeRebaseNeeded 

### PR DESCRIPTION
**Pull request by tgravescs**
This is a workaround for https://github.com/NVIDIA/spark-rapids/issues/1130

I found one flaky test that needed ignore order.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
Tests failed.  Do we need the same ignore order change in orc_write_test.py?

**Review by revans2 — DISMISSED** [review]

**Comment by revans2** [comment]
looks like ```16:54:51  FAILED ../../src/main/python/orc_write_test.py::test_buckets_write_fallback[ALLOW_NON_GPU(DataWritingCommandExec)]``` is failing now.

**Comment by tgravescs** [comment]
yes should be the same ignore order on that

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Pull request merged**
