### PR TITLE
Revert "Support `int96RebaseModeInWrite` and `int96RebaseModeInRead' (#3330)

### PR DESCRIPTION
**Pull request by tgravescs**
this is just get revert, no other changes. This commit is not up to date with the latest shim stuff and causes build failures in CDH and potentially others.

This reverts commit fc40c001446fd3ab7a33613ea8be43f05c94db96.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by tgravescs** [comment]
build

**Comment by abellina** [comment]
Note that Reza's commit had a fix for a test failure, I closed my PR for that test failure in favor of Reza's change. I'll reopen the other PR.

**Comment by abellina** [comment]
FYI @tgravescs https://github.com/NVIDIA/spark-rapids/pull/3615

**Review by gerashegalov — APPROVED** [review]

**Comment by razajafri** [comment]
Can we hold off on merging this? I may have the fix almost ready

**Comment by razajafri** [comment]
#3630 is ready for review

**Pull request closed without merging**
