### PR TITLE
Refactor for shims 320+

### PR DESCRIPTION
**Pull request by res-life**
This contributes #4447

This fixes the comments from @tgravescs in #4447
Add a new Spark320PlusShims; then Spark322PlusShims and Spark320until322Shims extends the Spark320PlusShims

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
This fixes the comments from @tgravescs in #4447
Add a new Spark320PlusShims; then Spark322PlusShims and Spark320until322Shims extends the Spark320PlusShims

**Comment by res-life** [comment]
build

**Comment by firestarman** [comment]
LGTM

**Review by tgravescs — APPROVED** [review]
looks good, can you please move the description of what is changing up to the first comment in the PR.  That makes it easier for reviewer.

**Pull request merged**
