### PR TITLE
Increase the Databricks cluster's timeout [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Increase the Databricks cluster's timeout.

    As more test cases are added, the timeout of Databricks cluster needs to be increased to run all the tests.

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Review by tgravescs — DISMISSED** [review]

**Comment by tgravescs** [comment]
actually I take that back, these should be changed in the jenkins files and the timeout for the jenkins should match or be similar to the timeout for the cluster.

As the comment above the line you changed says, you should change this line as well:
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/spark-rapids/Jenkinsfile.databricks301nightly#L51

**Comment by NvTimLiu** [comment]
Close as we changed the databricks nightly Jenkinsfile

**Pull request closed without merging**
