### PR TITLE
Fix empty table broadcast requiring a GPU on driver node

### LINKED ISSUE #975: [BUG] BroadcastExchangeExec fails to fall back to CPU on driver node on GCP Dataproc
**Describe the bug**
`java.lang.UnsatisfiedLinkError: /tmp/cudf6291133341730615510.so: libnvrtc.so.10.2: cannot open shared object file: No such file or directory` error when running the [Mortgage ETL notebook](https://nvidia.github.io/spark-rapids/docs/demo/GCP/Mortgage-ETL-GPU.ipynb) with the sample [mortgage data](https://rapidsai.github.io/demos/datasets/mortgage-data) on a GCP Dataproc cluster, when the master node is not a GPU node.  

Error message in this gist: https://gist.github.com/sameerz/b1df1130b0955b562a5801d7eb664811

**Steps/Code to reproduce bug**
1. Create a new cluster where the GPU node is CPU only and workers have CPU and GPU.  Sample cluster creation scripts: https://gist.github.com/sameerz/d655ff262a295e66b3384fcbd15b67dd
2. Launch and run the notebook, instructions here: https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-gcp.html

@tgravescs pointed out that this is avoidable if we set `conf.set('spark.rapids.sql.exec.BroadcastExchangeExec', 'false')`.  However this notebook worked on Dataproc previously.  

**Expected behavior**
GPU operations do not run on the master node if the master is CPU only.  

**Environment details (please complete the following information)**
 - Environment location: GCP Dataproc preview-ubuntu18, running either CUDA 10.2 or CUDA 11.0
 - 2 GPU worker nodes
 - Spark configuration settings related to the issue: Spark config settings are in the initialization script https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/rapids/rapids.sh#L120 and in the *Define Spark conf and Create Spark Session* section of the notebook https://github.com/NVIDIA/spark-rapids/blob/gh-pages/docs/demo/GCP/Mortgage-ETL-GPU.ipynb.  

One note, there is an unrelated error in this notebook - that same cell in the notebook needs to start with `from pyspark import SparkConf` , but that will be addressed in a separate PR.  

**Additional context**
This error occurs running the 0.2 plugin and 0.15 cudf.  Something may have changed in the Dataproc environment.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #975 

Changes broadcast code to use only HostColumnVector when constructing an empty table rather than requiring an empty `Table` to be created which requires `ColumnVector` and thus CUDA and a GPU to be available on the driver.  Note that I recently fixed `HostColumnVector` in https://github.com/rapidsai/cudf/pull/6633 to avoid loading native dependencies.

This PR also cleans up a bunch of minor nits IntelliJ was flagging in GpuColumnVector where `final` is redundant on a `static` method.  I'm happy to move those changes to another PR if desired.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]
Feels like a lot of small changes not related to this.  Not a big deal though.

**Pull request merged**
