### PR TITLE
Use CUDF's "UNBOUNDED" window boundaries for time-range queries.

### LINKED ISSUE #1039: [BUG] UNBOUNDED window ranges on null timestamp columns produces incorrect results.
**Describe the bug**
This is a follow on issue to #825. It looks like the window function was fixed for nulls, except for the UNBOUNDED case. 

**Steps/Code to reproduce bug**
`test_window_aggs_for_ranges` against cudf-0.17 currently fails all the time.  I will update the test with an xfail for those situations pointing to this issue.

**Expected behavior**
This test should pass

It looks like we are not handling unbounded properly and in the short term will have to disable nullable timestamp columns with unbounded preceding or following intervals.

I simplified the query to make debugging this simpler
```sql
select
  count(c) over 
    (partition by a order by cast(b as timestamp) asc
        range between  CURRENT ROW and UNBOUNDED following) as count_c_asc, a, b, c
from window_agg_table order by a, b, c
```
I dropped the length of the generated data to 100 and I see results like the following (with emphasis added)

CPU:
```
Row(count_c_asc=*5*, a=-5831592707909023540, b=None, c=756780896), 
Row(count_c_asc=4, a=-5831592707909023540, b=datetime.date(2020, 2, 29), c=-656902282), 
Row(count_c_asc=3, a=-5831592707909023540, b=datetime.date(2020, 3, 18), c=-756294971), 
Row(count_c_asc=2, a=-5831592707909023540, b=datetime.date(2020, 10, 10), c=2117211837), 
Row(count_c_asc=1, a=-5831592707909023540, b=datetime.date(2020, 12, 25), c=110877650), 
```

GPU:
```
Row(count_c_asc=*1*, a=-5831592707909023540, b=None, c=756780896), 
Row(count_c_asc=4, a=-5831592707909023540, b=datetime.date(2020, 2, 29), c=-656902282), 
Row(count_c_asc=3, a=-5831592707909023540, b=datetime.date(2020, 3, 18), c=-756294971), 
Row(count_c_asc=2, a=-5831592707909023540, b=datetime.date(2020, 10, 10), c=2117211837), 
Row(count_c_asc=1, a=-5831592707909023540, b=datetime.date(2020, 12, 25), c=110877650),
```

The GPU side appears to be doing what we talked about, but the CPU side appears to not care about the null in the timestamp column. It feels like unbounded really means unbounded, because when I switch the following to be INTERVAL 1000 DAYS the GPU now matches the CPU results.

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #1039. Depends on https://github.com/rapidsai/cudf/pull/6811.

This change aims to allow for unbounded time-range window function queries to return the right results. It depends on the explicit support to specify unbounded window boundaries in CUDF. This cannot be checked in without rapidsai/cudf#6811.

### CODE REVIEW

**Comment by revans2** [comment]
@mythrocks you need to update the commit with a signoff

**Review by revans2 — APPROVED** [review]

**Comment by mythrocks** [comment]
> Depends on rapidsai/cudf#6811.

This was merged a couple of hours ago. I have rebased the change and signed the commit.

**Comment by mythrocks** [comment]
> mythrocks dismissed revans2’s stale review via 1d6d130 26 minutes ago

With apologies to @revans2, this is a little harsh; I did no such thing. Signing the commit invalidated the previous review. The new commit has no material difference from the old one.

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by mythrocks** [comment]
An odd test failure:

```
11:59:31  [32m- a block fits entirely, but a subsequent block doesn't[0m
11:59:31  [32mHashAggregatesSuite:[0m
11:59:46  [31m*** RUN ABORTED ***[0m
11:59:46  [31m  java.lang.NoSuchMethodError: org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.canChangeNumPartitions()Z[0m
11:59:46  [31m  at org.apache.spark.sql.rapids.execution.GpuShuffleMeta.convertToGpu(GpuShuffleExchangeExec.scala:68)[0m
11:59:46  [31m  at org.apache.spark.sql.rapids.execution.GpuShuffleMeta.convertToGpu(GpuShuffleExchangeExec.scala:42)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:615)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.GpuOverrides$$anon$138.convertToGpu(GpuOverrides.scala:2046)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.GpuOverrides$$anon$138.convertToGpu(GpuOverrides.scala:2040)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:615)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.GpuSortMeta.convertToGpu(GpuSortExec.scala:42)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.GpuSortMeta.convertToGpu(GpuSortExec.scala:33)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.SparkPlanMeta.convertIfNeeded(RapidsMeta.scala:615)[0m
11:59:46  [31m  at com.nvidia.spark.rapids.GpuSortAggregateMeta.convertToGpu(aggregate.scala:285)[0m
11:59:46  [31m  ...[0m
11:59:46  [INFO] ------------------------------------------------------------------------
11:59:46  [INFO] Reactor Summary:
11:59:46  [INFO] 
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark Root Project ... SUCCESS [  1.368 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin ..... SUCCESS [  7.770 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark Shuffle Plugin . SUCCESS [  0.460 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Shims SUCCESS [  0.068 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.0 Shim SUCCESS [  0.592 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.0 EMR Shim SUCCESS [  0.432 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.1 Shim SUCCESS [  0.528 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.1 EMR Shim SUCCESS [  0.445 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.0 Shim SUCCESS [ 11.990 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.2 Shim SUCCESS [ 11.075 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Shim Aggregator SUCCESS [  0.069 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark Scala UDF Plugin SUCCESS [ 35.900 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark Distribution ... SUCCESS [  0.124 s]
11:59:46  [INFO] RAPIDS Accelerator for Apache Spark Tests .......... FAILURE [ 44.202 s]
11:59:46  [INFO] rapids-4-spark-integration-tests_2.12 .............. SKIPPED
11:59:46  [INFO] rapids-4-spark-api-validation ...................... SKIPPED
11:59:46  [INFO] ------------------------------------------------------------------------
11:59:46  [INFO] BUILD FAILURE
11:59:46  [INFO] ------------------------------------------------------------------------
11:59:46  [INFO] Total time: 01:55 min
11:59:46  [INFO] Finished at: 2020-11-25T19:59:48+00:00
11:59:46  [INFO] Final Memory: 116M/1315M
11:59:46  [INFO] ------------------------------------------------------------------------
```

**Comment by abellina** [comment]
Looks related to: https://github.com/apache/spark/pull/30432. So `ShuffleExchangeLike` changed and `canChangeNumPartitions` became `shuffleOrigin`

**Comment by mythrocks** [comment]
> Looks related to: apache/spark#30432. So ShuffleExchangeLike changed and canChangeNumPartitions became shuffleOrigin

#1206 has been committed. (Thanks, @jlowe.) I'll try a rebuild.

**Comment by mythrocks** [comment]
build

**Comment by jlowe** [comment]
> #1206 has been committed. (Thanks, @jlowe.) I'll try a rebuild.\

Note that you'll need to upmerge to branch-0.3 to pick up the fix in CI.

**Comment by mythrocks** [comment]
build

**Comment by sameerz** [comment]
build

**Comment by mythrocks** [comment]
> build

Thanks, @sameerz. The builds launched when I rebased seemed to hang as well. It seems to have worked that time. w007!

**Pull request merged**
