### PR TITLE
CaseWhen supports scalar of list and struct

### PR DESCRIPTION
**Pull request by firestarman**
Let `CaseWhen` support scalar of list and struct.

closes https://github.com/NVIDIA/spark-rapids/issues/2445

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
This PR depends on https://github.com/rapidsai/cudf/pull/8588/ , so it is draft.

**Comment by firestarman** [comment]
After the rapidsai/cudf#8588 is merged, I will verify whether the nested array and struct are supported. Since the cudf tests do not cover the cases.

**Review by jlowe — DISMISSED** [review]

**Comment by firestarman** [comment]
Ready for reivew because rapidsai/cudf#8588 has been merged.

**Review by wbo4958 — APPROVED** [review]
LGTM

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
I am going to merge this to unblock https://github.com/NVIDIA/spark-rapids/pull/2839, if any concern, we can have following PRs.

**Pull request merged**
