### PR TITLE
Support sample on ANSI interval types

### PR DESCRIPTION
**Pull request by res-life**
Contributes #4811

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Review by firestarman — COMMENTED** [review]
GLTM

**Review by revans2 — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
Build failure appears to be same issue as #5211

**Comment by res-life** [comment]
build

**Pull request merged**
