### PR TITLE
Revert Spark UT framework [databricks] 

### PR DESCRIPTION
**Pull request by binmahone**
…ts (#10743)"

This reverts commit 4dee2f841cfe4b102c2837f715f060e144502eed.

Because something went wrong with the databricks build.

### CODE REVIEW

**Comment by binmahone** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]
Revert the Spark UT changes since the build on Databricks is broken.

**Comment by binmahone** [comment]
build

**Comment by GaryShen2008** [comment]
As we filed https://github.com/NVIDIA/spark-rapids/pull/10796 to fix the problem, we can close this PR.

**Pull request closed without merging**
