### PR TITLE
Ensure column names are valid when writing benchmark query results to file

### PR DESCRIPTION
**Pull request by andygrove**
Ensure column names are valid when writing benchmark query results to file.

This closes https://github.com/NVIDIA/spark-rapids/issues/1246

### CODE REVIEW

**Comment by abellina** [comment]
Is this an issue for CPU plans as well? Or just the GPU plans?

**Comment by andygrove** [comment]
Yes, this happens on CPU as well:

```
org.apache.spark.sql.AnalysisException: Attribute name "round((sun_sales1 / sun_sales2), 2)" contains invalid character(s) among " ,;{}()\n\t=". Please use alias to rename it.;
	at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaConverter$.checkConversionRequirement(ParquetSchemaConverter.scala:583)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaConverter$.checkFieldName(ParquetSchemaConverter.scala:574)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport$.$anonfun$setSchema$2(ParquetWriteSupport.scala:472)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetWriteSupport$.$anonfun$setSchema$2$adapted(ParquetWriteSupport.scala:472)
```

**Review by abellina — APPROVED** [review]

**Comment by abellina** [comment]
build

**Comment by sameerz** [comment]
build

**Comment by abellina** [comment]
This PR needs to be upmerged to include the latest changes in branch-0.3

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
tests timed out - build

**Comment by andygrove** [comment]
build

**Pull request merged**
