### PR TITLE
Add a pre-commit hook to reject large files

### PR DESCRIPTION
**Pull request by gerashegalov**
Prevents large files as in #2644. 

Contributes to #2420, #2674
    
Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
Developer's use case:
```
$ fallocate -l 51M tools/src/test/resources/bigfile.txt
$ git add tools/src/test/resources/bigfile.txt
$ git commit -m test

Reject files over 50M....................................................Failed
- hook id: check-added-large-files
- exit code: 1

tools/src/test/resources/bigfile.txt (52224 KB) exceeds 51200 KB.
```

**Comment by abellina** [comment]
sounds good, I'd argue for a limit that allows our current repo to pass CI without any extra sha restrictions (something like 2.5MB).

**Comment by gerashegalov** [comment]
> sounds good, I'd argue for a limit that allows our current repo to pass CI without any extra sha restrictions (something like 2.5MB).

@abellina unfortunately, 2.5MiB won't do it per @revans2's comment  https://github.com/NVIDIA/spark-rapids/issues/2674#issuecomment-858772026

```bash
$ git ls-files | xargs ls -alhS | head -3
-rw-rw-r-- 1 gshegalov gshegalov   44M Jun  9 11:00 tools/src/test/resources/spark-events-qualification/nds_q86_fail_test
-rw-rw-r-- 1 gshegalov gshegalov   44M Jun  7 17:09 tools/src/test/resources/spark-events-qualification/nds_q86_test
-rw-rw-r-- 1 gshegalov gshegalov  4.6M Jun  7 17:09 tools/src/test/resources/spark-events-qualification/dsAndDf_eventlog
```

**Comment by revans2** [comment]
> sounds good, I'd argue for a limit that allows our current repo to pass CI without any extra sha restrictions (something like 2.5MB).

What files are that big?  

```
$ find . -type f | xargs ls -lSh | head -10
-rw-rw-r-- 1 user user   44M Jun  9 16:10 ./tools/src/test/resources/spark-events-qualification/nds_q86_fail_test
-rw-rw-r-- 1 user user   44M Jun  9 16:10 ./tools/src/test/resources/spark-events-qualification/nds_q86_test
-rw-rw-r-- 1 user user  4.6M Jun  9 16:10 ./tools/src/test/resources/spark-events-qualification/dsAndDf_eventlog
-rw-rw-r-- 1 user user  2.2M Jun  9 16:10 ./tools/src/test/resources/spark-events-profiling/rapids_join_eventlog
-rw-rw-r-- 1 user user  2.2M Jun 10 13:11 ./tools/src/test/resources/spark-events-profiling/rapids_join_eventlog2
-rw-rw-r-- 1 user user  1.7M Jun  9 16:10 ./tools/src/test/resources/spark-events-profiling/malformed_json_eventlog
-rw-rw-r-- 1 user user  1.7M Jun  9 16:10 ./tools/src/test/resources/spark-events-profiling/rp_sql_eventlog
-rw-rw-r-- 1 user user  1.6M Jun 10 13:11 ./tools/src/test/resources/spark-events-qualification/join_missing_sql_end
-rw-r--r-- 1 user user  1.1M Aug 21  2020 ./integration_tests/src/test/resources/Acquisition_2007Q3.txt
-rw-rw-r-- 1 user user 1003K Jun 10 13:11 ./tools/src/test/resources/spark-events-profiling/tasks_executors_fail_compressed_eventlog.zstd
```

It is all of the files that were just added in as a part of the tools tests.  Everything before that was small, and I would argue we should not have allowed the tools files in. We should have flagged it early on and someone should have looked at it and thought do we really need a 44M MiB file checked into the repo.

**Comment by revans2** [comment]
> those files can be compressed as well or we can decide to move them out

That does not fix the problem.  Once they are in the repo unless we do surgery to it, like we just did, they will be downloaded every time.  The point of these are not to fix what was already done. The point of this is to stop it from ever happening again in the future and making the problem worse

**Review by revans2 — APPROVED** [review]

**Comment by abellina** [comment]
Never mind (re 2.5MB). I was assuming the output from an earlier comment was all inclusive.

**Comment by gerashegalov** [comment]
build

**Pull request merged**
