### PR TITLE
Support repetitions in regexp choice expressions

### LINKED ISSUE #8045: [FEA] Support repetition in choice on regular expressions
**Is your feature request related to a problem? Please describe.**
I wish the RAPIDS Accelerator for Apache Spark would support repetitions on one side of a choice in regular expressions:

```
from pyspark.sql.functions import col
data = [("1", "123"), 
        ("2", "456"),
        ("3", "789"),
        ("4", "abc")]
df = spark.createDataFrame(data=data, schema=["id", "value"])
result = df.filter(col("value").rlike("[\d]+|[a-z]+"))
result.show()
```

Relevant unsupported message:
```
  !Exec <FilterExec> cannot run on GPU because not all expressions can be replaced
    @Expression <And> (isnotnull(value#1) AND RLIKE(value#1, [\d]+|[a-z]+)) could run on GPU
      @Expression <IsNotNull> isnotnull(value#1) could run on GPU
        @Expression <AttributeReference> value#1 could run on GPU
      !Expression <RLike> RLIKE(value#1, [\d]+|[a-z]+) cannot run on GPU because cuDF does not support repetition on one side of a choice near index 0
```

**Describe the solution you'd like**
I would like the RLike here to run on the GPU.

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #8045.

This is like #8047 in that there are no real transpiler updates but just enabling features. In this, choice expressions such as `a+|b`, `aab|b{1,2}`, and other repetitions are now enabled to work on the GPU.  These were likely fixed in https://github.com/rapidsai/cudf/pull/11654. There is one limitation: zero-length matching repetitions (ie ones that use `*` or `?` or `{0,n}`) are not supported in regexp_replace and regexp_split.  Unit tests have also been updated.

EDIT: There was one case for line anchors in choice for regexp_replace that was missed in #8047, this PR fixes that bug as well.

### CODE REVIEW

**Comment by NVnavkumar** [comment]
Leaving this in draft so that #8047 can be merged first, and the integration test for regexp choice expressions can be updated from that PR.

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

**Review by andygrove — APPROVED** [review]

**Pull request merged**
