### PR TITLE
Revert "Ignore failing Parquet filter test to unblock CI (#9519)"

### PR DESCRIPTION
**Pull request by sameerz**
Issue https://github.com/rapidsai/cudf/issues/14315 is closed with PR https://github.com/rapidsai/cudf/pull/14322 

This PR adds back tests for "Parquet filter pushdown - timestamp" by reverting commit eeb4168382c63a00201a1dbc833abca76a7d9828.

Closes https://github.com/NVIDIA/spark-rapids/issues/9507

### CODE REVIEW

**Comment by sameerz** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Review by jlowe — APPROVED** [review]
CI failed because the re-enabled test failed.  The cudf change had not yet been propagated to the spark-rapids-jni snapshot.  It should be there now after last night's build.

**Comment by jlowe** [comment]
build

**Pull request merged**
