### PR TITLE
Qualification tool: Update expected result for test

### PR DESCRIPTION
**Pull request by nartal1**
This fixes https://github.com/NVIDIA/spark-rapids/issues/3435

Updated the expected result as the score changed due to support of ORC read for map https://github.com/NVIDIA/spark-rapids/pull/3394

### CODE REVIEW

**Comment by nartal1** [comment]
build

**Comment by tgravescs** [comment]
please don't merge until https://github.com/NVIDIA/spark-rapids/pull/3411 and this will likely need upmerged

**Comment by tgravescs** [comment]
@nartal1 can you upmerge and then put the tests back in?  I commented it out in pr 3411.

**Comment by nartal1** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
