### PR TITLE
Download artifacts via wget [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
To fix: https://github.com/NVIDIA/spark-rapids/issues/11502

Download jars using wget instead of 'mvn dependency:get' to fix 'missing intermediate jars' failures, as we stopped deploying these intermediate jars since version 24.10

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
skip CI as the pre-merge job can not cover the change

**Comment by NvTimLiu** [comment]
Build PASS locally:

image

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Pull request merged**
