### PR TITLE
Merge branch 'branch-23.08' into main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge branch 'branch-23.08' into main

Change spark-rapids version to v23.08.0

**NOTE: merge this PR via "create a merge commit"**

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
Will upmerge CHANGELOG PR and other changes targeting to the branch-23.08 later. 

This change is for in-advance commit history review, thanks!

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
Please upmerge later to include latest bug fix and dep version bump up changes

We will merge remained doc update and changelog change next Monday and start building RC, thanks

**Review by jlowe — APPROVED** [review]
Missing some recent changes and more are pending, but what's here lgtm.

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
waiting for https://github.com/NVIDIA/spark-rapids/issues/9021

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
