### PR TITLE
Workaround for Databricks using AQE even when disabled

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/6158

It seems that Databricks is using AQE for some Delta stats even when we disable it in Spark. We see this on Databricks 10.4 with certain queries using delta files.

To workaround this we look for ProjectExecs that have ScalaUDFs using a function that contains tahoe.Snapshot as that is what we have seen from the stack traces. We also check explicitly for AdaptiveSparkPlan.  On Databricks, we don't support AQE right now so it shouldn't be used. In both cases we fallback to the CPU to run those operations.

Tested manually on queries that were failing and no longer see these failures.  Checking with customer to validate as well.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by revans2 — APPROVED** [review]
Are there any tests that we can add to verify that this is working? I know that #5981 is adding in some support for delta lake tests. Perhaps we can have a follow on issue to look into extending some of that for Databricks.

**Comment by tgravescs** [comment]
we don't have any current tests because we haven't been able to reproduce it consistently. I will file a followup though to see if we can narrow it down more to get a test added.

**Comment by tgravescs** [comment]
https://github.com/NVIDIA/spark-rapids/issues/6171 filed

**Comment by tgravescs** [comment]
databricks build is having timeout issues

**Pull request merged**
