### PR TITLE
Update cudfjni version to released 21.12.0 [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

I will trigger CI after cudfjni 21.12.0 is available on maven central

### CODE REVIEW

**Comment by pxLi** [comment]
converted to draft to avoid accidental merge

**Review by jlowe — APPROVED** [review]
> converted to draft to avoid accidental merge

Curious, if this passes CI why wouldn't we want to merge it?

**Comment by pxLi** [comment]
> > converted to draft to avoid accidental merge
> 
> Curious, if this passes CI why wouldn't we want to merge it?

ah yes, if CI passed we could merge it. We will start build cudfjni after cudf make the release

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
Going to merge this and trigger nightly build w/ released cudfjni

**Pull request merged**
