### PR TITLE
Fix explode with carry-along columns on GpuExplode single row retry handling

### PR DESCRIPTION
**Pull request by abellina**
This fixes a bug introduced as I applied review changes from this PR https://github.com/NVIDIA/spark-rapids/pull/10131, and no tests touched the multi-column carry-along scenario.

This fixes the bug and adds another column to exercise it.

Closes https://github.com/NVIDIA/spark-rapids/issues/10088.

### CODE REVIEW

**Review by jlowe — DISMISSED** [review]

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
