### PR TITLE
Decrease pre_merge_ci parallelism to 4 and reordering time-consuming tests

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

we added more test cases which made the mem usage for ci_2 in an unstable state.
Decrease it to 4 from 5, and will keep monitoring this.

Rebalance ci_1 and ci_2 to leave space for 320 UT

Also put expensive test cases to the head of xdist worker queue to avoid some cases got assigned to worker too late and increase the total time. Saved ~10 mins

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by zhanga5 — APPROVED** [review]

**Pull request merged**
