### PR TITLE
Optimize Databricks Jenkins scripts [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Remove duplicate try/catch/container script blocks

Move default Databricks parameters into the common Groovy library

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]
LGTM if CI pass, thanks

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Review by pxLi — APPROVED** [review]

**Comment by NvTimLiu** [comment]
There's no actual change from from commit2 to commit3 for the pre-merge CI, 
As we just PASS commit2's pre-merge CI, let's skip CI for the commit3 change.

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
