### PR TITLE
Hardcode python 3.8 to be used in databricks runtime for cudf_udf ENV [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
per https://docs.rapids.ai/notices/rsn0022/, and related issue https://github.com/rapidsai/cudf/issues/12764

hardcode the databricks python ENV version to 3.8

workaround #7639 
followup fix for #7737 

also skip pandas import check in db113 runtime for now to avoid fail require_minimum_pandas_version() check 
```
incorrect pandas version during required testing partially initialized 
module 'pandas' has no attribute '__version__' 
(most likely due to a circular import)
```

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Comment by NvTimLiu** [comment]
Suppose skipping cudf-udf test on DB113 is a temp workaround way. Is there any issue following up pandas import failure on DB113? Or are we good not skipping it?

```
incorrect pandas version during required testing partially initialized 
module 'pandas' has no attribute '__version__' 
(most likely due to a circular import)
```

**Pull request merged**
