### PR TITLE
Verify shuffle of decimal columns

### PR DESCRIPTION
**Pull request by sperlingxx**
This PR is about to verify shuffle of decimal columns through appending decimal column into TableBuilders for shuffle related test.

### CODE REVIEW

**Comment by sperlingxx** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Comment by sperlingxx** [comment]
build

**Comment by jlowe** [comment]
Test failure appears to be related.

**Comment by sperlingxx** [comment]
> Test failure appears to be related.

It failed because it relies on the contiguous split commit which has been reverted.

**Comment by jlowe** [comment]
build

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
build

**Comment by pxLi** [comment]
> build

@sperlingxx did you upmerge your commit to the latest? It failed due to `HiveStringType` on 310 which jason fix yesterday.
image

**Comment by sperlingxx** [comment]
> > build
> 
> @sperlingxx did you upmerge your commit to the latest? It failed due to `HiveStringType` on 310 which jason fixed #1218 yesterday.
> image

Hi Peixin, I conducted the up-merge in local, but I still got failures during locally running integration tests.

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
build

**Pull request merged**
