### PR TITLE
Revert "Disable asserts for non-empty nulls (#8183)" [databricks]

### LINKED ISSUE #5430: [FEA] Add in asserts when column views are created to verify that array nulls are empty
There is some upcoming work in CUDF where to be able to do some complicated operations correctly on arrays/lists we need to be 100% positive that if a list is null then the start and end offsets for that row point to the same index.  i.e. a null list must be backed by an empty list. Arrow does not have this same requirement. It is expensive to always check that this is true and it is also expensive to fix it when it is not true, so CUDF has decided to take the route of assuming that it will always be true for these operations and making sure that this will be true for the output of any operation from CUDF so long as the input to it also follows those guidelines.

Now we need to make sure that we are always going to follow those guidelines. We plan on doing this by having an check that can be enabled/disabled for testing every time we create column_view/column of lists and throw an exception if it is not true. CUDF plans to do some of this themselves to make sure that they can guarantee that their processing does the right thing. Hopefully we can use their same functionality when we run tests. If not, then we are going to need to add something ourselves that can be turned on or off when the JVM starts up to do these same kinds of checks. 

Then we need to fix anywhere that we find issues. I don't know how slow this is going to be for testing. If it is too slow we may only do it nightly.

At a minimum we are also going to have to explicitly check/clean up any data we get externally, if CUDF does not end up doing it for us. This is any data we get from arrow and just import in ourselves.

### LINKED ISSUE #8184: Enable asserts for checking non-empty nulls
As part of #8183 we disabled asserts for checking non-empty nulls. This is a follow-on issue to have a proper fix where we only disable the assertions where it's ok for us to have non-empty nulls and no where else

### LINKED ISSUE #8308: [BUG] Device Memory leak seen in integration_tests when AssertEmptyNulls are enabled
**Describe the bug**
Device memory is being leaked in integration_tests

**Steps/Code to reproduce bug**
Revert #8183 and run test_cast_nested or any of the following tests 

*  test_cast_array_to_string
*  test_cast_map_to_string
*  test_struct_count_distinct_cast
*  test_cast_struct_to_string

```
../../src/main/python/cast_test.py::test_cast_nested[Array(Byte)-ArrayType(IntegerType(), True)][INJECT_OOM] ### CPU RUN ###
### GPU RUN ###
23/05/17 19:12:27 WARN GpuOverrides: 
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#4 could run on GPU

### COLLECT: GPU TOOK 0.7290856838226318 CPU TOOK 4.090673923492432 ###
PASSED
../../src/main/python/cast_test.py::test_cast_nested[Array(Decimal(36,5))-ArrayType(DecimalType(38,5), True)][INJECT_OOM] ### CPU RUN ###
### GPU RUN ###
23/05/17 19:12:31 WARN GpuOverrides: 
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#12 could run on GPU

23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 68 0)
23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 33 0)
23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 32 0)
23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 69 0)
23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 138 0)
23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 139 0)
23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 167 0)
23/05/17 19:12:31 ERROR DeviceMemoryBuffer: A DEVICE BUFFER WAS LEAKED (ID: 113 0)
### COLLECT: GPU TOOK 1.3614916801452637 CPU TOOK 1.4461793899536133 ###

```

**Expected behavior**
There should be no leaks

### PR DESCRIPTION
**Pull request by razajafri**
This reverts commit 6f3818939a44c087122658e2860c2bf4cd7e4792 and enables asserts for non-empty nulls 

fixes #8184 
fixes #8308 
fixes #5430

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
Looks like there are memory leaks seen in the CI. I didn't see them in my smoke test. I will try to recreate them and update this PR

**Comment by razajafri** [comment]
This PR depends on https://github.com/rapidsai/cudf/pull/13597

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
Databricks is unreachable in the premerge

**Comment by razajafri** [comment]
build

**Comment by revans2** [comment]
build

**Comment by razajafri** [comment]
The DB is crashing because there is a double-free corruption happening on DB. I am currently working on root causing it

**Comment by razajafri** [comment]
This is caused by a `cudf::split` returning a ColumnView with non-empty nulls. I have created an issue for ithttps://github.com/rapidsai/cudf/issues/13638 

One thing to note is that DB CI is running cache_tests with PCBS enabled, while on other env we don't run PCBS tests

**Comment by razajafri** [comment]
I have verified that rapidsai/cudf#13647 fixes the issue on DB and on spark-311 when tested locally. I will kickoff premerge for this once cudf nightly has been published

**Comment by ttnghia** [comment]
build

**Comment by razajafri** [comment]
```
[2023-06-30T13:15:22.758Z] [gw0][36m [  0%] [0m[32mPASSED[0m ../../src/main/python/arithmetic_ops_test.py::test_addition_subtraction_mixed[+-Decimal(15,3)-Decimal(4,2)][INJECT_OOM] 
[2023-06-30T13:15:22.758Z] ../../src/main/python/arithmetic_ops_test.py::test_addition_subtraction_mixed[+-Decimal(15,3)-Decimal(3,-2)][INJECT_OOM] 23/06/30 13:15:22 ERROR Executor: Exception in task 1.0 in stage 24.0 (TID 97)
[2023-06-30T13:15:22.758Z] java.lang.ArithmeticException: Decimal(expanded,-7.6299917396276706084744903254669041E+39,36,-5}) cannot be represented as Decimal(38, 0).
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.types.Decimal.toPrecision(Decimal.scala:369)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.types.Decimal.floor(Decimal.scala:522)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2023-06-30T13:15:22.758Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-06-30T13:15:22.758Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-06-30T13:15:22.758Z] 	at java.lang.Thread.run(Thread.java:750)
[2023-06-30T13:15:22.758Z] 23/06/30 13:15:22 WARN TaskSetManager: Lost task 1.0 in stage 24.0 (TID 97) (premerge-ci-2-jenkins-rapids-premerge-github-7424-4gbrb-qvkh8 executor driver): java.lang.ArithmeticException: Decimal(expanded,-7.6299917396276706084744903254669041E+39,36,-5}) cannot be represented as Decimal(38, 0).
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.types.Decimal.toPrecision(Decimal.scala:369)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.types.Decimal.floor(Decimal.scala:522)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
[2023-06-30T13:15:22.758Z] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
[2023-06-30T13:15:22.758Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2023-06-30T13:15:22.758Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2023-06-30T13:15:22.759Z] 	at java.lang.Thread.run(Thread.java:750)
```

Seems like INJECT_OOM is causing ArithmeticException to be thrown. Still looking into this more

**Comment by razajafri** [comment]
So, only 340 still has memory leaks and the pre-merge fails due to JVM crash. Looking into this, will post an update ASAP

**Comment by razajafri** [comment]
I am unable to repro the crash on my workstation after running the crashing test, which seems to be `RegularExpressionTranspilerSuite` from the log. I also ran `OrcScanSuite` which shows memory leaks in pre-merge but not on my workstation. Researching further into the version of cudf running on pre-merge as there may be a discrepancy there.

**Comment by razajafri** [comment]
There is a separate [bug](https://github.com/NVIDIA/spark-rapids/issues/8418) for tracking this problem. Since it seems to be intermittent and most probably unrelated to this PR I will kick off the pre-merge again

**Comment by razajafri** [comment]
build

**Pull request merged**
