### PR TITLE
Update cudf Java bindings to 21.06.1

### PR DESCRIPTION
**Pull request by pxLi**
Update cudfJNI to 21.06.1
UPdate cudf py to 21.06.01

### CODE REVIEW

**Review by GaryShen2008 — APPROVED** [review]

**Review by NvTimLiu — APPROVED** [review]

**Comment by pxLi** [comment]
I will trigger pre-merge after cudfJNI 21.06.1 get deployed to central maven

**Comment by pxLi** [comment]
HOLD to wait for confirm of missed commit (https://github.com/rapidsai/cudf/commit/b5ffdf5ffb398adef25435bc696df3ff30c4aa9a) in cudf native v21.06.01

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
failed w/ repository.apache.org: Unknown host repository.apache.org
apache snapshot repo seems unreliable right now

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
DNS issue again

**Comment by pxLi** [comment]
build

**Pull request merged**
