### PR TITLE
Update Spark2 explain code for 22.06

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/5451.

Update the spark 2.x explain api code to pull in all the various changes. Run through the diff script and udpated everything I saw.  I manually ran this against tpcds queries and looked at output, only diff from 22.04 was dealing with a cast (Casting from floating point types to integral types) is now supported because we enabled it by default in 22.06.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by HaoYang670** [comment]
Build failure is due to #5744

**Comment by tgravescs** [comment]
build

**Review by nartal1 — APPROVED** [review]
LGTM. I ran diff for some of the files locally and got the same  results as above.
@tgravescs Can this be merged now OR should we wait for pending PR's for 22.06 ?

**Comment by tgravescs** [comment]
as far as I know everything pending isn't messing with the metadata but I'll keep an eye out.  merging it now.

**Pull request merged**
