### PR TITLE
Fix Java OOM in non-UTC case with lots of xfail (#9944)

### PR DESCRIPTION
**Pull request by res-life**
Cherry-pick OOM fix from branch-24.02 to branch-23.12

### CODE REVIEW

**Comment by res-life** [comment]
build

**Review by pxLi — DISMISSED** [review]

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
re-targeted to branch-23.12 and re-triggered CI

**Comment by res-life** [comment]
Sorry for targeting to a wrong branch.

**Review by pxLi — APPROVED** [review]

**Pull request merged**
