### PR TITLE
Merge branch-0.3 PRs onto main

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge branch-0.3 PRs onto main for release

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by jlowe** [comment]
Was this done a bit too early?  There are still PRs pending against branch-0.3 like #1371.

**Comment by pxLi** [comment]
> Was this done a bit too early? There are still PRs pending against branch-0.3 like #1371.

I was assuming this one was supposed to carry https://github.com/NVIDIA/spark-rapids/pull/1439 and get a fresh jar for QA regression testing.

cc @NvTimLiu @GaryShen2008 , I think there will be a final merge after no pending 0.3 PRs

**Comment by GaryShen2008** [comment]
> 
> 
> Was this done a bit too early? There are still PRs pending against branch-0.3 like #1371.
#1371 seems the doc update, it can be merged later.
This merge is to build the new staging jar for the AQE fixing.
Yes, we'll do a final merge from 0.3 to main at last for the docs.

**Pull request merged**
