### PR TITLE
Fix loading of ORC files with missing column names

### PR DESCRIPTION
**Pull request by jlowe**
This fixes an issue where ORC files without column names are not always going through positional evolution when aligning the read schema to the file schema.  If it fails to go through positional evolution when there are no column names, the file will be loaded as all nulls since it won't be able to find any of the read schema column names.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
The build failed because of tests in OrcScanSuite that are explicitly expecting the GPU loading behavior to be different than the CPU behavior.  The test is trying to load column names as the un-named column identifiers, e.g.: "_col3".  Spark CPU loads these positionally, and we should as well.  Updated the test to expect to match CPU behavior.

**Comment by jlowe** [comment]
build

**Review by abellina — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Review by razajafri — APPROVED** [review]

**Pull request merged**
