### PR TITLE
Add metrics documentation to the tuning guide

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

Add metrics documentation to the tuning guide.

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
@andygrove curious why this was closed without being merged?

**Comment by andygrove** [comment]
I didn't intentionally close this. I'm not sure what happened. Reopening.

**Comment by jlowe** [comment]
build

**Comment by andygrove** [comment]
I was deleting stale branches on my repo recently so I guess I deleted this branch by mistake.

**Pull request merged**
