### PR TITLE
Add `isFailed()` to MockTaskContext and Remove MockTaskContextBase.scala  [databricks]

### PR DESCRIPTION
**Pull request by razajafri**
This PR removes the MockContextBase and instead adds a method to MockTaskContext.scala

### CODE REVIEW

**Comment by razajafri** [comment]
@gerashegalov PTAL

This should go in after #9967 because the premerge on that has almost completed

**Review by gerashegalov — APPROVED** [review]
LGTM

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Review by gerashegalov — APPROVED** [review]

**Pull request merged**
