### PR TITLE
Fix Support of MapType in joins on Databricks

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/3078

reference https://github.com/NVIDIA/spark-rapids/pull/3011 which just missed the databricks shims for enabling the support.

Manually tested join_test on on databricks 7.3 and 8.2.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by tgravescs** [comment]
timed out for some reason

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
11:58:17  Cannot contact premerge-test-it-jenkins-rapids-premerge-github-2212-93ql-gq1c5: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
14:23:53  Cancelling nested steps due to timeout

@pxLi ideas on above, can we have it fail build, seems like it waited for timeout

**Comment by pxLi** [comment]
> 11:58:17 Cannot contact premerge-test-it-jenkins-rapids-premerge-github-2212-93ql-gq1c5: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
> 14:23:53 Cancelling nested steps due to timeout
> 
> @pxLi ideas on above, can we have it fail build, seems like it waited for timeout

Looks like ephemeral issue caused pod lost, please let me know if you see this frequently in the future.

**Pull request merged**
