### PR TITLE
Include memory access costs in cost models (cost-based optimizer)

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

This PR starts to introduce the mechansim for including memory access costs in the cost model. The default settings are 320 GB/s for GPU and 30 GB/s for CPU.

This also contains a fix for a bug that was highlighted during testing where CBO could move a BroadcastExchange back to CPU but leave the BHJ on GPU, resulting in an invalid plan.

### CODE REVIEW

**Review by revans2 — DISMISSED** [review]

**Comment by revans2** [comment]
> @revans2 This is what I have so far for incorporating memory access costs. It's very early and I have plenty to fix already but wanted to get your feedback early on to make sure I am heading in the right direction. I will handle kernel costs in a separate PR.

Jason had a good point when we talked that it is not really kernel costs as much as it is a fixed cost per operation. The cost of launching a kernel is likely small compared to other parts of the computation.

**Comment by andygrove** [comment]
@revans2 This is ready for review now.

**Comment by andygrove** [comment]
I filed a follow-on issue for improving our handling of BHJ: https://github.com/NVIDIA/spark-rapids/issues/2417

**Review by revans2 — DISMISSED** [review]
This looks fine to me, but I would like to hear from others

**Comment by andygrove** [comment]
I filed https://github.com/NVIDIA/spark-rapids/issues/2430 for adding kernel launch costs

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
Rebased to pull in fix for test failure

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
@revans2 Any objection to me merging this now so we can see the impact in the automated benchmarks?

**Review by revans2 — APPROVED** [review]

**Pull request merged**
