### PR TITLE
Fix host memory buffer leaks in SerializationSuite

### PR DESCRIPTION
**Pull request by jlowe**
Saw some logged leaks in recent unit test runs and tracked them down to host memory buffer leaks in SerializationSuite.  This fixes those host memory buffer leaks.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Review by abellina — APPROVED** [review]
thank you

**Pull request merged**
