### PR TITLE
use matrix to combine multiple jdk* jobs in maven-verify CI [skip ci]

### LINKED ISSUE #8275: [FEA] use matrix to combine multiple jdk* jobs in maven-verify CI
**Is your feature request related to a problem? Please describe.**
Follow up of https://github.com/NVIDIA/spark-rapids/pull/8234#discussion_r1188021188

This will help avoid the proliferation of copy and paste new jdk jobs in github workflow

**Describe the solution you'd like**
Use `matrix` for jdk* in https://github.com/NVIDIA/spark-rapids/blob/branch-23.06/.github/workflows/mvn-verify-check.yml#L146

### PR DESCRIPTION
**Pull request by YanxuanLiu**
fix #8275 

Added `jdk-version` to original matrix json.
Now the matrix list is like `{"include":[{"spark-version":"xxx","java-version":xx}]}'`

Also merged `jdk11` and `jdk17` stage into one `jdk` stage with the new matrix list.

### CODE REVIEW

**Comment by pxLi** [comment]
can you upmerge latest change and resolve the conflict from branch-23.06? thx

**Comment by gerashegalov** [comment]
Ideally we should fold `verify-all-modules-with-headSparkVersion` into the new matrix job. It's fine if it happens in a future PR. LGTM modulo pending upmerge

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]
LGTM. lets merge it after action CI passed

**Pull request merged**
