### PR TITLE
Compress large test event logs

### PR DESCRIPTION
**Pull request by nartal1**
This fixes https://github.com/NVIDIA/spark-rapids/issues/2644
Compressed the large event log files and updated the tests to read the compressed files.
Deleted the uncompressed files.

Signed-off-by: Niranjan Artal <nartal@nvidia.com>

### CODE REVIEW

**Comment by nartal1** [comment]
build

**Comment by nartal1** [comment]
build

**Comment by pxLi** [comment]
I have aborted the build ID 1849, new triggered 1850 is running.

plz help abort previous pre-merge runs to save resources in the future if trigger twice in short period, thx~

**Review by tgravescs — DISMISSED** [review]

**Comment by gerashegalov** [comment]
This PR looks good to me but let us discuss

**Comment by nartal1** [comment]
Will create another PR to update the tests.

**Pull request closed without merging**
