### PR TITLE
Fix ShimVectorizedColumnReader construction for recent Spark 3.3.0 changes

### LINKED ISSUE #5123: [BUG] Compile error for Spark330 because of VectorizedColumnReader constructor added a new parameter.
**Describe the bug**

mvn clean install -Dbuildver=330 -DskipTests
**not enough arguments for constructor VectorizedColumnReader**

```
[INFO] Compiler bridge file: /home/chong/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.12-1.3.1-bin_2.12.15__52.0-1.3.1_20191012T045515.jar
[INFO] Compiling 267 Scala sources and 29 Java sources to /home/chong/code/2-spark-rapids/sql-plugin/target/spark330/classes ...
[ERROR] [Error] /home/chong/code/2-spark-rapids/sql-plugin/src/main/321+/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ShimVectorizedColumnReader.scala:58: not enough arguments for constructor VectorizedColumnReader: (x$1: org.apache.parquet.column.ColumnDescriptor, x$2: org.apache.parquet.schema.LogicalTypeAnnotation, x$3: org.apache.parquet.column.page.PageReader, x$4: java.util.PrimitiveIterator.OfLong, x$5: java.time.ZoneId, x$6: String, x$7: String, x$8: String, x$9: String, x$10: org.apache.parquet.VersionParser.ParsedVersion)org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.
Unspecified value parameter x$10.
[ERROR] [Error] /home/chong/code/2-spark-rapids/sql-plugin/src/main/321+/scala/org/apache/spark/sql/execution/datasources/parquet/rapids/shims/ShimVectorizedColumnReader.scala:20: Unused import
[ERROR] two errors found
```

### LINKED ISSUE #5133: [BUG] Compile error for Spark330 because of Spark changed the method signature: QueryExecutionErrors.mapKeyNotExistError
**Describe the bug**

mvn clean install -Dbuildver=330 -DskipTests

[INFO] Compiling 267 Scala sources and 29 Java sources to /home/chong/code/2-spark-rapids/sql-plugin/target/spark330/classes ...
[ERROR] [Error] /home/chong/code/2-spark-rapids/sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/RapidsErrorUtils.scala:33: not enough arguments for method mapKeyNotExistError: (key: Any, isElementAtFunction: Boolean, context: String)NoSuchElementException.
Unspecified value parameter context.
[ERROR] one error found

Spark added a new parameter in `QueryExecutionErrors.mapKeyNotExistError`

**Additional context**
related to https://issues.apache.org/jira/browse/SPARK-38716 which affected 330+

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #5123.
Fixes #5133.

Adds in a `ParsedVersion` parameter which is new in the Spark 3.3.0 constructor for `VectorizedColumnReader`.  Creation of the parameter mirrors the same logic implemented in [SPARK-37974](https://issues.apache.org/jira/browse/SPARK-37974) and [SPARK-34863](https://issues.apache.org/jira/browse/SPARK-34863).

In addition this contains a build fix for the `QueryExecutionErrors` changes in [SPARK-38716](https://issues.apache.org/jira/browse/SPARK-38716).

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by tgravescs — DISMISSED** [review]

**Comment by jlowe** [comment]
Spark snapshots in premerge need to be updated to see the recent change.

**Comment by jlowe** [comment]
build

**Comment by res-life** [comment]
Another build PR: https://github.com/NVIDIA/spark-rapids/pull/5137

**Comment by jlowe** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
