### PR TITLE
Merge 0.4 to 0.5 [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
merge branch-0.4 to branch-0.5 to fix merge conflict https://github.com/NVIDIA/spark-rapids/pull/1993

**NOTE: this should be merged as a merge commit**

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
fixed commit history

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
