### PR TITLE
Removed spark.rapids.sql.castDecimalToString.enabled and enabled GPU decimal to string by default [databricks]

### PR DESCRIPTION
**Pull request by revans2**
This includes everything in https://github.com/NVIDIA/spark-rapids/pull/8439, but adds some fixes in the final commit.  The heavy lifting was done by @hyperbolic2346 

My part just adds in a few new integration tests so that the we are comparing to Spark instead of what we think Spark would produce in the current unit tests.  It also ads in a slow path for negative scale decimals in ANSI mode, which both of them are not common, so I think we might be okay with the slow path.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by jlowe — DISMISSED** [review]

**Comment by revans2** [comment]
looks like databricks 3.3.0 pulled in the Spark 3.4.0 cast change. Need to work on this a little more...

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by hyperbolic2346** [comment]
🎉

**Pull request merged**
