### PR TITLE
Update latest changelog [skip ci]

### PR DESCRIPTION
**Pull request by nvauto**
Update change log with CLI: 

   scripts/generate-changelog --token=<GIT_TOKEN> --releases=24.10,24.12

### CODE REVIEW

**Comment by YanxuanLiu** [comment]
NOTE: Merged Pull Requests w/o Project:
 ```
branch-24.12 #11752 Ability to decompress snappy and zstd Parquet files via CPU [databricks] https://github.com/NVIDIA/spark-rapids/pull/11752
 branch-24.12 #11759 Avoid using StringBuffer in single-threaded methods. https://github.com/NVIDIA/spark-rapids/pull/11759
 branch-24.12 #11766 Fix Kudo batch serializer to only read header in hasNext https://github.com/NVIDIA/spark-rapids/pull/11766
 branch-24.12 #11768 Fix `dpp_test.py` failures on [databricks] 14.3 https://github.com/NVIDIA/spark-rapids/pull/11768
 branch-24.12 #11771 Fix query hang when using rapids multithread shuffle manager with kudo https://github.com/NVIDIA/spark-rapids/pull/11771
 branch-24.12 #11777 Append knoguchi22 to blossom-ci whitelist [skip ci] https://github.com/NVIDIA/spark-rapids/pull/11777
 branch-24.12 #11794 exclude previous operator'\''s time out of firstBatchHeuristic https://github.com/NVIDIA/spark-rapids/pull/11794
 branch-24.12 #11832 Fix leak in GpuBroadcastNestedLoopJoinExecBase https://github.com/NVIDIA/spark-rapids/pull/11832
 branch-24.12 #11845 Fix leak in isTimeStamp https://github.com/NVIDIA/spark-rapids/pull/11845
```

**Comment by jlowe** [comment]
> NOTE: Merged Pull Requests w/o Project, please help check if we need update them!

All of these pull requests have a project, so not sure what's being requested here.  I set the roadmap to 24.12 and assigned a priority, but I don't understand why we would care about the project etc for PRs when generating a changelog.  The changelog should be generated by querying Github for what PRs went into the release branch, regardless of what the project says, i.e.: https://github.com/NVIDIA/spark-rapids/pulls?q=is%3Apr+is%3Amerged+base%3Abranch-24.12.  Labels can change whether it's grouped in bugfixes, feature, performance improvements, etc, but the list of what's there and what's not should soley be based on pull requests that were merged into the development branch.  Depending on metadata that needs to be manually updated is asking for trouble.

**Comment by NvTimLiu** [comment]
> > NOTE: Merged Pull Requests w/o Project, please help check if we need update them!
> 
> All of these pull requests have a project, so not sure what's being requested here. I set the roadmap to 24.12 and assigned a priority, but I don't understand why we would care about the project etc for PRs when generating a changelog. The changelog should be generated by querying Github for what PRs went into the release branch, regardless of what the project says, i.e.: https://github.com/NVIDIA/spark-rapids/pulls?q=is%3Apr+is%3Amerged+base%3Abranch-24.12. Labels can change whether it's grouped in bugfixes, feature, performance improvements, etc, but the list of what's there and what's not should soley be based on pull requests that were merged into the development branch. Depending on metadata that needs to be manually updated is asking for trouble.



> The changelog should be generated by querying Github for what PRs went into the release branch, regardless of what the project says

Yes, this suggestion is reasonable!

However, there may be other concerns regarding the project roadmap when generating the CHANGELOG.

I'll check with @pxLi and follow up on it.

**Comment by NvTimLiu** [comment]
> > > NOTE: Merged Pull Requests w/o Project, please help check if we need update them!
> > 
> > 
> > All of these pull requests have a project, so not sure what's being requested here. I set the roadmap to 24.12 and assigned a priority, but I don't understand why we would care about the project etc for PRs when generating a changelog. The changelog should be generated by querying Github for what PRs went into the release branch, regardless of what the project says, i.e.: https://github.com/NVIDIA/spark-rapids/pulls?q=is%3Apr+is%3Amerged+base%3Abranch-24.12. Labels can change whether it's grouped in bugfixes, feature, performance improvements, etc, but the list of what's there and what's not should soley be based on pull requests that were merged into the development branch. Depending on metadata that needs to be manually updated is asking for trouble.
> 
> > The changelog should be generated by querying Github for what PRs went into the release branch, regardless of what the project says
> 
> Yes, this suggestion is reasonable!
> 
> However, there may be other concerns regarding the project roadmap when generating the CHANGELOG.
> 
> I'll check with @pxLi and follow up on it.

Confirmed with @pxLi, we are good to generate the CHANGELOG from the target/release branch instead.

Previously, the CHANGELOG was managed by labels (the same as the project's roadmap); those PRs without a label are not included in the CHANGELOG.

We'll ignore the project roadmap checking and add PRs from the release branch to the CHANGELOG.

I'll follow up on it

**Comment by NvTimLiu** [comment]
Updated the CHANGELOG to latest, @sameerz can you help review it? Thanks!

**Comment by sameerz** [comment]
> Updated the CHANGELOG to latest, @sameerz can you help review it? Thanks!

I reviewed and made only a minor change in the issue list.  Am good if this is regenerated.

**Comment by YanxuanLiu** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Review by pxLi — APPROVED** [review]

**Pull request merged**
