### PR TITLE
Added Spark-3.4.2 Shims

### LINKED ISSUE #9260: [FEA] Create Spark 3.4.2 shim and build env
**Is your feature request related to a problem? Please describe.**
Create Spark 3.4.2 SNAPSHOT shim and build env

### PR DESCRIPTION
**Pull request by razajafri**
This PR adds shims for Spark-3.4.2. 

**Changes Made:**
Pretty much the result of running
```
mvn generate-sources -Dshimplify=true -Dshimplify.move=true -Dshimplify.overwrite=true -Dshimplify.add.shim=342 -Dshimplify.add.base=341
```
* The only files that were manually changed were pom.xml, SparkShimsSuite.scala and ShimServiceProvider.scala to add the 3.4.2 version to the VERSIONNAMES.
* Removed some empty lines as a result of the above Shimplify command. 
* Moved DecimalMultiply128.scala and GetSequenceSize.scala to the appropriate shim directory to maintain convention 

Tests:
All IT were run locally. 

fixes #9260

### CODE REVIEW

**Comment by tgravescs** [comment]
note this should have same issue with decimal multiply - https://github.com/NVIDIA/spark-rapids/issues/9859

**Comment by razajafri** [comment]
This uses changes from #9962 so until that is merged this will stay a draft PR

The following tests are failing but should be fixed when #9962 is merged 

```
====================================================================================== short test summary info 
FAILED ../../src/main/python/csv_test.py::test_csv_prefer_date_with_infer_schema[DATAGEN_SEED=1703008777, ALLOW_NON_GPU(FileSourceScanExec,CollectLimitExec,DeserializeToObjectExec)] - ValueError: year 0 is out of range
FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication[Decimal(38,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [907, '(CAST(-12 AS DECIMAL(38,10)) * b)']
FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Integer-Decimal(30,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [32, '(a * b)']
FAILED ../../src/main/python/collection_ops_test.py::test_sequence_too_long_sequence[Integer(not_null)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: Expected error 'Too long sequence' did not appear in 'py4j.protocol.Py4JJavaError: An error occurred while calling o45025.collectToPython.
FAILED ../../src/main/python/collection_ops_test.py::test_sequence_too_long_sequence[Long(not_null)][DATAGEN_SEED=1703008777] - AssertionError: Expected error 'Too long sequence' did not appear in 'py4j.protocol.Py4JJavaError: An error occurred while calling o45109.collectToPython.
FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(10,-2)-Decimal(30,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [50, '(a * b)']
FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(15,3)-Decimal(30,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [15, '(a * b)']
FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(30,12)-Integer][DATAGEN_SEED=1703008777] - AssertionError: GPU and CPU decimal values are different at [61, '(a * b)']
FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(30,12)-Decimal(16,7)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [37, '(a * b)']
FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(27,7)-Decimal(16,7)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [29, '(a * b)']
=============================================== 10 failed, 20648 passed, 1044 skipped, 380 xfailed, 294 xpassed, 8544 warnings in 2588.35s (0:43:08) ==========

```

**Comment by razajafri** [comment]
> This uses changes from #9962 so until that is merged this will stay a draft PR
> 
> The following tests are failing but should be fixed when #9962 is merged
> 
> ```
> ====================================================================================== short test summary info 
> FAILED ../../src/main/python/csv_test.py::test_csv_prefer_date_with_infer_schema[DATAGEN_SEED=1703008777, ALLOW_NON_GPU(FileSourceScanExec,CollectLimitExec,DeserializeToObjectExec)] - ValueError: year 0 is out of range
> FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication[Decimal(38,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [907, '(CAST(-12 AS DECIMAL(38,10)) * b)']
> FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Integer-Decimal(30,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [32, '(a * b)']
> FAILED ../../src/main/python/collection_ops_test.py::test_sequence_too_long_sequence[Integer(not_null)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: Expected error 'Too long sequence' did not appear in 'py4j.protocol.Py4JJavaError: An error occurred while calling o45025.collectToPython.
> FAILED ../../src/main/python/collection_ops_test.py::test_sequence_too_long_sequence[Long(not_null)][DATAGEN_SEED=1703008777] - AssertionError: Expected error 'Too long sequence' did not appear in 'py4j.protocol.Py4JJavaError: An error occurred while calling o45109.collectToPython.
> FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(10,-2)-Decimal(30,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [50, '(a * b)']
> FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(15,3)-Decimal(30,10)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [15, '(a * b)']
> FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(30,12)-Integer][DATAGEN_SEED=1703008777] - AssertionError: GPU and CPU decimal values are different at [61, '(a * b)']
> FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(30,12)-Decimal(16,7)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [37, '(a * b)']
> FAILED ../../src/main/python/arithmetic_ops_test.py::test_multiplication_mixed[Decimal(27,7)-Decimal(16,7)][DATAGEN_SEED=1703008777, INJECT_OOM] - AssertionError: GPU and CPU decimal values are different at [29, '(a * b)']
> =============================================== 10 failed, 20648 passed, 1044 skipped, 380 xfailed, 294 xpassed, 8544 warnings in 2588.35s (0:43:08) ==========
> ```

All of the above failing tests are now passing PTAL

**Comment by razajafri** [comment]
build

**Review by jlowe — COMMENTED** [review]
MockTaskContextBase needs a 342 shim directive added to it.

**Comment by razajafri** [comment]
> MockTaskContextBase needs a 342 shim directive added to it.

Done, PTAL

**Comment by razajafri** [comment]
build

**Comment by gerashegalov** [comment]
> MockTaskContextBase needs a 342 shim directive added to it.

@jlowe are you OK with getting rid of `MockTaskContextBase` per https://github.com/NVIDIA/spark-rapids/pull/10096#discussion_r1436600326

**Comment by jlowe** [comment]
> are you OK with getting rid of MockTaskContextBase

Yes, that's fine with me.

**Review by jlowe — APPROVED** [review]

**Comment by gerashegalov** [comment]
@razajafri I would drop MockTaskContextBase per https://github.com/NVIDIA/spark-rapids/pull/10096#discussion_r1436600326

**Comment by razajafri** [comment]
> @razajafri I would drop MockTaskContextBase per https://github.com/NVIDIA/spark-rapids/pull/10096#discussion_r1436600326

Keeping in line with keeping the PRs focused on what they are supposed to do, I think that should be a separate PR. What do you think about that?

**Comment by gerashegalov** [comment]
> Keeping in line with keeping the PRs focused on what they are supposed to do, I think that should be a separate PR. What do you think about that?

It is a valid point.  Just thought of it because it would have preempted this comment https://github.com/NVIDIA/spark-rapids/pull/9967#pullrequestreview-1797464507 in this PR.

**Pull request merged**
