### PR TITLE
[auto-merge] branch-0.2 to branch-0.3 - resolve conflict

### PR DESCRIPTION
**Pull request by tgravescs**
Fix the conflicts in https://github.com/NVIDIA/spark-rapids/pull/736

2 conflicts were  jenkins/spark-premerge-build.sh where the profile to include-databricks was removed and then other was in GpuCoalesceBatches where we changed the collect time metrics and the variable hasOnDeck changed names

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by revans2** [comment]
The newly added tests are failing for this in a way that looks like the python files in the jar were not added to the python path.

**Comment by tgravescs** [comment]
I'm going to go ahead and merge this.

**Comment by jlowe** [comment]
Note there are new changes on branch-0.2 that are not covered by this.

**Comment by jlowe** [comment]
Also remember to NOT squash this commit, must be a merge commit.

**Comment by tgravescs** [comment]
@GaryShen2008 @NvTimLiu @pxLi could you take a look at these test failures, is there something setup different in the 0.3 env?

**Comment by pxLi** [comment]
> @GaryShen2008 @NvTimLiu @pxLi could you take a look at these test failures, is there something setup different in the 0.3 env?

@tgravescs nothing different here for 0.3. we are seeing periodically failures should be related recent-merged python udf_test.
I saw @revans2 got this one https://github.com/NVIDIA/spark-rapids/pull/747, but there are still some udf tests are not marked as `skip` and could fail the test.

image

**Pull request merged**
