### PR TITLE
Unshim GpuColumnVector for easier debugging

### PR DESCRIPTION
**Pull request by gerashegalov**
This PR restores easier debugging in REPL. 
- Contributes to #5993
- Allows to compile XGBoost jvm-packages https://github.com/dmlc/xgboost/pull/8232

```Scala
scala> import ai.rapids.cudf._
import ai.rapids.cudf._

scala> import com.nvidia.spark.rapids._
import com.nvidia.spark.rapids._

scala> val dt = new HostColumnVector.ListType(true, new HostColumnVector.BasicType(true, DType.BOOL8))
dt: ai.rapids.cudf.HostColumnVector.ListType = ai.rapids.cudf.HostColumnVector$ListType@c546f73

scala> val singleEmptyListCV = ColumnVector.fromLists(dt, java.util.Arrays.asList())
singleEmptyListCV: ai.rapids.cudf.ColumnVector = ColumnVector{rows=1, type=LIST, nullCount=Optional.empty, offHeap=(ID: 6 7f60efd1f850)}

scala> GpuColumnVector.debug("singleEmtpy", singleEmptyListCV)
GPU COLUMN singleEmtpy - NC: 0 DATA: null VAL: null
GPU COLUMN singleEmtpy:DATA - NC: 0 DATA: null VAL: null
COLUMN singleEmtpy - LIST
OFFSETS
0 [0 - 0)
COLUMN singleEmtpy:DATA - BOOL8
```
Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by rwlee** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
This PR is likely to be closed without merging
- will file an separate PR for the jdeps analysis and the resulting issues
- I too verified that #6534 is a sufficient fix to resolve the issue with XGBoost  and it should be merged after addressing the other feedback .

**Comment by gerashegalov** [comment]
Due to the reflection-based nature of py4j used for pyspark accessing GpuColumnVector is easier from Python than in a Scala-based spark-shell
```Python
spark._jvm.com.nvidia.spark.rapids.GpuColumnVector.debug("equalTo", equalTo)
GPU COLUMN lessThan0_1 - NC: 0 DATA: DeviceMemoryBufferView{address=0x80000c000, length=1, id=-1} VAL: null
COLUMN lessThan0_1 - BOOL8
0 true
...
```

**Pull request closed without merging**
