### PR TITLE
Add the `FileIndexOptions` shims for Spark340

### LINKED ISSUE #6830: [Audit][SPARK-40667] Refactor File Data Source Options
**Is your feature request related to a problem? Please describe.**
https://github.com/apache/spark/commit/8e853933ba64bb43e02af78198bc36d471efaa18 refactored the File Data Source Options. For example, it moves the `BASE_PATH_PARAM` from `PartitioningAwareFileIndex` to `FileIndexOptions`.

We should move some values to the shim layer of spark340

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
close #6830.

## Changes in this PR
1. Add `330+-noncdh` to the spark340 build pom file.
2. Add `FileIndexOptionsShims` to `311until340` and `340` shims

## Rationals of the PR
Fix some compile error when building the plugin for spark340
### Before
```
...
[ERROR] [Error] /home/remziy/working/rapids/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuOrcFileFormat.scala:21: Unused import
[ERROR] 52 errors found

```

### After
```
...
[ERROR] [Error] /home/remziy/working/rapids/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala:1575: value checkForNumericExpr is not a member of object org.apache.spark.sql.catalyst.util.TypeUtils
[ERROR] 35 errors found
```

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

**Comment by HaoYang670** [comment]
@nartal1 could you please help to review?

**Review by nartal1 — APPROVED** [review]
LGTM. Thanks @HaoYang670 for putting up this fix!

**Review by gerashegalov — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Comment by HaoYang670** [comment]
Thanks all for your review.

**Pull request merged**
