### PR TITLE
Update to a valid cuda docker image for k8s run [skip ci]

### PR DESCRIPTION
**Pull request by wjxiz1992**
Signed-off-by: Allen Xu <allxu@nvidia.com>

To close: #6740.
Verified on internal DGX k8s cluster.

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by sameerz** [comment]
Before merging, can we also update the comments to recommend a Spark version 3.1+ instead of 3.0.2? 

https://github.com/NVIDIA/spark-rapids/blob/02b65587b45cd536515cb95776754b396157c5b6/docs/get-started/Dockerfile.cuda#L28-34

**Comment by wjxiz1992** [comment]
> Before merging, can we also update the comments to recommend a Spark version 3.1+ instead of 3.0.2?
> 
> https://github.com/NVIDIA/spark-rapids/blob/02b65587b45cd536515cb95776754b396157c5b6/docs/get-started/Dockerfile.cuda#L28-34

Updated.

**Review by GaryShen2008 — APPROVED** [review]

**Review by sameerz — APPROVED** [review]

**Comment by wjxiz1992** [comment]
build

**Pull request merged**
