### PR TITLE
Unit test for GPU exchange re-use with AQE

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

Implements a unit test to check that GPU exchanges are re-used correctly when AQE is enabled.

### CODE REVIEW

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Review by nartal1 — APPROVED** [review]
Test lgtm.

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
@nartal1 I had to rebase against branch-0.3, dismissing your previous approval.

**Review by nartal1 — APPROVED** [review]

**Pull request merged**
