### PR TITLE
Change version and branch to 24.02 in docs [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Version to 24.02.0-SNAPSHOT in CONTRIBUTING.md

Branch to branch-24.02 in docs/dev/testing.md

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
Odd  `mvn-verify-check.yml` GitHub action was not triggered : https://github.com/NVIDIA/spark-rapids/blob/branch-24.04/.github/workflows/mvn-verify-check.yml#L20

image

Try close-reopen to re-trigger  `mvn-verify-check.yml` check

**Pull request merged**
