### PR TITLE
Rename Spark 3.1.0 shim to Spark 3.1.1 to match community

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/1487

Rename the shim to match the community versions. There won't be a 3.1.0 so no reason to keep that shim. I left the 3.1.0-SNAPSHOT as supported in the service provider list for now in case anyone was using those snapshots.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by revans2 — APPROVED** [review]
My only concern is that `ParquetMaterializer` was moved, but it is not in a package that has the shim name in it, so if it changes again it might cause issues in the future, but this did nothing to cause that issue or fix it so it is fine.

**Comment by tgravescs** [comment]
@razajafri any reason the ParquetMaterializer wasn't in a shim specific package?  if not we should file an issue and put it in one. It can still be in the spark package for example we have: spark311/src/main/scala/org/apache/spark/sql/rapids/shims/spark311/GpuColumnarToRowTransitionExec.scala

**Comment by razajafri** [comment]
When I created the file I added a `rapids` to the end of the package name to make it obvious that it's a rapids file. I can file an issue to add `shims.spark311` to the end of the existing package. Will that work?

**Comment by tgravescs** [comment]
yes please match the other files in the shim with shims.spark311

**Pull request merged**
