### PR TITLE
Reenable tests originally bypassed for 3.4 [databricks]

### LINKED ISSUE #5748: [BUG] 3 cast tests fails on Spark 3.4.0
**Describe the bug**
In `AnsiCastOpSuite`.
```
- Copy ints to long *** FAILED ***
  java.lang.IllegalStateException: Expected 1 ansi_cast expressions, found 0
  at com.nvidia.spark.rapids.AnsiCastOpSuite.assertContainsAnsiCast(AnsiCastOpSuite.scala:833)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.doTableCopy(AnsiCastOpSuite.scala:759)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.$anonfun$new$177(AnsiCastOpSuite.scala:718)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect(SparkQueryCompareTestSuite.scala:423)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect$(SparkQueryCompareTestSuite.scala:419)
  at com.nvidia.spark.rapids.GpuExpressionTestSuite.collect(GpuExpressionTestSuite.scala:21)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.$anonfun$runOnCpuAndGpu$1(SparkQueryCompareTestSuite.scala:355)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:136)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession(SparkQueryCompareTestSuite.scala:197)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession$(SparkQueryCompareTestSuite.scala:192)
  ...
- Copy long to float *** FAILED ***
  java.lang.IllegalStateException: Expected 1 ansi_cast expressions, found 0
  at com.nvidia.spark.rapids.AnsiCastOpSuite.assertContainsAnsiCast(AnsiCastOpSuite.scala:833)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.doTableCopy(AnsiCastOpSuite.scala:759)
  at com.nvidia.spark.rapids.AnsiCastOpSuite.$anonfun$new$178(AnsiCastOpSuite.scala:722)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect(SparkQueryCompareTestSuite.scala:423)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.collect$(SparkQueryCompareTestSuite.scala:419)
  at com.nvidia.spark.rapids.GpuExpressionTestSuite.collect(GpuExpressionTestSuite.scala:21)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.$anonfun$runOnCpuAndGpu$1(SparkQueryCompareTestSuite.scala:355)
  at com.nvidia.spark.rapids.SparkSessionHolder$.withSparkSession(SparkQueryCompareTestSuite.scala:136)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession(SparkQueryCompareTestSuite.scala:197)
  at com.nvidia.spark.rapids.SparkQueryCompareTestSuite.withCpuSparkSession$(SparkQueryCompareTestSuite.scala:192)
```

In `CastOpSuite`.
```
- Test all supported casts with in-range values *** FAILED ***
  Cast from BooleanType to TimestampType failed; ansi=true org.apache.spark.sql.AnalysisException: cannot resolve 'CAST(c0 AS TIMESTAMP)' due to data type mismatch:
   cannot cast boolean to timestamp with ANSI mode on.
   If you have to cast boolean to timestamp, you can set spark.sql.ansi.enabled as false.
```

**Steps/Code to reproduce bug**
run `mvn test -Dbuildver=340`.

**Expected behavior**
Tests should pass

**Additional context**

### PR DESCRIPTION
**Pull request by rwlee**
Resolves #5748

https://github.com/NVIDIA/spark-rapids/pull/7152 

Tests were fixed as part of 11.3 -- unfortunately I had done duplicate work and only figured out these had already been fixed when hit a bunch of conflicts when upmerging.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by sameerz** [comment]
build

**Comment by revans2** [comment]
It looks like `test_partitioned_parquet_write[PartitionWriteMode.Dynamic][IGNORE_ORDER({'local': True})]` failed This might be related to https://github.com/NVIDIA/spark-rapids/issues/7679 so you might want to upmerge and try again.

**Comment by rwlee** [comment]
build

**Pull request merged**
