### PR TITLE
Update array_min and array_max to use new cudf operations

### PR DESCRIPTION
**Pull request by revans2**
CUDF finished work on segmented min and segmented max for strings and decimal. This lets us delete a lot of code and hopefully thing run even faster now too.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by jlowe — COMMENTED** [review]
Nice!  Has unused imports that failed the verify build, but otherwise lgtm.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
Our build system is too complicated. I do a build/buildall but it does not update the docs or warn me about style. So I have to do a buildall and a regular build for a single version to get everything I need to check before pushing something. This is really frustrating.

**Review by jlowe — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]
LGTM

**Comment by gerashegalov** [comment]
> Our build system is too complicated. I do a build/buildall but it does not update the docs or warn me about style. So I have to do a buildall and a regular build for a single version to get everything I need to check before pushing something. This is really frustrating.

One can obviously add whatever is missing to buildall . It does scalastyle on the lowest shim involved.  

At least now we receive this automated feedback in a couple of minutes instead of waiting for hours:  htps://github.com/NVIDIA/spark-rapids/runs/6528205143?check_suite_focus=true

**Comment by revans2** [comment]
@gerashegalov yes the few mins is so very nice compared to before.

**Pull request merged**
