### PR TITLE
Fix CDH Build 

### PR DESCRIPTION
**Pull request by razajafri**
This removes the SparkBaseShims.scala that was erroneously added as part of #3330

### CODE REVIEW

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
Note this has 3.2.0 test failures, but we will follow on with fix for that, this unblocks compilation failures.

**Pull request merged**
