### PR TITLE
Merge source to main branch from branch-21.12 [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Note:  `Create a Merge Request` to merge this PR

### CODE REVIEW

**Comment by NvTimLiu** [comment]
File the PR from code review, draft it as there are undergoing PRs need to merge to main

**Review by jlowe — COMMENTED** [review]
What's here seems fine, but we will also need #4258, #4307, and #4308

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Review by pxLi — APPROVED** [review]
this must be merged as a merge commit

**Pull request merged**
