### PR TITLE
Fix parquet test for nztimestamp on spark 3.4.0

### LINKED ISSUE #7039: [BUG] `nz timestamp (MILLIS AND MICROS)` fails on Spark 3.4
The unit test `nz timestamp (MILLIS AND MICROS)` fails on Spark 3.4.
```
- nz timestamp (MILLIS AND MICROS) NATIVE *** FAILED ***
  areEqual._1 was false VALUES NOT EQUAL 1970-01-01 00:00:01.0 1970-01-01T00:00:01
  VALUES NOT EQUAL 1970-01-01 00:00:00.000002 1970-01-01T00:00:00.000002 (ParquetFormatScanSuite.scala:264)
...
- nz timestamp (MILLIS AND MICROS) JAVA *** FAILED ***
  areEqual._1 was false VALUES NOT EQUAL 1970-01-01 00:00:01.0 1970-01-01T00:00:01
  VALUES NOT EQUAL 1970-01-01 00:00:00.000002 1970-01-01T00:00:00.000002 (ParquetFormatScanSuite.scala:264)
```

The reason is that on Spark 3.4, the return type is `LocalDateTime`, not `Timestamp`.

To reproduce:
```
mvn clean package -DwildcardSuites=org.apache.spark.sql.rapids.ParquetFormatScanSuite -Dbuildver=340
```

This is not related to our plugin because the test only runs on CPU, but we need to update our tests.

### PR DESCRIPTION
**Pull request by revans2**
This fixes #7039

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
looks like the test failure is related to the regexp regression in CUDF.

**Review by jlowe — APPROVED** [review]

**Review by HaoYang670 — APPROVED** [review]
Thank you, @revans2. I tested on my desktop and it works fine.

**Comment by revans2** [comment]
build

**Pull request merged**
