### PR TITLE
Increase robustness of MVN commands in pre-merge  scripts [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

part of #6289 for premerge test. Add retry logic to avoid instant fail w/ mvn repo service or unstable networking

**NOTE:** this update would not help if above issues would not be resolved in a short time. We still need to manually try rebuild after the service is back to normal

FYI update of nightly build and deploy will come later w/ some more testing

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by jlowe — APPROVED** [review]
lgtm.  CI failures are due to unrelated BinaryType test failures.

**Comment by jlowe** [comment]
build

**Pull request merged**
