### PR TITLE
Handle empty batch in ParquetCachedBatchSerializer [databricks]

### PR DESCRIPTION
**Pull request by razajafri**
This PR handles reading and writing empty batches. This can happen if we are caching a DF with no columns.

### CODE REVIEW

**Comment by revans2** [comment]
So what changed vs the previous PR that was reverted? It is hard to tell with the force push.

**Comment by razajafri** [comment]
> So what changed vs the previous PR that was reverted? It is hard to tell with the force push.

https://github.com/NVIDIA/spark-rapids/pull/8553/commits/058f6ccadc1a733f6ae7fe3ef4e0f5bc5d764570

**Comment by razajafri** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by pxLi** [comment]
`Caused by: java.util.NoSuchElementException: next on empty iterator`

```
[2023-06-12T23:17:56.416Z] [1m[31mE                   Driver stacktrace:[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3088)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3035)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3029)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3029)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1391)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1391)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at scala.Option.foreach(Option.scala:407)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1391)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3297)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3238)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3226)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1157)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2657)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:241)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:276)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:81)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:87)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:75)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:62)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.collectResult$1(ResultCacheManager.scala:575)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.computeResult(ResultCacheManager.scala:582)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:528)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at scala.Option.getOrElse(Option.scala:189)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:527)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:424)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:403)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:424)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:400)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$count$1(Dataset.scala:3210)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$count$1$adapted(Dataset.scala:3209)[0m
[2023-06-12T23:17:56.416Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3951)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:239)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:386)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:186)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:968)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:141)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:336)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3949)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.Dataset.count(Dataset.scala:3209)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at java.lang.reflect.Method.invoke(Method.java:498)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at py4j.Gateway.invoke(Gateway.java:295)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at java.lang.Thread.run(Thread.java:750)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   Caused by: java.util.NoSuchElementException: next on empty iterator[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.util.CompletionIterator.next(CompletionIterator.scala:29)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.convertCachedBatchToInternalRowIter(ParquetCachedBatchSerializer.scala:752)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at com.nvidia.spark.rapids.ParquetCachedBatchSerializer$CachedBatchIteratorConsumer$$anon$3.hasNext(ParquetCachedBatchSerializer.scala:733)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.hashAgg_doAggregateWithoutKey_0$(Unknown Source)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:151)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$3(ShuffleMapTask.scala:81)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$1(ShuffleMapTask.scala:81)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:156)[0m
[2023-06-12T23:17:56.417Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:125)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at org.apache.spark.scheduler.Task.run(Task.scala:95)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:832)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:835)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:690)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[2023-06-12T23:17:56.418Z] [1m[31mE                   	... 1 more[0m
```
failed in databricks runtime

**Comment by pxLi** [comment]
as discussed moved the BASE to 23.08 for now to avoid accidental merge into 23.06 for now

**Comment by razajafri** [comment]
I have finally been able to test on DB. Since my clusters keep disappearing after some time I cloned from an existing cluster that was uploading a jar that was overriding my build.

**Comment by razajafri** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
failed due to aws capacity issue
```
We currently do not have sufficient g4dn.2xlarge capacity in the Availability Zone you requested (us-west-2c). Our system will be working on provisioning additional capacity. You can currently get g4dn.2xlarge capacity by not specifying an Availability Zone in your request or choosing us-west-2a, us-west-2b.
```

retriggered w/ azure

**Comment by pxLi** [comment]
build

**Comment by razajafri** [comment]
```
[2023-06-13T09:00:03.768Z] # A fatal error has been detected by the Java Runtime Environment:

[2023-06-13T09:00:03.768Z] #

[2023-06-13T09:00:03.768Z] #  SIGSEGV (0xb) at pc=0x00007fbc03757f46, pid=1108894, tid=0x00007fbc0ea69700

[2023-06-13T09:00:03.768Z] #

[2023-06-13T09:00:03.768Z] # JRE version: OpenJDK Runtime Environment (8.0_362-b09) (build 1.8.0_362-8u372-ga~us1-0ubuntu1~20.04-b09)

[2023-06-13T09:00:03.768Z] # Java VM: OpenJDK 64-Bit Server VM (25.362-b09 mixed mode linux-amd64 compressed oops)

[2023-06-13T09:00:03.768Z] # Problematic frame:

[2023-06-13T09:00:03.768Z] # J 71333 C2 ai.rapids.cudf.ColumnView.copyToHost()Lai/rapids/cudf/HostColumnVector; (1738 bytes) @ 0x00007fbc03757f46 [0x00007fbc03757280+0xcc6]

[2023-06-13T09:00:03.768Z] #

[2023-06-13T09:00:03.768Z] # Core dump written. Default location: /home/jenkins/agent/workspace/jenkins-rapids_premerge-github-7361-ci-2/tests/core or core.1108894

[2023-06-13T09:00:03.768Z] #

[2023-06-13T09:00:03.768Z] # An error report file with more information is saved as:

[2023-06-13T09:00:03.768Z] # /home/jenkins/agent/workspace/jenkins-rapids_premerge-github-7361-ci-2/tests/hs_err_pid1108894.log
```

CI failed due to this crash. Looking into it more

**Comment by razajafri** [comment]
I couldn't see why the CI is failing but I did see memory leaks in the test that have been fixed

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
