### PR TITLE
Databricks: use pip to install pytest and disable cudf_udf test for now [databricks]

### PR DESCRIPTION
**Pull request by tgravescs**
Workaround for https://github.com/NVIDIA/spark-rapids/issues/7639 

For now just go back to using pip install for pytest since conda is having issues.

Comment out cudf_udf tests in the test.sh script until we can figure out conda issues.

For testing, I built on DB 9.1, 10.4, and 11.3 and started the test.sh script.  It started running the tests just fine there, I didn't wait for them to finish to post this PR

Signed-off-by: Thomas Graves <tgraves@nvidia.com>

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
@NvTimLiu @pxLi anything I may have missed to disable cudf_udf tests for now?

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
failed
```
[2023-02-13T23:14:45.928Z] ++ -c 'import sys; print("python{}.{}".format(sys.version_info.major, sys.version_info.minor))'

[2023-02-13T23:14:45.928Z] /home/ubuntu/test.sh: line 95: -c: command not found
```

**Comment by pxLi** [comment]
merged https://github.com/NVIDIA/spark-rapids/pull/7758 to get a CI run pass first.

**Pull request closed without merging**
