### PR TITLE
Update docs for rapids v0.4.2 release [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Update docs for rapids v0.4.2 release

Update cuDF dependency to v0.18.2

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — DISMISSED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Pull request merged**
