### PR TITLE
Fix a hanging issue when processing empty data.

### PR DESCRIPTION
**Pull request by firestarman**
The output iterator will wait on the batch queue when calling `hasNext`, and suppose to be waked up when the Python runner inserts something into the batch queue. But the insertion will never happen if the input data is empty. So it hangs forever.

The solution is to let the Python runner always wake up the output iterator after it finishes the data writing by calling the new added API `finish()`.

Also added the test for it. The 'small_data' is small enough to let some tasks get no data when running. 

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
build

**Review by revans2 — DISMISSED** [review]
Great work finding this.

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
@revans2 Added the test for it. Could you take another look?

**Comment by firestarman** [comment]
build

**Comment by revans2** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
