### PR TITLE
Update JNI and cudf-py version to 23.02 [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

fix https://github.com/NVIDIA/spark-rapids/issues/7064

### CODE REVIEW

**Comment by pxLi** [comment]
convert to draft first, will trigger build when 23.02 JNI artifact is available

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
filed https://github.com/NVIDIA/spark-rapids/issues/7092

remove databricks in title for premerge run

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Pull request merged**
