### PR TITLE
Shim GpuKryoRegistrator

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/3468

Add the GpuKryoRegistrator class to common unshimmed code and add the actual registration into the shim.  This made more sense to me to add into the shim module since its not create a new instance but just references the class by the spark version shim and I expect this code to be commonized when we commonize the base shim code.  If people have strong objections we can rework it but we haven't really put anything into the ShimLoader class like this yet.

I built all versions, tested on all apache versions. We need overrides to test cdh and need to figure out how to test on Databricks.  

Signed-off-by: Thomas Graves <tgraves@nvidia.com>

### CODE REVIEW

**Comment by tgravescs** [comment]
this will need to be upmerged to https://github.com/NVIDIA/spark-rapids/pull/3489

**Comment by tgravescs** [comment]
build

**Comment by gerashegalov** [comment]
If it's necessary I am ok with it 

in general, we should  start biasing much more to not adding  to Shims if it's avoidable imo   
 
Did we check if this fix changes anything about running in REPL? https://github.com/NVIDIA/spark-rapids/issues/3482#issuecomment-919643406

GpuKryoRegistrator may be safe to leave in the standard location unless it transitively references some incompatible Scala classes. I think mostly cudf java which is fine and Spark which is fine.  GpuKryoRegistrator bytecode is identical across shims:

```shell
$ diff -s ./spark311cdh/com/nvidia/spark/rapids/GpuKryoRegistrator.class ./spark302/com/nvidia/spark/rapids/GpuKryoRegistrator.class
Files ./spark311cdh/com/nvidia/spark/rapids/GpuKryoRegistrator.class and ./spark302/com/nvidia/spark/rapids/GpuKryoRegistrator.class are identical

$ diff -s ./spark311cdh/com/nvidia/spark/rapids/GpuKryoRegistrator.class ./spark320/com/nvidia/spark/rapids/GpuKryoRegistrator.class
Files ./spark311cdh/com/nvidia/spark/rapids/GpuKryoRegistrator.class and ./spark320/com/nvidia/spark/rapids/GpuKryoRegistrator.class are identical
```

**Comment by tgravescs** [comment]
yes I tested via spark-shell.

**Review by revans2 — APPROVED** [review]

**Pull request merged**
