### PR TITLE
Nulls out the dataframe if --gc-between-runs is set

### PR DESCRIPTION
**Pull request by abellina**
Signed-off-by: Alessandro Bellina <abellina@nvidia.com>

Small fix to allow GC to clean up shuffles between runs.

### CODE REVIEW

**Comment by abellina** [comment]
wait I think this causes other things to fail, that may need the `df` to be around.

**Review by andygrove — APPROVED** [review]
LGTM

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
@andygrove I had to rebase this to pick up cast changes.

**Review by andygrove — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Pull request merged**
