### PR TITLE
Support ORC write Map column

### LINKED ISSUE #3784: [FEA] Support ORC write Map column(single level)
**Is your feature request related to a problem? Please describe.**
ORC Writer for Maps (Single level)

**Describe the solution you'd like**
cuDF has the PR https://github.com/rapidsai/cudf/pull/9369 to support it.
We can add it to the plugin side. Make sure we have the correct type check to follow up what cuDF supports.
And add enough test cases.

### PR DESCRIPTION
**Pull request by res-life**
This fixes #3784

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
The premerge build passed after I shrink the map(max_length=5), see my second commit, but I do not know way it passed.  
I saw the following warnning in my local build log, may be there are some clue:
```
21/10/15 05:42:50 WARN TaskSetManager: Stage 135 contains a task of very large size (32945 KiB). The maximum recommended task size is 1000 KiB.

```

**Comment by res-life** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
@revans2  please review, no more change. 
CUDF fixed the blocking issue and the premerge passed: [Can not read the generated ORC file by Spark CPU](https://github.com/rapidsai/cudf/issues/9478)

**Review by revans2 — APPROVED** [review]

**Pull request merged**
