### PR TITLE
Add in docs to describe window performance

### PR DESCRIPTION
**Pull request by revans2**
Right now this is a document only change, but I really would be interested to hear from others if we think we should include some configs to allow users to selectively disable window operations. The problem is that the slowness is based off of the window size, and this is data dependent, as you can see from #3021. That means we cannot detect ahead of time if we are going to see slowness. I will file a follow on issue/epic for optimizations we know we can do.

### CODE REVIEW

**Review by jlowe — APPROVED** [review]
Docs look good to me.

> I really would be interested to hear from others if we think we should include some configs to allow users to selectively disable window operations.

It might be handy in practice to have window configs to control the various window types.  That way if a user discovers a performance problem or bug in windowing then they can easily work around that case without forcing all window operations off the GPU.  If it's easy I say let's do it, but if it's quite a bit of work then maybe we wait until we more clearly see the need.  It seems to come down to how likely do we think a query will have multiple types of windows where disabling one window type but leaving another enabled is better than blanket disabling `GpuWindowExec`.

**Comment by jlowe** [comment]
build

**Comment by revans2** [comment]
build

**Comment by jlowe** [comment]
> I am not sure that this is what we want either.

Yeah so then I'm thinking maybe we hold off a bit until we get clearer guidance from real-world use as to what we really need.

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
Had some offline review comments that I tried to clarify.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
I filed https://github.com/NVIDIA/spark-rapids/issues/3023 to try and track some possible performance optimizations.

**Pull request merged**
