### PR TITLE
add maven profiles for supported CUDA versions

### PR DESCRIPTION
**Pull request by rongou**
Maybe there is a better way, but this was the only way I could get IntelliJ to use a different CUDA version.

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by sameerz** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by tgravescs** [comment]
do we want to add docs for this? https://github.com/NVIDIA/spark-rapids/blob/branch-0.5/CONTRIBUTING.md#building-from-source

**Comment by rongou** [comment]
Done: https://github.com/NVIDIA/spark-rapids/pull/1983

**Pull request merged**
