### PR TITLE
Disable 311cdh build by default because of a missing dependency

### PR DESCRIPTION
**Pull request by tgravescs**
The build started to fail to build 311cdh due to missing dependency in their repo:

`[2022-01-28T17:38:28.398Z] [ERROR] Failed to execute goal on project rapids-4-spark-sql_2.12: Could not resolve dependencies for project com.nvidia:rapids-4-spark-sql_2.12:jar:22.04.0-SNAPSHOT: Could not find artifact log4j:log4j:jar:1.2.17-cloudera1 in apache-snapshots-repo (https://urm.nvidia.com/artifactory/sw-spark-maven) -> [Help 1]`

Since they will change CDH version when they pick up 22.02 we can stop building 311cdh for now.

Disable in the premerge and the nightly and also remove it from the buildall script.

Signed-off-by: Thomas Graves <tgraves@nvidia.com>

### CODE REVIEW

**Review by abellina — APPROVED** [review]
LGTM

**Comment by abellina** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
