### PR TITLE
Qualification tool: Allow app start and app name filtering and test with filesystem filters

### PR DESCRIPTION
**Pull request by tgravescs**
Qualification tool: Allow app start and app name filtering (AND based).

Add a bunch of tests for filesystem based filters.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
need to update for scalastyle

**Comment by tgravescs** [comment]
build

**Review by nartal1 — APPROVED** [review]
Thanks for adding  tests which includes both  FileSystem filters and application filters.

**Pull request merged**
