### PR TITLE
[FEA][AUDIT][SPARK-44641] Incorrect result in certain scenarios when SPJ is not triggered

### PR DESCRIPTION
**Pull request by andygrove**
Closes https://github.com/NVIDIA/spark-rapids/issues/9180

This PR copies the 340 shim version of `BatchScanExec` into the 350 shim and applies the following change, to reflect the change made in https://github.com/apache/spark/commit/5c7d1e2f8a#diff-f82edfef27867e1285af13f3603efbc5e77d81d715d427db4b51f0c3e3a0df14.

```
<               finalPartitions = p.partitionValues.map { partValue =>
---
> 
>               // In case `commonPartitionValues` is not defined (e.g., SPJ is not used), there
>               // could exist duplicated partition values, as partition grouping is not done
>               // at the beginning and postponed to this method. It is important to use unique
>               // partition values here so that grouped partitions won't get duplicated.
>               finalPartitions = p.uniquePartitionValues.map { partValue =>
```

As noted in the issue, it is not easy to add a test for this because OSS Spark does not have any V2 data sources that implement `SupportsReportPartitioning`.

### CODE REVIEW

**Review by revans2 — DISMISSED** [review]

**Comment by revans2** [comment]
To reduce code duplication. Would it be okay to fix this bug in all versions of Spark? I know we would not be bug for bug compatible, technically, but it would save on a lot of code duplication, and I don't think it would be that big of a deal.

**Comment by andygrove** [comment]
> To reduce code duplication. Would it be okay to fix this bug in all versions of Spark? I know we would not be bug for bug compatible, technically, but it would save on a lot of code duplication, and I don't think it would be that big of a deal.

I added a new shim `KeyGroupedPartitioningShim` for getting the unique partitions and removed the duplicate of `GpuBatchScanExec`. I did not port the fix back to 3.3.0 or earlier because the `GpuBatchScanExec` code in Spark is structured differently for those versions and it isn't clear to me where the fix should be applied.

**Comment by andygrove** [comment]
> > To reduce code duplication. Would it be okay to fix this bug in all versions of Spark? I know we would not be bug for bug compatible, technically, but it would save on a lot of code duplication, and I don't think it would be that big of a deal.
> 
> I added a new shim `KeyGroupedPartitioningShim` for getting the unique partitions and removed the duplicate of `GpuBatchScanExec`. I did not port the fix back to 3.3.0 or earlier because the `GpuBatchScanExec` code in Spark is structured differently for those versions and it isn't clear to me where the fix should be applied.

The v2 bucketing configs are new in 3.4.0, so I don't think we need to do anything with prior versions.

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Pull request merged**
