### PR TITLE
Enable get_json_object by default and remove legacy version

### PR DESCRIPTION
**Pull request by revans2**
This fixes https://github.com/NVIDIA/spark-rapids/issues/10832

We don't need the legacy version any more as everything passes and the performance is good enough that we can turn it on by default now.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Review by ttnghia — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@ttnghia could you please take another look. I missed updating one of the CSV files for Spark 4.0.0

**Review by ttnghia — APPROVED** [review]

**Review by amahussein — APPROVED** [review]

**Pull request merged**
