### PR TITLE
Spark 4:  Fix parquet_test.py [databricks]

### LINKED ISSUE #11015: Fix tests failures in parquet_test.py
```
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_many_column_project
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_nested_pruning_and_case_insensitive
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_check_schema_compatibility
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_compress_read_round_trip
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_decimal_read_legacy
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_fallback
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_input_meta
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_int32_downcast
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_nested_column_missing
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_partitioned_read_just_partitions
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_pred_push_round_trip
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_avoid_coalesce_incompatible_files
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_buffer_allocation_empty_blocks
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_coalescing_multiple_files
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_count
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_encryption
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_forced_binary_schema
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_ignore_missing
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_int_upcast
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_merge_schema
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_merge_schema_from_conf
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_roundtrip_datetime_with_legacy_rebase
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_schema_missing_cols
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_read_with_corrupt_files
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_reading_from_unaligned_pages_all_types
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_reading_from_unaligned_pages_all_types_dict_optimized
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_reading_from_unaligned_pages_basic_filters
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_reading_from_unaligned_pages_basic_filters_with_nulls
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_parquet_simple_partitioned_read
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_read_case_col_name
FAILED ../../../../integration_tests/src/main/python/parquet_test.py::test_small_file_memory
```

### LINKED ISSUE #11531: Fix Parquet tests for Databricks 14.3
Build the plugin against the Databricks 14.3 cluster using #11467. Once built successfully run the parquet tests by `TESTS=parquet_test.py jenkins/databricks/test.sh` 

The following tests fail 
```
[gw2] [ 90%] FAILED ../../src/main/python/parquet_test.py::test_parquet_check_schema_compatibility
```

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #11015.
Fixes #11531.
Contributes to #11004 and #10661.

This commit addresses the tests that fail in parquet_test.py, when run on Spark 4.

1. Some of the tests were failing as a result of #5114.  Those tests have been disabled, at least until we get around to supporting aggregations with ANSI mode enabled.

2. `test_parquet_check_schema_compatibility` fails on Spark 4 regardless of ANSI mode, because it tests implicit type promotions where the read schema includes wider columns than the write schema.  This will require new code.  The test is disabled until #11512 is addressed.

3. `test_parquet_int32_downcast` had an erroneous setup phase that fails in ANSI mode.  This has been corrected. The test was refactored to run in ANSI and non-ANSI mode.

### CODE REVIEW

**Comment by mythrocks** [comment]
Build

**Comment by razajafri** [comment]
Thanks for this. 

The fix for `test_parquet_check_schema_compatibility` will directly port on Databricks 14.3

**Review by razajafri — APPROVED** [review]

**Comment by mythrocks** [comment]
@razajafri:  I've modified this PR to also include a fix for #11531.

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
> @razajafri: I've modified this PR to also include a fix for #11531. 

I have tested that this addresses the test failure in Databricks 14.3.  

In making this change, I had to dismiss your earlier review.  If you wouldn't mind taking another look, I'd appreciate it.

**Review by razajafri — APPROVED** [review]

**Comment by mythrocks** [comment]
This has been merged.  Thank you for the review, @razajafri.

**Pull request merged**
