### PR TITLE
add corresponding close call for HostMemoryOutputStream

### PR DESCRIPTION
**Pull request by wbo4958**
Signed-off-by: Bobby Wang <wbo4958@gmail.com>

### CODE REVIEW

**Review by jlowe — APPROVED** [review]
Note that the close method for `HostMemoryOutputStream` doesn't do anything, so this PR should have net-zero effect.  Still it's useful to close at the appropriate place just in case semantics are added to the close method later. :smile:

**Comment by gerashegalov** [comment]
given Jason's comment it's irrelevant but technically you want `close` inside a finally block, maybe using withResource

**Comment by sameerz** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Pull request merged**
