### PR TITLE
Add test cases for read/write User Defined Type (UDT) to ORC

### LINKED ISSUE #8730: CPU fallback for user-defined types in ORC read/write: OrcQuerySuite.scala#L108

### PR DESCRIPTION
**Pull request by res-life**
Closes [#8730 ](https://github.com/NVIDIA/spark-rapids/issues/8730)

Fall back to CPU becasue do not support UDT

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by res-life** [comment]
build

**Comment by pxLi** [comment]
known issue at https://github.com/NVIDIA/spark-rapids/issues/8418

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
The last compile error is caused by: Bad Gateway (502) when transfer private jar and jni jar.
Trigger compile again.

**Comment by res-life** [comment]
build

**Pull request merged**
