### PR TITLE
Use withGpuSparkSession to customize SparkConf

### LINKED ISSUE #9768: [BUG] `cast decimal to string` ScalaTest relies on a side effects
A a couple of tests rely on other tests executed before to have an active Spark Session

```bash
$ mvn package -pl tests -am -Dbuildver=330 \
       -Dsuffixes='.*CastOpSuite' \
       -Dtests='@cast decimal to string' 
```

```
Run starting. Expected test count is: 1
CastOpSuite:
- cast decimal to string *** FAILED ***
  java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:529)
  at scala.None$.get(Option.scala:527)
  at com.nvidia.spark.rapids.CastOpSuite.$anonfun$new$40(CastOpSuite.scala:448)
```

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #9768 

(Ansi)CastOpSuite @ (ansi) cast decimal to string

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Review by andygrove — APPROVED** [review]

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
failure related to #9781

**Comment by gerashegalov** [comment]
build

**Pull request merged**
