### PR TITLE
Move pandas_udf functions into the tests functions

### PR DESCRIPTION
**Pull request by tgravescs**
Move pandas_udf functions into the tests functions so they don't try to compile when skipped.

Fixes https://github.com/NVIDIA/spark-rapids/issues/922

Note I can now run tests without this failing, but I haven't run the test to make sure it passes as I don't have the env setup to do it.

### CODE REVIEW

**Comment by tgravescs** [comment]
@firestarman @shotai any chance you have env setup you can make sure the test still works when config specified?

**Comment by tgravescs** [comment]
build

**Comment by firestarman** [comment]
Thanks a lot for finding this.

One little issue is the two udfs `_sum_cpu_func` and `_sum_gpu_func` should be defined again in  test `tet_window` since this test  also uses these 2 udfs.

Something like: https://github.com/firestarman/spark-rapids/commit/900a91d9ef556c0265c4fb243e4a11247c4ec684
```python
@cudf_udf
def test_window(enable_cudf_udf):
+    @pandas_udf("int")
+    def _sum_cpu_func(v: pd.Series) -> int:
+        return v.sum()
+
+   @pandas_udf("integer")
+   def _sum_gpu_func(v: pd.Series) -> int:
+       import cudf
+       gpu_series = cudf.Series(v)
+       return gpu_series.sum()
+
    def cpu_run(spark):
          df = _create_df(spark)
          w = Window.partitionBy('id').rowsBetween(Window.unboundedPreceding, Window.unboundedFollowing)

```

**Comment by firestarman** [comment]
With the change above, i can get cudf udf tests passed locally.
`========== 11 passed, 3418 deselected, 1 warning in 131.68s (0:02:11) ==========`

**Comment by tgravescs** [comment]
@firestarman thanks for the review, I added them to test_window. I realize this duplicates the functions so if there is a better way you can come up with not to duplicate the functions that is more ideal. I tried putting them in a class but that still compiled it. 
I think this pr will work for now though.

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by firestarman — APPROVED** [review]

**Pull request merged**
