### PR TITLE
Use BasicColumnarWriteTaskStats instead of BasicWriteTaskStats

### LINKED ISSUE #1006: [BUG] Spark3.1.0 changed BasicWriteTaskStats breaks BasicColumnarWriteTaskStatsTracker
Looks like Spark 3.1.0 changed the api for BasicWriteTaskStats here https://github.com/apache/spark/commit/b38f3a5557b45503e0f8d67bc77c5d390a67a42f 

This breaks our BasicColumnarWriteTaskStatsTracker

Cause: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.BasicWriteTaskStats.<init>(IIJJ)V
13:34:22    at org.apache.spark.sql.rapids.BasicColumnarWriteTaskStatsTracker.getFinalStats(BasicColumnarWriteStatsTracker.scala:107)
13:34:22    at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.$anonfun$commit$1(GpuFileFormatDataWriter.scala:82)
13:34:22    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
13:34:22    at scala.collection.immutable.List.foreach(List.scala:392)
13:34:22    at scala.collection.TraversableLike.map(TraversableLike.scala:237)
13:34:22    at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
13:34:22    at scala.collection.immutable.List.map(List.scala:298)
13:34:22    at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.commit(GpuFileFormatDataWriter.scala:82)
13:34:22    at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$executeTask$1(GpuFileFormatWriter.scala:298)
13:34:22    at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1460)
13:34:22    ...

### PR DESCRIPTION
**Pull request by jlowe**
This fixes the plugin build against Spark 3.1.0 by using a custom `BasicColumnarWriteTaskStats` case class instead of trying to reuse Spark's `BasicWriteTaskStats` which recently changed in Spark 3.1.0.

Fixes #1006

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
The testes failed with a new error that looks like it is related to `RegexpReplace`

Looks like RegexpReplace needs to be added to the shim layer now.

https://issues.apache.org/jira/browse/SPARK-30796

https://github.com/apache/spark/commit/eb33bcb4b2db2a13b3da783e58feb8852e04637b

**Comment by revans2** [comment]
Looking at it we can probably get away with just the replacement rule for RegexpReplace being in the shim layer.  They added in a new position argument. In 3.1+ we should verify that position is a literal that is 1 and then just ignore it when we replace it.  We should also file a follow on issue to eventually support it properly.

**Comment by revans2** [comment]
This was merged/fixed as a part of #1012

**Pull request closed without merging**
