### PR TITLE
Draft: override hadoop dependency for emr 3.0.1

### PR DESCRIPTION
**Pull request by wbo4958**

### CODE REVIEW

**Comment by wbo4958** [comment]
build script

``` bash
#!/bin/bash
##
# Maven build spark-rapids jars agaisnt the emr spark runtime
##
set -ex

## set environment:
CLUSTER_WORKDIR=${CLUSTER_WORKDIR:-`pwd`} && cd $CLUSTER_WORKDIR
BUILD_PROFILES=${BUILD_PROFILES:-'!snapshot-shims'}

## spark-rapids need maven3.5.0 and above version, NOT via 'yum install -y maven' as it installs maven 3.0.5
if [ ! -d "$CLUSTER_WORKDIR/apache-maven-3.6.0/" ];then
    wget -q -P $CLUSTER_WORKDIR https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
    cd $CLUSTER_WORKDIR && tar zxf apache-maven-3.6.0-bin.tar.gz && rm -rf apache-maven-3.6.0-bin.tar.gz
fi

export PATH=$CLUSTER_WORKDIR/apache-maven-3.6.0/bin:$PATH
#rm -rf $CLUSTER_WORKDIR/spark-rapids && mkdir -p $CLUSTER_WORKDIR/spark-rapids
#tar zxf $CLUSTER_WORKDIR/spark-rapids.tgz -C $CLUSTER_WORKDIR/spark-rapids

## EMR_SPARK_JARSTR '/usr/lib/spark/jars/spark-sql_${EMR_SCALA_VER}-${EMR_SPARK_VER}-amzn-0.jar'
EMR_SPARK_JARSTR=`ls /usr/lib/spark/jars/spark-sql_*.jar`
if [ -n "$EMR_SPARK_JARSTR" ]; then
    EMR_SCALA_VER=${EMR_SPARK_JARSTR##*'spark-sql_'}
    EMR_SCALA_VER=${EMR_SCALA_VER%%'-'*}
    if [ "$EMR_SCALA_VER" == "$EMR_SPARK_JARSTR" ]; then
        EMR_SCALA_VER=''
    fi
    EMR_SPARK_VER=${EMR_SPARK_JARSTR##*"spark-sql_$EMR_SCALA_VER-"}
    EMR_SPARK_VER=${EMR_SPARK_VER%%'-'*}
    if [ "$EMR_SPARK_VER" == "$EMR_SPARK_JARSTR" ]; then
        EMR_SPARK_VER=''
    fi
    echo "EMR_SCALA_VER $EMR_SCALA_VER, EMR_SPARK_VER: $EMR_SPARK_VER"
else
    echo "ERROR spark-sql*.jar NOT found on the emr cluster!"
    exit 255
fi

cd $CLUSTER_WORKDIR/spark-rapids
## Pick up new built rapids jar and latest CuDF jar, integration_tests.zip
PLUGIN_VERSION=`mvn help:evaluate -q -Dexpression=project.version -DforceStdout`
CUDF_VERSION=`mvn help:evaluate -q -Dexpression=cudf.version -DforceStdout`
SCALA_VERSION=`mvn help:evaluate -q -Dexpression=scala.binary.version -DforceStdout`
SPARK_VERSION=`mvn help:evaluate -q -Dexpression=spark.version -DforceStdout`
CUDA_VERSION=`mvn help:evaluate -q -Dexpression=cuda.version -DforceStdout`

## replace 'spark.version' and 'scala.binary.version' in pom.xml
if [[ -n "$EMR_SPARK_VER" && "$SPARK_VERSION" != "$EMR_SPARK_VER" ]]; then
    sed -i "s/<spark.version>$SPARK_VERSION/<spark.version>$EMR_SPARK_VER/g" pom.xml
    SPARK_VERSION=$EMR_SPARK_VER
fi
if [[ -n "$EMR_SCALA_VER" && "$SCALA_VERSION" != "$EMR_SCALA_VER" ]]; then
    sed -i "s/<scala.binary.version>$SCALA_VERSION/<scala.binary.version>$EMR_SCALA_VER/g" pom.xml
    SCALA_VERSION=$EMR_SCALA_VER
fi

## Run the build once to download all the apache spark jars into the ~/.m2
mvn -B clean package -DskipTests -P${BUILD_PROFILES} -P spark301emr || true

## Install the emr runtime jars into the ~/.m2
mvn -B install:install-file \
   -Dmaven.repo.local=/home/hadoop/.m2/repository \
   -Dfile=/usr/lib/spark/jars/spark-sql_$SCALA_VERSION-$SPARK_VERSION-amzn-0.jar \
   -DgroupId=org.apache.spark \
   -DartifactId=spark-sql_$SCALA_VERSION \
   -Dversion=$SPARK_VERSION \
   -Dpackaging=jar

mvn -B install:install-file \
   -Dmaven.repo.local=/home/hadoop/.m2/repository \
   -Dfile=/usr/lib/spark/jars/spark-catalyst_$SCALA_VERSION-$SPARK_VERSION-amzn-0.jar \
   -DgroupId=org.apache.spark \
   -DartifactId=spark-catalyst_$SCALA_VERSION \
   -Dversion=$SPARK_VERSION \
   -Dpackaging=jar

mvn -B install:install-file \
   -Dmaven.repo.local=/home/hadoop/.m2/repository \
   -Dfile=/usr/lib/spark/jars/spark-core_$SCALA_VERSION-$SPARK_VERSION-amzn-0.jar \
   -DgroupId=org.apache.spark \
   -DartifactId=spark-core_$SCALA_VERSION \
   -Dversion=$SPARK_VERSION \
   -Dpackaging=jar

mvn -B install:install-file \
   -Dmaven.repo.local=/home/hadoop/.m2/repository \
   -Dfile=/usr/lib/spark/jars/spark-sketch_$SCALA_VERSION-$SPARK_VERSION-amzn-0.jar \
   -DgroupId=org.apache.spark \
   -DartifactId=spark-sketch_$SCALA_VERSION \
   -Dversion=$SPARK_VERSION \
   -Dpackaging=jar

mvn -B install:install-file \
   -Dmaven.repo.local=/home/hadoop/.m2/repository \
   -Dfile=/usr/lib/spark/jars/spark-sketch_$SCALA_VERSION-$SPARK_VERSION-amzn-0.jar \
   -DgroupId=org.apache.spark \
   -DartifactId=spark-sketch_$SCALA_VERSION \
   -Dversion=$SPARK_VERSION \
   -Dpackaging=jar

## Config to build and test with CUDA-compat runtime
if [ -d "/usr/local/cuda/compat" ]; then
    export LD_LIBRARY_PATH="/usr/local/cuda/compat":$LD_LIBRARY_PATH
fi
## The CUDA-compat libs is installed 1 minute after the cluster is ready to run
nvidia-smi

## Rebuild the spark rapids against the emr $SPARK_VERSION jars.
mvn -B clean package -P${BUILD_PROFILES} -P spark301emr


## Prepare jars to for the IT scripts
cp ~/.m2/repository/ai/rapids/cudf/${CUDF_VERSION}/cudf-${CUDF_VERSION}-${CUDA_VERSION}.jar $CLUSTER_WORKDIR
cp "$CLUSTER_WORKDIR/spark-rapids/dist/target/rapids-4-spark_${SCALA_VERSION}-${PLUGIN_VERSION}.jar" $CLUSTER_WORKDIR
cp "$CLUSTER_WORKDIR/spark-rapids/integration_tests/target/rapids-4-spark-integration-tests_${SCALA_VERSION}-${PLUGIN_VERSION}-pytest.tar.gz" $CLUSTER_WORKDIR
cp "$CLUSTER_WORKDIR/spark-rapids/integration_tests/target/rapids-4-spark-integration-tests_${SCALA_VERSION}-${PLUGIN_VERSION}.jar" $CLUSTER_WORKDIR
cp "$CLUSTER_WORKDIR/spark-rapids/udf-examples/target/rapids-4-spark-udf-examples_${SCALA_VERSION}-${PLUGIN_VERSION}.jar"  $CLUSTER_WORKDIR

```

**Comment by tgravescs** [comment]
why are we doing this - add a description please

**Comment by wbo4958** [comment]
> why are we doing this - add a description please

Hi @tgravescs, this PR is for https://github.com/NVIDIA/spark-rapids/issues/2488

**Comment by tgravescs** [comment]
Please add a description. I should not have to guess at what a pull request is for. link it to the issue.

**Comment by wbo4958** [comment]
close this PR temporarily

**Pull request closed without merging**
