### PR TITLE
[REVIEW] Fixed failing cache tests

### PR DESCRIPTION
**Pull request by razajafri**
Signed-off-by: Raza Jafri <rjafri@nvidia.com>

 Fixed failing tests. There seems to be a change in 3.1.0 that is causing the Timestamp to go past or beyond the year 0 or 9999

The purpose of this test is to test GpuExpandExec which is still true. I have created a follow on issue to investigate the failure if deemed necessary #842. I think its a failure we have seen before w.r.t timestamps being represented in python

### CODE REVIEW

**Comment by razajafri** [comment]
build

**Comment by revans2** [comment]
It looks like there were a number of things that happened to the rebaseing code for 3.1

https://github.com/apache/spark/commits/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/RebaseDateTime.scala

From what I can see `all_gen_restricting_dates` does not restrict timestamps and this is where we are getting into problems.

I am also not sure what any of that has to do with the test that is doing a rollup.  I am nervous on that one that we are just changing the test and end up hiding a real bug.

**Comment by razajafri** [comment]
I am OK with closing this if the CI isn't testing with 3.1.0. The sole reason for this PR is to make the build pass and triage #842 to investigate the bug?

**Comment by razajafri** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
