### PR TITLE
[auto-merge] branch-0.2 to branch-0.3 [skip ci] [bot]

### PR DESCRIPTION
**Pull request by nvauto**
auto-merge triggered by github actions on `branch-0.2` to create a PR keeping `branch-0.3` up-to-date. If this PR is unable to be merged due to conflicts, it will remain open until manually fix.

### CODE REVIEW

**Comment by svcngcc** [comment]
Can one of the admins verify this patch?

**Comment by tgravescs** [comment]
I'm working on resolving

**Comment by tgravescs** [comment]
see https://github.com/NVIDIA/spark-rapids/pull/738 with resolved conflicts

**Comment by tgravescs** [comment]
closing this and any remaining changes should be fixed up by next commit.

**Pull request closed without merging**
