### PR TITLE
More time ops

### LINKED ISSUE #29: [FEA] DayOfYear SQL operation
**Is your feature request related to a problem? Please describe.**
day of the year functionality already exists in cudf we should support the corresponding SQL operation.

### LINKED ISSUE #34: [FEA] LastDay of the month SQL function
**Is your feature request related to a problem? Please describe.**
cudf supports this operation we should then be able to make this work.

### LINKED ISSUE #35: [FEA] Quarter sql function
**Is your feature request related to a problem? Please describe.**
This returns the quarter of the year for a given date, in the range 1 to 4.  We should be able to do this by getting `(month/3 + 1)`.  Not ideal and we can file something with CUDF in the future if we need it.

### LINKED ISSUE #75: [FEA] Support DayOfWeek and WeekDay SQL functions
**Is your feature request related to a problem? Please describe.**
We should support `dayofweek` 1 based starting at Sunday, and `weekday` 0 based starting at Monday functions.

### PR DESCRIPTION
**Pull request by revans2**
This depends on https://github.com/rapidsai/cudf/pull/5559

This fixes #34 
This fixes #29 
This fixes #75 
This fixes #35 

A few simple date/time SQL functions that CUDF supports, but needed a bit of plumbing.

### CODE REVIEW

**Comment by revans2** [comment]
rapidsai/cudf#5559 was merged in so removed the WIP marker

**Comment by razajafri** [comment]
test

**Comment by razajafri** [comment]
build

**Comment by revans2** [comment]
@razajafri @abellina I upmerged to the latest branch-0.2 and there were merge conflicts that required some changes to the code, switch `GpuExpression` to `Expression` in a few cases.  Could you take another look?

**Comment by revans2** [comment]
build

**Pull request merged**
