### PR TITLE
Fix auto merge conflict 11034 [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Resolve auto-merge conflict at https://github.com/NVIDIA/spark-rapids/pull/11034.

Keep dependency versions 24.08.0-SNAPSHOT in pom.xml

NOTE: this must be merged as create a merge commit

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by jlowe — DISMISSED** [review]

**Comment by jlowe** [comment]
@NvTimLiu note that there are new commits that have been added to #11034 (e.g.: https://github.com/NVIDIA/spark-rapids/pull/11034/commits/e9ccf97e453ff6ba1e97aa867f7f80c516d13189)  that need to be upmerged.  If that's not going to be addressed by this, we'll need to trigger the auto-merge afterwards.

**Comment by NvTimLiu** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
