### PR TITLE
List supported Spark versions when no shim found

### LINKED ISSUE #8202: [FEA] List supported Spark builds when the Shim is not found
**Is your feature request related to a problem? Please describe.**
When the Plugin fails to find a shim for the host Spark build it throws 
```
java.lang.IllegalArgumentException: Could not find Spark Shim Loader for 3.0.2
        at com.nvidia.spark.rapids.ShimLoader$.$anonfun$detectShimProvider$18(ShimLoader.scala:292)
```

**Describe the solution you'd like**
To make the error message more actionable the Plugin could list all the versions it supports in the error message potentially along the URL to the doc https://nvidia.github.io/spark-rapids/docs/download.html

**Describe alternatives you've considered**
Go on as is 

**Additional context**
Support question

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #8202

- Attaches the list of all supported shim versions / buildvers to the error message
- Modifies ClouderaShimVersion toString to follow the same scheme as DatabricksShimVersion by including the vendor name  

Signed-off-by: Gera Shegalov <gera@apache.org>

Testing 

#### build with 3 shims without support for Spark 3.3.2 

```bash
./build/buildall --profile=321cdh,330cdh,340
```

#### start an intergration test with 3.3.2 SPARK_HOME

```bash
SPARK_HOME=~/dist/spark-3.3.2-bin-hadoop2 ./integration_tests/run_pyspark_from_build.sh -k 'array_exists'
```
yielding 
<details>
<summary>
<pre>
INTERNALERROR> py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
INTERNALERROR> : java.lang.IllegalArgumentException: This RAPIDS Plugin build does not support Spark build 3.3.2. Supported Spark versions: 3.2.1-cloudera-3.2.7171000 {buildver=321cdh}, 3.3.0-cloudera-3.3.7180 {buildver=330cdh}, 3.4.0 {buildver=340}. Consult the Release documentation at https://nvidia.github.io/spark-rapids/docs/download.html
</pre>
</summary>
<pre>
INTERNALERROR>  at com.nvidia.spark.rapids.ShimLoader$.$anonfun$detectShimProvider$18(ShimLoader.scala:296)
INTERNALERROR>  at scala.Option.getOrElse(Option.scala:189)
INTERNALERROR>  at com.nvidia.spark.rapids.ShimLoader$.detectShimProvider(ShimLoader.scala:290)
INTERNALERROR>  at com.nvidia.spark.rapids.ShimLoader$.findShimProvider(ShimLoader.scala:307)
INTERNALERROR>  at com.nvidia.spark.rapids.ShimLoader$.initShimProviderIfNeeded(ShimLoader.scala:104)
INTERNALERROR>  at com.nvidia.spark.rapids.ShimLoader$.getShimClassLoader(ShimLoader.scala:197)
INTERNALERROR>  at com.nvidia.spark.rapids.ShimReflectionUtils$.loadClass(ShimReflectionUtils.scala:29)
INTERNALERROR>  at com.nvidia.spark.rapids.ShimReflectionUtils$.newInstanceOf(ShimReflectionUtils.scala:35)
INTERNALERROR>  at com.nvidia.spark.rapids.ShimLoader$.newDriverPlugin(ShimLoader.scala:351)
INTERNALERROR>  at com.nvidia.spark.SQLPlugin.driverPlugin(SQLPlugin.scala:29)
INTERNALERROR>  at org.apache.spark.internal.plugin.DriverPluginContainer.$anonfun$driverPlugins$1(PluginContainer.scala:47)
INTERNALERROR>  at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
INTERNALERROR>  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
INTERNALERROR>  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
INTERNALERROR>  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
INTERNALERROR>  at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
INTERNALERROR>  at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
INTERNALERROR>  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
INTERNALERROR>  at org.apache.spark.internal.plugin.DriverPluginContainer.<init>(PluginContainer.scala:46)
INTERNALERROR>  at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:210)
INTERNALERROR>  at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:193)
INTERNALERROR>  at org.apache.spark.SparkContext.<init>(SparkContext.scala:570)
INTERNALERROR>  at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
INTERNALERROR>  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INTERNALERROR>  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INTERNALERROR>  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INTERNALERROR>  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INTERNALERROR>  at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
INTERNALERROR>  at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
INTERNALERROR>  at py4j.Gateway.invoke(Gateway.java:238)
INTERNALERROR>  at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
INTERNALERROR>  at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
INTERNALERROR>  at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
INTERNALERROR>  at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
INTERNALERROR>  at java.lang.Thread.run(Thread.java:750)
</pre>
</details>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
maven central conn reset. re-trigger build

**Comment by gerashegalov** [comment]
build

**Review by tgravescs — APPROVED** [review]
looks fine, the only weird thing might be the odd version number like 3.3.0.3.3.7180 that I assume is Databricks? that doesn't match what you would specify for buildver but not sure its a big deal as this is definitely an improvement.

>Supported Spark build versions: 3.2.0, 3.3.0.3.3.7180,

**Comment by tgravescs** [comment]
if the toString it only used for informational it would be nice to have something like that.  they still have to do mapping from version to buildver number but at least that makes it more obvious

**Comment by gerashegalov** [comment]
> if the toString it only used for informational it would be nice to have something like that. they still have to do mapping from version to buildver number but at least that makes it more obvious

Made toString for CDH similar to DBR and added buildvers to the error message
> Supported Spark versions: 3.2.1-cloudera-3.2.7171000 {buildver=321cdh}, 3.3.0-cloudera-3.3.7180 {buildver=330cdh}, 3.4.0 {buildver=340}

**Comment by gerashegalov** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
