### PR TITLE
Handle null values when merging Bloom filters

### LINKED ISSUE #9032: [BUG] Multiple NDS queries fail with Spark-3.4.1 with bloom filter exception
Running NDS @ SF3K results in multiple query failures (80, 91, 64, 16, 40, 13, 61) with this JNI exception related to bloom filter support:
```
23/08/14 13:30:29 WARN TaskSetManager: Lost task 0.0 in stage 298.0 (TID 21455) (executor 0): ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-510-cuda11/src/main/cpp/src/bloom_filter.cu:288: Encountered invalid/mismatched bloom filter buffer data
        at com.nvidia.spark.rapids.jni.BloomFilter.merge(Native Method)
        at com.nvidia.spark.rapids.jni.BloomFilter.merge(BloomFilter.java:67)
        at com.nvidia.spark.rapids.GpuBloomFilterMerge.$anonfun$reductionAggregate$3(GpuBloomFilterAggregate.scala:113)
        at com.nvidia.spark.rapids.AggHelper.$anonfun$performReduction$2(aggregate.scala:360)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at com.nvidia.spark.rapids.AggHelper.$anonfun$performReduction$1(aggregate.scala:356)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
        at com.nvidia.spark.rapids.AggHelper.performReduction(aggregate.scala:354)
        at com.nvidia.spark.rapids.AggHelper.aggregate(aggregate.scala:293)
        at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$4(aggregate.scala:310)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
        at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$3(aggregate.scala:308)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
        at com.nvidia.spark.rapids.AggHelper.$anonfun$aggregateWithoutCombine$2(aggregate.scala:307)
        at com.nvidia.spark.rapids.RmmRapidsRetryIterator$AutoCloseableAttemptSpliterator.next(RmmRapidsRetryIterator.scala:431)
        at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryIterator.next(RmmRapidsRetryIterator.scala:542)
        at com.nvidia.spark.rapids.RmmRapidsRetryIterator$RmmRapidsRetryAutoCloseableIterator.next(RmmRapidsRetryIterator.scala:468)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:496)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at com.nvidia.spark.rapids.GpuMergeAggregateIterator.aggregateInputBatches(aggregate.scala:789)
        at com.nvidia.spark.rapids.GpuMergeAggregateIterator.$anonfun$next$2(aggregate.scala:746)
        at scala.Option.getOrElse(Option.scala:189)
        at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(aggregate.scala:743)
        at com.nvidia.spark.rapids.GpuMergeAggregateIterator.next(aggregate.scala:710)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.$anonfun$next$6(aggregate.scala:2029)
        at scala.Option.map(Option.scala:230)
        at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(aggregate.scala:2029)
        at com.nvidia.spark.rapids.DynamicGpuPartialSortAggregateIterator.next(aggregate.scala:1893)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.$anonfun$fetchNextBatch$2(GpuColumnarToRowExec.scala:258)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.fetchNextBatch(GpuColumnarToRowExec.scala:255)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.loadNextBatch(GpuColumnarToRowExec.scala:228)
        at com.nvidia.spark.rapids.ColumnarToRowIterator.hasNext(GpuColumnarToRowExec.scala:272)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:888)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:888)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
        at org.apache.spark.scheduler.Task.run(Task.scala:139)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #9032. When merging Bloom filters, some of the filters may be null if an upstream task received no input rows in the Bloom filter aggregation.  The BloomFilter.merge method does not properly handle nulls, so this works around the issue by filtering out any nulls before calling BloomFilter.merge.  If all rows are null a null scalar is directly returned rather than calling BloomFilter.merge.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
Retargeted to branch-23.08 per request from @sameerz.

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
