### PR TITLE
Added the id back for struct children to make them unique [databricks]

### PR DESCRIPTION
**Pull request by razajafri**
The children of the struct also need to have a unique name which was erroneously removed as part of the #4955 

Also, removed the unnecessary concurrent AtomicLong and use a simple stack variable. Also added a test to see if the order of the structs matters when writing to caching and pulling from cache
  
Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Comment by razajafri** [comment]
build

**Review by firestarman — APPROVED** [review]

**Comment by razajafri** [comment]
@pxLi how the PR #4955 was able to pass CI? while the PR #4971 created by @nartal1 failed CI?

**Comment by pxLi** [comment]
> @pxLi how the PR #4955 was able to pass CI? while the PR #4971 created by @nartal1 failed CI?

#4955 was merged 3 days ago, premerge CI was just testing against merged code of PR at that moment, I am not sure if any following commits break the tests

**Comment by pxLi** [comment]
@razajafri also https://github.com/NVIDIA/spark-rapids/pull/4955 run w/o databricks while #4971 failed only w/ databricks

**Comment by razajafri** [comment]
@pxLi how the PR #4955 was able to pass CI? while the PR #4971 created by @nartal1 failed CI? 

> @razajafri also #4955 run w/o databricks while #4971 failed only w/ databricks
> 
> And IIRC, we do not have cache test w/ PCBS enabled in pre-merge CI non-databricks part (we have for databricks and nightly CI though). As our base shim has become spark311, If you need this to be tested in premerge non-db env, either make the PCBS as default config or add a separate test in the https://github.com/NVIDIA/spark-rapids/blob/branch-22.04/jenkins/spark-premerge-build.sh#L105 ci_2 part~

The premerge doesn't run PCBS but I wasn't aware that we run PCBS tests for DB. Thanks for letting me know. 
@tgravescs I know we decided against running premerge for PCBS in the past but given that we have 31x as the default version should we turn the premerge with PCBS on even for nondb Spark versions?

**Pull request merged**
