### PR TITLE
Init 23.08 changelog [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
init changelog w/
```
GITHUB_TOKEN=<PAT> scripts/generate-changelog --releases=23.06,23.08
```

This is for in-advance review, we will update the changelog before RC building

### CODE REVIEW

**Comment by pxLi** [comment]
@mattahrens @sameerz @GaryShen2008 Please help adjust titles/labels/project of 23.08 issues and PRs, I will re-generate later thanks

**Review by sameerz — COMMENTED** [review]
I reviewed and made some label changes.  Ok to approve after regenerating.

**Comment by pxLi** [comment]
> I reviewed and made some label changes. Ok to approve after regenerating.

thanks, re-generated

**Review by sameerz — APPROVED** [review]

**Comment by pxLi** [comment]
I will update the changelog to latest right before we try to build Release candidate

**Comment by pxLi** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Pull request merged**
