### PR TITLE
Fix comments style to pass scala style check

### PR DESCRIPTION
**Pull request by LuciferYang**
There are 4 files in shuffle-plugin module use Incorrect comments format as following:

- UCXTransaction.scala
- UCXShuffleTransport.scala 
- UCX.scala
- UCXConnection.scala

They don't follow the `NoScalaDoc` check rule, this pr fix these to pass scala style check.

### CODE REVIEW

**Comment by svcngcc** [comment]
Can one of the admins verify this patch?

**Comment by LuciferYang** [comment]
gentle ping @jlowe  plz have a review, thx

**Comment by tgravescs** [comment]
build

**Comment by revans2** [comment]
Thanks for the fix this is great, but legal requires that you sign your commits as described here.  We don't have CI setup yet to enforce this but it should be coming soon.

https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/CONTRIBUTING.md#sign-your-work

**Comment by jlowe** [comment]
> Need to have commits signed

To be clear, we need the commits to be _signed-off_ rather than _signed_.  We do not require that commits are cryptographically signed.  The sign-off essentially boils down to adding the `-s` flag when you perform the git commit as a conscious decision that you agree to the Developer Certificate of Origin.

**Comment by LuciferYang** [comment]
Is ok now or "commit -s " required for the first commit? @jlowe @revans2

**Comment by revans2** [comment]
build

**Comment by LuciferYang** [comment]
@revans2 Thank you for your explanation ~

**Comment by revans2** [comment]
The test failure from CI appeared to be a flaky test, so I am going to merge this anyways.

**Comment by jlowe** [comment]
I filed #473 to track the test failure.

**Pull request merged**
