### PR TITLE
[databricks] Reorganize and shim ScanExecMeta overrides and fix interval file IO

### LINKED ISSUE #7324: [BUG] Support DayTimeIntervalType in Databricks-11.3 to fix integration tests
**Describe the bug**
Below tests are failing due to missing DayTimeIntervalType in 330db shim. 

- [ ] test_parquet_read_daytime_interval_cpu_file
- [ ] test_parquet_read_daytime_interval_gpu_file
- [ ] test_round_trip_for_interval
- [x] test_abs_ansi_no_overflow_day_time_interval
- [x] test_abs_ansi_overflow_day_time_interval
- [x] test_day_time_interval_division_nan
- [x] #7387
- [x] test_day_time_interval_division_number_no_overflow2
- [x] test_day_time_interval_division_round_overflow
- [x] test_day_time_interval_multiply_number
- [x] test_timeadd_daytime_column

Reason for failure(Exec name changes but the reason is same) - 
```
!Exec <FileSourceScanExec> cannot run on GPU because unsupported data types in output: DayTimeIntervalType(0,3) [_c1#5]
```

**Steps/Code to reproduce bug**
Build and run integration tests on Databricks-11.3 environment.
Build  steps - Pull in this PR locally if not merged - https://github.com/NVIDIA/spark-rapids/pull/7152 
                      /home/ubuntu/spark-rapids$ ./jenkins/databricks/build.sh

Test steps:  Modify the test.sh under jenkins/databrikcs to run a specific test.
                Example: Comment all lines starting from `export TEST_PARALLEL=${TEST_PARALLEL:-4}` in the file and add below lines:
                ```
                export TEST_PARALLEL=${TEST_PARALLEL:-1}
                TEST_NAME=$1
                bash /home/ubuntu/spark-rapids/integration_tests/run_pyspark_from_build.sh -k $TEST_NAME
               ```

Run Test -  `./jenkins/databricks/test.sh test_day_time_interval_division_nan `

**Expected behavior**
All above tests should pass on Databricks-11.3 shim

**Environment details (please complete the following information)**
Databricks-11.3 runtime.

**Additional context**

### PR DESCRIPTION
**Pull request by rwlee**
Resolves #7324

Resolves the file IO issues for interval type on DB 11.3.

Shims the `FileSourceScanExec` and `BatchScanExec` overrides starting in 320. With some changes shimming in 31x could eliminate more duplicate code but held off given the prioritization of 11.3.

`FileSourceScanExecMeta` and `BatchScanExecMeta` were originally defined in `Spark320PlusShims.scala` but that made reusing the meta definitions difficult when shimming the gpu overrides. Additionally, `FileSourceScanExecMeta` had a DB specific implementation where the gpu override was being remapped multiple times (originally `FileSourceScanExec` had an override in 320+, 321db, 330+, and would need a 330db override as well). Pulling the meta definitions into their own files allows for cleaner override definitions with a split platform specific implementation. `tagFileSourceScanExec` is also pulled into `ScanExecShims` for better logical grouping and solves similar problems of repeated overrides for platform specific implementation.

`ScanExecShims.execs` only needs to be added to execs once in `Spark320PlusShims.scala` because all future shims should inherit the 320 `getExecs` changes via calls to `super.getExecs` (as seen in `Spark330PlusShims.scala` and other `Plus` shims). Resulting behavior will rely on the unique `ScanExecShims.scala` and `*ScanExecMeta.scala` files available to a given build managed by the pom.

### CODE REVIEW

**Comment by rwlee** [comment]
build

**Comment by gerashegalov** [comment]
Need to add at least one signoff commit https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/CONTRIBUTING.md#sign-your-work 

Please describe the changes in more detail. E.g. how do 330+ shims consume overrides now that they are removed from the trait

**Comment by rwlee** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Pull request merged**
