### PR TITLE
Improve aggregation performance of average on DECIMAL128 columns [databricks]

### LINKED ISSUE #4722: Optimize DECIMAL128 average aggregations
The optimizations for DECIMAL128 sum aggregations and overflow checking in #4688 should be applied to aggregations producing an average of DECIMAL128.  Since average aggregations are a combination of sum aggregation and count aggregations, it should be relatively straightforward to adopt the same approach that was done for sum aggregations.

### PR DESCRIPTION
**Pull request by jlowe**
Fixes #4722.

Accelerates DECIMAL128 average aggregations using the same technique employed in #4688.  This allows the use of the cudf hash-based algorithm instead of the slower sort-based algorithm for these types of aggregations.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by jlowe** [comment]
CI failed due to recent cudf string split API breakage:
```
Error: :43:11.360Z] [ERROR] [Error] /home/jenkins/agent/workspace/jenkins-rapids_premerge-github-3972/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala:1371: overloaded method value stringSplitRecord with alternatives:
[2022-02-14T17:43:11.361Z]   (x$1: String,x$2: Int)ai.rapids.cudf.ColumnVector <and>
[2022-02-14T17:43:11.361Z]   (x$1: String,x$2: Boolean)ai.rapids.cudf.ColumnVector
[2022-02-14T17:43:11.361Z]  cannot be applied to (ai.rapids.cudf.Scalar, Int)
```

**Comment by jlowe** [comment]
build

**Review by abellina — APPROVED** [review]

**Comment by jlowe** [comment]
CI couldn't find resources:
```
[2022-02-15T15:28:14.617Z] Waited 60 times already, stopping
```

**Comment by jlowe** [comment]
build

**Pull request merged**
