### PR TITLE
Added in basic support for scalar structs to named_struct

### LINKED ISSUE #2501: [FEA] Add support for scalar structs to named_struct
this is a follow on to #2498 and #2436

They added in support for maps and lists to be children of `named_struct`. Which really the thing blocking them was the ability to deal with scalar nested values.  We still need to add in support for structs because the cudf code for that is not 100% ready just yet.

### PR DESCRIPTION
**Pull request by revans2**
This fixes #2501

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@tgravescs it is not just to named_struct, even though that is being fixed by this. It just makes it possible for literal structs in general, including in project.

**Review by jlowe — APPROVED** [review]

**Comment by tgravescs** [comment]
ok can we update description and issue, it points to an issue that says for named_structs

**Pull request merged**
