### PR TITLE
[Doc]update getting started doc for EMR and databricks[skip ci]

### PR DESCRIPTION
**Pull request by nvliyuan**
this PR is to :
1. update getting started on EMR for emr-690 release
2. update getting started on databricks since we don't need to disable auto-scaling
Signed-off-by: liyuan <yuali@nvidia.com>

### CODE REVIEW

**Comment by nvliyuan** [comment]
verified
image

**Comment by nvliyuan** [comment]
verified Databricks: `current` worker autoscaled from 1 to 3
image

**Comment by nvliyuan** [comment]
for the markdown failure, filed an [issue](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/169)

**Review by sameerz — APPROVED** [review]

**Comment by sameerz** [comment]
build

**Pull request merged**
