### PR TITLE
Fix Orc writer test failure with Spark 3.4

### PR DESCRIPTION
**Pull request by andygrove**
Closes https://github.com/NVIDIA/spark-rapids/issues/7751

A test was failing against 3.4 because the plan includes the new `WriteFilesExec` operator, and this was not part of the `execsAllowedNonGpu` list.

This PR adds this operator to `execsAllowedNonGpu`.

### CODE REVIEW

**Comment by andygrove** [comment]
build

**Review by NVnavkumar — APPROVED** [review]
LGTM

**Review by nartal1 — APPROVED** [review]

**Comment by abellina** [comment]
Do we need to create `GpuWriteFilesExec`? @andygrove

**Comment by andygrove** [comment]
> Do we need to create `GpuWriteFilesExec`? @andygrove

It is already implemented (see https://github.com/NVIDIA/spark-rapids/pull/7542). This test needs to fall back to CPU still because we don't support Orc encryption.

**Review by abellina — APPROVED** [review]

**Pull request merged**
