### PR TITLE
More compilation fixes for Spark 4.0.0 [databricks]

### LINKED ISSUE #10972: Spark 4.0 compile errors
```
[ERROR] /home/rjafri/dev/worktrees/SP-9259-400-shim/sql-plugin/src/main/spark311/scala/org/apache/spark/rapids/shims/GpuShuffleExchangeExec.scala:53: class GpuShuffleExchangeExec needs to be abstract.
Missing implementation for member of trait ShuffleExchangeLike:
  def shuffleId: Int = ???

[ERROR] /home/rjafri/dev/worktrees/SP-9259-400-shim/sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/GpuOrcDataReader.scala:53: class GpuOrcDataReader needs to be abstract.
Missing implementation for member of trait DataReader:
  def releaseAllBuffers(): Unit = ???

[ERROR] /home/rjafri/dev/worktrees/SP-9259-400-shim/sql-plugin/src/main/spark400/scala/com/nvidia/spark/rapids/shims/GpuBatchScanExec.scala:47: `override` modifier required to override concrete member:
lazy val batch: org.apache.spark.sql.connector.read.Batch (defined in class GpuBatchScanExecBase)

```

### PR DESCRIPTION
**Pull request by razajafri**
This PR solves the last bit of the compilation errors, when building for Spark 4.0.

fixes #10972

### CODE REVIEW

**Review by mythrocks — APPROVED** [review]
LGTM!

**Comment by razajafri** [comment]
Sorry, this should be shimmed!

**Comment by razajafri** [comment]
build

**Comment by mythrocks** [comment]
Reviewing the latest version now.

**Review by mythrocks — APPROVED** [review]
Ok, that looks better.  We use the trait for the `CudfUnsafeRow` object, and `Base` for the class.  That works for me.

**Pull request merged**
