### PR TITLE
Remove the MIT license from tools jar[skip ci]

### PR DESCRIPTION
**Pull request by GaryShen2008**
we have moved tools to spark-rapids-tools/core
These MIT licenses are only for the UI of tools jar

Contribute: https://github.com/NVIDIA/spark-rapids-tools/issues/46

Signed-off-by: gashen <gashen@nvidia.com>

### CODE REVIEW

**Comment by GaryShen2008** [comment]
build

**Review by jlowe — COMMENTED** [review]
There's a number of things in NOTICE and NOTICE-binary that also need to be removed (Bootstrap, DataTablesSrc, jQuery, Mustache, and Spur).

**Comment by amahussein** [comment]
> There's a number of things in NOTICE and NOTICE-binary that also need to be removed (Bootstrap, DataTablesSrc, jQuery, Mustache, and Spur).

+1

Since we do not include those binaries into the JAR, then NOTICE and NOTICE-binary also need to be updated.

**Review by amahussein — CHANGES_REQUESTED** [review]
Remove the JS from NOTICE and NOTICE-binary

**Comment by GaryShen2008** [comment]
Updated NOTICE and NOTICE-binary

**Comment by GaryShen2008** [comment]
build

**Comment by GaryShen2008** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Comment by GaryShen2008** [comment]
build

**Comment by GaryShen2008** [comment]
build

**Pull request merged**
