### PR TITLE
Update docs and scripts to 0.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by jlowe**
When branch-0.4 was setup only the pom versions were updated.  There were many references to 0.3.0-SNAPSHOT in the documentation and scripts that were missed.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
