### PR TITLE
Move to the cudf-0.15 release

### PR DESCRIPTION
**Pull request by revans2**
Changes our dependency to be the official cudf 0.15 release,

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by jlowe** [comment]
Can we update all the 0.15-SNAPSHOT references in the docs while we're at it?

**Comment by jlowe** [comment]
There are also references to 0.15-SNAPSHOT under jenkins/

**Comment by kuhushukla** [comment]
Can we update the jenkins and docs files for this version change?

**Comment by revans2** [comment]
`find . -type f | xargs grep -l 0.15-SNAPSHOT` returns nothing.

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by kuhushukla — APPROVED** [review]

**Pull request merged**
