### PR TITLE
Fix the time zone check issue

### PR DESCRIPTION
**Pull request by firestarman**
Fixes https://github.com/NVIDIA/spark-rapids/issues/5678

There are two settings for time zone, the Spark session local time zone and JVM's default time zone. And they may be different from each other according to issue #5678. 

With this PR, plugin now requires both of the two settings being equal to UTC to support timestamp type.

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
For early review

**Comment by tgravescs** [comment]
did you mean this to be against 22.06?

**Comment by firestarman** [comment]
> did you mean this to be against 22.06? Unless specifically requested this should go against 22.08

It is a bug fix, so I thought it should go into 06.

**Comment by jlowe** [comment]
build

**Comment by gerashegalov** [comment]
The change looks good as a narrow fix. 

However, the logic for timezone error handling in the plugin initialization is not quire clear  
- first we stash away the initial value of the default  timezone on the driver  https://github.com/NVIDIA/spark-rapids/blob/0b2eeb1589409a2f3813ac8a80a3ea24d57cdc0f/sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala#L141 . 
- We don't throw an exception on the driver, if it's not a supported time zone, which I think is OK because it can still be changed for the JVM using java.util.TimeZone.setDefault
- Then on the executor side plugin init we throw an exception on discrepancy between the driver and executor default timezones but only if the driver timezone is UTC https://github.com/NVIDIA/spark-rapids/blob/aba390e2909fc9e753a128095d97bc46e774e8ec/sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala#L221  This does not make sense to me. Either always throw when timezones are different. Or adjust the executor timezone with TimeZone.setDefault(TimeZone.getTimeZone(driverTimeZone)) unless it is explicitly overridden with  user.timezone in executor Java options

We need to file the issue to clarify this if it's beyond the current PR.

**Review by gerashegalov — APPROVED** [review]
LGTM with caveats regarding Plugin init checks

**Comment by firestarman** [comment]
Personally the current time zone checks in Plugin init are OK. (Please correct me if I am wrong)

At the init stage on the driver, Plugin does not know whether the time zone will be used. So it is not necessary to check the time zone. And this check will be executed during the related operators overriding later. 

On executors, the time zone is required to be equal to the driver's only for the time related GPU operators, I think. If time zone is not supported, no time related GPU operators exists (all fall back to CPU), then no need to check the difference of the time zones.

**Comment by firestarman** [comment]
I am going to merge this, if any issue, we can follow up in new issues.

**Comment by gerashegalov** [comment]
> > We need to file the issue to clarify this if it's beyond the current PR.
> 
> Personally the current time zone checks in Plugin init are OK. (Please correct me if I am wrong)
> 
> At the init stage on the driver, Plugin does not know whether the time zone will be used. So it is not necessary to check the time zone here. And this check will be executed during the time related operators' overriding process later.
> 

> On executors, the time zone is required to be equal to the driver's only for the time related GPU operators, I think. If time zone is not supported, no time related GPU operators exist (all fall back to CPU), then no need to check the difference of the time zones.

So looks like you are arguing for dropping the check https://github.com/NVIDIA/spark-rapids/blob/aba390e2909fc9e753a128095d97bc46e774e8ec/sql-plugin/src/main/scala/com/nvidia/spark/rapids/Plugin.scala#L221

because it's an init-time check.

Also again the default timezone of the driver as of init time may be different at the query time. I'll file an issue to clarify these limitations.

**Pull request merged**
