### PR TITLE
Auto abort dup pre-merge builds [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

fix https://github.com/NVIDIA/spark-rapids/issues/3486

verified in forked repo

**NOTE:** please help review. Allow me to merge this and do some verification, thanks

### CODE REVIEW

**Comment by pxLi** [comment]
convert to draft to avoid accidental merge

**Review by GaryShen2008 — APPROVED** [review]

**Review by zhanga5 — APPROVED** [review]

**Review by jlowe — APPROVED** [review]
Thanks for working on this, @pxli!

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
Going to do some verifications

**Pull request merged**
