### PR TITLE
Add Shim JSON Headers for Databricks 13.3

### PR DESCRIPTION
**Pull request by razajafri**
This pull request introduces support for Databricks 13.3. This PR is part of a series of PRs that will address the complete support for Databricks 13.3. The primary focus of this PR is the addition of necessary shims for 341db.

**Changes Made:**

Shims for 341db: This PR includes the implementation of shims to support this version of Databricks, ensuring that our codebase remains compatible.

**Testing:**

Tests will be addressed in subsequent PRs

contributes towards #9175

### CODE REVIEW

**Comment by razajafri** [comment]
build

**Review by andygrove — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
The PR headline should be updated to be a bit more descriptive.  As it is, it implies this PR adds support for Databricks 13.3 which isn't quite accurate.

**Comment by gerashegalov** [comment]
If this PR merely shimplify-generated it would help if we can see the command line used in the description. 

Should spark341db.RapidsShuffleManager be part of the PR?

**Comment by razajafri** [comment]
> If this PR merely shimplify-generated it would help if we can see the command line used in the description.
> 
> Should spark341db.RapidsShuffleManager be part of the PR?

Thank you for the comment. This isn't just shimplify-generated code but a commit from a branch that is already building. I have just broken the commits down so they are easier to review. 

You can see the branch [here](https://github.com/razajafri/spark-rapids/tree/SP-9175-db13.3-clean-rebased-2). 

The RapidsShuffleManager will be a part of the boilerplate that will follow in subsequent PRs.

**Comment by razajafri** [comment]
build

**Comment by gerashegalov** [comment]
> > If this PR merely shimplify-generated it would help if we can see the command line used in the description.
> > Should spark341db.RapidsShuffleManager be part of the PR?
> 
> Thank you for the comment. This isn't just shimplify-generated code but a commit from a branch that is already building. I have just broken the commits down so they are easier to review.
> 
> You can see the branch [here](https://github.com/razajafri/spark-rapids/tree/SP-9175-db13.3-clean-rebased-2).
> 
> The RapidsShuffleManager will be a part of the boilerplate that will follow in subsequent PRs.

In the future It is easier for the reviews if we follow the standard procedure that also takes care of the RapidsShuffleManager
https://github.com/NVIDIA/spark-rapids/blob/97089e67574ecf45edfc93f408c73492bdafcf11/docs/dev/shimplify.md?plain=1#L185-L187

**Comment by razajafri** [comment]
> > > If this PR merely shimplify-generated it would help if we can see the command line used in the description.
> > > Should spark341db.RapidsShuffleManager be part of the PR?
> > 
> > 
> > Thank you for the comment. This isn't just shimplify-generated code but a commit from a branch that is already building. I have just broken the commits down so they are easier to review.
> > You can see the branch [here](https://github.com/razajafri/spark-rapids/tree/SP-9175-db13.3-clean-rebased-2).
> > The RapidsShuffleManager will be a part of the boilerplate that will follow in subsequent PRs.
> 
> In the future It is easier for the reviews if we follow the standard procedure that also takes care of the RapidsShuffleManager
> 
> https://github.com/NVIDIA/spark-rapids/blob/97089e67574ecf45edfc93f408c73492bdafcf11/docs/dev/shimplify.md?plain=1#L185-L187

I do see your point. In this case, however, breaking down the commits into smaller chunked PRs was an afterthought.

**Comment by NvTimLiu** [comment]
@razajafri  

Please add 13.3 in the below line to run pre-merge CI with Databricks 13.3 against your PR,   `values '10.4', '11.3', '12.2', '13.3'`
https://github.com/NVIDIA/spark-rapids/blob/branch-23.12/jenkins/Jenkinsfile-blossom.premerge-databricks#L91

**Comment by razajafri** [comment]
> @razajafri
> 
> You can add 13.3 in the below line to run pre-merge CI with Databricks 13.3 against your PR, `values '10.4', '11.3', '12.2', '13.3'` https://github.com/NVIDIA/spark-rapids/blob/branch-23.12/jenkins/Jenkinsfile-blossom.premerge-databricks#L91

Thanks, I will add it after the pom changes are in as we aren't building against 13.3 yet.

**Pull request merged**
