### PR TITLE
Update fastparquet to 2024.5.0 for numpy2 compatibility [databricks]

### LINKED ISSUE #11070: [BUG] numpy2 fail fastparquet cases: numpy.dtype size changed
**Describe the bug**
numpy has just released 2.0.0 to pip and conda, we found that it would fail our fastparquet cases (pip install on different ENV could result non-deterministic versions)

**py3.8/3.9** still use pandas 2.0.x + numpy 1.2x 
but **py3.10** use pandas 2.2.x + numpy 2.0
as pip install defaults. But all the defaults would eventually be upgraded to use numpy 2.0+

```
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

during ENV preparation
```
Downloading numpy-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)

numpy==2.0.0
├── fastparquet==0.8.3 [requires: numpy>=1.18]
├── pandas==2.2.2 [requires: numpy>=1.22.4]
│   └── fastparquet==0.8.3 [requires: pandas>=1.1.0]
└── pyarrow==16.1.0 [requires: numpy>=1.16.6]
```

Please help determine if we should xfail the cases to wait for compatibility support (or adjust existing deps versions) or we explicitly limit numpy version to <2.0.0 for now

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**
Pass the tests with numpy2 

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

### PR DESCRIPTION
**Pull request by pxLi**
try fix #11070 

1. update fastparquet to 2024.5.0 based on https://github.com/numpy/numpy/issues/26191
2. keep fastparquet 0.8.3 for python 3.8 only (databricks 11.x,12.x runtime)
3. revert the previous WAR to check if all tests work fine

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
need to determine if we would like to continue test against fastparquet-0.8 + py38 for the case.

https://github.com/NVIDIA/spark-rapids/issues/11070#issuecomment-2207719495

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
Confirmed all cases passed in CI with py38(fq0.8.3+numpy1),py39&py310(fq2024.5.0+numpy2). 

Please evaluate if it's still necessary to maintain the test run using fastparquet 0.8.3? This version may be significantly outdated (released in 2022) cc @sameerz @mythrocks @amahussein

**Review by NvTimLiu — APPROVED** [review]

**Comment by mythrocks** [comment]
> Please evaluate if it's still necessary to maintain the test run using fastparquet 0.8.3?

At the time I wrote the fastparquet tests, the later fastparquet versions were still in flux.  Depending on the earlier version helped stabilize the behaviour of the tests.

If the tests are passing with the updated fastparquet version, then I'm all for keeping the new version.

**Pull request merged**
