### PR TITLE
Fix `collection_ops_test` for [databricks] 14.3

### LINKED ISSUE #11532: Fix Collections tests on Databricks 14.3
Build the plugin against the Databricks 14.3 cluster using #11467. Once built successfully run the collection ops tests by `TESTS=collection_ops_test.py jenkins/databricks/test.sh` 

The following tests fail 
```
[gw3] [ 13%] FAILED ../../src/main/python/collection_ops_test.py::test_sequence_too_long_sequence
```

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #11532.

This commit introduces a `RapidsErrorUtils` shim for Databricks 14.3, to deal with the new error messages thrown for large array/sequences.

This should fix the failure in `collection_ops_test.py::test_sequence_too_long_sequence` on Databricks 14.3.

### CODE REVIEW

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
Build

**Review by razajafri — APPROVED** [review]
LGTM

**Comment by mythrocks** [comment]
Thank you for the review, @razajafri.  I've merged this change.

**Pull request merged**
