### PR TITLE
regexp: Catch "nothing to repeat" errors nested in groups

### PR DESCRIPTION
**Pull request by anthony-chang**
Fixes https://github.com/NVIDIA/spark-rapids/issues/6243

cuDF recently merged https://github.com/rapidsai/cudf/pull/11373 which caught some new cases that it should not be able to support. We previously caught some of these but not all of them, and this PR adds checks for those remaining cases.

### CODE REVIEW

**Comment by anthony-chang** [comment]
build

**Review by andygrove — APPROVED** [review]

**Comment by anthony-chang** [comment]
The build is failing with 
```
/home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:1395: not found: value readDataSchema
```
which looks unrelated. Is this a known issue?

**Comment by jlowe** [comment]
22.10 build is currently broken due to a bad auto-merge from 22.08.  I have a fix in #6246, but it's failing CI due to this bug.

@anthony-chang can you cherry-pick this commit into your branch?  Then we should have something that can pass CI and unblock 22.10.  https://github.com/NVIDIA/spark-rapids/pull/6246/commits/c24f790fec92135066ca832805a04de9c969917e

**Comment by anthony-chang** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
