### PR TITLE
Skip tests that fail due to recent cuDF changes related to end of string/line anchors

### PR DESCRIPTION
**Pull request by andygrove**
Related to https://github.com/NVIDIA/spark-rapids/issues/7090

Creating this PR to fix the build while I work on the real fixes, which may take some time.

### CODE REVIEW

**Comment by andygrove** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by NVnavkumar — APPROVED** [review]

**Comment by andygrove** [comment]
There was a test failure that appears to be unrelated to the changes in this PR:

```
2022-11-29T18:19:30.4769693Z [2022-11-29T18:07:58.556Z] ^[[31m- Test Parquet nested unsigned int: uint8, uint16, uint32 *** FAILED ***^[[0m
2022-11-29T18:19:30.4770528Z [2022-11-29T18:07:58.556Z] ^[[31m  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 251.0 failed 1 times, most recent failure: Lost task 0.0 in stage 251.0 (TID 1125) (premerge-ci-2-jenkins-rapids-premerge-github-6187-06svq-vckx8 executor driver): java.lang.IllegalArgumentException: Cannot grow BufferHolder by size -8 because the size is negative^[[0m
2022-11-29T18:19:30.4770954Z [2022-11-29T18:07:58.556Z] ^[[31m  at org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder.grow(BufferHolder.java:67)^[[0m
20
```

**Comment by jlowe** [comment]
@andygrove Can you reproduce the failure locally?  I was unable to do so on vanilla 23.02.0-SNAPSHOT.

**Comment by andygrove** [comment]
> @andygrove Can you reproduce the failure locally? I was unable to do so on vanilla 23.02.0-SNAPSHOT.

No, works fine locally. I guess I'll just kick off the build again.

**Comment by andygrove** [comment]
build

**Pull request merged**
