### PR TITLE
Update actions version [skip ci]

### PR DESCRIPTION
**Pull request by YanxuanLiu**
Update actions version for Node.js 20

### CODE REVIEW

**Comment by YanxuanLiu** [comment]
build

**Comment by sameerz** [comment]
Is this critical for 24.04, or can it be targeted to 24.06?

**Comment by YanxuanLiu** [comment]
> Is this critical for 24.04, or can it be targeted to 24.06?

changed to 24.06

**Comment by YanxuanLiu** [comment]
build

**Comment by YanxuanLiu** [comment]
Note that we will not update action versions in `blossom-ci.yml`, since there is strict file verification from blossom team. They will update the actions for all teams using blossom-ci later.

**Comment by YanxuanLiu** [comment]
build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Pull request merged**
