### PR TITLE
Use new getJsonObject kernel for json_tuple

### PR DESCRIPTION
**Pull request by thirtiseven**
This PR updates json_tuple with new getJsonObject kernel.

All current xfailed cases got passed:
```
./integration_tests/run_pyspark_from_build.sh -s -k json_tuple
......
============= 16 passed, 13 xpassed, 8 warnings in 49.36s ============
```

I think the performance will not be good because it calls getJsonObject kernel many times, which is not very fast by itself.

With the new json_parser in jni, I think we can implement a kernel for json_tuple to get much higher performance by passing all fields in one pass. So this PR will be a short-term workaround, even if it gets merged. 

Depends on https://github.com/NVIDIA/spark-rapids-jni/pull/1893

### CODE REVIEW

**Comment by revans2** [comment]
> Wow, so it is actually quite fast. Not sure if I tested it right.

A bit of feedback on the quick test.

1. Looks like you only ran it once. Cold runs are usually a lot slower than hot runs, but even then.
2. All of your data is the same. Which means that there is no thread divergence in the GPU. 
3. You don't mention what CPU/system was used so it is hard to tell if it is a fair comparison or not.
4. It would be nice to see how fast the parquet read is compared to the CPU. all of the performance gains might be in that, just because it is a single string column repeated 3,000,000 times.

**Review by revans2 — APPROVED** [review]
Might also be nice to have a follow on issue to see if we can drop the special field name checks.

**Comment by thirtiseven** [comment]
Updated, the special field name checks are safe to drop.

**Comment by thirtiseven** [comment]
build

**Comment by thirtiseven** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by thirtiseven** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by thirtiseven** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
