### PR TITLE
Remove an unused config shuffle.spillThreads

### PR DESCRIPTION
**Pull request by abellina**
Removes an unused config `spark.rapids.sql.shuffle.spillThreads` from `RapidsConf`

### CODE REVIEW

**Comment by abellina** [comment]
build

**Review by jlowe — COMMENTED** [review]
config docs need to be generated, since this config appears there.  Interesting that we marked this as commonly used when it has no effect?

**Comment by abellina** [comment]
> config docs need to be generated, since this config appears there. Interesting that we marked this as commonly used when it has no effect?

Ah let me generate.

Agree, it has been in the repo for 4 years according to the blame history.

**Comment by abellina** [comment]
build

**Pull request merged**
