### PR TITLE
Revert Null Join Filter

### LINKED ISSUE #744: [BUG] TPC-DS query 6 now produces incorrect results.
**Describe the bug**
When I run TPC-DS query 6 on scale factor 1 I get an incorrect result relative to the CPU.  The GPU version is missing a null `state` count.

**Steps/Code to reproduce bug**
```
./run_pyspark_from_build.sh -k 'tpcds[q6]' --tpcds_path=/home/roberte/src/data/tpcds/SF1_parquet/ --tpcds_format=parquet
```

**Expected behavior**
It should pass, but it fails.

**Environment details (please complete the following information)**
0.2 pre-release

**Additional context**
I had to make some minor changes to get this to work because the java/scala APIs changed a bit and things needed to be updated. I'll add in a patch.

### PR DESCRIPTION
**Pull request by revans2**
This fixes #744 

This reverts #594 

It appears that I missed something when I put in the original change and I cannot think of what I did wrong quickly, so I am going to revert this for 0.2 and reopen the original issue so I can try again in 0.3

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
I reran all of the tpc-ds tests and scale factor 1 and they all pass now.

**Review by jlowe — APPROVED** [review]
Unfortunate that some nice code cleanup is also getting reverted with this.

**Review by abellina — APPROVED** [review]

**Comment by revans2** [comment]
> Unfortunate that some nice code cleanup is also getting reverted with this.

I plan on putting this back in again for 0.3 once I have more then an hour to try and figure out what is happening.

**Comment by jlowe** [comment]
Actually now that this is getting punted to 0.3 and thus cudf-0.16, I wonder if we should focus our efforts on implementing the fix in libcudf as mentioned by https://github.com/rapidsai/cudf/issues/6052#issuecomment-677672991.  I think that would be the preferred solution from a performance and code complexity perspective.

**Pull request merged**
