### PR TITLE
Profile/qualification tool error handling improvements and support spark < 3.1.1

### PR DESCRIPTION
**Pull request by tgravescs**
I found a few issues with bad event logs, added more error handling and tests.

I also added support for running with Spark versions < 3.1.1, this was due to the ResourceProfile event only in 3.1.

Renamed Rank to be Score based on feedback.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by nartal1 — DISMISSED** [review]

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
missed test files on upmerge

**Comment by tgravescs** [comment]
build

**Review by nartal1 — APPROVED** [review]

**Pull request merged**
