### PR TITLE
Qualification tool application time calculation can count stages twice if in separate sql queries 

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/6637

the same stage might be referenced from multiple sql queries, we have to dedup them
with the assumption the stage was reused so time only counts once

Manually verified with customer event log and also wrote unit test. Without the fix the unit test fails when hits assert at:

```
java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:208)
    at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.calculateNonSQLTaskDataframeDuration(QualificationAppInfo.scala:134)
    at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.$anonfun$aggregateStats$1(QualificationAppInfo.scala:396)
   
```

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Review by amahussein — APPROVED** [review]
LGTM

**Comment by tgravescs** [comment]
link checker failed on ERROR: 1 dead links found!
[✖] https://www.mellanox.com/products/infiniband-drivers/linux/mlnx_ofed → Status: 0 

But it looks like its back now

**Review by nartal1 — APPROVED** [review]
LGTM

**Pull request merged**
