### PR TITLE
Move GpuWindowInPandasExec in shims layers

### PR DESCRIPTION
**Pull request by NvTimLiu**
For https://github.com/NVIDIA/spark-rapids/issues/844

Add the shim layers for GpuWindowInPandasExec.  The base class of GpuWindowInPandasExec is WindowExecBase. 

WindowExecBase is an abstract class in Spark 3.0.x, but becomes a trait in Spark 3.1.0.

So need to add shims layers to support among Spark 3.0.0 and 3.1.0.

Unit tests and IT pass.

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by firestarman** [comment]
build failed due to 
`error file=/ansible-managed/jenkins-slave/slave4/workspace/spark/rapids_premerge-github/shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/Spark300Shims.scala message=File line length exceeds 100 characters line=182`

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by firestarman** [comment]
build

**Review by firestarman — APPROVED** [review]

**Comment by NvTimLiu** [comment]
@tgravescs Could you please help to review this change? Thanks!

We need to add `GpuWindowInPandasExec` in shims layer because spark-3.1.0 changed its base class `[WindowExecBase](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/window/WindowExecBase.scala#L29)`  from abstract class to trait.

**Review by revans2 — APPROVED** [review]
It would be nice to see if there are some things that we could make common between the 3.0.0 and the 3.1.0 versions.  But it should be fine for now.

**Comment by tgravescs** [comment]
yeah it would be nice to see if we can reuse some code

**Comment by NvTimLiu** [comment]
> yeah it would be nice to see if we can reuse some code
@tgravescs @revans2 
Thanks for your suggestion, I'll  make a common class/trait between the 3.0.0 and the 3.1.0 versions, to reuse some code

**Pull request merged**
