### PR TITLE
Make tools inherit common dependency versions from parent pom

### PR DESCRIPTION
**Pull request by gerashegalov**
Tools should not unnecessarily override parent pom versions

Recurrence of #2088 

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by sameerz** [comment]
Does this belong in 21.06 or 21.08?

**Comment by gerashegalov** [comment]
re-targetted to `branch-21.08`

**Comment by pxLi** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by pxLi** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
