### PR TITLE
Change logInfo to logWarning

### LINKED ISSUE #3959: [Audit][FEA] [SPARK-36070][CORE] Log time cost info for writing rows out and committing the task
**Is your feature request related to a problem? Please describe.**
This issue is just to keep GpuFileFormatWriter.scala in sync with changes in Apache Spark FileFormatWriter.scala. The PR is used to add logging which would help to debug. It doesn't affect functionality in anyway.
PR- https://github.com/apache/spark/commit/f5a63322de

Another trivial change - https://github.com/apache/spark/commit/2fc9c0bfb5 (change logInfo to logWarning)

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
close #3959 

This PR is to keep in sync with apache/spark@2fc9c0b (change logInfo to logWarning)

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by gerashegalov — APPROVED** [review]

**Comment by HaoYang670** [comment]
build

**Comment by revans2** [comment]
build

**Comment by HaoYang670** [comment]
build

**Pull request merged**
