### PR TITLE
Init 22.04 changelog [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

Generated w/ 
`GITHUB_TOKEN=<xxx> scripts/generate-changelog --releases=21.06,21.06.1,21.06.2,21.08,21.08.1,21.10,21.12,22.02,22.04`

We will do a followup update after all 22.04 PRs got merged.

### CODE REVIEW

**Comment by pxLi** [comment]
@sameerz can you help check the details of 22.04 changelog? I will re-generate if any updates, thanks!

**Comment by sameerz** [comment]
> @sameerz can you help check the details of 22.04 changelog? I will re-generate if any updates, thanks!

I checked and made a few changes to 22.04 and updated some old issues to assign them to projects where they were missing.  Please regenerate.  There will be a few late issues coming in after this, of course.

**Comment by pxLi** [comment]
build

**Review by zhanga5 — APPROVED** [review]

**Comment by pxLi** [comment]
merged. I will do a final update of the changelog before release

**Pull request merged**
