### PR TITLE
If the GpuShuffleEnv is not initialized throw an IllegalStateException

### PR DESCRIPTION
**Pull request by abellina**
This avoids an NPE as raised here: https://github.com/NVIDIA/spark-rapids/issues/479 to work.

### CODE REVIEW

**Comment by revans2** [comment]
I do want to hear back from @wbo4958 that this meets his needs

**Comment by abellina** [comment]
I did test this with his example and I ran into the NPE. With the fix it was gone. 

I think that in addition to the `GpuShuffleEnv` not being initialized, neither will RMM and it also seems that the gpu initialization (which gpu id we choose) is left going to be skipped, so I assume that other code will get on the GPU and manage memory.

**Comment by revans2** [comment]
GPU initialization is not something that we can skip.  We might end up with running on the wrong GPU.

**Comment by abellina** [comment]
Yes, certainly in this case we are initializing late in the game (when we start needing the context). 

I do believe that having this function NPE (so not doing this fix), prevents any user from initializing RMM/GPU manually. I am not changing the docs saying that this is a supported config, but at least I am not outright getting in the way of a developer. 

So I think this change has some value on its own. It allows the plugin to successfully fallback to partitioning on the CPU. But let me know if you would like to outright disable this (in that case I'd need to throw with something that says this is an invalid config).

**Comment by revans2** [comment]
Running with diminished functionality is one thing, but we might be running on completely the wrong GPU, which is the thing that I personally don't think is something we want to support even if we are trying to get out of the way of a developer.

**Comment by revans2** [comment]
I prefer this fix but we should not close #479 with this patch now.

Originally we did a lazy initialization of the GPU and RMM, but we switched out of performance concerns.  Perhaps we can look at supporting both.

**Comment by abellina** [comment]
@revans2 that's correct. I'll remove that link, it just makes it less painful than an NPE for the time being.

The thing is that this happens in the executor. I think one solution is that the user needs to prepend our `SQLExecPlugin` with their own in the extensions, and initialize the things we need (in this case only `GpuShuffleEnv` which needs the cuda mem info so that the stores can be initialized).

**Comment by revans2** [comment]
build

**Comment by abellina** [comment]
Sorry @revans2 forgot to sign my last commit. Pushed that amend.

**Comment by revans2** [comment]
build

**Pull request closed without merging**
