### PR TITLE
Fix the bug COALESCING reading does not work for v2 parquet/orc datasource

### PR DESCRIPTION
**Pull request by wbo4958**
Backport https://github.com/NVIDIA/spark-rapids/pull/5171 to 22.04

### CODE REVIEW

**Comment by wbo4958** [comment]
build

**Comment by pxLi** [comment]
if decide to target 22.04, plz close #5171 as auto-merge will take care of the commit for 22.06

**Comment by wbo4958** [comment]
I think we should merge it in 22.04 @sameerz what's your opinion?

**Comment by tgravescs** [comment]
the datasource v2 readers are off by default so its definitely less likely this is an issue.  Do we know any customers explicitly using it?  Otherwise I would say leave out of 22.40

**Comment by GaryShen2008** [comment]
Agree, let's leave it out of 22.04. It'll use multithread, not block the feature, only impact the performance.

**Pull request closed without merging**
