### PR TITLE
[DOC] update doc for 24.10 release [skip ci]

### PR DESCRIPTION
**Pull request by nvliyuan**
This PR updates download docs for 24.10.0 release.
Signed-off-by: liyuan <yuali@nvidia.com>

### CODE REVIEW

**Review by sameerz — APPROVED** [review]

**Comment by nvliyuan** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by nvliyuan** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
build

**Pull request merged**
