### PR TITLE
Update to 0.2.0-SNAPSHOT and cudf-0.15-SNAPSHOT

### PR DESCRIPTION
**Pull request by jlowe**
This updates the versions on branch-0.2 to use 0.2.0-SNAPSHOT for the plugin and 0.15-SNAPSHOT for cudf.

### CODE REVIEW

**Comment by abellina** [comment]
Should: https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/jenkins/Jenkinsfile.nightly also be updated?

**Comment by revans2** [comment]
Overall it looks good.  My main concern is around cudf-0.15-SNAPSHOT.  It is not out yet so we should either update in the dev docs about what to do to build it, or we need to get someone working on publishing SNAPSHOT builds for it ASAP.

**Comment by jlowe** [comment]
> My main concern is around cudf-0.15-SNAPSHOT.

Excellent point, I'll work on getting cudf 0.15 snapshot builds published so devs don't have to build their own cudf when working with branch-0.2.

**Comment by jlowe** [comment]
> Should: https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/jenkins/Jenkinsfile.nightly also be updated?

Yes, nice catch!  I also noticed I missed the primary cudf version in the parent pom, so it's sorta important to update that one too. 😄

**Comment by jlowe** [comment]
> Should: https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/jenkins/Jenkinsfile.nightly also be updated?

Yes, nice catch!  I also noticed I missed the primary cudf version in the parent pom, so it's sorta important to update that one too. 😄

**Comment by jlowe** [comment]
> Should: https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/jenkins/Jenkinsfile.nightly also be updated?

Yes, nice catch!  I also noticed I missed the primary cudf version in the parent pom, so it's sorta important to update that one too. 😄

**Comment by jlowe** [comment]
Github is acting up on this PR.  I need to recreate my fork for the public repo anyway, so I'll just post a new PR for this with the updated changes.  Apologies for the move.

**Pull request closed without merging**
