### PR TITLE
Fix scalar leak in SumBinaryFixer (#10510)

### PR DESCRIPTION
**Pull request by jbrennan333**
This is a cherry-pick of #10510, which went into 24.04.

I am putting this up in case we want to merge this in 24.02 at this point?

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by jbrennan333** [comment]
build

**Review by abellina — APPROVED** [review]

**Comment by jbrennan333** [comment]
For context, this bug looks like it was introduced by https://github.com/NVIDIA/spark-rapids/pull/4272, which went into 22.02, so this leak has been there for quite some time.

**Comment by jbrennan333** [comment]
As a validation, I ran nds power run at scale 100 and verified there were no errors, and the output data was correct.

**Comment by sameerz** [comment]
I am ok with this going into 24.02 late, as it is a relatively small fix.  
@NvTimLiu @GaryShen2008 if it is too late for 24.0, we can close this rather than merge it.

**Pull request merged**
