### PR TITLE
Added Shim for BatchScanExec to Support Spark 4.0 [databricks]

### LINKED ISSUE #10712: [AUDIT] BatchScanExec/DataSourceV2Relation to group splits by join keys if they differ from partition keys
As part of https://github.com/apache/spark/commit/9520087409d Spark made a change to change BatchScanExec/DataSourceV2Relation to group splits by join keys if they differ from partition keys (previously grouped only by partition values).  Do same for all auxiliary data structure, like commonPartValues.

This change should be mirrored in GpuBatchScanExec

### PR DESCRIPTION
**Pull request by razajafri**
Spark made a change to [change](https://github.com/apache/spark/commit/9520087409d) BatchScanExec/DataSourceV2Relation to group splits by join keys if they differ from partition keys (previously grouped only by partition values). Do same for all auxiliary data structure, like commonPartValues.

This PR makes changes in the plugin to support that change. 

fixes #10712

### CODE REVIEW

**Comment by mythrocks** [comment]
I can see how this addresses #10711 as well.  I was hoping to address the same with less code repetition.

I'm taking a crack at #10711 right now.  If there isn't a clean way to do this, I'll defer to the approach in this PR.

**Comment by razajafri** [comment]
> I can see how this addresses #10711 as well. I was hoping to address the same with less code repetition.
> 
> I'm taking a crack at #10711 right now. If there isn't a clean way to do this, I'll defer to the approach in this PR.

I thought about refactoring but considering the previous `GpuBatchScanExec` versions I thought it is probably OK to keep it this way. Let's connect offline to see if we can merge your effort with this one

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Review by mythrocks — APPROVED** [review]
Yep, LGTM.

**Pull request merged**
