### PR TITLE
Fix index-based access to the head elements

### PR DESCRIPTION
**Pull request by gerashegalov**
Signed-off-by: Gera Shegalov <gera@apache.org>

Fix simple collection operations. Contributes to #2109 
- replace map with foreach when the return value is not used
- forall where appropriate
- access head elements without specifying indices.
- simplify index iteration

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by pxLi** [comment]
build

**Review by andygrove — APPROVED** [review]
Nice cleanup. LGTM.

**Review by jlowe — APPROVED** [review]

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
ran a shim spark301db build too

**Pull request merged**
