### PR TITLE
Add config to override shims provider class (#765)

### PR DESCRIPTION
**Pull request by NvTimLiu**
* Add config to override shims provider class

Signed-off-by: Jason Lowe <jlowe@nvidia.com>

* Update docs for shims provider override config

Signed-off-by: Jason Lowe <jlowe@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by jlowe** [comment]
This shouldn't be a cherry-pick, it should be a re-merge of branch-0.2 to main.

**Comment by NvTimLiu** [comment]
Using merge instead of cherry-picking, new PR: https://github.com/NVIDIA/spark-rapids/pull/770

**Comment by NvTimLiu** [comment]
Using merge instead of cherry-picking, new PR: #770

**Pull request closed without merging**
