### PR TITLE
Add in support for FIXED_LEN_BYTE_ARRAY as binary

### PR DESCRIPTION
**Pull request by revans2**
This depends on https://github.com/rapidsai/cudf/pull/13437

This fixes https://github.com/NVIDIA/spark-rapids/issues/7449

The is to support https://issues.apache.org/jira/browse/SPARK-41096 in the plugin. It went into 3.4.0 so these changes and tests are specific to 3.4.0, although some of the back end support in this patch goes into a 3.3.0+ shim, but Spark itself tends to prevent this from happening in anything beyond 3.4.0. I did not thoroughly test this though and if we want more tests/verification that this is going to work I am happy to do that.

I wrote this because the author of https://github.com/rapidsai/cudf/pull/13437 asked me to test it, and this was the simplest way to test it.

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
The dependent PR is still in draft. I will move this to 23.10 when the dependent PR is also updated to 23.10

**Comment by revans2** [comment]
The dependency was merged into CUDF last night, but the CI failed so we might need to wait a little longer before this is ready to test.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe could you take another look?

**Review by jlowe — APPROVED** [review]

**Pull request merged**
