### PR TITLE
Fix canonicalization of GpuScalarSubquery

### LINKED ISSUE #3400: [BUG] Canonicalized GPU plans sometimes not consistent when using Spark 3.2
**Describe the bug**
The following test suites have one or more failures due to `canonicalizationMatchesCpu=true != canonicalizationMatchesGpu=false` when running against Spark 3.2.0-SNAPSHOT

- HashAggregateSuite
- ExpandExecSuite
- ScalarSuubquerySuite

**Steps/Code to reproduce bug**
Run tests with Spark 3.2

**Expected behavior**
Tests should pass

**Additional context**

The issue seems to be related to a change in how partial aggregate expressions are represented in the plan, possibly related to a change in how filter expressions are handled. When running `ExpandExecSuite` against Spark 3.0.1, we see the following functions (with normalized `exprId`).

```
functions=[
  partial_gpucount(if ((1 = none#3)) none#1 else null), 
  partial_gpucount(if ((2 = none#3)) none#2 else null), 
  partial_gpufirst(if ((0 = none#3)) none#4L else null, true),
  ...
]
```

We see the following when running against Spark 3.2.0 and the `exprId` is not getting normalized.

```
functions=[
  partial_wrappedaggfunction(gpucount(none#355), wrappedaggfunction(gpucount(none#2), (2 = none#3))),
  partial_wrappedaggfunction(gpucount(none#354), wrappedaggfunction(gpucount(none#1), (1 = none#3))),
  partial_wrappedaggfunction(gpufirst(none#359L) ignore nulls, ....
]

```

### PR DESCRIPTION
**Pull request by revans2**
This fixes #3400

I will file some follow on issues for a few other things I found while doing this.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by sameerz** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
UT failed
```
[2021-09-14T01:16:57.968Z] ScalarSubquerySuite:

[2021-09-14T01:16:58.895Z] - WITH DECIMALS: Uncorrelated Scalar Subquery *** FAILED ***

[2021-09-14T01:16:58.895Z]   canonicalizationMatchesCpu=false != canonicalizationMatchesGpu=true

[2021-09-14T01:16:58.895Z]   CPU plan: *(1) Project [none#0L, Subquery scalar-subquery#42254, [id=#115307] AS #0L]

[2021-09-14T01:16:58.895Z]   :  +- Subquery scalar-subquery#42254, [id=#115307]

[2021-09-14T01:16:58.895Z]   :     +- *(2) HashAggregate(keys=[], functions=[max(more_longs#42249L)], output=[max(more_longs)#42256L])

[2021-09-14T01:16:58.895Z]   :        +- Exchange SinglePartition, true, [id=#115303]

[2021-09-14T01:16:58.895Z]   :           +- *(1) HashAggregate(keys=[], functions=[partial_max(more_longs#42249L)], output=[max#42261L])

[2021-09-14T01:16:58.895Z]   :              +- FileScan csv [more_longs#42249L] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-2635/tests/ta..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<more_longs:bigint>

[2021-09-14T01:16:58.895Z]   +- FileScan csv [none#0L] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-2635/tests/ta..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<longs:bigint>

[2021-09-14T01:16:58.895Z]   

[2021-09-14T01:16:58.895Z]   GPU plan: GpuColumnarToRow false

[2021-09-14T01:16:58.895Z]   +- GpuProject [none#0L, Subquery Subquery, [id=#115398] AS #0L]

[2021-09-14T01:16:58.895Z]      :  +- Subquery Subquery, [id=#115398]

[2021-09-14T01:16:58.895Z]      :     +- GpuColumnarToRow false

[2021-09-14T01:16:58.895Z]      :        +- GpuHashAggregate(keys=[], functions=[gpumax(none#0L)], output=[#0L])

[2021-09-14T01:16:58.895Z]      :           +- GpuShuffleCoalesce 2147483647

[2021-09-14T01:16:58.895Z]      :              +- GpuColumnarExchange gpusinglepartitioning$(), false, [id=#115384]

[2021-09-14T01:16:58.895Z]      :                 +- GpuHashAggregate(keys=[], functions=[partial_gpumax(none#0L)], output=[none#0L])

[2021-09-14T01:16:58.895Z]      :                    +- GpuFileGpuScan csv [none#0L] Batched: true, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-2635/tests/ta..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<more_longs:bigint>

[2021-09-14T01:16:58.895Z]      +- GpuFileGpuScan csv [none#0L] Batched: true, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/home/jenkins/agent/workspace/jenkins-rapids_premerge-github-2635/tests/ta..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<longs:bigint> (SparkQueryCompareTestSuite.scala:367)
```

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
To me this feels like a test issue. Spark fixed canonicalization on ScalarSubquery for 3.2, and now we have issues where we can cannonicalize it, but the CPU cannot for older versions of Spark.  I think I will keep it how it is and update the test unless someone else disagrees.

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by revans2** [comment]
build

**Pull request merged**
