### PR TITLE
Remove -SNAPSHOT in documentation in preparation for release

### PR DESCRIPTION
**Pull request by sameerz**

### CODE REVIEW

**Review by jlowe — COMMENTED** [review]
QualificationInfoUtils.scala has a ["how to use" comment](https://github.com/NVIDIA/spark-rapids/blob/branch-21.06/rapids-4-spark-tools/src/test/scala/com/nvidia/spark/rapids/tool/profiling/QualificationInfoUtils.scala#L140-L143) that probably should be updated.

**Comment by sameerz** [comment]
build

**Review by jlowe — APPROVED** [review]
#2574 is reworking the qualification tool comment, so I think that will be covered.

**Comment by sameerz** [comment]
build

**Pull request merged**
