### PR TITLE
Fix the collect_list over window tests failures on db

### PR DESCRIPTION
**Pull request by firestarman**
Fix the failing tests `test_window_aggs_for_rows_collect_list_no_nulls `on databricks by updating the window frame specification, to avoid using the plan `RunningWindowRunctionExec ` on databricks.

Seems Databricks will NOT use the plan "`RunningWindowRunctionExec`" when
- window function is a `SizeBasedWindowFunction`, or
- window function is a `OffsetWindowFunction`, or
- window function is a `PythonUDF`, or
- window frame specification is not `SpecifiedWindowFrame(RowFrame, UnboundedPreceding, CurrentRow)`

`RunningWindowRunctionExec `does not exist outside of Databricks, and has not been supported on GPU.

The related issue https://github.com/NVIDIA/spark-rapids/issues/1680 

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
> This is a fine fix in the short term, but can you file a follow on issue for us to look into supporting `RunningWindowRunctionExec` in databricks?

Here is the issue https://github.com/NVIDIA/spark-rapids/issues/1791

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
@mythrocks could you also take a look and make sure that this is OK with you?

**Comment by firestarman** [comment]
Waiting for @mythrocks feedback.

**Review by mythrocks — APPROVED** [review]
This is fine for now. Good job, @firestarman!

**Pull request merged**
