### PR TITLE
Prepare for spark-rapids v0.3.0 release

### PR DESCRIPTION
**Pull request by NvTimLiu**
1, Merge source code from branch `branch-0.3` to `main`

2, Change version from `0.3.0-SNAPSHOT` to `0.3.0`

3, Change cuDF dependency from `0.17-SNAPSHOT` to `0.17`

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
make sure we choose the `create a merge commit` to merge this PR
image

**Review by GaryShen2008 — APPROVED** [review]

**Comment by jlowe** [comment]
Really wish I had a chance to review this.  This is a major PR that appears to have been rushed in.

I'm not a fan of merges to main as part of a release being more than just a merge to main.  The change to have 0.3 be based on cudf-0.17 instead of 0.17-SNAPSHOT should have happened on branch-0.3.   Also all of the documentation was missed as part of these updates.  There are references to 0.17-SNAPSHOT and 0.3.0-SNAPSHOT in many places.

The `main` branch should be a trivial merge from the dev branch, not with a bunch of development tacked on as well.  It makes it hard to track down where changes come from relative to a dev branch and _this did not go through premerge CI testing_.

In the future please don't develop on the `main` branch.

**Comment by revans2** [comment]
I agree with @jlowe on this all work needs to be done on the dev branch and only after that is it merged to master.  Can we fix that for the rework that is needed for the docs?  Can we update branch-0.3 so it is in sync with master, fix the docs, and then merge the result to master?

**Comment by jlowe** [comment]
I'm about to put up a PR that makes the cudf-0.17-SNAPSHOT -> cudf-0.17 changes to branch-0.3 that we can merge to main afterwards.  I can also put up another one that updates the docs to use 0.3.0 instead of 0.3.0-SNAPSHOT.

**Comment by GaryShen2008** [comment]
My mistake. Forgot to update cuDF 0.17 on dev branch first.
About the docs, I thought we would update it on main branch later, not on the dev branch.
Am I wrong?

**Comment by jlowe** [comment]
Ideally we'd like to minimize the development on `main` and have it just be a record of the releases.  I went ahead and updated cudf to 0.17 on branch-0.3 in #1387 which was merged and a followup to update the versions to 0.3 (including in docs and scripts) in branch-0.3 at #1389.  If you could take a look at #1389 and merge if it loos OK that'd be great.  When we're totally ready to cut 0.3 (i.e.: there are no more changes expected) then we can do another merge from branch-0.3 to main.  We'll probably need to regenerate the changelog as one of the last commits to branch-0.3.

There's at least one doc change in #1371 that's still targeting branch-0.3, cc: @sameerz to see if branch-0.3 should remain open until it is merged.

**Comment by pxLi** [comment]
@jlowe I am not a big fan to have only one `main` as release branch, although we have tags here. what do you think if we do not keep the main but just create new release branch each time, like release-0.3.0 for major, release-0.3.1 for minor? In this way we could have simple bug fix branch in the future based on specific release, and keep the branch history clean. 

Or we just want to make bug fix to latest release and tell people to upgrade?

**Comment by jlowe** [comment]
I'm not tied to `main`.  If we want to tag directly on the branch-* development branches that's fine with me.

This release process was setup to mirror the process performed by the RAPIDS repositories.  If we'd rather not follow that process and do something different (e.g.: use `main` as the development branch and cut release branches when updating versions/docs and tagging for a release) that's fine with me as well.

Ultimately we need the ability to separate release burndown and version updating activities from normal development activities for the next release.  There's lots of ways to do this.  We initially chose to mimic the RAPIDS process since there were people familiar with that process, and it meets the needs of separating burndown for release from future release development.

**Pull request merged**
