### PR TITLE
Correct the channel for cudf installation

### PR DESCRIPTION
**Pull request by firestarman**
This PR is to correct the conda channel to install the release version of cudf via conda.

No unit test is needed, only change the related dockerfile

### CODE REVIEW

**Review by jlowe — DISMISSED** [review]

**Comment by jlowe** [comment]
build

**Comment by firestarman** [comment]
Updated to add sign-off

**Comment by sameerz** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Pull request merged**
