### PR TITLE
Add in framework for unbounded to unbounded window agg optimization

### PR DESCRIPTION
**Pull request by revans2**
This is an initial pass at setting up the framework needed for the new unbounded to unbounded window aggregation performance and memory optimization. This is part of https://github.com/NVIDIA/spark-rapids/issues/10114

The goal of this really is to get enough framework in place that both I and @mythrocks can work on different parts together.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
So it looks like my inc ref count code is causing lots of problems because lots of places are assuming that they can close the SpillableColumnarBatch multiple times. I'll work on removing the check and then file an issue to go look into it. Probably related to the leak detection code we have talked about.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
This does a bit more than just the framework now. It has enough code to do the split and some unit tests for that too.  @mythrocks please take a look when you have time.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Review by mythrocks — APPROVED** [review]
This looks good to me.  I've been working with this code for a few weeks now.

**Pull request merged**
