### PR TITLE
Enable Databricks 13.3 in pre-merge CI [databricks]

### PR DESCRIPTION
**Pull request by NvTimLiu**
As the title

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
@razajafri  Got below error while building Databricks 13.3 shim, looks like we need to add/update 341db shim source to make sure `rapids-4-spark-db-bom`  get built before mvn compiling `rapids-4-spark-shim-deps-parent_2.12`?
```
 [INFO] RAPIDS Accelerator for Apache Spark Root Project ... SUCCESS [  3.422 s]
 [INFO] rapids-4-spark-jdk-profiles_2.12 ................... SUCCESS [  0.457 s]
 [INFO] rapids-4-spark-shim-deps-parent_2.12 ............... FAILURE [  0.011 s]
 [INFO] rapids-4-spark-sql-plugin-api_2.12 ................. SKIPPED
 [INFO] RAPIDS Accelerator for Apache Spark SQL Plugin ..... SKIPPED
 [INFO] RAPIDS Accelerator for Apache Spark Shuffle Plugin . SKIPPED
 [INFO] RAPIDS Accelerator for Apache Spark Scala UDF Plugin SKIPPED
 [INFO] RAPIDS Accelerator for Apache Spark Delta Lake Stub  SKIPPED
 [INFO] RAPIDS Accelerator for Apache Spark Aggregator ..... SKIPPED
 [INFO] Data Generator ..................................... SKIPPED
 [INFO] RAPIDS Accelerator for Apache Spark Distribution ... SKIPPED
 [INFO] rapids-4-spark-integration-tests_2.12 .............. SKIPPED
 [INFO] RAPIDS Accelerator for Apache Spark Tests .......... SKIPPED
 [INFO] rapids-4-spark-api-validation_2.12 ................. SKIPPED
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time:  4.097 s
 [INFO] Finished at: 2023-11-09T05:48:19Z
 [INFO] ------------------------------------------------------------------------
 [ERROR] Failed to execute goal on project rapids-4-spark-shim-deps-parent_2.12: Could not resolve dependencies for project com.nvidia:rapids-4-spark-shim-deps-parent_2.12:pom:23.12.0-SNAPSHOT: Failure to find com.nvidia:rapids-4-spark-db-bom:pom:23.12.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced -> [Help 1]
```

**Comment by razajafri** [comment]
@NvTimLiu the problem here is that the pom changes are not in yet. If this change is all we need we can make this change a part of the pom changes.

**Comment by NvTimLiu** [comment]
> @NvTimLiu the problem here is that the pom changes are not in yet. If this change is all we need we can make this change a part of the pom changes.

Yes, this is all to enable pre-merge CI, please help to add it as a part of the pom update, thanks!

**Comment by jlowe** [comment]
Superceded by #9677

**Pull request closed without merging**
