### PR TITLE
Add jars to get access to s3 storage in Dockerfile [skip ci]

### PR DESCRIPTION
**Pull request by wjxiz1992**
Signed-off-by: Allen Xu <allxu@nvidia.com>
This PR adds in s3 storage accessibility for k8s containers created by our Dockerfile.
This PR is verified in EKS cluster with a GPU enabled simple query.

### CODE REVIEW

**Comment by tgravescs** [comment]
@wjxiz1992 ping on question above?

**Comment by tgravescs** [comment]
build

**Comment by wjxiz1992** [comment]
@tgravescs No we don't have one, according to @GaryShen2008 , we now focus on https://github.com/NVIDIA/spark-rapids-container/pull/18 and plan to replace this dockerfile and related doc by referring to the new repo. So I think we will build some new CI based on the new PR above.

**Comment by wjxiz1992** [comment]
close, waiting for https://github.com/NVIDIA/spark-rapids-container/pull/18.

**Pull request closed without merging**
