### PR TITLE
Update latest changelog [skip ci]

### PR DESCRIPTION
**Pull request by nvauto**
Update change log with CLI: 

   scripts/generate-changelog --token=<GIT_TOKEN> --releases=24.08,24.10

### CODE REVIEW

**Comment by NvTimLiu** [comment]
Mark the change as drafted

This change is for in advance review,

I'll up merge the following changes if needed.

**Comment by NvTimLiu** [comment]
NOTE: Merged Pull Requests w/o Project:

    branch-24.10 #11569 Have "dump always" dump input files before trying to decode them https://github.com/NVIDIA/spark-rapids/pull/11569

**Comment by sameerz** [comment]
> @sameerz Can you help review? thanks!
> 
> NOTE: Merged Pull Requests w/o Project:
> 
> branch-24.10 #11569 Have "dump always" dump input files before trying to decode them #11569

Updated some labels and fixed merge request without project.  Am good to sign off once regenerated.

**Comment by NvTimLiu** [comment]
> > @sameerz Can you help review? thanks!
> > NOTE: Merged Pull Requests w/o Project:
> > branch-24.10 #11569 Have "dump always" dump input files before trying to decode them #11569
> 
> Updated some labels and fixed merge request without project. Am good to sign off once regenerated.

Updated, thanks!

**Review by pxLi — DISMISSED** [review]

**Comment by pxLi** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
