### PR TITLE
Add support for ORC forced positional evolution

### PR DESCRIPTION
**Pull request by nartal1**
This fixes https://github.com/NVIDIA/spark-rapids/issues/1922

This is to keep OrcUtils in sync with Spark's code. In the Spark PR https://github.com/apache/spark/pull/29737/ they have added a check for 'orc.force.positional.evolution` for matching top level column by position. 
Updated the code so that when this config is set, we read the columns based on positions and not the column names.
Added test to verify the behavior.

### CODE REVIEW

**Comment by razajafri** [comment]
Adding a test is always a good idea, even if it's a simple one just to do a sanity check

**Comment by jlowe** [comment]
This looks good, but agree it would be nice to have a test to show this works.  The original Spark PR could be a reference of how to approach testing this.

**Comment by nartal1** [comment]
build

**Comment by nartal1** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by razajafri — APPROVED** [review]

**Pull request merged**
