### PR TITLE
Init changelog for 23.04 [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
command used to generate,
```
GITHUB_TOKEN=<PAT> scripts/generate-changelog --releases=23.02,23.04
```

initiate the changelog for review in advance. 
We will put another PR to do final update for 23.04 changelog before RC build.

### CODE REVIEW

**Comment by pxLi** [comment]
Below PRs have no correct roadmap setup,
```
NOTE: Merged Pull Requests w/o Project:
branch-23.04 #7222 Automatic conversion to shimplified directory structure  [databricks] https://github.com/NVIDIA/spark-rapids/pull/7222
branch-23.04 #7572 Enables spillable/unspillable state for RapidsBuffer and allow buffer sharing https://github.com/NVIDIA/spark-rapids/pull/7572
branch-23.04 #7621 Document GNU sed for macOS auto-copyrighter users [skip ci] https://github.com/NVIDIA/spark-rapids/pull/7621
branch-23.04 #7728 Fix estimatedNumBatches in case of OOM for Full Outer Join https://github.com/NVIDIA/spark-rapids/pull/7728
branch-23.04 #7734 Temporarily skip the test_parquet_read_ignore_missing on Databricks https://github.com/NVIDIA/spark-rapids/pull/7734
branch-23.04 #7787 Document a workaround to RuntimeException 'boom' [skip ci] https://github.com/NVIDIA/spark-rapids/pull/7787
branch-23.04 #7789 Update script for integration tests on Databricks [databricks] https://github.com/NVIDIA/spark-rapids/pull/7789
branch-23.04 #7839 Add reduced pom to dist jar in the packaging phase [databricks] https://github.com/NVIDIA/spark-rapids/pull/7839
branch-23.04 #7854 Optimize `regexp_extract*` by transpiling capture groups to non-capturing groups so that only the required capturing group is manifested https://github.com/NVIDIA/spark-rapids/pull/7854
branch-23.04 #8007 Fix leak where RapidsShuffleIterator for a completed task was kept alive https://github.com/NVIDIA/spark-rapids/pull/8007
branch-23.04 #8040 Fix device vector leak in RmmRetryIterator.splitSpillableInHalfByRows https://github.com/NVIDIA/spark-rapids/pull/8040
branch-23.04 #8070 Fixes closed RapidsShuffleHandleImpl leak in ShuffleBufferCatalog https://github.com/NVIDIA/spark-rapids/pull/8070
branch-23.04 #8071 Fix error in deploy script [skip ci] https://github.com/NVIDIA/spark-rapids/pull/8071
branch-23.04 #8076 Add in docs about RetryOOM [skip ci] https://github.com/NVIDIA/spark-rapids/pull/8076
branch-23.04 #8087 Add an FAQ entry on encryption support [skip ci] https://github.com/NVIDIA/spark-rapids/pull/8087
```

@sameerz @GaryShen2008 please help review the change, and adjust update to issues and PRs, I will re-generate later thanks!

**Comment by sameerz** [comment]
Added roadmap to PRs and updated labels on issues.  

cc: @mattahrens

**Review by sameerz — APPROVED** [review]

**Comment by pxLi** [comment]
I will do a final update before RC build tomorrow, thx

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
