### PR TITLE
Support WindowExec partitioning by Decimal 128 on the GPU

### LINKED ISSUE #4712: [FEA] Allow <WindowExec> to partition on Decimal 128 when running on the GPU
**Is your feature request related to a problem? Please describe.**
Currently, the Spark Rapids plugin limits the types supported for WindowExec calls to common types and Decimal 64. I wish the plugin will support Decimal 128 in the partition spec for Window operations.  This relates to the issue #4626 which was closed when `StructType` support was enabled in #4673. 

**Describe the solution you'd like**
GPU support should be enabled and corresponding test should be added to test for proper support of this feature.

**Additional context**
`libcudf` `grouped_rolling_window()` was tested for `__decimal128` support earlier, so this should work in the plugin now.

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #4712.

This updates the WindowExec type check to allow Decimal 128 as a valid type in the partitionSpec. Also, integration tests for window functions have been updated to support higher precision decimals to test Decimal 128 support.

Signed-off-by: Navin Kumar <navink@nvidia.com>

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by NVnavkumar** [comment]
build

**Review by mythrocks — DISMISSED** [review]

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by jlowe — COMMENTED** [review]
I expected `window_function_test.py` to be updated as part of this to add coverage of the new functionality.  Is that not needed?

**Review by jlowe — APPROVED** [review]
Haha, nevermind, I read right over the window_function_test.py change. 🤦

**Pull request merged**
