### PR TITLE
Support Read/Write ORC on Decimal128

### LINKED ISSUE #3882: [FEA] Decimal 128 Support: Read/Write ORC
The CUDF PR to support decimal 128 is still missing support for ORC reads/writes. This should hopefully show up soon and then we can implement this.

### PR DESCRIPTION
**Pull request by sperlingxx**
Signed-off-by: sperlingxx <lovedreamf@gmail.com>

Closes #3882

### CODE REVIEW

**Review by jlowe — APPROVED** [review]
We will want to revisit this with a followup if libcudf gives us some form of control over decimal loading behavior (e.g.: it's wasteful to load all decimal columns as decimal128 if nothing in the file schema needs 128-bit precision).  Ideally we would be able to specify this on a per-column behavior or even at a global setting, but this is a good first start.

**Comment by revans2** [comment]
@sperlingxx what does this depend on from CUDF? I am getting lots of test failures.

```
21/11/08 18:06:51 ERROR Executor: Exception in task 6.0 in stage 2.0 (TID 30)
ai.rapids.cudf.CudfException: cuDF failure at: /home/roberte/src/decimal_128_cudf/cpp/src/io/orc/reader_impl.cu:959: Precision of column _c14 is over 18, use 128-bit Decimal.
	at ai.rapids.cudf.Table.readORC(Native Method)
	at ai.rapids.cudf.Table.readORC(Table.java:945)
```

I am inclined to revert this until it can be fixed.

**Comment by sperlingxx** [comment]
> @sperlingxx what does this depend on from CUDF? I am getting lots of test failures.
> 
> ```
> 21/11/08 18:06:51 ERROR Executor: Exception in task 6.0 in stage 2.0 (TID 30)
> ai.rapids.cudf.CudfException: cuDF failure at: /home/roberte/src/decimal_128_cudf/cpp/src/io/orc/reader_impl.cu:959: Precision of column _c14 is over 18, use 128-bit Decimal.
> 	at ai.rapids.cudf.Table.readORC(Native Method)
> 	at ai.rapids.cudf.Table.readORC(Table.java:945)
> ```
> 
> I am inclined to revert this until it can be fixed.

It seems to me that the cuDF side is ready. I ran the tests in `orc_test.py` and `orc_write_test.py` locally. All tests passed.

**Comment by revans2** [comment]
@sperlingxx Sorry I should have been more clear. The CUDF patch is ready, but this patch is not. I don't know if the two got out of sync with each other or what.

If you look at the ORC read API, there is a new API

https://github.com/rapidsai/cudf/blob/89004c7e276c95f5d71b70fd66e689a94b22814f/cpp/include/cudf/io/orc.hpp#L228-L233

That we will need to call from java/JNI for us to get back decimal 128 columns.

https://github.com/rapidsai/cudf/pull/9483 is the base patch for C++ decimal128 support.
https://github.com/rapidsai/cudf/pull/9485 is the patch that we have been using as the java branch to build and test off of. It is based off of the previous PR, but adds java JNI support for the same. This does not call `set_decimal128_columns` at all. I am happy to update it in some way to make it work, but it is not doing the right thing right now. If you want to put up a PR to my branch so I can include your work in my PR that would be great.  If you want me to take over this work and figure out how to make it work that is great too.

One of the things you need to be careful with is the names of the columns for nested types. I am not 100% sure how that works. I spoke with @vuule about it and he said that it matches the `set_decimal_cols_as_float` API, but we don't use that either so we might need to play around with it a bit to totally understand what is happening.

**Comment by sperlingxx** [comment]
> @sperlingxx Sorry I should have been more clear. The CUDF patch is ready, but this patch is not. I don't know if the two got out of sync with each other or what.
> 
> If you look at the ORC read API, there is a new API
> 
> https://github.com/rapidsai/cudf/blob/89004c7e276c95f5d71b70fd66e689a94b22814f/cpp/include/cudf/io/orc.hpp#L228-L233
> 
> That we will need to call from java/JNI for us to get back decimal 128 columns.
> 
> [rapidsai/cudf#9483](https://github.com/rapidsai/cudf/pull/9483) is the base patch for C++ decimal128 support. [rapidsai/cudf#9485](https://github.com/rapidsai/cudf/pull/9485) is the patch that we have been using as the java branch to build and test off of. It is based off of the previous PR, but adds java JNI support for the same. This does not call `set_decimal128_columns` at all. I am happy to update it in some way to make it work, but it is not doing the right thing right now. If you want to put up a PR to my branch so I can include your work in my PR that would be great. If you want me to take over this work and figure out how to make it work that is great too.
> 
> One of the things you need to be careful with is the names of the columns for nested types. I am not 100% sure how that works. I spoke with @vuule about it and he said that it matches the `set_decimal_cols_as_float` API, but we don't use that either so we might need to play around with it a bit to totally understand what is happening.

Hi @revans2, I was not aware that libcudf enabled the reading selected columns  as decimal 128. And I am working on the cuDF Java adaption for this feature. I successfully ran a unit test about ORC I/O on selected decimal 128 usage:
```java
  void testORCReadAndWriteForDecimal() throws IOException {
    File tempFile = File.createTempFile("test", ".orc");
    try (Table t = getExpectedFileTable(true, true, true);
         Table decTable = new Table(t.getColumn(7), t.getColumn(8), t.getColumn(10),
             t.getColumn(13), t.getColumn(14))) {
      ORCWriterOptions options = ORCWriterOptions.builder()
          .withNullableColumns("dec64", "dec128")
          .withStructColumn(ColumnWriterOptions.structBuilder("dec128_struct")
              .withNullableColumns( "c0").build())
          .withListColumn(ColumnWriterOptions.listBuilder("dec64_list", false)
              .withNullableColumns("c0").build())
          .withListColumn(ColumnWriterOptions.listBuilder("dec128_list", true)
              .withNullableColumns("c0").build())
          .build();
      decTable.writeORC(options, tempFile.getAbsoluteFile());
      ORCOptions opts = ORCOptions.builder()
          .includeColumn("dec64", "dec128", "dec128_struct", "dec64_list", "dec128_list")
          .decimal128Column("dec128", "dec128_struct.c0", "dec128_list.1")
          .build();
      try (Table decTableOut = Table.readORC(opts, tempFile.getAbsoluteFile())) {
        assertTablesAreEqual(decTable, decTableOut);
      }
    } finally {
      tempFile.delete();
    }
  }

```
For struct columns, libcudf accepts the name formatted in  `[struct_column_name].[child_column_name]`.
For list columns, `[list_column_name].1` refers to the data column of the list.
Certainly, above rules can be used in combination, such as: `list.1.child0` .

**Pull request merged**
