### PR TITLE
Update JNI and private version to released 23.08.0 [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
bump up JNI and private versions to 23.08.0

**NOTE:** I will trigger CI after JNI and private artifacts are available at maven central

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
please ignore failed spark333test (release private do not include snapshot shims)
`mvn[compile,RAT,scalastyle,docgen] / package-tests (333, true) (pull_request) `

**Review by GaryShen2008 — APPROVED** [review]

**Review by NvTimLiu — APPROVED** [review]

**Review by YanxuanLiu — APPROVED** [review]

**Comment by revans2** [comment]
We had test failures for this. Why is it that we didn't disable the 333 pre-commit?  Any PR after this for 3.8 is also not going to pass.

**Comment by pxLi** [comment]
> We had test failures for this. Why is it that we didn't disable the 333 pre-commit? Any PR after this for 3.8 is also not going to pass.

This should be the last change for pre-release, if any followups people could just ignore the optional snapshot shim test.

And yes, we could add some specific control to make sure we skip the snapshot shims in github actions.
Currently due to our auto-merge strategy, we will always update in multiple places to make sure that the change would not also fail/forget required shims the current dev branches.

If needed, we can consider adding some global VAR to control instead of oral notification or code changes in multiple branches

**Pull request merged**
