### PR TITLE
Add Hao to blossom-ci whitelist

### PR DESCRIPTION
**Pull request by viadea**
Add Hao to blossom-ci whitelist

### CODE REVIEW

**Review by tgravescs — DISMISSED** [review]

**Review by jlowe — DISMISSED** [review]

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
looks like another conflict, please resolve

**Comment by tgravescs** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by gerashegalov** [comment]
should have been a `[skip ci]` PR title to save resources

**Pull request merged**
