### PR TITLE
Throw exception on parse error in ANSI mode when casting String to Date

### PR DESCRIPTION
**Pull request by firestarman**
This fixes https://github.com/NVIDIA/spark-rapids/issues/1941.

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
Trigger the premerge to make sure at least it will not break anthing before Spark 3.2.0.

**Review by revans2 — APPROVED** [review]
Looks good to me. I would like to see @andygrove review it too, just because he has done a lot more with string to date/timestamp casting

**Comment by firestarman** [comment]
> Looks good to me. I would like to see @andygrove review it too, just because he has done a lot more with string to date/timestamp casting

Sure, will wait for @andygrove's comments.

**Review by andygrove — APPROVED** [review]
LGTM

**Pull request merged**
