### PR TITLE
Add NVTX ranges to identify Spark stages and tasks

### PR DESCRIPTION
**Pull request by jlowe**
When capturing profiles, it is sometimes difficult to map activity in the profile trace to the query.  This adds an NVTX range that spans the lifetime of a Spark task, and the text of the range identifies the Spark stage ID and task ID.  These can be used to locate the corresponding stage and task within the Spark UI, and from there we can navigate to the Spark job for that stage and the Spark query for that job.

### CODE REVIEW

**Comment by jlowe** [comment]
Keeping this in draft until I can run some at-scale performance tests to verify there are no regressions.

**Comment by jlowe** [comment]
build

**Review by abellina — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Comment by jlowe** [comment]
Ran performance tests, did not see any statistically significant regressions.

**Pull request merged**
