### PR TITLE
Add rapids configs to enable GPU running in Spark UT

### PR DESCRIPTION
**Pull request by GaryShen2008**
Exclude 2 new failed cases

Close https://github.com/NVIDIA/spark-rapids/issues/10962

### CODE REVIEW

**Comment by GaryShen2008** [comment]
build

**Comment by sameerz** [comment]
Do we want to enable all the configs all at once?  Can these be enabled on a per test basis?

**Comment by GaryShen2008** [comment]
> Do we want to enable all the configs all at once? Can these be enabled on a per test basis?
It'll require us to figure out what fallback happens in each Suite separately.
I wonder if we need to do that.
If the test case doesn't include a fallback because of a config, I think it won't have impact on the test case with the redundant configs. 
Do you think the configs have any conflict or will have some side-effect?

**Comment by sameerz** [comment]
I am thinking there might be unintended side effects if all the features are enabled, but agree that the likelihood of that is small.  Would these changes impact all test cases, or just the Spark UT test cases?

**Comment by GaryShen2008** [comment]
> I am thinking there might be unintended side effects if all the features are enabled, but agree that the likelihood of that is small. Would these changes impact all test cases, or just the Spark UT test cases?

This change only impacts the Spark UT.

**Review by binmahone — APPROVED** [review]

**Pull request merged**
