### PR TITLE
Fix test_map_scalars_supported_key_types

### PR DESCRIPTION
**Pull request by abellina**
Closes https://github.com/NVIDIA/spark-rapids/issues/8922

This changes and re-enables `test_map_scalars_supported_key_types`. The prior test was not deterministic, because of it's reliance on `first` and producing several null rows. This change makes it so we have a single row that we are going to scalar-subquery into a `GetMapValue`. I used the `row_number` function over the whole table to generate an index that I can then randomly picked (the random number is printed as part of the test). That means we are getting a random scalar map for each of the data gens. 

The test will pick the same single key we have put into the map, ~~and the key "null" which seems to be easily handled by all data types according to my testing. I was trying to find keys that matched and keys that didn't.~~ (removed this part since map[null] is being optimized out by Spark). Instead I am creating a second scalar map using the next row, and asking for a key I know does not exist.

I am targeting this in 23.08 since it is a test-only change, and it was a follow on task for GetMapValue changes in 23.08.

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
Because of parallel tests I am running into the issue that the test names change, since I added a random variable in the name. I am going to have to seed the random generator with the same seed.

**Comment by abellina** [comment]
I pushed https://github.com/NVIDIA/spark-rapids/pull/8971/commits/e2ba52d36a08258e0f83a66b7c25c1081805eb65 to deal with the test name issue, doing the same trick I did with the OOM injection random. I did rename `SPARK_RAPIDS_TEST_INJECT_OOM_SEED` to `SPARK_RAPIDS_TEST_RANDOM_SEED`, even though not all tests are using this seed. We do different things in different places.

**Comment by abellina** [comment]
build

**Review by jlowe — DISMISSED** [review]

**Review by revans2 — COMMENTED** [review]
The changes look fine, but I want us to be careful with how much randomness we add into the test suite. It is just too much of human nature to rerun something that failed without looking into why it failed and if it passes the second time just check it in.  I would prefer to explore other ways to get the coverage we need. But I also don't want pre commit builds that take a day to run, so...

**Comment by abellina** [comment]
I'll take a closer look at the other map tests before hitting the button, I'll ping folks with any changes if needed.

**Comment by abellina** [comment]
Filed these as follow on:
- (test bug) Add missing BinaryType key tests in map_test.py: https://github.com/NVIDIA/spark-rapids/issues/8985
- (actual bug) Check that keys are not null when creating a map: https://github.com/NVIDIA/spark-rapids/issues/8984

**Review by revans2 — DISMISSED** [review]

**Comment by abellina** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Pull request merged**
