### PR TITLE
Update default speedup factors for qualification tool

### LINKED ISSUE #5831: [FEA] Update default speedup factors used for qualification tool
**Is your feature request related to a problem? Please describe.**
Existing speedup factor defaults for execs and expressions are conservative relative to observed speedups in different performance tests.

**Describe the solution you'd like**
Update speedup factor defaults to be in line with performance tests.

### PR DESCRIPTION
**Pull request by mattahrens**
Signed-off-by: mattahrens <matthewahrens@gmail.com>

Fixes #5831 

Updating exec default speedup factor to 3 and expression default speedup factor (not yet used) to 4.  Also updated Sort and SortMergeJoin based on recent performance tests.

### CODE REVIEW

**Comment by mattahrens** [comment]
build

**Review by nartal1 — DISMISSED** [review]
LGTM

**Review by tgravescs — DISMISSED** [review]
we will need to update the documentation example and the integration test results.  Perhaps we should file a separate issue for documentation since we will be adding expressions and other things anyway.

**Comment by amahussein** [comment]
This will conflict with pending #5810 
If @mattahrens going to be away, I do not mind merging this PR first, then I can revisit #5810

**Comment by mattahrens** [comment]
issue filed for 22.08 doc updates for qualification tool: https://github.com/NVIDIA/spark-rapids/issues/5843

**Comment by mattahrens** [comment]
build

**Review by nartal1 — APPROVED** [review]

**Pull request merged**
