### PR TITLE
Qualification tool: Add support for join, pandas, aggregate execs

### PR DESCRIPTION
**Pull request by nartal1**
This fixes https://github.com/NVIDIA/spark-rapids/issues/5362.

This PR adds support for these execs:
HashAggregateExec
 ObjectHashAggregateExec
 SortAggregateExec
 BroadcastHashJoinExec
 BroadcastNestedLoopJoinExec
 ShuffledHashJoinExec
 SortMergeJoinExec
 WindowExec
 AggregateInPandasExec
 ArrowEvalPythonExec
 FlatMapGroupsInPandasExec
 MapInPandasExec
 WindowInPandasExec

Using static eventlog for testing pandas related execs as creating eventlog on the fly isn't easy. Have generated one eventlog which includes all the pandas related execs. Rest of the execs create eventlog while running the tests.

### CODE REVIEW

**Comment by nartal1** [comment]
build

**Review by tgravescs — COMMENTED** [review]
for the pandas event log, its fairly big, does it need to be that large?  I assume you couldn't dynamically create that?

**Comment by nartal1** [comment]
> for the pandas event log, its fairly big, does it need to be that large? I assume you couldn't dynamically create that?

Running 1 query related to pandas generated eventlog(compressed) which was about 21K. I have included 5 different queries to generate different execs which we support(so it's about 132K). I couldn't figure out a way to easily generate the eventlog(to include pandas and other pyspark related API's in the test itself.

**Comment by tgravescs** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
