### PR TITLE
Remove InMemoryTableScanExec support for Spark 3.5+ [databricks]

### PR DESCRIPTION
**Pull request by razajafri**
This PR removes support for InMemoryTableScanExec from Spark-3.5+. 

**Changes**
* Disabled GpuInMemoryTableScanExec support by default for Spark 3.5+

**Tests**
* Ran cache_tests

contributes towards #8678

### CODE REVIEW

**Comment by revans2** [comment]
Instead of removing it, and we just have it be off by default in 3.5.x, until we get a fix into Spark? That lets us and customers experiment with it. It also makes it so that we can run tests on it and see if they are mostly working or not.

**Comment by razajafri** [comment]
The only thing I don't like about this implementation is that the GPU plan will show 
```
! <InMemoryTableScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.columnar.InMemoryTableScanExec
``` 
which is the default message we print when an Exec isn't supported. 

If others also think this should be improved then I can add an override in the shim which always returns with an error message with more info about why we aren't supporting it by calling the `willNotWorkOnGpu` method

**Comment by revans2** [comment]
if you use disabledByDefault it lets you put in a comment about why it is disabled.

**Comment by razajafri** [comment]
I like this approach better as it has less code churn. We may have to resort to adding shims after we reenable it. 
@revans2 thanks for the suggestion. PTAL

**Comment by razajafri** [comment]
I am using an unconventional way in this PR to avoid code duplication, I hope it's OK

**Review by revans2 — COMMENTED** [review]
I was not concerned with the shim code duplication. There are other things we can do to work around that. I was more concerned with the impact that there would be to tests and also our ability to try and work on getting this to work properly on 3.5.0.

Have you run the cache integration tests on 3.5.0? I have to assume that they are going to fail, unless we explicitly enable/disable the InMemoryTableScanExec replacement.

**Comment by razajafri** [comment]
> I was not concerned with the shim code duplication. There are other things we can do to work around that. I was more concerned with the impact that there would be to tests and also our ability to try and work on getting this to work properly on 3.5.0.
> 
> Have you run the cache integration tests on 3.5.0? I have to assume that they are going to fail, unless we explicitly enable/disable the InMemoryTableScanExec replacement.

Yes, I did run them on 311 and 350 and they all passed. 
I don't remember if this was deliberate but we are never looking for InMemoryTableScanExec to be on the GPU, possibly because the cache_test.py can be run without PCBS in which case the said Exec will not be on the GPU. We can see that on this line https://github.com/NVIDIA/spark-rapids/blob/a56da0c37a00dd78a1457bd532e791b1eb5bf413/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuTransitionOverrides.scala#L635 that it will not check for the plan on GPU and move on.

**Review by revans2 — APPROVED** [review]

**Comment by razajafri** [comment]
build

**Pull request merged**
