### PR TITLE
Update the version to 0.3.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by firestarman**
As titled
No unit test is needed.

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by revans2** [comment]
None of the jenkins files nor the docs have been updated to point to 0.3.0-SNAPSHOT.  In general you probably want to grep for all of the files that have the old version number in them and then look to see if they should be modified or not.  I make the same mistake all of the time.  I think this is why the pre-merge build failed.

**Comment by tgravescs** [comment]
was this changed with the maven set version command?

**Comment by tgravescs** [comment]
Ok, I'm going to merge this and then fix up some of the jenkins files. I'll create the 0.3 databricks build as well.

**Comment by firestarman** [comment]
This was done by command `sed -i "s/0\.2\.0-SNAPSHOT/0\.3\.0-SNAPSHOT/g" `find -name pom.xml``

**Pull request merged**
