### PR TITLE
Use Databricks instance Spark version as default

### LINKED ISSUE #7096: [FEA] Databricks build and test scripts should compute BASE_SPARK_VERSION
**Is your feature request related to a problem? Please describe.**
In order to use the scripts under jenkins/databricks, one must first remember to set BASE_SPARK_VERSION (and of course know what proper value to use when setting it).  This is easy to forget and requires developers to know what values correspond to the various Databricks versions.

**Describe the solution you'd like**
We're already automatically detecting which Databricks version we're on in our shim provider by examining the value of `spark.databricks.clusterUsageTags.sparkVersion` in /databricks/common/conf/deploy.conf. The Databricks build and test scripts could do the same.  We can then maintain the mapping of Databricks version to proper Spark base version in the scripts directly rather than requiring a developer to maintain the lookup table in their head.

### PR DESCRIPTION
**Pull request by gerashegalov**
Instead of hardcoding 3.1.2, read the version ingrained in the instance image

Contributes to #6979
Fixes #7096 

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by amahussein** [comment]
Related issue https://github.com/NVIDIA/spark-rapids/issues/6979

**Comment by gerashegalov** [comment]
build

**Review by zhanga5 — APPROVED** [review]
👍

**Comment by gerashegalov** [comment]
build

**Pull request merged**
