### PR TITLE
Fix ORC reading over different schemas

### LINKED ISSUE #5562: [BUG] read ORC file with various file schemas
**Describe the bug**
When I tried to remove the restriction of mergeSchema on ORC reading, GPU ORC reader returned me some weird outputs. With some investigation, I found that the problem occured when we read ORC file with various schemas. Interestingly, the problem occurs occasionally. And it occurs under all 3 read patterns.

**Steps/Code to reproduce bug**
```python
def test_merge_schema_read_1(spark_tmp_path):
    first_data_path = spark_tmp_path + '/ORC_DATA/key=0'
    with_cpu_session(
            lambda spark : gen_df(spark, [('a', int_gen)], length=50).write.orc(first_data_path))
    second_data_path = spark_tmp_path + '/ORC_DATA/key=1'
    with_cpu_session(
            lambda spark : gen_df(spark, [('b', int_gen), ('a', int_gen)], length=50).write.orc(second_data_path))
    data_path = spark_tmp_path + '/ORC_DATA'
    assert_gpu_and_cpu_are_equal_collect(
            lambda spark : spark.read.orc(data_path),
            conf={'spark.rapids.sql.format.orc.reader.type': 'PERFILE',
                  'spark.sql.sources.useV1SourceList': ''})
```

### PR DESCRIPTION
**Pull request by sperlingxx**
Fixes #5562

This PR is to fix the bug which fails reading ORC data from multiple file schemas. The root cause of the bug is multi-thread modification on a thread unsafe variable (broadcasted Hadoop Conf).

Signed-off-by: sperlingxx <lovedreamf@gmail.com>

### CODE REVIEW

**Comment by sperlingxx** [comment]
build

**Review by jlowe — COMMENTED** [review]
I find it interesting that this PR claims it fixes #5562 but does not use the same repro test from that issue as part of its test case.  The test in #5562 seems subtly different than the one used here, as the order of columns in the dataframe is intentionally different, whereas here the test preserves the same order and the extra one is on the end.  Have we verified the same test from #5562 now passes with this change?

**Comment by sperlingxx** [comment]
> I find it interesting that this PR claims it fixes #5562 but does not use the same repro test from that issue as part of its test case. The test in #5562 seems subtly different than the one used here, as the order of columns in the dataframe is intentionally different, whereas here the test preserves the same order and the extra one is on the end. Have we verified the same test from #5562 now passes with this change?

Yes, the case in #5562 can be addressed by this PR.  I decided to use current case rather than the original case, because it looks stronger and more representative. In terms of the column order, I shuffled the order of columns to include the factor into the case.

**Comment by sperlingxx** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
