### PR TITLE
Revert "Support split non-AST-able join condition for BroadcastNested… [databricks]

### PR DESCRIPTION
**Pull request by winningsix**
…LoopJoin (#9635)"

This reverts commit c20a843ed6003ef6138c99ae73a77b647ade4f80. which breaks databricks branch.

### CODE REVIEW

**Comment by winningsix** [comment]
build

**Comment by winningsix** [comment]
build

**Comment by winningsix** [comment]
cc @pxLi

**Review by pxLi — APPROVED** [review]
+1. Lets wait for the pre-merge CI

**Comment by winningsix** [comment]
I got a hot fix https://github.com/NVIDIA/spark-rapids/pull/9696. Let's wait for it before reverting this.

**Pull request merged**
