### PR TITLE
[DOC]update doc for emr6.6[skip ci]

### PR DESCRIPTION
**Pull request by nvliyuan**
update getting started doc for aws emr 6.6.0 release
https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-660-release.html#emr-660-relnotes

### CODE REVIEW

**Comment by nvliyuan** [comment]
image
image
image

**Comment by viadea** [comment]
@nvliyuan The new picture's dimension is much bigger than the original one:  W: 1220px | H: 846px . Is there any reason for that? I would suggest you keep the same dimension

**Comment by nvliyuan** [comment]
> @nvliyuan can you also mask the public DNS in section "Finish Cluster Configuration"? thx

updated

**Review by viadea — APPROVED** [review]

**Review by sameerz — APPROVED** [review]

**Comment by sameerz** [comment]
build

**Pull request merged**
