### PR TITLE
Centralize source-related properties in parent pom for consistent usage in submodules

### PR DESCRIPTION
**Pull request by gerashegalov**
Contributes to #7487. Use a consistent scheme of properties for sql-plugin and tests modules for easier automation.  

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Comment by gerashegalov** [comment]
databricks premerge build worked module the currently expected failure #7595 . Rerunning `build` without 3XYdb shims.

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Pull request merged**
