### PR TITLE
Update Spark2 Explain API code for 22.08

### PR DESCRIPTION
**Pull request by tgravescs**
contributes to https://github.com/NVIDIA/spark-rapids/issues/6081
Note i'm not saying fixes since we are still checking things in we should do this check again when we actually code freeze.

Tested manually using the NDS 1 queries and diffing the output. Ran against a couple of different 2.4.x versions.  Also ran a few various queries by hand.

This is used for allowing user on spark2 to get explain output to determine if query is good fit for gpu.. Just for reference, instructions on using this API are: https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-workload-qualification.html#2-get-the-explain-output

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by revans2 — APPROVED** [review]
I really find it hard to review diffs of diffs, but I think it looks okay.

**Review by jlowe — APPROVED** [review]

**Pull request merged**
