### PR TITLE
Change signoff check image to slim-buster [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

fix signoff check

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
Going to force merge this to unblock signoff check

**Comment by tgravescs** [comment]
Please add description as to why we changed it

**Comment by pxLi** [comment]
> Please add description as to why we changed it

updated PR desc

**Pull request merged**
