### PR TITLE
Change to build tools module with all the versions by default

### PR DESCRIPTION
**Pull request by tgravescs**
Build the tools module all the time when building single version to make sure something doesn't get broken. Previously it only build with the Spark 3.1.1 version.  Updated the build scripts to skip building it with the nightly when we build all the versions.  

The buildlall script actually already skips it for most of the versions because it uses the  -pl aggregator. The tools module gets built on the final mvn package command at the end.

I tested the nightly script with a test jenkins build and it only built tools jar once and it pushed it successfully.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Comment by tgravescs** [comment]
tests failed, unrelated, looks like no space on device:

12:09:39  - Exchange reuse *** FAILED ***
12:09:39    org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 92.0 failed 1 times, most recent failure: Lost task 0.0 in stage 92.0 (TID 994) (premerge-ci-1-jenkins-rapids-premerge-github-3378-fmr0v-k9jd3 executor driver): java.io.IOException: No space left on device

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Pull request merged**
