### PR TITLE
Update changelog 21.12 to latest [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
bound some PRs to project 21.12, can you help update the changelog to latest?

**Comment by NvTimLiu** [comment]
@sameerz  Could you please help to check if there is anything to be adjusted? thanks!

**Review by sameerz — COMMENTED** [review]
I've updated the labels on some issues.  Can the changelog be regenerated?

**Comment by sameerz** [comment]
I am ok to have this merged after the changelog is regenerated.

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Review by pxLi — APPROVED** [review]

**Pull request merged**
