### PR TITLE
Update code coverage to find source files in new places

### PR DESCRIPTION
**Pull request by revans2**
I noticed that code coverage was not good for the UDF compiler, and that the source files were not being picked up either.  
This hopefully fixes the later problem, for the former one I'm not sure if it was that the tests were not being picked up properly or if the coverage is really just not great.  Once I know this works.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
Yup the code coverage is accurate, we just need to spend some time on making it better.  The source files are now captured.

**Comment by revans2** [comment]
I targeted this to 0.2, but it is minor and could easily be in 0.3 if needed.

**Review by jlowe — DISMISSED** [review]
I'm OK with this going into 0.2 since it doesn't affect the main build but only the code coverage build and is arguably a bugfix.

**Comment by abellina** [comment]
So this PR didn't fix the problem right? I don't think it hurts to merge, just making sure i understand.

**Review by pxLi — COMMENTED** [review]
can you also make a change to https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/jenkins/Jenkinsfile-blossom.premerge#L238? The old premerge pipeline will be retired after 0.2 release, so during this period we have do it in 2 places before we sunset the old one.

But I can make another PR if you want

**Comment by revans2** [comment]
@pxLi great catch.

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by abellina — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by revans2** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
