### PR TITLE
Updating the config documentation for filecache configs [skip ci]

### PR DESCRIPTION
**Pull request by res-life**
Add the following config to doc

- spark.rapids.filecache.useChecksums

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
Failed because of mvn verify automatically remove the 2 configs:
```
-<a name="filecache.minimumFreeSpace.bytes"></a>spark.rapids.filecache.minimumFreeSpace.bytes|Specify the minimum amount of free space in the Spark local disks. When the amount of free space on the Spark local disks drops below this value, cache data will be removed automatically to free disk space. A zero or negative value will disable this feature. In order to avoid full disk errors, set this value as the max disk speed multiples filecache.minimumFreeSpace.checkInterval.|30G|Startup
-<a name="filecache.minimumFreeSpace.checkInterval"></a>spark.rapids.filecache.minimumFreeSpace.checkInterval|Specifies the time interval, in seconds, between checks for free disk space.|5|Startup
```

Remove them.

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
@nvliyuan 
will add filecache.minimumFreeSpace configs in a follow on PR.

**Comment by nvliyuan** [comment]
Why do we draft different pr for implementation and doc?

**Comment by nvliyuan** [comment]
oh i got it, file cache related pr is in private repo

**Review by jlowe — APPROVED** [review]

**Pull request merged**
