### PR TITLE
Binary and ternary handling of scalar audit and some fixes [databricks]

### PR DESCRIPTION
**Pull request by abellina**
Closes https://github.com/NVIDIA/spark-rapids/issues/8303

I need to add tests, and this is a draft for that reason.

I would like to show the approach here to make sure it's not too far off. I have added new subclasses of `GpuBinaryExpression` and `GpuTernaryExpression` to final override certain methods that we used to override + throw in specific expressions. For example, `GpuBinaryExpression_Any_Scalar` will throw if `doColumnar(*, GpuColumnVector)` is invoked. I tried to standardize the error message.

This change also implements some `doColumnar` functions that it looks like we can implement for: ArrayContains and GetMapValue. I will add tests to make sure I cover these, and again those are not included yet.

### CODE REVIEW

**Review by revans2 — COMMENTED** [review]
Just a few comments. Generally I like the direction.

**Review by jlowe — COMMENTED** [review]
"AnyScalar" has the unfortunate implication of any scalar among the arguments (naming is hard).  However the approach seems fine to me.  I like that this is deleting more code than it's adding (before tests).

**Comment by abellina** [comment]
I added some tests for GetMapValue and ArrayContains because I removed some preconditions in the GpuOverrides: https://github.com/NVIDIA/spark-rapids/pull/8833/commits/b4dcdd53d9ea211e03cd0fda4b08fc159a7d51dc.

I would like to know if there are other cases I should cover. I am not 100% sure that the way I did it is correct.

These tests are needed because of these `tagExprForGpu` changes: https://github.com/NVIDIA/spark-rapids/pull/8833/files#diff-8926565c5f6bc26203bed459ac37ea0fba15f9f5488aa2412aeac26b31f80ea6

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Review by jlowe — DISMISSED** [review]

**Comment by abellina** [comment]
Note that `test_cpu_fallback_map_scalars` was replaced with `test_basic_scalar_map_get_map_value`. It is the same test but it doesn't fallback to the CPU, because we implemented that functionality. It also doesn't fallback by mistake because of the cast, that was a separate issue that I fixed here.

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
@revans2 @jlowe this is ready for another look

**Pull request merged**
