### PR TITLE
Enable the tests for collect over window.

### LINKED ISSUE #1638: [BUG] Tests `test_window_aggs_for_rows_collect_list` fails when there are null values in columns.
**Describe the bug**
Spark will drop nulls when collecting, but seems GPU does not yet, so exceptions as below come up.
``` java
E      Caused by: java.lang.AssertionError:  value at 350 is null
E          	at ai.rapids.cudf.HostColumnVectorCore.assertsForGet(HostColumnVectorCore.java:228)
E         	at ai.rapids.cudf.HostColumnVectorCore.getInt(HostColumnVectorCore.java:254)
E         	at com.nvidia.spark.rapids.RapidsHostColumnVectorCore.getInt(RapidsHostColumnVectorCore.java:109)
E         	at org.apache.spark.sql.vectorized.ColumnarArray.getInt(ColumnarArray.java:128)
```

**Steps/Code to reproduce bug**
Run the tests `test_window_aggs_for_rows_collect_list` with latest cudf and rapids jars.

**Expected behavior**
Tests should pass.

### PR DESCRIPTION
**Pull request by firestarman**
This PR is to enable the tests `test_window_aggs_for_rows_collect_list` by removing the `xfail ` marker, since cuDF supports skipping null values by the following two PRs
   rapidsai/cudf#7264 (merged)
   rapidsai/cudf#7457 (merged)

closes #1638

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
Pending by the PR rapidsai/cudf#7457

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
@mythrocks could you help review this ?

**Review by mythrocks — APPROVED** [review]
LGTM!

**Pull request merged**
