### PR TITLE
update cudf Java binding version to 21.08.2

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

update cudfjni version to 21.08.2, doc update in https://github.com/NVIDIA/spark-rapids/pull/3080

I will trigger pre-merge build after the cudfjni 21.08.2 gets deployed to maven central

### CODE REVIEW

**Review by jlowe — DISMISSED** [review]

**Review by razajafri — DISMISSED** [review]

**Comment by pxLi** [comment]
added doc update from 21.08.0 to 21.08.2 for cudfjni

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Review by NvTimLiu — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
`from cloudera-repo failed: Read timed out` timeout downloading from cloudera repo, re-triggered

**Pull request merged**
