### PR TITLE
Add more parameters related to GDS or UCX in profiling tool.

### PR DESCRIPTION
**Pull request by viadea**

### CODE REVIEW

**Comment by tgravescs** [comment]
any tests need to be updated or do we not have any?

**Comment by viadea** [comment]
> any tests need to be updated or do we not have any?

I could not find some test case for this. @nartal1 can you help confirm?thx

**Comment by viadea** [comment]
Will create a new PR later due to the 21.06 branch issue.

**Comment by nartal1** [comment]
@viadea Sorry I missed this earlier. Not sure which code I had look into. Please tag me in your next PR.

**Pull request closed without merging**
