### PR TITLE
Init 22.06 changelog [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

Init changelog of 22.06 w/
```
GITHUB_TOKEN=XXX scripts/generate-changelog --releases=21.06,21.06.1,21.06.2,21.08,21.08.1,21.10,21.12,22.02,22.04,22.06
```

We will have a final update changelog update before release

### CODE REVIEW

**Comment by pxLi** [comment]
@sameerz @GaryShen2008 please help review if any PR/Issue titles/labels need to be adjusted, thanks!

**Comment by sameerz** [comment]
@pxLi I reviewed the issues, feel free to regenerate the changelog.

**Comment by pxLi** [comment]
build

**Review by zhanga5 — APPROVED** [review]
LGTM

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
