### PR TITLE
Update latest changelog [skip ci]

### PR DESCRIPTION
**Pull request by nvauto**
Update change log with CLI: 

   scripts/generate-changelog --token=<GIT_TOKEN> --releases=24.04,24.06

### CODE REVIEW

**Comment by NvTimLiu** [comment]
```
NOTE: Merged Pull Requests w/o Project:
branch-24.06 #10292 Upgrade to UCX 1.16.0 https://github.com/NVIDIA/spark-rapids/pull/10292
branch-24.06 #10635 Use new getJsonObject kernel for json_tuple https://github.com/NVIDIA/spark-rapids/pull/10635
branch-24.06 #10652 Substitute murmurHash32 for spark32BitMurmurHash3 [databricks] https://github.com/NVIDIA/spark-rapids/pull/10652
branch-24.06 #10678 Append new authorized user to blossom-ci whitelist [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10678
branch-24.06 #10723 Implement chunked ORC reader https://github.com/NVIDIA/spark-rapids/pull/10723
branch-24.06 #10754 Substitute whoami for $USER https://github.com/NVIDIA/spark-rapids/pull/10754
branch-24.06 #10767 Add rows-only batches support to RebatchingRoundoffIterator https://github.com/NVIDIA/spark-rapids/pull/10767
branch-24.06 #10800 Add number normalization test and address followup for getJsonObject https://github.com/NVIDIA/spark-rapids/pull/10800
branch-24.06 #10811 Fix NPE in GpuParseUrl for null keys. https://github.com/NVIDIA/spark-rapids/pull/10811
branch-24.06 #10820 workaround #10801 temporally https://github.com/NVIDIA/spark-rapids/pull/10820
branch-24.06 #10824 Support zstd for GPU shuffle compression https://github.com/NVIDIA/spark-rapids/pull/10824
branch-24.06 #10839 Replace anonymous classes for SortOrder and FIlterExec overrides https://github.com/NVIDIA/spark-rapids/pull/10839
branch-24.06 #10858 Add Support for Multiple Filtering Keys for Subquery Broadcast  https://github.com/NVIDIA/spark-rapids/pull/10858
branch-24.06 #10860 [Spark 4.0] Account for `PartitionedFileUtil.getPartitionedFile` signature change. https://github.com/NVIDIA/spark-rapids/pull/10860
branch-24.06 #10870 Add support for self-contained profiling https://github.com/NVIDIA/spark-rapids/pull/10870
branch-24.04 #10778 Update version to 24.04.1-SNAPSHOT https://github.com/NVIDIA/spark-rapids/pull/10778
branch-24.04 #10784 Update latest changelog [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10784
branch-24.04 #10788 [DOC] Update archive page for v24.04.1 [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10788
branch-24.04 #10844 Update rapids private dependency to 24.04.3 https://github.com/NVIDIA/spark-rapids/pull/10844
```

**Comment by NvTimLiu** [comment]
Draft the PR, we'll do the final update until all PRs targeting to branch-24.06 get merged

**Comment by sameerz** [comment]
Reviewed and updated the untargeted PRs and changelog.

**Comment by NvTimLiu** [comment]
> #10870




> Reviewed and updated the untargeted PRs and changelog.

Re-gen the Changelog after the PR review, thanks! 

Please ignore warnings if we need not to tag the below PRs


NOTE: Merged Pull Requests w/o Project:
branch-24.04 #10778 Update version to 24.04.1-SNAPSHOT https://github.com/NVIDIA/spark-rapids/pull/10778
branch-24.04 #10784 Update latest changelog [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10784
branch-24.06 #10678 Append new authorized user to blossom-ci whitelist [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10678

**Comment by sameerz** [comment]
> Re-gen the Changelog after the PR review, thanks!
> 
> Please ignore warnings if we need not to tag the below PRs, @sameerz
> 
> NOTE: Merged Pull Requests w/o Project:

Updated these PRs as well

**Comment by NvTimLiu** [comment]
build

**Review by sameerz — APPROVED** [review]

**Pull request merged**
