### PR TITLE
Change struct and array shuffle tests to work in distributed mode

### PR DESCRIPTION
**Pull request by kuhushukla**
Signed-off-by: Kuhu Shukla <kuhus@nvidia.com>

Fixes https://github.com/NVIDIA/spark-rapids/issues/1541 

**I am not terribly happy with what we are doing to make this work but it is a conversation starter at least.**
The issue is when we have multiple executors / distributed mode, the null key based values after the sort can be scrambled even though the sort is not semantically wrong after the shuffle. Shown below : 
CPU 
```
[Row(a=None, first_val=None),
 Row(a=[None, 234332775, 1, 1213716675, 1480654027, 271807679, 1930674352, -2080086848], first_val=None),
 Row(a=[], first_val=None),
 Row(a=None, first_val=None),
 Row(a=[None, 960244105, 84216343, -1373438663], first_val=None),
 Row(a=None, first_val=None),
 Row(a=[None, -1, 1718684370, 367231360, 1106778379, -1839778244, 666610294, 240175002, -672665733, -1803941716, -207959582, 53255033, 1, -1637040765, -2049878346, -2065016803], first_val=None),
 Row(a=[], first_val=None),
 Row(a=[], first_val=None)
```
GPU:
```
[Row(a=None, first_val=None),
 Row(a=[None, -1, 1718684370, 367231360, 1106778379, -1839778244, 666610294, 240175002, -672665733, -1803941716, -207959582, 53255033, 1, -1637040765, -2049878346, -2065016803], first_val=None),
 Row(a=[], first_val=None), 
 Row(a=[], first_val=None),
 Row(a=None, first_val=None), 
 Row(a=[], first_val=None),
 Row(a=None, first_val=None),
 Row(a=[None, 960244105, 84216343, -1373438663], first_val=None),
 Row(a=[None, 234332775, 1, 1213716675, 1480654027, 271807679, 1930674352, -2080086848], first_val=None)
```
If we anticipate this being a bug we should handle this change differently and I invite suggestions on that. The current fix is based on the understanding that this output is ok, I have reworked the tests to ignore_order. The reason why the queries themselves were changed is that when we ignore order, we do an explicit sort which does not go on the GPU since the original tests were projecting a nested column, something we cannot sort _on_, using local sort doesn't work due to NoneType comparisons failing on it. Another way to handle this is not have nulls in the tests but I don't really advocate that approach. Also for the `array_of_structs` case , I use a couple selects as we don't support certain operators like `GetArrayStructFields` to do a simple lookup. Appreciate any improvements for the tests and initial comments. I verified that taking out the change for https://github.com/NVIDIA/spark-rapids/pull/1477 does fail these tests so we should be good there.

### CODE REVIEW

**Comment by kuhushukla** [comment]
@tgravescs in an offline suggested  using unique values to sort on to simplify the query. I am looking into it now.

**Comment by revans2** [comment]
Also know that even if we cannot sort on the GPU for nested types we can pull the data back to the python process and sort it here.  That works too.  `@ignore_order(local=True)`

**Comment by kuhushukla** [comment]
> That works too. @ignore_order(local=True)
>
Thanks Bobby, I tried that but it had difficulty comparing nonetype and int type. I can dig into that a bit more but did not follow that path.

**Comment by tgravescs** [comment]
I will fix this under separate PR, closing this one.

**Pull request closed without merging**
