### PR TITLE
Clean up $M2_CACHE to avoid side-effect of previous dependency:get [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Follow up of https://github.com/NVIDIA/spark-rapids/pull/10201#discussion_r1467144648

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
SKIP CI as this script is only called from nightly CI jog, pre-merge will not run it.

**Comment by NvTimLiu** [comment]
build

**Review by gerashegalov — APPROVED** [review]
LGTM

**Comment by NvTimLiu** [comment]
Build PASS 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.403 s
[INFO] Finished at: 2024-01-26T10:39:11+08:00
[INFO] ------------------------------------------------------------------------
++ read line
++ ls --color=auto -l /tmp/test-get-dest
total 984040
-rw-r--r-- 1 timl root 503823658 1月  26 10:37 rapids-4-spark_2.12-24.02.0-SNAPSHOT-cuda11.jar
-rw-r--r-- 1 timl root 503823658 1月  25 02:37 rapids-4-spark_2.12-24.02.0-SNAPSHOT.jar
-rw-r--r-- 1 timl root         2 1月  25 02:37 rapids-4-spark_2.12-24.02.0-SNAPSHOT-javadoc.jar
-rw-r--r-- 1 timl root         4 1月  25 02:37 rapids-4-spark_2.12-24.02.0-SNAPSHOT-sources.jar
```

**Review by jlowe — APPROVED** [review]

**Pull request merged**
