### PR TITLE
Make dist jar compression opt-out optional

### PR DESCRIPTION
**Pull request by gerashegalov**
This PR speeds up iterating on features especially in the realm of [spark-rapids-jni / cudf](https://github.com/NVIDIA/spark-rapids-jni/blob/branch-22.08/CONTRIBUTING.md#local-testing-of-cross-repo-contributions-cudf-spark-rapids-jni-and-spark-rapids). 

After the initial build of `spark-rapids` when the only code changed is outside spark-rapids it suffices to execute
```
mvn package -pl dist  -Dbuildver=330 -DskipTests -Dskip -Dmaven.scalastyle.skip -Dmaven.javadoc.skip
...
[INFO] Total time:  35.624 s
```
to repackage all the dependencies

By disabling jar compression for local testing the same command speeds up from 35+ seconds to 10+ seconds  on my machine

```
mvn package -pl dist  -Dbuildver=330 -DskipTests -Dskip -Dmaven.scalastyle.skip -Dmaven.javadoc.skip -Ddist.jar.compress=false
...
[INFO] Total time:  10.775 s
```
 
### Other changes
- Add options advertised in buildall help without implementation to the parser
- Add rebuild-dist-only 

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Review by ttnghia — DISMISSED** [review]
Thanks for working on this. It is soooo helpful.

**Review by abellina — DISMISSED** [review]

**Comment by tgravescs** [comment]
do we want to document in contributing guide or anything?

**Comment by gerashegalov** [comment]
> do we want to document in contributing guide or anything?

initially was planing to only add it in spark-rapids-jni, but good idea to do it here as well

**Review by jbrennan333 — DISMISSED** [review]

**Comment by gerashegalov** [comment]
build

**Review by jbrennan333 — APPROVED** [review]
+1 this looks good to me

**Review by ttnghia — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Comment by gerashegalov** [comment]
> do we want to document in contributing guide or anything?

@tgravescs please take a look when you get to it

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
