### PR TITLE
Aggregate reductions in Complete mode should use updateExpressions

### LINKED ISSUE #898: [BUG] count reductions are failing on databricks because lack for Complete support
**Describe the bug**
In databricks the tests for `test_generic_reductions` are failing.  I traced this down to databricks using the `Complete` aggregation type, which our code does not properly support. 

**Steps/Code to reproduce bug**
Run `test_generic_reductions` on databricks with the latest branch-0.3 code.

**Expected behavior**
Test should pass

This looks like it should be somewhat simple to fix in a stop gap, but I am not 100% sure that we are doing the right thing in all cases with this. Ideally we check all possible aggregation types instead of just checking for a single one, but that may be difficult.

The reason this works for `count(*)` is because it is turned into `count(1)` and we do a SUM reduction on it, so it comes out the same.

### PR DESCRIPTION
**Pull request by kuhushukla**
Fixes #898 
Signed-off-by: Kuhu Shukla <kuhus@nvidia.com>

This fixes the reduction aggregates to work in complete mode. We already had some of this covered for when we have grouping keys. This change merely extends that change to reductions.

### CODE REVIEW

**Comment by kuhushukla** [comment]
build

**Comment by kuhushukla** [comment]
I additionally ran some hash agg integration tests on DB cluster and they pass after this change.

**Review by abellina — APPROVED** [review]

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
test fail due to issue in 3.1.0 with HiveStringType

**Comment by kuhushukla** [comment]
build

**Pull request merged**
