### PR TITLE
create new sparkContext explicitly in CPU notebook

### PR DESCRIPTION
**Pull request by mengdong**
create new sparkContext explicitly

### CODE REVIEW

**Comment by svcngcc** [comment]
Can one of the admins verify this patch?

**Comment by revans2** [comment]
build

**Review by revans2 — APPROVED** [review]
The change looks fine assuming that it was manually tested.

**Comment by revans2** [comment]
Sorry @mengdong you need to sign off on your PR by doing a -s when you commit at least one of the commits. See https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/CONTRIBUTING.md#sign-your-work

**Comment by sameerz** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
