### PR TITLE
Remove build link from the premerge-CI workflow

### PR DESCRIPTION
**Pull request by NvTimLiu**

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
image

image
[FAILED LOG](https://github.com/NVIDIA/spark-rapids/actions/runs/8589327692/job/23535335707)


image

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
