### PR TITLE
Substitute murmurHash32 for spark32BitMurmurHash3 [databricks]

### LINKED ISSUE #10487: Stop using ColumnVector.spark32BitMurmurHash3
cudf is planning to remove the Spark-specific MurmurHash3 kernel since it has been implemented in the `Hash` class in spark-rapids-jni.  See rapidsai/cudf#15074 for details.  The code needs to be updated to stop using ai.rapids.cudf.ColumnVector.spark32BitMurmurHash3 and start using com.nvidia.spark.rapids.jni.Hash.murmurHash32.

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #10487
    
Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
CI failed due to #10656

**Comment by jlowe** [comment]
build

**Pull request merged**
