### PR TITLE
Abstract the text based PartitionReader

### PR DESCRIPTION
**Pull request by wbo4958**
This PR tries to abstract the text-based PartitionReader which will be applied to CSV reader (This PR added) and the in-coming JSON reader

Signed-off-by: Bobby Wang <wbo4958@gmail.com>

### CODE REVIEW

**Comment by wbo4958** [comment]
build

**Review by revans2 — APPROVED** [review]
This looks fine to me. I am less sure about the `hasHeader` flag in the generic text reader. Just because JSON is not going to need it.  But it should be fine.

**Comment by wbo4958** [comment]
> This looks fine to me. I am less sure about the `hasHeader` flag in the generic text reader. Just because JSON is not going to need it. But it should be fine.

Thx, You're right, the headerFlag should not in the abstract class. Removed it. Thx

**Comment by wbo4958** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
