### PR TITLE
Update Databricks 10.4 for changes to the QueryStageExec and ClusteredDistribuion [databricks]

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/5154

Looks like 2 different changes.

 - pulled in https://issues.apache.org/jira/browse/SPARK-38237 which was changed in spark 3.3 back.  These changes are in our Spark 3.3 shim so it was just copying them back to 321db.
 - adds an extra parameter to *QueryStageExec called isSparkExchange. 

I had to copy some files around to make it 321db specific.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by tgravescs** [comment]
forgot to check in the build.sh script changes for 10.4, will update shortly

**Comment by sameerz** [comment]
@tgravescs can we backport this to 22.04 please?

**Comment by tgravescs** [comment]
closing this and putting up against 22.04

**Pull request closed without merging**
