### PR TITLE
Update changelog for v24.08.0 release [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Update change log with CLI:

scripts/generate-changelog --token=<GIT_TOKEN> --releases=24.06,24.08

### CODE REVIEW

**Comment by NvTimLiu** [comment]
NOTE: Merged Pull Requests w/o Project, @sameerz  can you help review this change? Thanks!

```
branch-24.08 #10917 Adopt changes from JNI for casting from float to decimal https://github.com/NVIDIA/spark-rapids/pull/10917
branch-24.08 #10929 Append new authorized user to blossom-ci whitelist [skip ci] https://github.com/NVIDIA/spark-rapids/pull/10929
branch-24.08 #10943 Fix Spark UT issues in RapidsDataFrameAggregateSuite https://github.com/NVIDIA/spark-rapids/pull/10943
branch-24.08 #10946 Unarchive Spark test jar for spark.read(ability) https://github.com/NVIDIA/spark-rapids/pull/10946
branch-24.08 #10978 More compilation fixes for Spark 4.0.0 [databricks] https://github.com/NVIDIA/spark-rapids/pull/10978
branch-24.08 #11044 Fixed Failing tests in arithmetic_ops_tests for Spark 4.0.0 [databricks] https://github.com/NVIDIA/spark-rapids/pull/11044
branch-24.08 #11073 Disable ANSI mode for window function tests [databricks] https://github.com/NVIDIA/spark-rapids/pull/11073
branch-24.08 #11083 Exclude a case based on JDK version in Spark UT https://github.com/NVIDIA/spark-rapids/pull/11083
branch-24.08 #11278 Fix formatting of advanced configs doc https://github.com/NVIDIA/spark-rapids/pull/11278
branch-24.08 #11292 Add work around for string split with empty input. https://github.com/NVIDIA/spark-rapids/pull/11292
```

**Comment by NvTimLiu** [comment]
This PR is for in-advance review, will update the changelog to latest if needed, thanks!.

**Comment by pxLi** [comment]
> NOTE: Merged Pull Requests w/o Project, @sameerz can you help review this change? Thanks!
> 
> branch-24.08 #10917 Adopt changes from JNI for casting from float to decimal #10917 branch-24.08 #10929 Append new authorized user to blossom-ci whitelist [skip ci] #10929 branch-24.08 #10943 Fix Spark UT issues in RapidsDataFrameAggregateSuite #10943 branch-24.08 #10946 Unarchive Spark test jar for spark.read(ability) #10946 branch-24.08 #10978 More compilation fixes for Spark 4.0.0 [databricks] #10978 branch-24.08 #11044 Fixed Failing tests in arithmetic_ops_tests for Spark 4.0.0 [databricks] #11044 branch-24.08 #11073 Disable ANSI mode for window function tests [databricks] #11073 branch-24.08 #11083 Exclude a case based on JDK version in Spark UT #11083 branch-24.08 #11278 Fix formatting of advanced configs doc #11278 branch-24.08 #11292 Add work around for string split with empty input. #11292

those were just missing adding a roadmap. I have updated

**Comment by NvTimLiu** [comment]
> > NOTE: Merged Pull Requests w/o Project, @sameerz can you help review this change? Thanks!
> > branch-24.08 #10917 Adopt changes from JNI for casting from float to decimal #10917 branch-24.08 #10929 Append new authorized user to blossom-ci whitelist [skip ci] #10929 branch-24.08 #10943 Fix Spark UT issues in RapidsDataFrameAggregateSuite #10943 branch-24.08 #10946 Unarchive Spark test jar for spark.read(ability) #10946 branch-24.08 #10978 More compilation fixes for Spark 4.0.0 [databricks] #10978 branch-24.08 #11044 Fixed Failing tests in arithmetic_ops_tests for Spark 4.0.0 [databricks] #11044 branch-24.08 #11073 Disable ANSI mode for window function tests [databricks] #11073 branch-24.08 #11083 Exclude a case based on JDK version in Spark UT #11083 branch-24.08 #11278 Fix formatting of advanced configs doc #11278 branch-24.08 #11292 Add work around for string split with empty input. #11292
> 
> those were just missing adding a roadmap. I have updated

Thanks, updated the changelog to include these PRs

**Comment by sameerz** [comment]
Reviewed the change log and made some label changes.

**Comment by NvTimLiu** [comment]
> Reviewed the change log and made some label changes.

Updated, thanks！

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
