### PR TITLE
ORC reader supports list

### PR DESCRIPTION
**Pull request by firestarman**
Let ORC reader support list, since cudf has the support by the PR rapidsai/cudf#8599 .

This is related to #2879

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
As suggested by @sameerz , we plan to make two separate PRs for list and struct respectively.

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
@tgravescs 
Hi,
The file "supportedDataSource.csv" under tool module has been updated accordingly after `mvn verify`. Is it expected ?
And the pre-merge failed, did I miss anything ?

https://blossom.nvidia.com/sw-gpu-spark-jenkins/job/rapids_premerge-github/2101/consoleText
```Bash
[2021-07-16T08:04:38.060Z] [31m- test dsv1 complex and decimal *** FAILED ***[0m
[2021-07-16T08:04:38.060Z] [31m  java.lang.AssertionError: assertion failed[0m
[2021-07-16T08:04:38.060Z] [31m  at scala.Predef$.assert(Predef.scala:208)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.ToolTestUtils$.compareDataFrames(ToolTestUtils.scala:83)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.qualification.QualificationSuite.$anonfun$runQualificationTest$1(QualificationSuite.scala:93)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.qualification.QualificationSuite.$anonfun$runQualificationTest$1$adapted(QualificationSuite.scala:75)[0m
```

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
The previous pre-merge build failed because of the follow failure.
```
[2021-07-16T08:04:38.060Z] 
[2021-07-16T08:04:38.060Z] [31m- test dsv1 complex and decimal *** FAILED ***[0m
[2021-07-16T08:04:38.060Z] [31m  java.lang.AssertionError: assertion failed[0m
[2021-07-16T08:04:38.060Z] [31m  at scala.Predef$.assert(Predef.scala:208)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.ToolTestUtils$.compareDataFrames(ToolTestUtils.scala:83)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.qualification.QualificationSuite.$anonfun$runQualificationTest$1(QualificationSuite.scala:93)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.qualification.QualificationSuite.$anonfun$runQualificationTest$1$adapted(QualificationSuite.scala:75)[0m
[2021-07-16T08:04:38.060Z] [31m  at org.apache.spark.sql.TrampolineUtil$.withTempDir(TrampolineUtil.scala:36)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.qualification.QualificationSuite.runQualificationTest(QualificationSuite.scala:75)[0m
[2021-07-16T08:04:38.060Z] [31m  at com.nvidia.spark.rapids.tool.qualification.QualificationSuite.$anonfun$new$35(QualificationSuite.scala:441)[0m
[2021-07-16T08:04:38.060Z] [31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[2021-07-16T08:04:38.060Z] [31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m
[2021-07-16T08:04:38.060Z] [31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m
```
Not sure the change under tool module is required, now drop it to pass the pre-merge build.

**Comment by firestarman** [comment]
The new pre-merge build failed due to the updated file `supportedDataSource.csv`, now it is blocked.
```
[2021-07-16T09:30:01.132Z] found modified files during mvn verify:
[2021-07-16T09:30:01.133Z]  M tools/src/main/resources/supportedDataSource.csv
[2021-07-16T09:30:01.392Z] [ERROR] Command execution failed.
[2021-07-16T09:30:01.392Z] org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

**Comment by tgravescs** [comment]
The best had expected orc to fail we need to update the expected results file. ./tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv.

run the qualification tool something like this:
java -cp /home/tgraves/workspace/spark-rapids/tools/target/rapids-4-spark-tools_2.12-21.08.0-SNAPSHOT.jar:$SPARK_HOME/jars/*  com.nvidia.spark.rapids.tool.qualification.QualificationMain ./tools/src/test/resources/spark-events-qualification/complex_dec_eventlog.zstd

diff rapids_4_spark_qualification_output/rapids_4_spark_qualification_output.csv ./tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv

If you add support for lists then the final column ORC[map:array:struct:decimal] should not include array anymore.  If that is the case just copy the new results there.

**Review by jlowe — COMMENTED** [review]
Changes look OK to me other than the need to update the tools CSV file.

@tgravescs are the steps to update the tools CSV file documented somewhere in the repository or is there a way we can better automate the update?  I suspect other devs are going to run into this in the future and wonder how to fix it.

**Comment by tgravescs** [comment]
No its not documented, we can add documentation. not sure I want to automate it because I think a dev should verify what is expected is right.  Other then  maybe have a target to update and then dev still checks before checking in. let me file an issue for that.

**Comment by firestarman** [comment]
Thanks all.
I executed the two commands below to update the expected result file.
```Bash
java -cp $PROJECT_ROOT/tools/target/rapids-4-spark-tools_2.12-21.08.0-SNAPSHOT.jar:$SPARK_HOME/jars/* com.nvidia.spark.rapids.tool.qualification.QualificationMain ./tools/src/test/resources/spark-events-qualification/complex_dec_eventlog.zstd
cp rapids_4_spark_qualification_output/rapids_4_spark_qualification_output.csv ./tools/src/test/resources/QualificationExpectations/complex_dec_expectation.csv
```

**Comment by firestarman** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by tgravescs** [comment]
yeah the score should change to be higher because there is now one more operations being used that we support. that diff looks fine.

**Pull request merged**
