### PR TITLE
IGNORE: approx percentile debug logging [databricks]

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

Debug logging to help learn more about https://github.com/NVIDIA/spark-rapids/issues/4060

### CODE REVIEW

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by jlowe** [comment]
@andygrove can this be closed?  I think this has served its purpose.

**Comment by andygrove** [comment]
Sure, I can recreate once the fix is ready for testing.

**Pull request closed without merging**
