### PR TITLE
Add GPU support for EphemeralSubstring [databricks]

### PR DESCRIPTION
**Pull request by jlowe**
Adds support for the EphemeralSubstring expression by translating these operations to the existing GpuSubstring expression.  Ephemeral substrings are simply a performance optimization for certain situations where substrings are generated and have no semantic differences from a regular substring.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by abellina — APPROVED** [review]
LGTM

**Comment by abellina** [comment]
Hmm, there seems to be a related integration test failure in DB 9.1 at least, where the other test builds aborted:
```
[2023-02-21T23:37:20.982Z] FAILED ../../src/main/python/string_test.py::test_ephemeral_substring - pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columna...
```

**Comment by jlowe** [comment]
Yes, I was somewhat expecting this.  The plan is to drop 9.1 support in #7463, so this is only implemented for Databricks 10.4+.  I'll exclude Databricks 9.1 from the test for now.

**Comment by jlowe** [comment]
build

**Review by razajafri — APPROVED** [review]

**Pull request merged**
