### PR TITLE
Mark more tests as premerge_ci_1

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

mark map_test , orc_test and window_function_test as premerge_ci_1

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Review by zhanga5 — DISMISSED** [review]
👍

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by zhanga5 — APPROVED** [review]

**Pull request merged**
