### PR TITLE
Mirror apache repos to urm

### PR DESCRIPTION
**Pull request by firestarman**
Add mirrors for the two apache repos (apache.snapshots.https, apache-snapshots-repo) to accelerate the CI/CD build.

```Bash
Downloading from apache-snapshots-repo: https://urm.nvidia.com:443/artifactory/sw-spark-maven/org/apache/spark/spark-sql_2.12/3.1.3-SNAPSHOT/maven-metadata.xml
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/org/apache/spark/spark-sql_2.12/3.1.3-SNAPSHOT/maven-metadata.xml
Downloading from apache.snapshots.https: https://urm.nvidia.com:443/artifactory/sw-spark-maven/org/apache/spark/spark-sql_2.12/3.1.3-SNAPSHOT/maven-metadata.xml
```

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]
LGTM. require owner's approval

**Review by gerashegalov — APPROVED** [review]

**Comment by firestarman** [comment]
build

**Comment by firestarman** [comment]
@sperlingxx found the repo `apache.snapshots` is still being used, so keep it unchanged and add the `https ` as a new one .

**Review by jlowe — APPROVED** [review]

**Pull request merged**
