### PR TITLE
Append new authorized user to blossom-ci whitelist [skip ci]

### PR DESCRIPTION
**Pull request by liurenjie1024**

### CODE REVIEW

**Comment by liurenjie1024** [comment]
build

**Comment by liurenjie1024** [comment]
build

**Review by GaryShen2008 — DISMISSED** [review]

**Comment by GaryShen2008** [comment]
build

**Comment by GaryShen2008** [comment]
Let's retarget to branch-24.06 since 24.04 is in code freeze.

**Comment by GaryShen2008** [comment]
build

**Review by gerashegalov — APPROVED** [review]

**Pull request merged**
