### PR TITLE
Support Collect-like Reduction Aggregations

### PR DESCRIPTION
**Pull request by sperlingxx**
Current PR is the last piece of the puzzle of the [collect aggregations supporting](https://github.com/NVIDIA/spark-rapids/issues/2062), which enables collect aggregations under reduction context in spark-rapids. 

Signed-off-by: sperlingxx <lovedreamf@gmail.com>

### CODE REVIEW

**Comment by sperlingxx** [comment]
This PR is supposed to be shipped in release 22.06

**Comment by sperlingxx** [comment]
> Can we put this in draft until branch-22.06 is available?

Good idea! It's done.

**Comment by abellina** [comment]
This one can now target 22.06

**Review by ttnghia — APPROVED** [review]

**Comment by sameerz** [comment]
build

**Comment by sperlingxx** [comment]
build

**Pull request merged**
