### PR TITLE
Improve test coverage for sorting structs

### PR DESCRIPTION
**Pull request by gerashegalov**
Relates to #1607

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by abellina** [comment]
I ran with @gerashegalov's branch locally with 12 tasks (that's the number of cores I have), for `test_large_orderby[Struct(('child0', Long))`:

```
../../src/main/python/sort_test.py::test_large_orderby[Struct(('child0', Long))] 21/05/26 13:22:36 ERROR Executor: Exception in task 6.0 in stage 5.0 (TID 66)
ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-dev-github-324-cuda11/cpp/include/cudf/table/row_operators.cuh:361: Mismatched number of columns.
	at ai.rapids.cudf.Table.bound(Native Method)
	at ai.rapids.cudf.Table.upperBound(Table.java:1409)
	at ai.rapids.cudf.Table.upperBound(Table.java:1434)
	at com.nvidia.spark.rapids.GpuSorter.$anonfun$upperBound$2(SortUtils.scala:168)
```
These other tests passed:
```
../../src/main/python/sort_test.py::test_large_orderby_stable[Struct(('child0', Long))] PASSED [ 66%]
../../src/main/python/sort_test.py::test_large_orderby_nested_ridealong[Struct(('child1', Byte))] PASSED [100%]
```

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by revans2 — APPROVED** [review]
Some of the test cases added are a bit redundant, but I would rather have more coverage than less so I am fine with it.

**Review by abellina — APPROVED** [review]

**Pull request merged**
