### PR TITLE
Remove spark.rapids.sql.nonUTC.enabled configuration option

### PR DESCRIPTION
**Pull request by winningsix**
This closes https://github.com/NVIDIA/spark-rapids/issues/9881.

Check framework already covers well for targeted expressions/execs. And we don't need extra configuration to turn on/off timezone related work. Also, it brings extra burden for adding more expression functions.

### CODE REVIEW

**Comment by winningsix** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by revans2** [comment]
Looks like the fallback tests for FromUTCTimestamp were relying on this config to pass.

```
[2023-12-13T14:38:53.308Z] FAILED ../../src/main/python/date_time_test.py::test_from_utc_timestamp_non_utc_fallback[Timestamp-Asia/Shanghai][DATAGEN_SEED=1702474979, ALLOW_NON_GPU(ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback.assertDidFallBack.
[2023-12-13T14:38:53.308Z] FAILED ../../src/main/python/date_time_test.py::test_from_utc_timestamp_non_utc_fallback[Timestamp-EST][DATAGEN_SEED=1702474979, ALLOW_NON_GPU(ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback.assertDidFallBack.
[2023-12-13T14:38:53.309Z] FAILED ../../src/main/python/date_time_test.py::test_from_utc_timestamp_non_utc_fallback[Timestamp-MST][DATAGEN_SEED=1702474979, ALLOW_NON_GPU(ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback.assertDidFallBack.
[2023-12-13T14:38:53.309Z] FAILED ../../src/main/python/date_time_test.py::test_from_utc_timestamp_non_utc_fallback[Timestamp-VST][DATAGEN_SEED=1702474979, INJECT_OOM, ALLOW_NON_GPU(ProjectExec)] - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.sql.rapids.ExecutionPlanCaptureCallback.assertDidFallBack.
```

We probably want to skip these tests if the timezone is not supported instead.

**Comment by winningsix** [comment]
build

**Comment by winningsix** [comment]
build

**Review by res-life — APPROVED** [review]

**Pull request merged**
