### PR TITLE
Update 22.06.0 changelog to latest [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

as title

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — DISMISSED** [review]

**Comment by NvTimLiu** [comment]
Seems 2 issues not included into the CHANGELOG:
https://github.com/NVIDIA/spark-rapids/issues/5722 FIXED BY https://github.com/NVIDIA/spark-rapids/pull/5764
https://github.com/NVIDIA/spark-rapids/issues/5246 FIXED BY https://github.com/NVIDIA/spark-rapids/pull/5761

**Review by GaryShen2008 — APPROVED** [review]

**Review by NvTimLiu — APPROVED** [review]

**Comment by GaryShen2008** [comment]
build

**Pull request merged**
