### PR TITLE
Remove the struct support in ORC reader

### PR DESCRIPTION
**Pull request by firestarman**
We do this because of the issue https://github.com/NVIDIA/spark-rapids/issues/3059, which seems not to be easy to fix in a short time.

closes https://github.com/NVIDIA/spark-rapids/issues/3059 

Signed-off-by: Firestarman <firestarmanllc@gmail.com>

### CODE REVIEW

**Comment by firestarman** [comment]
I will take care of the issue https://github.com/NVIDIA/spark-rapids/issues/3059 when enabling the struct support in the future PR  for 21.10.

**Comment by firestarman** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
we need an issue to track putting this back and specifically also make sure the test failure gets fixed.

**Comment by tgravescs** [comment]
reopened https://github.com/NVIDIA/spark-rapids/issues/2879

**Review by jlowe — APPROVED** [review]

**Comment by firestarman** [comment]
> reopened #2879

Thanks

**Pull request merged**
