### PR TITLE
Fix merge conflict with branch-0.4

### PR DESCRIPTION
**Pull request by jlowe**
Fixes the merge conflict flagged by #1936.  All the conflicts were with documentation or doc strings in code.  All conflicts were dropped in favor of the existing branch-0.5 version except for `download.md` where the change needed to be migrated to the new layout in that document.

**NOTE: This needs to be committed with a merge commit, not squashed!**

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by pxLi** [comment]
https://github.com/NVIDIA/spark-rapids/pull/1936 got more commits merged, 
can you help fix the conflict within this PR? I can start a new one if you are not available, thanks!

**Comment by jlowe** [comment]
Yes, I'll update this with the new commits

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by jlowe** [comment]
build

**Pull request merged**
