### PR TITLE
Update workspace for the spark300db shims

### PR DESCRIPTION
**Pull request by NvTimLiu**
Update workspace path for the spark300db shims for release

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Review by firestarman — APPROVED** [review]

**Comment by jlowe** [comment]
This looks like a non-merge PR that was done directly on `main`.  Normally we do not want such things, as that means the change appears **only on main** and not in any development branch.

Why was this change not done on branch-0.2 and merged to main afterwards?  Do we not want this change going forward in branch-0.3?

**Comment by NvTimLiu** [comment]
> This looks like a non-merge PR that was done directly on `main`. Normally we do not want such things, as that means the change appears **only on main** and not in any development branch.
> 
> Why was this change not done on branch-0.2 and merged to main afterwards? Do we not want this change going forward in branch-0.3?

@jlowe, Sorry for the delayed reply. This PR should be done on branch-0.2 and forward to branch-0.3

**Pull request merged**
