### PR TITLE
Qualification tool support recognizing decimal operations

### PR DESCRIPTION
**Pull request by tgravescs**
This adds support for the qualification tool trying to recognize decimal operations and adds them to the potential problems columns.  It also adds any sql ops with decimals to the sql duration for problematic.

This fixes a couple of issues found during testing, like if the sql start event is missing  but end event was there, we were setting time to 0 rather than the sql end time.

Output now looks like:

csv:
```
App Name,App ID,Score,Potential Problems,SQL Dataframe Duration,App Duration,Executor CPU Time Percent,App Duration Estimated,SQL Duration with Potential Problems,SQL Ids with Failures
Spark shell,local-1626199951158,0.65,**UDF:DECIMAL**,1421,219771,60.49,false,**1121**,""

```

specifically note the Potential Problems and SQL Duration with Potential Problems

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
build

**Review by nartal1 — DISMISSED** [review]

**Comment by nartal1** [comment]
LGTM. Please resolve conflicts.

**Comment by tgravescs** [comment]
build

**Pull request merged**
