### PR TITLE
Fix ConditionalExpr parser in Qualification tool

### LINKED ISSUE #7059: [BUG] Qualification - Incorrect parsing of conditional expressions
**Describe the bug**

The qualification tool skips many application logs due to an exception parsing condition Expressions.

A sample of expressions causing the exception:
```
Filter (((lower(partition_act#90) = moduleview) && (isnotnull(productarr#22) && NOT (productarr#22=[]))) || (lower(moduletype#13) = saveforlater))
```

While replacing "OR" by "||" and "AND" by "&&" gets rid of the exception, the parser still is not handling the expression correctly because it splits around, AND, then OR, then NOT.
This produces an incorrect expression. For example, before crashing the parser will be looking into the following array of expressions
```
[")))", "(lower(moduletype#13)"]
```

instead of

```
[
"(lower(partition_act#90) = moduleview) && (isnotnull(productarr#22) && NOT (productarr#22=[]))",
"lower(moduletype#13) = saveforlater"
]
```

Exception triggered:

```
22/11/14 10:21:12 WARN Qualification: Unexpected exception processing log file:/Users/ahussein/workspace/repos/issues/umbrella-7044/spark-2x-logs/application_1667271647355_0001_1.lz4, skipping!
scala.MatchError: || (of class java.lang.String)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.$anonfun$parseConditionalExpressions$7(SQLPlanParser.scala:620)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parseConditionalExpressions(SQLPlanParser.scala:599)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parseFilterExpressions(SQLPlanParser.scala:571)
	at com.nvidia.spark.rapids.tool.planparser.FilterExecParser.parse(FilterExecParser.scala:34)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parsePlanNode(SQLPlanParser.scala:146)
	at com.nvidia.spark.rapids.tool.planparser.WholeStageExecParser.$anonfun$parse$3(WholeStageExecParser.scala:43)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.nvidia.spark.rapids.tool.planparser.WholeStageExecParser.parse(WholeStageExecParser.scala:42)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parsePlanNode(SQLPlanParser.scala:109)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.$anonfun$parseSQLPlan$1(SQLPlanParser.scala:86)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.nvidia.spark.rapids.tool.planparser.SQLPlanParser$.parseSQLPlan(SQLPlanParser.scala:85)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.$anonfun$aggregateStats$6(QualificationAppInfo.scala:354)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.$anonfun$aggregateStats$1(QualificationAppInfo.scala:352)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.sql.rapids.tool.qualification.QualificationAppInfo.aggregateStats(QualificationAppInfo.scala:332)
	at com.nvidia.spark.rapids.tool.qualification.Qualification.com$nvidia$spark$rapids$tool$qualification$Qualification$$qualifyApp(Qualification.scala:126)
	at com.nvidia.spark.rapids.tool.qualification.Qualification$QualifyThread.run(Qualification.scala:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Additional context:**

- Failing in one expression should not skip the entire app: #7044

### PR DESCRIPTION
**Pull request by amahussein**
Signed-off-by: Ahmed Hussein (amahussein) <a@ahussein.me>

fixes #7059 

This PR revisited the implementation of `SQLParserPlan.parseConditionalExpressions`

- Added the following operators to the expressions:
  - `AND` / `&&`: the `&&` for backward compatibility with Spark2.x
  - `OR` / `||`: the `||` for backward compatibility with Spark2.x
  - `IN`,
  - Arithmetic "`-`, `*`"
- Unrecognized operators are being ignored for now.
- Added unit test to test parsing sample of condition expressions.

### CODE REVIEW

**Comment by amahussein** [comment]
build

**Comment by amahussein** [comment]
build

**Comment by amahussein** [comment]
build

**Review by nartal1 — APPROVED** [review]
LGTM

**Pull request merged**
