### PR TITLE
Make JSON parsing common between JsonToStructs and ScanJson

### LINKED ISSUE #4779: [FEA] JSON reader should parse non-boolean values as null
**Is your feature request related to a problem? Please describe.**
When parsing the following JSON file and specifying that the `number` column is a boolean type, Spark will produce the values `true` and `null`, but on GPU we would produce `true` for both rows (once https://github.com/NVIDIA/spark-rapids/pull/4780 is merged).

There is a similar issue with numeric values. 

```json
{ "number": true }
{ "number": "true" }
```

**Describe the solution you'd like**
We should have consistent behavior with Spark. We need to remove the XFAIL from the test in json_test.py that references this issue.

**Describe alternatives you've considered**
None

**Additional context**
Depends on https://github.com/rapidsai/cudf/issues/10283

### LINKED ISSUE #9588: [FEA][JSON] Respect `allowNumericLeadingZeros` in `from_json`
**Is your feature request related to a problem? Please describe.**
Our implementation of `from_json` supports leading zeros for numeric values, but Spark does not support this with the default setting of `allowNumericLeadingZeros=false`, so we are not compatible.

**Describe the solution you'd like**
We should respect this setting, or fall back to CPU if the schema asks for numeric values and `allowNumericLeadingZeros=false`.

We have a test `test_from_json_struct` that contains a reference to this issue and should be updated once this issue is resolved.

**Describe alternatives you've considered**
None

**Additional context**
None

### LINKED ISSUE #10456: [BUG] allowNonNumericNumbers OFF supported for JSON Scan, but not JsonToStructs
**Describe the bug**
Just like it says doing a JsonScan with allowNonNumericNumbers set to false works, but it fails for from_json/JsonToStructs. It does not fall back to the CPU, nor does it produce the correct answers.

### LINKED ISSUE #10460: [BUG] JsonToStructs should reject float numbers for integer types
**Describe the bug**
{"int": 1.0} when read as an integer type, like ByteType, ShortType, IntegerType, and LongType is returned as null. Our code is not consistent in this. JsonToStructs does not fix this up at all but it looks like ScanJson is doing something for this.

### LINKED ISSUE #10467: [BUG] JsonToStructs should reject 1. as a valid number
**Describe the bug**
For some reason ScanJson does the right thing, but JsonToStructs/from_json interprets this as 1.0 instead of a failure that is null. I think this applies to all numbers formatted in a similar way. (with just a trailing .)

### LINKED ISSUE #10468: [BUG] JsonToStructs and ScanJson should not treat quoted strings as valid integers
**Describe the bug**
Integer types like byte, short, int and long should return null for quoted strings as input. Currently we parse the contents of the quoted string and see what the result is.

### LINKED ISSUE #10469: [BUG] ScanJson should accept "1." as a valid Decimal
**Describe the bug**
This is kind of the opposite of https://github.com/NVIDIA/spark-rapids/issues/10467

Spark happily accepts quoted strings as decimal values and interprets "1." as a value of 1.0. This appears to work right now for from_json, but not for a scan.

### LINKED ISSUE #10470: [BUG] ScanJson and JsonToStructs should support parsing quoted decimal strings that are formatted by local (at least for en-US)
**Describe the bug**
Decimal values in JSON are odd. If the number is in quotes it is treated differently from when it is outside of quotes.  If it is in quotes, then the locale can be taken into account when trying to parse it. So numbers like "1,000.001" are valid in quotes for decimals, but not outside of quotes.

In theory any local that java supports could also be supported for parsing these quoted string numbers.  Sadly numbers from Thai and Hindi appear to be supported for `en-US` which is the default.

Not sure how much we want to split this up or what, but it is a bit complicated.

### LINKED ISSUE #10494: [BUG] JsonToStructs parses INF wrong when nonNumbericNumbers is enabled
**Describe the bug**
when nonNumbericNumbers are enabled (on versions 3.3.0+) INF and "INF" produce `null`, but we produce `inf` when parsing a float or double.

### PR DESCRIPTION
**Pull request by revans2**
This fixes #10456 
This fixes #10467 
This fixes #10469 
This fixes #10494 
This fixes #9588 
This fixes #4779 
This fixes #10470 
This fixes #10460 
This fixes #10468 

The fixes are mostly from combining fixes that were in ScanJson with fixes that were in JsonToStructs, which removed a lot of corner cases where one had fixed some things and the other had fixed others.

Sadly it did not fix the date/timestamp parsing. The Date/Timestamp parsing is based off of ScanJson, which was more liberal in many areas compared to `from_json`, but does not support reading numbers as dates/timestamps like `from_json` partially did. It caused a number of tests in `from_json` to start failing partly because it is not falling back in cases that ScanJson has problems. 

As a part of this it also added in some nested type support for ScanJson with tests added from https://github.com/NVIDIA/spark-rapids/pull/10325

With this we also have adopted the configs `spark.rapids.sql.json.read.float.enabled`, `spark.rapids.sql.json.read.double.enabled`, and `spark.rapids.sql.json.read.decimal.enabled` for `from_json`.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @revans2

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@andygrove could you please take another look? I had gotten some schema mixed up that fixed things for JSON, but ended up breaking CSV. That should be fixed now.

**Review by andygrove — APPROVED** [review]

**Comment by revans2** [comment]
This also fixed https://github.com/NVIDIA/spark-rapids/issues/4647

**Pull request merged**
