### PR TITLE
Merge branch 'branch-23.10' into main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge branch 'branch-23.10' into main

Change spark-rapids version to v23.10.0

**NOTE: merge this PR via "create a merge commit"**

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
This change is for in-advance commit history review. Please upmerge later to include latest bug fix and dep version bump up changes

We will merge remained doc update and changelog change next Monday and start building RC, thanks

**Comment by pxLi** [comment]
We will do a final update before release candidate build.
Please help review the commit history in advance, thanks

23.10 PRs : https://github.com/NVIDIA/spark-rapids/pulls?q=is%3Apr+is%3Aopen+base%3Abranch-23.10

**Review by jlowe — APPROVED** [review]

**Review by pxLi — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Pull request merged**
