### PR TITLE
Fixed Databricks build [databricks]

### PR DESCRIPTION
**Pull request by razajafri**
PR https://github.com/NVIDIA/spark-rapids/pull/10858 broke the Databricks build because of misisng shims. 

This PR fixes it.

### CODE REVIEW

**Comment by razajafri** [comment]
@NVnavkumar I missed the DB shims in the last PR. can you PTAL.

**Review by NVnavkumar — DISMISSED** [review]

**Comment by NVnavkumar** [comment]
build

**Review by mythrocks — APPROVED** [review]
LGTM!

**Comment by razajafri** [comment]
build

**Review by NVnavkumar — APPROVED** [review]

**Review by mythrocks — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Pull request merged**
