### PR TITLE
Update Parquet binaryAsString integration to use a static parquet file

### LINKED ISSUE #5837: [BUG] test_parquet_read_round_trip_binary_as_string failures on YARN and Dataproc
**Describe the bug**
The following tests failed on YARN integration tests, looks like perhaps a setup issue with files not found:

`[2022-06-15T13:09:36.649Z] [1m[31mE   FileNotFoundError: [Errno 2] Failed to open local file '/tmp/py****_tests//****-egx-02-main-98-1966622921//binary_as_string.parquet'. Detail: [errno 2] No such file or directory[0m
`

```
[2022-06-15T13:09:36.609Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs0-read_parquet_df] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.609Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs0-read_parquet_sql] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.609Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs1-read_parquet_df] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.609Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs1-read_parquet_sql] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs2-read_parquet_df] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs2-read_parquet_sql] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs3-read_parquet_df] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs3-read_parquet_sql] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs4-read_parquet_df] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs4-read_parquet_sql] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs5-read_parquet_df] [31mFAILED[0m[31m [  4%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[-reader_confs5-read_parquet_sql] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs0-read_parquet_df] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs0-read_parquet_sql] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs1-read_parquet_df] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs1-read_parquet_sql] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs2-read_parquet_df] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs2-read_parquet_sql] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs3-read_parquet_df] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs3-read_parquet_sql] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs4-read_parquet_df] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs4-read_parquet_sql] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs5-read_parquet_df] [31mFAILED[0m[31m [  5%][0m
[2022-06-15T13:09:36.610Z] integration_tests/src/main/python/parquet_test.py::test_parquet_read_round_trip_binary_as_string[parquet-reader_confs5-read_parquet_sql] [31mFAILED[0m[31m [  5%][0m

```

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #5837.

This updates the parquet integration test which tests the functionality of `spark.sql.parquet.binaryAsString=true` in the plugin to use a static file, so that integration test can run on clustered environments which only have access to HDFS.

Signed-off-by: Navin Kumar <navink@nvidia.com>

Steps to create the binary as string parquet file (in Python):

```python
import random

import sre_yield
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

base_strings = sre_yield.AllStrings("(.|\n){1,30}", flags=0, charset=sre_yield.CHARSET, max_count=(1 << 64)
strings = [base_strings[random.randint(0, (1 << 64))] for i in range(500)]
records = [(i, s.encode(), s) for i, s in enumerate(strings)]
df = pd.DataFrame.from_records(records)
pq.write_table(pa.Table.from_pandas(df), 'binary_as_string.parquet')
```

### CODE REVIEW

**Comment by NVnavkumar** [comment]
build

**Comment by NVnavkumar** [comment]
build

**Review by jlowe — APPROVED** [review]
I'm OK with using a pre-built file to fix the broken nightly build, but shouldn't we be able to create files locally by using the `file:` schema explicitly?  That could be investigated in a followup.

**Comment by NVnavkumar** [comment]
> I'm OK with using a pre-built file to fix the broken nightly build, but shouldn't we be able to create files locally by using the `file:` schema explicitly? That could be investigated in a followup.

The fundamental issue here was that the integration tests broken running on a cluster (YARN). I think it makes sense if we can set up the test environment to make it easier to create files on the shared HDFS that the Spark executors would have access to.

**Pull request merged**
