### PR TITLE
Update Version to 21.12.0-SNAPSHOT [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
Update plugin version and dependency cudfJNI version to 21.12.0-SNAPSHOT

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
databricks CI failed due to https://github.com/NVIDIA/spark-rapids/issues/3611. I will re-trigger after the fix gets merged https://github.com/NVIDIA/spark-rapids/pull/3615

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by zhanga5 — APPROVED** [review]
👍

**Comment by pxLi** [comment]
error out due to cache_test, will try retrigger w/ new build of cudfJNI 21.12.0 (merged commits from branch-21.10 yesterday)

**Comment by pxLi** [comment]
build

**Pull request merged**
