### PR TITLE
Verify DPP over LIKE ANY/ALL expression

### LINKED ISSUE #2031: [FEA] audit [SPARK-34436][SQL] DPP support LIKE ANY/ALL expression
I don't think this will impact us, but we should look at the testing being done and verify that it works on the GPU like we expect it to.  We don't have full support for like yet, but we should spend the time to understand what is happening.

### PR DESCRIPTION
**Pull request by sperlingxx**
Closes #2031

Check DPP over LIKE ANY/ALL working correctly on the GPU. The GPU plan stack is correct, since  the reuse of GPU broadcast occurs as expected. The LikeAny tests are skipped in premerge ci so far, because the feature is added in Spark 3.1.2+. In addition, the dpp tests are reorganized to be conciser.

```
GpuColumnarToRow false
+- GpuProject [key#92, skey#93, value#91]
   +- GpuBroadcastHashJoin [key#92], [key#94], Inner, GpuBuildRight
      :- GpuFileGpuScan orc default.tmp_table_master_488800073_0[value#91,key#92,skey#93] Batched: true, DataFilters: [], Format: ORC, Location: InMemoryFileIndex[file:/home/alfred/workspace/codes/spark-rapids/integration_tests/target/run_dir..., PartitionFilters: [isnotnull(key#92), dynamicpruningexpression(key#92 IN dynamicpruning#105)], PushedFilters: [], ReadSchema: struct<value:int>
      :     +- GpuSubqueryBroadcast dynamicpruning#105, 0, [key#94]
      :        +- GpuBroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, true] as bigint)),false), [id=#1134]
      :           +- GpuProject [key#94]
      :              +- GpuRowToColumnar targetsize(104857600)
      :                 +- *(1) Filter (((((Contains(filter#95, 00) OR Contains(filter#95, 01)) OR Contains(filter#95, 10)) OR Contains(filter#95, 11)) OR likeany(filter#95)) AND isnotnull(key#94))
      :                    +- GpuColumnarToRow false
      :                       +- GpuFileGpuScan orc default.tmp_table_master_488800073_1[key#94,filter#95] Batched: true, DataFilters: [((((Contains(filter#95, 00) OR Contains(filter#95, 01)) OR Contains(filter#95, 10)) OR Contains(..., Format: ORC, Location: InMemoryFileIndex[file:/home/alfred/workspace/codes/spark-rapids/integration_tests/target/run_dir..., PartitionFilters: [], PushedFilters: [IsNotNull(key)], ReadSchema: struct<key:int,filter:string>
      +- ReusedExchange [key#94], GpuBroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, true] as bigint)),false), [id=#1134]
```

Signed-off-by: sperlingxx <lovedreamf@gmail.com>

### CODE REVIEW

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
build

**Comment by sperlingxx** [comment]
Hi @andygrove, can you help to review this PR? Thanks!

**Comment by sperlingxx** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
