### PR TITLE
Update location of dependency reduced pom

### PR DESCRIPTION
**Pull request by tgravescs**
Put the dependency reduced pom under the target directory from review comments.

fixes https://github.com/NVIDIA/spark-rapids/issues/3440

Signed-off-by: Thomas Graves <tgraves@nvidia.com>

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by tgravescs** [comment]
that is very weird, rat is now finding files in target directory, investigating

**Comment by revans2** [comment]
> that is very weird, rat is now finding files in target directory, investigating

From what I have seen rat automatically excludes target directories if there is a pom.xml in the parent directory that is a part of the current build. If it is excluded as a part of the build then rat sees the target directory as fair game.

**Comment by tgravescs** [comment]
will revisit later if needed

**Pull request closed without merging**
