### PR TITLE
Move Support for `RaiseError` to a Shim Excluding Spark 4.0.0 [databricks]

### PR DESCRIPTION
**Pull request by razajafri**
This PR moves the support for RaiseError to a shim because Spark 4.0.0 has changed the way they throw exceptions [here](https://github.com/apache/spark/commit/9109d7037f4) 

The feature to add support for it to Spark 4.0 is tracked by https://github.com/NVIDIA/spark-rapids/issues/10969 issue and #10107

contributes to #10969 
contributes to https://github.com/NVIDIA/spark-rapids/issues/10107

### CODE REVIEW

**Comment by razajafri** [comment]
build

**Comment by mythrocks** [comment]
The change here is easy enough to understand.  But the description in neither this PR nor #10969 links to the change in Apache Spark 4.0 that breaks compatibility.  

Would you mind adding a link to the change, so that the reviewer doesn't have to hunt for the breakage?

**Comment by razajafri** [comment]
Thanks for pointing that out @mythrocks I have updated the description.

**Review by mythrocks — APPROVED** [review]
LGTM!

**Pull request merged**
