### PR TITLE
Add in neverReplaceExec and several rules for it

### LINKED ISSUE #499: [FEA] disable any kind of warnings about ExecutedCommandExec not being on the GPU
We are never going to run anything from `ExecutedCommandExec` on the GPU.  It only does metadata operations.  When the plugin explains what is and isn't on the GPU we should either just not print anything out for these parts of the plan, or we should print out something saying it is supposed to run on the CPU. 

This is also for `AlterNamespaceSetPropertiesExec`, `CreateNamespaceExec`, `AlterTableExec`,  `CreateTableExec`, `DeleteFromTableExec`, `DescribeNamespaceExec`, `DescribeTableExec`, `DropNamespaceExec`, `AtomicReplaceTableExec`, `RefreshTableExec`, `RenameTableExec`, `ReplaceTableExec`, `SetCatalogAndNamespaceExec`, `ShowCurrentNamespaceExec`, `ShowNamespacesExec`, `ShowTablePropertiesExec`, `ShowTablesExec`, and `DropTableExec`

### PR DESCRIPTION
**Pull request by revans2**
This extends the great work done in #647 but fixes an issue there where we were still outputting config documentation for execs we never plan to replace.

I also made adding one of these in simpler and more common.  I then added in rules for all of the other commands we currently don't want to warn about or ever replace.

This fixes #499

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by andygrove — APPROVED** [review]
Thanks, that's much nicer. LGTM.

**Comment by jlowe** [comment]
> fixes an issue there where we were still outputting config documentation for execs we never plan to replace.

Curious, I expected to see some deletes in configs.md as part of this.  Did we miss the configs.md changes from the previous PR somehow?

**Comment by revans2** [comment]
> Curious, I expected to see some deletes in configs.md as part of this. Did we miss the configs.md changes from the previous PR somehow?

Yup if there had been there I would not have approved it, but they showed up afterward for me as a part of another build, so I thought why not fix it and also knock out #499 too while I was at it.

**Comment by jlowe** [comment]
We probably need a CI check for docs being modified during the build (maybe any checked out file being modified?), indicating PR should have included some changes that are missing.  I'll file an issue.

**Pull request merged**
