### PR TITLE
Fix RapidsErrorUtils compile error for recent Spark 3.3.0 changes

### LINKED ISSUE #5133: [BUG] Compile error for Spark330 because of Spark changed the method signature: QueryExecutionErrors.mapKeyNotExistError
**Describe the bug**

mvn clean install -Dbuildver=330 -DskipTests

[INFO] Compiling 267 Scala sources and 29 Java sources to /home/chong/code/2-spark-rapids/sql-plugin/target/spark330/classes ...
[ERROR] [Error] /home/chong/code/2-spark-rapids/sql-plugin/src/main/330+/scala/com/nvidia/spark/rapids/shims/RapidsErrorUtils.scala:33: not enough arguments for method mapKeyNotExistError: (key: Any, isElementAtFunction: Boolean, context: String)NoSuchElementException.
Unspecified value parameter context.
[ERROR] one error found

Spark added a new parameter in `QueryExecutionErrors.mapKeyNotExistError`

**Additional context**
related to https://issues.apache.org/jira/browse/SPARK-38716 which affected 330+

### PR DESCRIPTION
**Pull request by res-life**
Fixes #5133 

Fix RapidsErrorUtils compile error for recent Spark 3.3.0 changes

Signed-off-by: Chong Gao <res_life@163.com>

### CODE REVIEW

**Comment by res-life** [comment]
build

**Comment by res-life** [comment]
@jlowe , please review

This fixes another 330 build issue, and it merged your PR #5124 to pass the compile.
About this issue, Spark added a new parameter `context` in `QueryExecutionErrors.mapKeyNotExistError`.
It makes a better error msg when `ElementAt` and `GetMapValue` occur `not found error`

`context`  is a SQL string with line and position info, like:

```
== SQL(line 1, position 0) ==
element_at(col, 5)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The `context` is generated from `TreeNode.origin.context`,
because of `origin` is thread local variable while CPU processing data, we can't catch it on GPU.
Let's only pass an empty string. This will no effect processing on GPU, only lack above msg when occurs `not found error`

e.g.:

**CPU error info**
```
Caused by: org.apache.spark.SparkNoSuchElementException: Key 5 does not exist. To return NULL instead, use 'try_element_at'. If necessary set spark.sql.ansi.enabled to false to bypass this error.
== SQL(line 1, position 0) ==
element_at(col, 5)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**GPU error info**
```
Caused by: org.apache.spark.SparkNoSuchElementException: Key 5 does not exist. To return NULL instead, use 'try_element_at'. If necessary set spark.sql.ansi.enabled to false to bypass this error.
```

**Comment by jlowe** [comment]
> because of origin is thread local variable while CPU processing data, we can't catch it on GPU.

I don't think this is correct.  IIUC the context is relative to the original SQL query, i.e.: how the current node in the plan maps back to the original SQL query text.  That applies to GPU processing just as much as CPU processing.

The CI failed because Spark added _yet another_ change to VectorizedColumnReader.  I've updated #5124 to fix that along with this RapidsErrorUtils change by passing the origin so the context can be retrieved when running on Spark 3.3+

**Comment by jlowe** [comment]
Superceded by #5124.

**Comment by res-life** [comment]
I tested the latest code, `origin`  is empty.
Still need to investigate in my opinion.

```

spark.conf.set("spark.sql.ansi.enabled",True)

from pyspark.sql.types import *
schema = StructType([StructField("map_col", MapType(ByteType(), ByteType()))])

data = [({1:1},)]
df = spark.createDataFrame(data, schema)
df.show()

# test GPU
df.selectExpr("element_at(map_col, 5)").show()

# test CPU
spark.conf.set("spark.rapids.sql.enabled", False)
df.selectExpr("element_at(map_col, 5)").show()

```

Outputs of GPU and CPU are:
```
# GPU
Caused by: org.apache.spark.SparkNoSuchElementException: Key 5 does not exist. To return NULL instead, use 'try_element_at'. If necessary set spark.sql.ansi.enabled to false to bypass this error.

# CPU
Caused by: org.apache.spark.SparkNoSuchElementException: Key 5 does not exist. To return NULL instead, use 'try_element_at'. If necessary set spark.sql.ansi.enabled to false to bypass this error.
== SQL(line 1, position 0) ==
element_at(map_col, 5)
^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jlowe** [comment]
Agree, seems using the origin is no more helpful than passing an empty string as was done in this PR.  I filed #5152 to investigate.

**Pull request closed without merging**
