### PR TITLE
Bump up dep version to 23.08.0-SNAPSHOT [databricks]

### LINKED ISSUE #8358: [FEA] Bump up JNI, private, cudf-py versions to 23.08 in branch-23.08
**Is your feature request related to a problem? Please describe.**

File this ticket to remind use to bump up dependencies versions to 23.08 when available

### PR DESCRIPTION
**Pull request by pxLi**
fix #8358 

bump up dep versions to 23.08.0-SNAPSHOT

### CODE REVIEW

**Comment by pxLi** [comment]
new artifact is under compiling, I will re-trigger CI  later

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
failed due to https://github.com/NVIDIA/spark-rapids/issues/8409

**Review by tgravescs — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Pull request merged**
