### PR TITLE
Upgrade to UCX 1.16.0

### PR DESCRIPTION
**Pull request by abellina**
We have seen a segfault in CI as soon as we moved to UCX 1.16.

I'd like to get this patch up and try to run with this. In the past, the memtype cache is recommended because it causes more issues than benefits (e.g. misdetects GPU/CPU memory type). We don't need this cache because we are registering eagerly via bounce buffers, so it should be just always disabled, and my guess is that UCX 1.16 tweaked access to this.

I'll follow up with UCX team. If we don't get some stable runs here, we may add logging or consider reverting.

Might address: https://github.com/NVIDIA/spark-rapids/issues/10291

### CODE REVIEW

**Comment by abellina** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by abellina** [comment]
Since the UCX 1.16 PR is definitely blocking others, rather than experiment now, @sameerz proposed reverting and trying this again Monday. We hope we have more info from the UCX team and we could run UCX in debug/logging mode to get good info. As such, I'll let this run as it's already going, but I'll PR a revert.

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
build

**Comment by sameerz** [comment]
There is a UCX [1.16.0-rc5](https://github.com/openucx/ucx/releases/tag/v1.16.0-rc5) available.  

Can we target this PR to 24.06?

**Comment by abellina** [comment]
> There is a UCX [1.16.0-rc5](https://github.com/openucx/ucx/releases/tag/v1.16.0-rc5) available.
> 
> Can we target this PR to 24.06?

Thanks @sameerz, targeting to 24.06

**Comment by sameerz** [comment]
UCX 1.16.0 is now available: https://github.com/openucx/ucx/releases/tag/v1.16.0 .  Let's upgrade and test.

**Comment by abellina** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
