### PR TITLE
Enable line/string anchors in choice

### LINKED ISSUE #6882: [FEA] Regular expressions - support line anchors in choice
**Is your feature request related to a problem? Please describe.**
I wish the RAPIDS Accelerator for Apache Spark supported line anchors in Regular Expression choice (`|`) expressions. 

**Describe the solution you'd like**

```scala
scala> spark.conf.set("spark.rapids.sql.enabled", "false")
scala> val df = spark.range(0, 1000).selectExpr("CAST(id AS STRING) as id")

scala> df.createOrReplaceTempView("table")

scala> spark.sql("select concat(a.id, '/', b.id, '\n') as id from table as a right join  table as b on a.id = b.id").write.mode("overwrite").parquet("/tmp/test-re-data-20221021")

scala> spark.conf.set("spark.rapids.sql.enabled", "true")

scala> spark.read.parquet("/tmp/test-re-data-20221021").selectExpr("regexp_extract(id, '\\\\d+(6$|7$)', 1)").collect()
22/10/21 17:40:44 WARN GpuOverrides:
!Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced
  @Expression <Alias> regexp_extract(id#103, \d+(6$|7$), 1) AS regexp_extract(id, \d+(6$|7$), 1)#105 could run on GPU
    !Expression <RegExpExtract> regexp_extract(id#103, \d+(6$|7$), 1) cannot run on GPU because cuDF does not support terms ending with line anchors on one side of a choice near index 4; regex group count is 0, but the specified group index is 1
      @Expression <AttributeReference> id#103 could run on GPU
      @Expression <Literal> \d+(6$|7$) could run on GPU
      @Expression <Literal> 1 could run on GPU

res19: Array[org.apache.spark.sql.Row] = Array([], [], [], [6], [7], [], [], [], [6], [7], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [], [6], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [7], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [6], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [7], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [6], [7], [], [], [], [], [], [], [], [6], [7], [], [], [], [], [6], [7], [], ...
```

I would like the RegExpExtract to run on the GPU.

### PR DESCRIPTION
**Pull request by NVnavkumar**
Fixes #6882.

This enables support for line and string anchors in regular expression choice syntax (e.g. `a$|^b`). This cleans up the unit tests for support this new feature, and adds an integration test for regular expression choice.  

In this case, many of the checks were removed, and the functionality had started working. This most likely became possible due to the work done in https://github.com/rapidsai/cudf/pull/11654 to fix choice and https://github.com/rapidsai/cudf/pull/12181 to fix EOL anchors. Issue #7585 remains unresolved.

### CODE REVIEW

**Comment by NVnavkumar** [comment]
build

**Review by revans2 — COMMENTED** [review]
The code and the tests look good to me, but I am a little confused because it looks like all you did was remove the checks. There is no new transpiling to make it work. Did the existing rules just work out of the box?

**Comment by NVnavkumar** [comment]
> > The code and the tests look good to me, but I am a little confused because it looks like all you did was remove the checks. There is no new transpiling to make it work. Did the existing rules just work out of the box?
> 
> It is possible that something changed in cuDF since these tests and checks were added, but would be good to get a link to the relevant cuDF PRs if possible.

Updated the description with a reference to the cudf PR that might have fixed this.

**Comment by NVnavkumar** [comment]
Added a couple of more items to the unit test to ensure we are capturing items related to `\r` as well as `\n`

**Comment by NVnavkumar** [comment]
build

**Review by revans2 — APPROVED** [review]
But I am not regular expression expert so I really would like more eyes on this than just me

**Review by andygrove — APPROVED** [review]
LGTM

**Pull request merged**
