### PR TITLE
Update JNI version to released 22.10.0 [databricks]

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

I will trigger the CI when released JNI artifact is available in maven central

### CODE REVIEW

**Comment by pxLi** [comment]
convert to draft to wait for JNI 22.10.0 release

**Review by jlowe — APPROVED** [review]

**Review by NvTimLiu — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
seems github has some inconsistent issue a few hours ago, github action cannot update my check status of this PR.

let me close and re-file a new one





[14:47](https://nvidia.slack.com/archives/C021GR1KTDY/p1665730030373429)
let me close and re-file a new one

**Comment by pxLi** [comment]
And we lost status updates of ACL check and blackduck scan, the following premerge test run status updates should be fine

T urns out this should be related to NVIDIA org remove the write permission of GITHUB_TOKEN. We have asked them to help re-enable the permission, not sure if they would help or not :derp

**Pull request closed without merging**
