### PR TITLE
[window] Disable GPU for COUNT(exp) queries

### PR DESCRIPTION
**Pull request by mythrocks**
Mitigates #218.

GpuWindowExec currently counts null-rows when running `COUNT(col)`
(or generally `COUNT(expr)`) window queries, owing to a bug in CUDF/Java.
Left unchecked, this will produce incorrect results for said queries.

This commit disables GPU acceleration for `COUNT(expr)` queries, while
retaining support for `COUNT(1)` and `COUNT(*)`.

This may be reverted once we have a fix in CUDF/Java.

Please note that there is already an XFAIL test that checks this condition, in [window_function_test.py](https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/integration_tests/src/main/python/window_function_test.py#L114)

Signed-off-by: Mithun RK <mythrocks@gmail.com>

### CODE REVIEW

**Review by kuhushukla — APPROVED** [review]
Can we link the cudf bug issue to this PR? Approving as changes look good to me.

**Comment by mythrocks** [comment]
> Can we link the cudf bug issue to this PR? Approving as changes look good to me.

Linking the bug will close it when this PR is merged. I'd like to keep it open, and actually fix it in `0.3`, after pushing a fix to `cudf/java`.

**Comment by kuhushukla** [comment]
Oh, I didn't know that cudf issues would close automatically as well if a PR in this repo went in! Thought it was only the rapids plugin issues. I stand corrected.

**Comment by mythrocks** [comment]
> Oh, I didn't know that cudf issues would close automatically as well if a PR in this repo went in! Thought it was only the rapids plugin issues. I stand corrected.

D'oh! Wait, maybe not. I'll raise the CUDF bug and leave a link here.

**Comment by mythrocks** [comment]
> Can we link the cudf bug issue to this PR? Approving as changes look good to me.

rapidsai/cudf#6156 seems to be the cause. The `libcudf` implementation seems fine. The `COUNT` operation is lost in translation, in the Java layer. #218 has been updated to reflect this.

**Comment by revans2** [comment]
For it to be closed you have to say something like fixes hash-bug-number or closes hash-bug-number

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
build

**Comment by mythrocks** [comment]
> For it to be closed you have to say something like fixes hash-bug-number or closes hash-bug-number

The text under "Linked issues" on the right pane seems to suggest that the issues listed there "may" be closed. 

In any case, I can't seem to manually link CUDF issues or indeed anything outside of `spark-rapids` there. :shrug: Oh, well.

**Comment by mythrocks** [comment]
Thanks for the reviews, all.

**Pull request merged**
