### PR TITLE
Fix multiple problems reported and improve error handling

### PR DESCRIPTION
**Pull request by tgravescs**
fixes https://github.com/NVIDIA/spark-rapids/issues/2659 
uses collect_set instead of collect_list to remove duplicates in potential problems

fixes https://github.com/NVIDIA/spark-rapids/issues/2652
Add in better checks before calling into sql and remove system.exit from the application information class that would cause exits vs just skipping applications.  I tried to add in useful logging about skipping logs and applications that are bad.  
I was trying to make as minimal impacting changes so the checks are a bit of brute force for now.

Added in tests and cleaned up some event logs.

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by sameerz** [comment]
This is targeted to branch-21.08.

**Comment by pxLi** [comment]
build

**Comment by tgravescs** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
pending resource. re-triggered

**Review by nartal1 — APPROVED** [review]
I agree that checks can be improved. Can be taken up  later in next iteration. LGTM

**Comment by pxLi** [comment]
build

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
Please wait to trigger build

**Comment by tgravescs** [comment]
build

**Comment by pxLi** [comment]
build

**Review by nartal1 — APPROVED** [review]

**Pull request merged**
