### PR TITLE
Fix ORC reader for `CHAR(N)` columns written from Hive

### LINKED ISSUE #8294: [BUG] ORC `CHAR(N)` columns written from Hive unreadable with RAPIDS plugin
When `CHAR(N)` columns (i.e. fixed-length strings) are written to ORC files via Apache Hive, those columns are unreadable through the RAPIDS Plugin for Spark.
Reading such a column produces the following error/stacktrace:
```
Caused by: org.apache.spark.sql.execution.QueryExecutionException: GPU ORC does not support type conversion from file type char(2) (1) to reader type string (1)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.checkTypeCompatibility(GpuOrcScan.scala:1536)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.$anonfun$checkTypeCompatibility$4(GpuOrcScan.scala:1506)
  at scala.Option.foreach(Option.scala:407)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.$anonfun$checkTypeCompatibility$3(GpuOrcScan.scala:1504)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.$anonfun$checkTypeCompatibility$3$adapted(GpuOrcScan.scala:1503)  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.checkTypeCompatibility(GpuOrcScan.scala:1503)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.checkSchemaCompatibility(GpuOrcScan.scala:1462)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.getOrcPartitionReaderContext(GpuOrcScan.scala:1262)
...
```

## Repro
The simplest repro is as follows: 

1. Write a `CHAR(2)` column in Apache Hive:
```sql
-- In HiveSQL.
CREATE TABLE borked(data CHAR(2)) STORED AS ORCFILE LOCATON "file:///tmp/borked";
INSERT INTO borked VALUES ("a1"), ("b2");
```
2. Read it back in Spark, with the plugin enabled:
```scala
spark.read.orc("/tmp/borked").show
```

An [example file](https://github.com/NVIDIA/spark-rapids/files/11481914/hive.00000_0.zip) that reproduces the problem is attached.

Bug-id: 4114855

### PR DESCRIPTION
**Pull request by mythrocks**
Fixes #8294.

This commit fixes reads of fixed-length strings when written through Apache Hive.

Before this fix, when `CHAR(N)` columns (i.e. fixed-length strings) were written to ORC files via Apache Hive, those columns were unreadable through the RAPIDS Plugin for Spark. Reading such a column produces the following error/stacktrace:
```
Caused by: org.apache.spark.sql.execution.QueryExecutionException: GPU ORC does not support type conversion from file type char(2) (1) to reader type string (1)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.checkTypeCompatibility(GpuOrcScan.scala:1536)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.$anonfun$checkTypeCompatibility$4(GpuOrcScan.scala:1506)
  at scala.Option.foreach(Option.scala:407)
  at com.nvidia.spark.rapids.GpuOrcFileFilterHandler$GpuOrcPartitionReaderUtils.$anonfun$checkTypeCompatibility$3(GpuOrcScan.scala:1504)
...
```

The same data, when written through Spark, remains readable from the plugin.

This arises from a difference in serialization between Apache Hive and Apache Spark. When a `CHAR(2)` column is written through Hive, the type of the column is preserved:
```
Processing data file file:/tmp/hive.00000_0.orc [length: 212]
Structure for file:/tmp/hive.00000_0.orc
File Version: 0.12 with ORC_517
Rows: 1
Compression: ZLIB
Compression size: 262144
Type: struct<id:char(2)>
``` 

When Spark writes the column, its type is changed to `STRING`:
```
Processing data file file:/tmp/part-00000-ecbe264b-fa68-4d26-8c56-ba45602263b7-c000.snappy.orc [length: 200]
Structure for file:/tmp/part-00000-ecbe264b-fa68-4d26-8c56-ba45602263b7-c000.snappy.orc
File Version: 0.12 with ORIGINAL
Rows: 1
Compression: SNAPPY
Compression size: 262144
Type: struct<id:string>
```

This fix adds support to cast `CHAR(N)` to `STRING` in the ORC Reader, alongside `VARCHAR`.

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
My only comment is that it might be nice to check in a small test file and add an integration test so we don't regress in this.

**Comment by mythrocks** [comment]
I think we have a problem here with strings that are shorter than N. I'm trying isolate that behaviour and understand it.

**Comment by mythrocks** [comment]
Ok, I can confirm that there's a discrepancy between the behaviour of Apache Hive/Spark on one side, and CUDF/Plugin on the other.
Consider the following data written via Apache Hive:
```sql
-- Insert as CHAR(3).
CREATE TABLE foobar (foo CHAR(3)) STORED AS ORCFILE LOCATION 'file:///tmp/foobar';
INSERT INTO foobar VALUES (""), ("0"), ("1 "), (" 1"), ("22"), ("4444");

-- Read as STRING.
CREATE EXTERNAL TABLE foobar_as_string (foo STRING) STORED AS ORCFILE LOCATION 'file:///tmp/foobar';
```
With Hive or Spark, reading data from either table above produces the different results results from CUDF or the RAPIDS plugin:
```sql
SELECT foo, CONCAT('"', foo, '"'), LENGTH(foo) FROM foobar;
```
From Spark/Hive: (Trailing spaces are removed, even if the data had it during insertion.)
```
foo     quoted  len
        ""      0
0       "0"     1
1       "1"     1
 1      " 1"    2
22      "22"    2
444     "444"   3
Time taken: 0.074 seconds, Fetched: 6 row(s)
```
From RAPIDS: Fixed length strings, as the ORC spec would dictate.
```
        "   "   3
0       "0  "   3
1       "1  "   3
 1      " 1 "   3
22      "22 "   3
444     "444"   3
```
This will need post-processing, before it matches what Apache Spark produces.

**Review by revans2 — APPROVED** [review]

**Comment by mythrocks** [comment]
Build

**Pull request merged**
