### PR TITLE
Cherry-pick: Fix a memory leak in json tuple (#10360)

### LINKED ISSUE #10404: [BUG] GpuJsonTuple memory leak
```bash
SPARK_HOME=~/dist/spark-3.1.1-bin-hadoop3.2  \
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
TEST_PARALLEL=0 \
COVERAGE_SUBMIT_FLAGS="-Dai.rapids.refcount.debug=true" \
TZ= ./integration_tests/run_pyspark_from_build.sh -k test_json_tuple_select_non_generator_col -s |& tee build.log
```
which is already responsible for 20 Leaked buffers . It reproduces on my laptop and desktop GPU, so pretty sure it's on the CI log and would have been caught by #6947 had it already been implemented.

_Originally posted by @gerashegalov in https://github.com/NVIDIA/spark-rapids/issues/9974#issuecomment-1932721058_

### PR DESCRIPTION
**Pull request by gerashegalov**
Fixes #10404 

Signed-off-by: Robert (Bobby) Evans <bobby@apache.org>
(cherry picked from commit 73b3279330f16f7e1af664e1b7acf5f8762359fb)

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by abellina** [comment]
Thank you  @gerashegalov and @revans2

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
First CI run failed due to #10227, Second CI run timed out on Scala2.13

**Comment by gerashegalov** [comment]
build

**Pull request merged**
