### PR TITLE
Xfail struct and array order by tests on Dataproc

### LINKED ISSUE #1541: [BUG] Tests fail in integration in distributed mode after allowing nested types through in sort and shuffle
**Describe the bug**
``` =================================== FAILURES ===================================
05:33:42  _______________________ test_orderby_array[Array(Byte)] ________________________
05:33:42  
05:33:42  data_gen = Array(Byte)
05:33:42  
05:33:42      @pytest.mark.parametrize('data_gen', single_level_array_gens, ids=idfn)
05:33:42      def test_orderby_array(data_gen):
05:33:42  >       assert_gpu_and_cpu_are_equal_sql(
05:33:42              lambda spark : unary_op_df(spark, data_gen),
05:33:42              'array_table',
05:33:42              'select array_table.a, array_table.a[0] as first_val from array_table order by first_val',
05:33:42              conf=allow_negative_scale_of_decimal_conf)
05:33:42  
05:33:42  src/main/python/array_test.py:60: 
05:33:42  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
05:33:42  src/main/python/asserts.py:362: in assert_gpu_and_cpu_are_equal_sql
05:33:42      assert_gpu_and_cpu_are_equal_collect(do_it_all, conf)
05:33:42  src/main/python/asserts.py:336: in assert_gpu_and_cpu_are_equal_collect
05:33:42      _assert_gpu_and_cpu_are_equal(func, True, conf=conf)
05:33:42  src/main/python/asserts.py:328: in _assert_gpu_and_cpu_are_equal
05:33:42      assert_equal(from_cpu, from_gpu)
05:33:42  src/main/python/asserts.py:90: in assert_equal
05:33:42      _assert_equal(cpu, gpu, float_check=get_float_check(), path=[])
05:33:42  src/main/python/asserts.py:38: in _assert_equal
05:33:42      _assert_equal(cpu[index], gpu[index], float_check, path + [index])
05:33:42  src/main/python/asserts.py:31: in _assert_equal
05:33:42      _assert_equal(cpu[field], gpu[field], float_check, path + [field])
05:33:42  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
05:33:42  
05:33:42  cpu = [], gpu = [None, 5, -121, 76, -128, 42]
05:33:42  float_check = <function get_float_check.<locals>.<lambda> at 0x7f8e57a2df70>
05:33:42  path = [0, 'a']
05:33:42  
05:33:42      def _assert_equal(cpu, gpu, float_check, path):
05:33:42          t = type(cpu)
05:33:42          if (t is Row):
05:33:42              assert len(cpu) == len(gpu), "CPU and GPU row have different lengths at {}".format(path)
05:33:42              if hasattr(cpu, "__fields__") and hasattr(gpu, "__fields__"):
05:33:42                  for field in cpu.__fields__:
05:33:42                      _assert_equal(cpu[field], gpu[field], float_check, path + [field])
05:33:42              else:
05:33:42                  for index in range(len(cpu)):
05:33:42                      _assert_equal(cpu[index], gpu[index], float_check, path + [index])
05:33:42          elif (t is list):
05:33:42  >           assert len(cpu) == len(gpu), "CPU and GPU list have different lengths at {}".format(path)
05:33:42  E           AssertionError: CPU and GPU list have different lengths at [0, 'a']
05:33:42  
05:33:42  src/main/python/asserts.py:36: AssertionError
05:33:42  ----------------------------- Captured stdout call -----------------------------
05:33:42  ### CPU RUN ###
05:33:42  ### GPU RUN ###
05:33:42  ### COLLECT: GPU TOOK 0.8999466896057129 CPU TOOK 1.1249110698699951 ###
05:33:42  _______________________ test_orderby_array[Array(Short)] _______________________
05:33:42  
05:33:42  data_gen = Array(Short)
05:33:42  
05:33:42      @pytest.mark.parametrize('data_gen', single_level_array_gens, ids=idfn)
05:33:42      def test_orderby_array(data_gen):
05:33:42  >       assert_gpu_and_cpu_are_equal_sql(
05:33:42              lambda spark : unary_op_df(spark, data_gen),
05:33:42              'array_table',
05:33:42              'select array_table.a, array_table.a[0] as first_val from array_table order by first_val',
05:33:42              conf=allow_negative_scale_of_decimal_conf)
05:33:42  
05:33:42  src/main/python/array_test.py:60: 
05:33:42  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
05:33:42  src/main/python/asserts.py:362: in assert_gpu_and_cpu_are_equal_sql
05:33:42      assert_gpu_and_cpu_are_equal_collect(do_it_all, conf)
05:33:42  src/main/python/asserts.py:336: in assert_gpu_and_cpu_are_equal_collect
05:33:42      _assert_gpu_and_cpu_are_equal(func, True, conf=conf)
05:33:42  src/main/python/asserts.py:328: in _assert_gpu_and_cpu_are_equal
05:33:42      assert_equal(from_cpu, from_gpu)
05:33:42  src/main/python/asserts.py:90: in assert_equal
05:33:42      _assert_equal(cpu, gpu, float_check=get_float_check(), path=[])
05:33:42  src/main/python/asserts.py:38: in _assert_equal
05:33:42      _assert_equal(cpu[index], gpu[index], float_check, path + [index])
05:33:42  src/main/python/asserts.py:31: in _assert_equal
05:33:42      _assert_equal(cpu[field], gpu[field], float_check, path + [field])
05:33:42  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
05:33:42  
05:33:42  cpu = [None, -20249, -359, -23148], gpu = []
05:33:42  float_check = <function get_float_check.<locals>.<lambda> at 0x7f8e57393670>
05:33:42  path = [108, 'a']
05:33:42  
05:33:42      def _assert_equal(cpu, gpu, float_check, path):
05:33:42          t = type(cpu)
```

### PR DESCRIPTION
**Pull request by kuhushukla**
Fixes #1541
to the point that the tests do not fail. I am triaging the actual issue in the mean time but this should help with the builds.

### CODE REVIEW

**Review by tgravescs — APPROVED** [review]
I assume you will work with Tim to enable for our dataproc builds to pass in the --runtime_env dataproc

**Comment by kuhushukla** [comment]
> I assume you will work with Tim to enable for our dataproc builds to pass in the --runtime_env dataproc
> 
Yes! :)

**Comment by kuhushukla** [comment]
build

**Comment by kuhushukla** [comment]
@NvTimLiu can we add the runtime env set to dataproc for the build? Thanks!

**Pull request merged**
