### PR TITLE
Fix verify build after integration tests are run

### LINKED ISSUE #656: [BUG] integration tests produce hive metadata files
When I manually run the integration tests I end up with some hive metastore columns like

derby.log and metastore_db

These end up causing issues with my next run because rat complains about them and they also are leaked.

We should at least white list them in rat, but ideally move them, if possible, to the target directory.

### PR DESCRIPTION
**Pull request by revans2**
Not perfect but tries to deal with fixing some issues with hive metastore files in the integration tests.

This fixes #656

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by jlowe** [comment]
Removing these directories would be a nasty surprised to anyone who ran spark from the top of the plugin repo.  Granted may not be a common thing, but still destruction of data the tests didn't necessarily create.

It would be preferable to have the integration tests run from a directory somewhere underneath `integration_tests/target/` so Maven's `clean` will clean it up by default and the user doesn't expect things there to be unaffected during builds.  Would it be better to update `run_pyspark_from_build.sh` to do something like that?

**Review by kuhushukla — DISMISSED** [review]

**Comment by revans2** [comment]
> It would be preferable to have the integration tests run from a directory somewhere underneath integration_tests/target/

This script only works being run from the main test directory. So having someone try to run this script from another directory already will run into issues with not being able to find dependencies. Which because of the `set -x` should cause the script to fail when `spark-submit` fails so the files would not be removed.  

I can try to play around with some things in pytest, but generally pytest assumes that you are running from the base directory with how it tries to play games with importing things.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe the tests now run in a sub-directory of target by default.

**Review by jlowe — APPROVED** [review]

**Review by kuhushukla — APPROVED** [review]

**Pull request merged**
