### PR TITLE
Pre-merge CI to support Databricks 12.2 [databricks]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Depends on  https://github.com/NVIDIA/spark-rapids/pull/8282

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Review by jlowe — DISMISSED** [review]

**Comment by sameerz** [comment]
We will retarget Databricks 12.2 for 23.08 to ensure we address test case failures on Delta Lake.

**Comment by andygrove** [comment]
https://github.com/NVIDIA/spark-rapids/pull/8282 has now been merged into 23.08

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
retarget to 23.08

**Comment by pxLi** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
