### PR TITLE
Add in support for sorting arrays with structs in sort_array

### PR DESCRIPTION
**Pull request by revans2**
This is a part of #4900 but is only a small part of it. CUDF already supported everything so it was only a few more mins to implement this patch with proper tests than it was to verify that it was working manually.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Review by jlowe — COMMENTED** [review]
Need to generate the updated supported ops documentation, but otherwise lgtm.

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
@jlowe I updated the docs. I forgot that buildall does not do that for us anymore, and I have to manually build with the default version to make it happen

**Comment by gerashegalov** [comment]
>  forgot that buildall does not do that for us anymore, and I have to manually build with the default version to make it happen

we could change CI to push the result of `antrun:run@update_config_docs` to the PR branch instead of having it complain that the developer forgot to run it for the default version

**Review by jlowe — APPROVED** [review]

**Pull request merged**
