### PR TITLE
[Doc] Update the getting started guide for databricks: Change from 8.2 to 9.1 runtime [skip ci]

### PR DESCRIPTION
**Pull request by viadea**
Update the getting started guide for databricks: Change from 8.2 to 9.1 runtime.

### CODE REVIEW

**Review by sameerz — CHANGES_REQUESTED** [review]
Please update the supported versions in https://github.com/NVIDIA/spark-rapids/blob/branch-21.12/docs/FAQ.md#which-distributions-are-supported

**Comment by viadea** [comment]
> Please update the supported versions in https://github.com/NVIDIA/spark-rapids/blob/branch-21.12/docs/FAQ.md#which-distributions-are-supported

Fixed.thx

**Review by zhanga5 — APPROVED** [review]
nice! 👍

**Comment by pxLi** [comment]
since we added spark312db(9.1 runtime), just curious are we going to remove the spark311db(8.2 runtime) shim layer? also, do we plan to update all the previous docs to remove the deprecated 8.2 runtime support?

**Comment by jlowe** [comment]
> are we going to remove the spark311db(8.2 runtime) shim layer?

Given the runtime is no longer available when creating a new Databricks cluster, I don't see any reason to keep it around.  I filed #4015 to track removing the shim.

**Review by sameerz — APPROVED** [review]

**Comment by sameerz** [comment]
build

**Review by jlowe — APPROVED** [review]

**Pull request merged**
