### PR TITLE
[WIP] - Databricks 11.3 Runtime - compile only

### LINKED ISSUE #6879: [FEA] Support Databricks 11.3 ML LTS
**Is your feature request related to a problem? Please describe.**
Add support for Databricks 11.3 ML LTS in the 22.12 release

**Describe the solution you'd like**
Create a shim layer for Databricks 11.3 ML LTS so that users of the plugin can run on Databricks.  

**Describe alternatives you've considered**

**Additional context**
https://docs.databricks.com/release-notes/runtime/11.3ml.html

https://github.com/NVIDIA/spark-rapids/issues/6879#tasklist-block-796a6486-d728-4e3c-9bb1-e222ba112966

### PR DESCRIPTION
**Pull request by nartal1**
Fixes #6879

This is a WIP PR to build(compile) Databricks-11.3 build. Many hacks are done to get it to compile. It needs to be cleaned before it can be reviewed. Created the PR so that others can pull the branch to build/test/contribute to the PR.

### CODE REVIEW

**Comment by amahussein** [comment]
Report of integration tests based on the last commit 8b3fdc1

```
5646 failed, 6701 passed, 267 skipped, 925 xfailed, 16 xpassed, 3300 errors in 5284.48s (1:28:04)
```

[report_8b3fdc1.log.gz](https://github.com/NVIDIA/spark-rapids/files/10036854/report_8b3fdc1.log.gz)

I will work on jenkins/test.sh to see if it needs fixes to get the correct environment settings. 

CC: @sameerz @nartal1 @gerashegalov @razajafri

**Comment by pxLi** [comment]
> Report of integration tests based on the last commit [8b3fdc1](https://github.com/NVIDIA/spark-rapids/commit/8b3fdc135a3db8f62e79bfa3fd45dfef36ee5483)
> 
> ```
> 5646 failed, 6701 passed, 267 skipped, 925 xfailed, 16 xpassed, 3300 errors in 5284.48s (1:28:04)
> ```
> 
> [report_8b3fdc1.log.gz](https://github.com/NVIDIA/spark-rapids/files/10036854/report_8b3fdc1.log.gz)
> 
> I will work on jenkins/test.sh to see if it needs fixes to get the correct environment settings.
> 
> CC: @sameerz @nartal1 @gerashegalov @razajafri

we have a ticket for this https://github.com/NVIDIA/spark-rapids/issues/7092

**Comment by amahussein** [comment]
With changes done to jenkins/databricks/test.sh as in [db113_testscript_fix-branch](https://github.com/amahussein/spark-rapids/blob/db113_testscript_fix/jenkins/databricks/test.sh)

```
1275 failed, 13525 passed, 279 skipped, 495 xfailed, 206 xpassed, 32 warnings in 10956.36s (3:02:36)
```

[report_2022-11-18-16-00-summary.log.gz](https://github.com/NVIDIA/spark-rapids/files/10045255/report_2022-11-18-16-00-summary.log.gz)

**Comment by nartal1** [comment]
Closing this in favor of https://github.com/NVIDIA/spark-rapids/pull/7152 instead.

**Pull request closed without merging**
