### PR TITLE
Simplify Transpilation of $ with Extended Line Separator Support in cuDF Regex

### LINKED ISSUE #11554: [FEA] Reimplement $ transpilation using cuDF new line terminator support
**Is your feature request related to a problem? Please describe.**

cuDF added support for multiple new-line characters in https://github.com/rapidsai/cudf/pull/15961, which allows support for the different Java unicode line terminator characters. This requires passing a flag to the cuDF regex APIs to enable this mode, and updating the transpiler to a more simplified implementation of $ (which only needs to add support for the `\r\n` combination in addition to the individual characters already supported by cuDF:

* `\n` line-feed (already supported)
* `\r` carriage-return
* `\u0085` next line (NEL)
* `\u2028` line separator
* `\u2029` paragraph separator

**Additional context**

This might fix failing tests here:
* https://github.com/NVIDIA/spark-rapids/issues/10641
* https://github.com/NVIDIA/spark-rapids/issues/9731

Also, can look into a possible solution for:
* https://github.com/NVIDIA/spark-rapids/issues/10764

### PR DESCRIPTION
**Pull request by SurajAralihalli**
Resolves #11554, #7585

In cuDF, support for multiple newline characters was expanded from NEW_LINE (`\n`) to include the following:

* NEXT_LINE (`\u0085`)
* LINE_SEPARATOR (`\u2028`)
* PARAGRAPH_SEPARATOR (`\u2029`)
* CARRIAGE_RETURN (`\r`)
* NEW_LINE (`\n`)

PR [#17139](https://github.com/rapidsai/cudf/pull/17139) introduced this change to cuDf JNI with `RegexFlag::EXT_LINE`. This PR simplifies the transpilation of `$` by changing the pattern from `(?:\r|\u0085|\u2028|\u2029|\r\n)?$` to the simpler `(?:\r\n)?$` and updates all functions to use `RegexFlag::EXT_LINE` wherever this transpilation occurs.

This PR also drops support for `$\z` because `\z` is not supported by cuDf. Alternatively, we could transpile `$\z `to `$(?![\r\n\u0085\u2028\u2029])`. However, cuDf doesn't support negative look ahead.

This PR also drops support for regex patterns with end-of-line anchors `$` and `\Z` when followed by any escape sequences like `\W`, `\B`,`\b` etc, as they produce different results on CPU and GPU.

### CODE REVIEW

**Comment by NVnavkumar** [comment]
Can we confirm some of the behavior described in [compatibility.md](https://github.com/NVIDIA/spark-rapids/blob/branch-24.12/docs/compatibility.md) and update accordingly?

**Comment by SurajAralihalli** [comment]
> Can we confirm some of the behavior described in [compatibility.md](https://github.com/NVIDIA/spark-rapids/blob/branch-24.12/docs/compatibility.md) and update accordingly?

Thank you for pointing it, I found another issue that is resolved by this PR. I've updated the guide and tests to reflect this. 
As part of the process we also reviewed the feasibility of solving https://github.com/NVIDIA/spark-rapids/issues/10641 and https://github.com/NVIDIA/spark-rapids/issues/10764 in this PR. Updated these issues with the status.

**Comment by SurajAralihalli** [comment]
\build

**Comment by SurajAralihalli** [comment]
build

**Comment by SurajAralihalli** [comment]
Build

**Review by NVnavkumar — APPROVED** [review]
LGTM. pending pre-merge.

**Pull request merged**
