### PR TITLE
Bump up GPU reserve memory to 640MB

### PR DESCRIPTION
**Pull request by rongou**
As some queries involving regex kernels need more non-RMM GPU memory.

Signed-off-by: Rong Ou <rong.ou@gmail.com>

### CODE REVIEW

**Comment by rongou** [comment]
build

**Review by jlowe — COMMENTED** [review]
This should target branch-21.12.

**Comment by abellina** [comment]
looks good to me other than the target branch.

**Comment by rongou** [comment]
build

**Review by abellina — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Pull request merged**
