### PR TITLE
Merge branch-24.12 into main 

### PR DESCRIPTION
**Pull request by nvauto**
Change version to 24.12.0

Note: merge this PR with **Create a merge commit to merge**

### CODE REVIEW

**Review by jlowe — APPROVED** [review]

**Review by abellina — APPROVED** [review]
No diffs with 24.12. SNAPSHOT changes look good to me.

**Comment by YanxuanLiu** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Comment by YanxuanLiu** [comment]
build

**Comment by YanxuanLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Pull request merged**
