### PR TITLE
Remove support for databricks 7.0 runtime - shim spark300db

### PR DESCRIPTION
**Pull request by tgravescs**
For 0.3.0 we are only going to support databricks 7.3 runtime. Remove the shim layer for the 7.0 runtime which is spark300db.

fixes:  https://github.com/NVIDIA/spark-rapids/issues/1144

Note we have an internal PR to remove the databricks build for the 7.0 runtime

### CODE REVIEW

**Comment by tgravescs** [comment]
build

**Review by revans2 — DISMISSED** [review]

**Comment by tgravescs** [comment]
build

**Comment by tgravescs** [comment]
I'll rebase

**Comment by tgravescs** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by tgravescs** [comment]
test failures are fixed by my other pr: https://github.com/NVIDIA/spark-rapids/pull/1147

17:13:49  FAILED ../../src/main/python/orc_write_test.py::test_buckets_write_fallback[ALLOW_NON_GPU(DataWritingCommandExec)]
17:13:49  FAILED ../../src/main/python/parquet_write_test.py::test_buckets_write_fallback[ALLOW_NON_GPU(DataWritingCommandExec)]

**Comment by tgravescs** [comment]
upmerged to pull test fixes and rebuilding.

**Comment by tgravescs** [comment]
build

**Pull request merged**
