### PR TITLE
Fork jvm for maven-source-plugin

### PR DESCRIPTION
**Pull request by gerashegalov**
Maybe addresses #11225

I was not able to reproduce GCLocker issue using the CI docker. However, since the issue consistently affected maven-source-plugin running inside the parent Maven JVM it may be mitigated by starting it in a fresh JVM

Signed-off-by: Gera Shegalov <gera@apache.org>

### CODE REVIEW

**Comment by gerashegalov** [comment]
build

**Comment by gerashegalov** [comment]
build

**Review by jlowe — APPROVED** [review]
I'm fine with a workaround to unblock the nightly pipelines, but I feel like we're patching symptoms rather than getting at root causes.  We've never seen this issue before moving to JDK17 in the build, so that implies JDK17 is much more likely to OOM than JDK8 with the same heap settings.

**Comment by gerashegalov** [comment]
This PR explicitly not closing #11225, especially since I cannot reproduce the issue to test it. Whether we decide to experiment with MAVEN_OPTS or this PR's method it will take monitoring the CI to check whether the experiment works.

**Pull request merged**
