### PR TITLE
Revert "Support barrier mode for mapInPandas/mapInArrow (#10343)"

### LINKED ISSUE #10359: [BUG] Build failure on Databricks nightly run with `GpuMapInPandasExecMeta`
From the [Databricks build log](https://prod.blsm.nvidia.com/sw-gpu-spark-jenkins/job/rapids_databricks_nightly-dev-github/958/console):
```
01:49:20  [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:70: object GpuMapInPandasExecMeta is not a member of package org.apache.spark.sql.rapids.shims
01:49:20  [ERROR] import org.apache.spark.sql.rapids.shims.{GpuAscii, GpuMapInPandasExecMeta, GpuTimeAdd}
01:49:20  [ERROR]        ^
01:49:22  [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:4356: not found: type GpuMapInPandasExecMeta
01:49:22  [ERROR]       (mapPy, conf, p, r) => new GpuMapInPandasExecMeta(mapPy, conf, p, r)),
01:49:22  [ERROR]                                  ^
01:49:23  [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:70: Unused import
01:49:23  [ERROR] import org.apache.spark.sql.rapids.shims.{GpuAscii, GpuMapInPandasExecMeta, GpuTimeAdd}
01:49:23  [ERROR]                                                     ^
01:49:25  + SPARK_PLUGIN_JAR_VERSION=24.04.0-SNAPSHOT
01:49:25  ++ mvn -Dmaven.wagon.http.retryHandler.count=3 help:evaluate -q -pl dist -Dexpression=scala.binary.version -DforceStdout
01:49:26  + SCALA_VERSION=2.12
01:49:26  ++ mvn -Dmaven.wagon.http.retryHandler.count=3 help:evaluate -q -pl dist -Dexpression=cuda.version -DforceStdout
01:49:26  [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:70: object GpuMapInPandasExecMeta is not a member of package org.apache.spark.sql.rapids.shims
01:49:26  [ERROR] import org.apache.spark.sql.rapids.shims.{GpuAscii, GpuMapInPandasExecMeta, GpuTimeAdd}
01:49:26  [ERROR]        ^
01:49:27  + CUDA_VERSION=cuda11
01:49:27  + RAPIDS_BUILT_JAR=rapids-4-spark_2.12-24.04.0-SNAPSHOT.jar
01:49:27  + SKIP_DEP_INSTALL=0
01:49:27  + export M2DIR=/home/ubuntu/.m2/repository
01:49:27  + M2DIR=/home/ubuntu/.m2/repository
01:49:27  + WITH_DEFAULT_UPSTREAM_SHIM=1
01:49:27  + printf '+ %*s +\n' 100 ''
01:49:27  + tr ' ' =
```
Seems to be an issue with shimming.

### PR DESCRIPTION
**Pull request by wbo4958**
Fixes #10359.

This reverts commit 6723a68705188c5a743339780658fc4dafca3969, which seems to have caused a compile error on Databricks:
```
01:49:20  [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:70: object GpuMapInPandasExecMeta is not a member of package org.apache.spark.sql.rapids.shims
01:49:20  [ERROR] import org.apache.spark.sql.rapids.shims.{GpuAscii, GpuMapInPandasExecMeta, GpuTimeAdd}
01:49:20  [ERROR]        ^
01:49:22  [ERROR] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:4356: not found: type GpuMapInPandasExecMeta
01:49:22  [ERROR]       (mapPy, conf, p, r) => new GpuMapInPandasExecMeta(mapPy, conf, p, r)),
```

### CODE REVIEW

**Review by GaryShen2008 — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by mythrocks** [comment]
Pardon me, I've taken the liberty to add some context to the description.

**Review by jlowe — APPROVED** [review]

**Comment by wbo4958** [comment]
Hi @jlowe, I got the info from @GaryShen2008 that 24.02 branch was burned down, so I reverted this PR in 24.02 and will merge it in 24.04. Sorry for the trouble.

**Comment by sameerz** [comment]
@wbo4958 do we need to reopen the original issue https://github.com/NVIDIA/spark-rapids/issues/10344 and retarget it to 24.04?

**Comment by wbo4958** [comment]
> @wbo4958 do we need to reopen the original issue #10344 and retarget it to 24.04?

Yeah, I've just opened it.

**Pull request merged**
