### PR TITLE
Add integration test for RLike with embedded null in input

### PR DESCRIPTION
**Pull request by andygrove**
Signed-off-by: Andy Grove <andygrove@nvidia.com>

Depends on https://github.com/rapidsai/cudf/pull/9470.

This adds an integration test related to https://github.com/NVIDIA/spark-rapids/issues/3797 and updates documentation.

### CODE REVIEW

**Review by jlowe — DISMISSED** [review]

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by andygrove** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by andygrove** [comment]
`test_rlike_null_pattern` fails in CI but works locally (against Spark 3.0.1 in both cases).

CI failure:

```
                   py4j.protocol.Py4JJavaError: An error occurred while calling z:com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.assertDidFallBack.^[[0m
                   : java.lang.AssertionError: assertion failed: Could not find RLike in the GPU plan^[[0m
                   GpuColumnarToRow false^[[0m
                   +- GpuProject [a#336606 gpurlike a^@ AS a RLIKE a^@#336608]^[[0m
                      +- GpuRowToColumnar targetsize(2147483647)^[[0m
                         +- *(1) Scan ExistingRDD[a#336606]^[[0m
```

**Comment by andygrove** [comment]
build

**Pull request merged**
