### PR TITLE
Revert "Add in support for lists in some joins (#2702)"

### PR DESCRIPTION
**Pull request by abellina**
This reverts commit 44a48ca08c1eecf6280fa0d8b83fdc55b0d48e6c. 

Signed-off-by: Alessandro Bellina <abellina@nvidia.com>

Due to #2723, we'd like to revert this change while we investigate a solution.

### CODE REVIEW

**Comment by abellina** [comment]
build

**Review by jlowe — COMMENTED** [review]
Revert looks OK, but is there a followup issue against 21.08 to track restoring this functionality?

**Comment by abellina** [comment]
#2723 is the issue tracking it from our side. I was thinking the cudf issue can be filed once we have a repro.

**Comment by jlowe** [comment]
> #2723 is the issue tracking it from our side.

I saw #2723 mostly as tracking the original bug which doesn't necessarily require restoring this revert in order to declare it "fixed," especially if it ends up just being delegated to a cudf issue.  I'm OK with #2723 being the tracking issue as long as it's clear in that issue that it must not be considered closed until the functionality being reverted here is restored.

**Comment by abellina** [comment]
Ok I see what you mean. I'll make it clear in the issue to re-add Bobby's code. It seems like it is the passing criteria for #2723, that the added types and tests pass.

**Review by jlowe — APPROVED** [review]

**Review by revans2 — APPROVED** [review]

**Pull request merged**
