### PR TITLE
Prepare for v0.2.0 release

### PR DESCRIPTION
**Pull request by NvTimLiu**
1, Merge source code from branch branch-0.2 to main

2, Change version from 0.2.0-SNAPSHOT to 0.2.0

3, Change Jenkins scripts for the release pipeline.

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by NvTimLiu** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Review by tgravescs — APPROVED** [review]
looked through poms and Jenkins file looks ok

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
