### PR TITLE
Update gh-pages for 21.08 release

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: Yuan Li yuali@nvidia.com

Update gh-pages for 21.08 release  #3030

### CODE REVIEW

**Comment by nvliyuan** [comment]
Update all documents except "download.md", maybe @viadea and @karthikeyan can help me to check the "Release Notes" details of 21.08

**Review by sameerz — CHANGES_REQUESTED** [review]
Needs updates from PR #3080.

**Comment by nvliyuan** [comment]
> Needs updates from PR #3080.

done

**Comment by nvliyuan** [comment]
@sameerz @viadea @GaryShen2008 I just finish the document update, could you please help review the pull request?

**Review by jlowe — COMMENTED** [review]
Interestingly this looks like it has been interactively edited rather than simply cherry-picked from branch-21.08.  There's a number of whitespace changes and other tweaks that I would expect to have come from the original 21.08 source rather than edited here.  Otherwise the docs on branch-21.08 are missing those changes, and if someone views the docs on that branch directly rather than via gh-pages they will be missing those changes.

**Comment by jlowe** [comment]
> this looks like it has been interactively edited

For reference, I am performing a simple diff of the docs between branch-21.08 and this PR to see this, e.g.:
```
$ cd src/spark-rapids
$ git fetch https://github.com/nvliyuan/spark-rapids.git gh-pages-branch-21.08
$ git diff branch-21.08 FETCH_HEAD docs
```

There should not be very many diffs remaining, mostly around changes for Jekyll.

**Comment by nvliyuan** [comment]
@jlowe yes, many of the diffs have been interactively edited. Because there are some files such as supported_ops.md which has so many diffs and it would be better to copy the file. And when I paste the code it was reformated by my IDE, so you see some whitespace. Please refer to this [pr](https://github.com/NVIDIA/spark-rapids/pull/3233/) which most of the files were updated by cherry-picked. I will close this one.

**Pull request closed without merging**
