### PR TITLE
Make serialization key checks uniform for Hive Text file read/write.

### PR DESCRIPTION
**Pull request by mythrocks**
This is a minor change, to bring the serialization format checks on the Read and Write sides of Hive text files in line with each other.

The read side would check if the serialization-key is set to empty (""): https://github.com/NVIDIA/spark-rapids/blob/aa2da410511d8a737e207257769ec662a79174fe/sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala#L155-L161

The write side was checking for the expected default: "1": https://github.com/NVIDIA/spark-rapids/blob/aa2da410511d8a737e207257769ec662a79174fe/sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/GpuHiveFileFormat.scala#L130-L136

This caused confusion in behaviour, as voiced in https://github.com/NVIDIA/spark-rapids/issues/11803.

The change in this commit makes the checks uniformly conservative.

### CODE REVIEW

**Comment by mythrocks** [comment]
Build

**Review by revans2 — APPROVED** [review]
Do you know if this fixes https://github.com/NVIDIA/spark-rapids/issues/11803?

**Comment by mythrocks** [comment]
> Do you know if this fixes #11803?

I'm afraid this doesn't fix #11803. :/  That error is on the read path, while this fix affects (only the defaults in) the write path.

**Comment by mythrocks** [comment]
Looks like I spoke too soon about making these checks the same.  Debugging now.

**Comment by mythrocks** [comment]
I've had to add an xfail case for 3.2, where creating a table via CTAS doesn't not seem to set the "serialization.format" key in the storage properties.  That bug seems to have been fixed in subsequent Spark versions.  

Note that this is only in the test setup.

**Comment by mythrocks** [comment]
Build

**Comment by mythrocks** [comment]
It now looks like there is no guarantee of `serialization.format` being set correctly, when constructed via CTAS.  The CI failure seems to be with Spark 3.3.0.  I was also able to repro this from 3.3.4.  

I'll look into setting this programmatically.

**Comment by mythrocks** [comment]
I have documented the need for the different settings over at https://github.com/NVIDIA/spark-rapids/pull/11856.

**Pull request closed without merging**
