### PR TITLE
[window] Add GpuWindowExec requiredChildOrdering

### LINKED ISSUE #486: [BUG] GpuWindowExec does not implement requiredChildOrdering
@nartal1 reports on #388 that `GpuWindowExec` does not accept the `partitionSpec` or `orderSpec` in its constructor.
As explained in [a comment in #388](https://github.com/NVIDIA/spark-rapids/issues/388#issuecomment-666594661), the partition/ordering information is not lost; it is retrieved and processed in `GpuWindowExpression`.

`WindowExec` uses `partitionSpec`/`orderSpec` to implement `WindowExec::requiredChildOrdering()`. We should add back `partitionSpec` and `orderSpec` to the `GpuWindowExec` constructor, to do the same, just in case the ordering is required elsewhere.

### PR DESCRIPTION
**Pull request by mythrocks**
Closes #486.

WindowExec has checks for child ordering and distribution.
This commit adds requiredChildOrdering and requiredChildDistribution
to GpuWindowExec.

Signed-off-by: Mithun RK <mythrocks@gmail.com>

### CODE REVIEW

**Review by andygrove — DISMISSED** [review]
LGTM based on comparing to the Spark source code. This seems consistent.

**Comment by kuhushukla** [comment]
The changes LGTM! Curious if there is a way to test this change?

**Comment by mythrocks** [comment]
> Curious if there is a way to test this change? 

Haven't a Scooby Doo, truth be told. :] This change is to assuage concerns that our Exec doesn't share the signature/preconditions of `WindowExec`. Doesn't seem to affect query behaviour, in my limited testing. 

As an aside, there's one more change coming to this PR.

**Comment by revans2** [comment]
The main reason to do this is for the optimizations that we have where we could remove a sort, like with operations where we can do a hash aggregate instead of a sort aggregate or where we might replace a sort-merge join with a hash based join.

In those cases the output of the join/aggregate operation will not match with how the plan was originally setup, and if spark optimized out a sort, because it was relying on the output of one of the operators already being sorted, then without this patch we will not add it back in properly.

I don't know how often in the real world this would happen, but it is a possibility.

**Comment by mythrocks** [comment]
P.S I can look into concocting a test. This change declares what the expected ordering of its inputs are. So this is an assertion check against losing that ordering.

**Comment by mythrocks** [comment]
Hey, thanks Bobby. (Missed your reply.)

Thanks for confirming. Based on how we're currently replacing ops/execs, I think we might not run into that scenario (of losing the ordering). Unless AQE changes things in some way.

**Comment by kuhushukla** [comment]
Makes sense, we have such code in Partitioning and other places too but I was mainly curious what this would really change as far as functionality goes, so thanks for the explanation Bobby, Mithun. :)

**Comment by mythrocks** [comment]
> As an aside, there's one more change coming to this PR.

Chaps, apologies for the churn on this PR. I intended to push a workaround for #218 to this PR. It slipped my mind that we will be squashing commits.

I will raise a separate PR to address #218 for the `0.2` release.

**Review by kuhushukla — APPROVED** [review]

**Comment by tgravescs** [comment]
seems fine, I do worry a little about the Databricks code since we had different output columns there. I would think this is ok since its basically just a pass through.

**Comment by mythrocks** [comment]
> I do worry a little about the Databricks code since we had different output columns there.

Yeah, I did consider that. I think we should be in the clear, since this is the input ordering.

**Comment by mythrocks** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by mythrocks** [comment]
Thanks for the reviews, @andygrove, @kuhushukla, @revans2, @tgravescs!

**Pull request merged**
