### PR TITLE
Update cudf dependency to 0.16-SNAPSHOT

### PR DESCRIPTION
**Pull request by jlowe**
This updates the cudf dependency to 0.16-SNAPSHOT.

Marking this as a draft for now, as it appears somehow the libcudf.so in the current cudf-0.16-SNAPSHOT says it requires librmm.so which fails the build because the jar does not contain librmm.so.  Investigating.

### CODE REVIEW

**Review by revans2 — DISMISSED** [review]

**Comment by jlowe** [comment]
The librmm.so issue with cudf-0.16-SNAPSHOT has been resolved, this should be ready to go.

**Comment by jlowe** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by jlowe** [comment]
Waiting on https://github.com/rapidsai/cudf/pull/6215 to cleanup the `rmm_log.txt` files that are failing the CI build.

**Review by revans2 — DISMISSED** [review]

**Comment by jlowe** [comment]
It might take a while to get the `rmm_log.txt` issue fully resolved, so for now I excluded it from the rat checks.  If this is acceptable as a short-term solution, I'll file a followup issue to have it removed when cudf is no longer emitting this file by default.

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Pull request merged**
