### PR TITLE
Update `test_add_overflow_with_ansi_enabled` and `test_subtraction_overflow_with_ansi_enabled` to check the exception type for Integral case.

### PR DESCRIPTION
**Pull request by HaoYang670**
Signed-off-by: remzi <13716567376yh@gmail.com>
This a subtask of #5196.

# Changes in this PR.
Update `test_add_overflow_with_ansi_enabled` and `test_subtraction_overflow_with_ansi_enabled` to check the type of exception thrown.
Please note that we only update the `IntegralType` case and **don't** modify the `DecimalType` case, because it is difficult to get a Spark's `Decimal` from a cuDF's `ColumnView`, which makes it hard to use the `RapidsErrorUtil.cannotChangeDecimalPrecisionError`: https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala#L1501-L1516

### CODE REVIEW

**Comment by HaoYang670** [comment]
build

**Comment by jlowe** [comment]
> Please note that we only update the IntegralType case and don't modify the DecimalType case, because it is difficult to get a Spark's Decimal from a cuDF's ColumnView, which makes it hard to use the RapidsErrorUtil.cannotChangeDecimalPrecisionError:

Why are we trying to get the Spark type from the cudf type?  We know both the Spark type of the input and the Spark type of the output from the query plan.  We may not know it in `fixDecimalBounds` given its limited parameters, but the code that eventually calls that method knows the input and output decimal types.

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
Hiccup on the artifact server, kicking the build again

**Comment by jlowe** [comment]
build

**Comment by HaoYang670** [comment]
> We may not know it in fixDecimalBounds given its limited parameters, but the code that eventually calls that method knows the input and output decimal types.

The `fixDecimalBounds` method is called from here: https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/decimalExpressions.scala#L45-L60. 
If we want to get the decimal value, we should also pass `input` to the `GpuCast.checkNFixDecimalBounds`. Otherwise, we have to rebuild the `GpuColumnVector` from `ColumnView` in `fixDecimalBounds`, which is difficult.

As this would cause API changes or maybe more memory allocation, I'm not sure whether this is worth to do when our target is just to match the error message with Spark's.

**Comment by tgravescs** [comment]
build

**Comment by HaoYang670** [comment]
> We may not know it in fixDecimalBounds given its limited parameters, but the code that eventually calls that method knows the input and output decimal types.

Hi @jlowe, according to your comments, what I am trying to do is add the original Spark column as another parameter of `checkNFixDecimalBounds`, like this:
```scala
  def checkNFixDecimalBounds(
      sparkInput: GpuColumnVector,
      input: ColumnView,
      to: DecimalType,
      ansiMode: Boolean): ColumnVector = {
    assert(input.getType.isDecimalType)
    withResource(DecimalUtil.outOfBounds(input, to)) { outOfBounds =>
      fixDecimalBounds(sparkInput, input, outOfBounds, ansiMode)
    }
  }
```
Then, we can get the Spark decimal type.

However, it will cause some API changes in the `GpuDecimalSum`, which will change other APIs ... I'm not sure whether we should do it. Or is there another way for us to get the Spark decimal value from a column?

**Review by jlowe — APPROVED** [review]
> If we want to get the decimal value, we should also pass input to the GpuCast.checkNFixDecimalBounds.

Yep, that or separately pass the input `DataType`.  Either works.

> As this would cause API changes or maybe more memory allocation

We own the APIs in question (they are internal, not public), so this would not be a major change.  There's no additional memory allocation involved to pass an existing object instance to a method, not sure what you're getting at there?  

Determining the input datatype takes no additional memory, but besides the datatype we would need to extract a specific, offending value from the input to call `cannotChangeDecimalPrecisionError` which does require additional GPU processing and memory.  As such I'm fine with this just matching the base exception type for now.  We can put in the effort to extract a value in a followup PR if deemed necessary.

**Pull request merged**
