### PR TITLE
[Doc]revert the changes in FAQ for deltalake table support[skip ci]

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>

revert the changes in FAQ for deltalake table support

### CODE REVIEW

**Review by jlowe — DISMISSED** [review]
This looks OK to me, although not sure it's worth respinning 22.12 for this small doc change.

**Comment by sameerz** [comment]
@nvliyuan Let's retarget this to 23.02.

**Comment by nvliyuan** [comment]
> @nvliyuan Let's retarget this to 23.02.

updated

**Review by jlowe — APPROVED** [review]

**Comment by nvliyuan** [comment]
build

**Pull request merged**
