### PR TITLE
Fix some 21.12 branch related doc issues on gh-pages branch.[skip ci]

### PR DESCRIPTION
**Pull request by viadea**
Signed-off-by: Hao Zhu <hazhu@nvidia.com>

Fix some 21.12 branch related doc issues on gh-pages branch.[skip cli]

@nvliyuan please file a separate PR to fix 21.12 branch's docs for the same things when we need to update for cuDF 21.12.1 hotfix jar at that time.

### CODE REVIEW

**Comment by jlowe** [comment]
We should be updating branch-21.12 _first_ then cherry-picking the change to gh-pages, not the other way around.

**Comment by viadea** [comment]
> We should be updating branch-21.12 _first_ then cherry-picking the change to gh-pages, not the other way around.

Agree. This is a miss for sure. 
We need to fix 21.12 branch later.

**Comment by jlowe** [comment]
> We need to fix 21.12 branch later.

Why not fix it now then cherry-pick?  What's the reason to circumvent the normal process here?

**Comment by viadea** [comment]
> 

I thought we can not change 21.12 branch , can we? if yes, then i can update the samething on 21.12 branch

**Comment by sameerz** [comment]
I think it is ok to make the documentation fixes on 21.12 while it is open.  We can make the change there first, then push the change to gh-pages and 22.02.  Once 21.12 closes we will not make further changes on that branch even for documentation fixes.

**Comment by jlowe** [comment]
> push the change to gh-pages and 22.02. 

Note that the changes should try to auto-merge to branch-22.02 once we commit to branch-21.12, just like any other branch-21.12 change.

**Comment by viadea** [comment]
@jlowe  @sameerz 
https://github.com/NVIDIA/spark-rapids/pull/4367 is submitted to update 21.12 branch. 

@nvliyuan

**Review by sameerz — APPROVED** [review]

**Pull request merged**
