### PR TITLE
Fix issues with cached partitions not matching

### LINKED ISSUE #1885: [BUG] natural join on string key results in a data frame with spurious NULLs
**Describe the bug**

I have a data frame SRC that is backed by a Parquet file, and two data frames AGG1 and AGG2 that have the same set of values for a key column but different columns for the remaining columns (these column values come from performing different aggregates on SRC).  When I perform a natural join on AGG1 and AGG2, generating a new data frame JOINED, the result appears as I would expect it to:  one record for each key value, with the union of the columns of AGG1 and AGG2.  Furthermore, filtering JOINED with `isnull` or `isnan` on each column reveals no null or NaN values in any column.  However, when running on GPU (but not CPU):

1. `JOINED.dropna().count()` is approximately 0.05% of `JOINED.count()`
2. using `JOINED` on the left side of another join results in NULLs for the columns in `JOINED` in the output frame

Relevant query plans for the input relations are [here](https://gist.github.com/willb/713a10abe6df1accbec53503f46e462f) and an example REPL session exhibiting this behavior is [here](https://gist.github.com/willb/91d5bc8dfc112200885a61bbf87631b5).

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

1. run `spark-submit --driver-memory 16G generate.py` from [this repo](https://github.com/willb/telco-churn-augmentation)
2. submit [this reproducer script](https://gist.github.com/willb/f63bed40752cd75d27da203d8ba8fdcc) to Spark with and without the GPU plugin loaded (or run the linked notebook).

**Expected behavior**

The output should show that `customer_charges` had no records with NULL values whether running on CPU or GPU.

**Environment details (please complete the following information)**

This requires no special Spark configuration.  I've reproduced it with a local master running under Docker with at least the following configurations:

- rapids-4-spark 0.2.0, cudf 0.15, cuda 10.1
- rapids-4-spark 0.3.0, cudf 0.17, cuda 11
- rapids-4-spark 0.4.0, cudf 0.18, cuda 11

**Additional context**

### PR DESCRIPTION
**Pull request by revans2**
This fixes #1885 

This is a rather large and comprehensive change for this late in the 0.4 release cycle. Please help test this as much as possible I am going to do the same on my end.

### CODE REVIEW

**Comment by revans2** [comment]
build

**Comment by revans2** [comment]
I ran tests on 3.0.2, but I am seeing some tests fail on 3.1.1. I am going to start digging into those.

**Comment by revans2** [comment]
This is not going to work. AQE makes it so it is impossible to do what we want to try with this.

**Review by jlowe — COMMENTED** [review]
Filing these in case this gets reopened.

**Pull request closed without merging**
