### PR TITLE
MVN_OPT to last, as it is empty in most cases [databricks]

### PR DESCRIPTION
**Pull request by NvTimLiu**
MVN_OPT to last, as it is empty in most cases 

Signed-off-by: Tim Liu <timl@nvidia.com>

### CODE REVIEW

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]
LGTM to unblock nightly and premerge for databricks.

Please also have a ticket to follow up clean jenkinsfile and rename the `build_profiles` param, thanks!

**Review by pxLi — CHANGES_REQUESTED** [review]
need to comment out `-b` to pass premerge CI as jenkinsfile in this PR won't take effect

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]

**Comment by pxLi** [comment]
Passed build stages. Going to force merge this one to unblock CIs.

@NvTimLiu Please help create a follow up PR to refactor param to support mvn_opt in databricks env, thanks!

**Comment by NvTimLiu** [comment]
Related issue: https://github.com/NVIDIA/spark-rapids/issues/5535

**Pull request merged**
