### PR TITLE
WIP: Add new regexp fuzz tests that run with unicode input

### PR DESCRIPTION
**Pull request by andygrove**
Related issue: https://github.com/NVIDIA/spark-rapids/issues/5549

These are new tests that I would like to add but they are failing in CI for some reason and I am trying to debug why.

### CODE REVIEW

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
build

**Comment by andygrove** [comment]
CI fails with:

```
javaPattern[1]=\z\u20282, cudfPattern=$\u20282, input='????', cpu=????, gpu=???????????? (RegularExpressionTranspilerSuite.scala:728)
```

Running the same test locally, I see:

```
javaPattern[1]=\z\u20282, cudfPattern=$\u20282, input='鈻瑜㶯眀', cpu=鈻瑜㶯眀, gpu=鈻瑜㶯眀
```

**Comment by anthony-chang** [comment]
Also related to issue #5521

**Comment by andygrove** [comment]
build

**Pull request closed without merging**
