### PR TITLE
update changelog 0.4.1 [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
update changelog to 0.4.1

`GITHUB_TOKEN=xxx  scripts/generate-changelog --releases=0.1,0.2,0.3,0.4,0.4.1`

### CODE REVIEW

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
I will update this one if  https://github.com/NVIDIA/spark-rapids/issues/1985 passed Integration tests

**Review by NvTimLiu — DISMISSED** [review]

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
build

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
