### PR TITLE
Fix issue in GpuArrayExists where a parent view outlived the child

### PR DESCRIPTION
**Pull request by abellina**
Signed-off-by: Alessandro Bellina <abellina@nvidia.com>

Closes https://github.com/NVIDIA/spark-rapids/issues/5183.

This fixes a subtle bug with `GpuArrayExists.legacyExists` that manifests itself with the CUDA async allocator, but is not caused by it.

In the old code, `noNullsChildView` was closed when `replaceChildNullsByFalseView` returned, and it was assumed to be a valid child in the calling code (`legacyExists`). I changed it so this child view is alive and well while we call `existsReduce`.

Note this seems to me like a bug that exists in 22.04 also.

### CODE REVIEW

**Comment by abellina** [comment]
@tgravescs @sameerz @jlowe fyi it wasn't a cuDF bug as I originally thought. Should we backport this to 22.04?

**Comment by abellina** [comment]
build

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Review by gerashegalov — APPROVED** [review]
The change LGTM. 

As for 22.04 it is not a high priority because the call path is off by default on Spark 3.x. But so is the fix is also very localized to this call path, thus it's a strict improvement without risking to break anything that was not broken before.

**Pull request merged**
