### PR TITLE
Verify CPU fallback class when creating HIVE table [Databricks]

### LINKED ISSUE #8017: [BUG]Spark-3.4 Integration tests failure  due to InsertIntoHadoopFsRelationCommand not running on GPU
**Describe the bug**
Some of the integration tests are failing due to different reasons in InsertIntoHadoopFsRelationCommand. Posting the errors below:

#### Group 1
- [x] test_optimized_hive_bucketed_fallback
- [ ] test_write_hive_bucketed_table_fallback
```
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  !Output <InsertIntoHadoopFsRelationCommand> cannot run on GPU because bucketing is not supported
  !Exec <WriteFilesExec> cannot run on GPU because WriteFilesExec can't run on GPU because parent can't run on GPU
```

#### Group 2
- [x] test_optimized_hive_ctas_configs_fallback
```
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  !Output <InsertIntoHadoopFsRelationCommand> cannot run on GPU because LEGACY rebase mode for dates and timestamps is not supported; LEGACY rebase mode for int96 timestamps is not supported
  !Exec <WriteFilesExec> cannot run on GPU because WriteFilesExec can't run on GPU because parent can't run on GPU
```

#### Group 3
- [ ] test_orc_write_bloom_filter_sql_cpu_fallback
- [ ] test_orc_write_bloom_filter_with_options_cpu_fallback
```
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  !Output <InsertIntoHadoopFsRelationCommand> cannot run on GPU because Bloom filter write for ORC is not yet supported on GPU. If bloom filter is not required, unset "orc.bloom.filter.columns"
  !Exec <WriteFilesExec> cannot run on GPU because WriteFilesExec can't run on GPU because parent can't run on GPU
```

#### Group 4
- [ ] test_parquet_write_bloom_filter_sql_cpu_fallback
- [ ] test_parquet_write_bloom_filter_with_options_cpu_fallback
```
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  !Output <InsertIntoHadoopFsRelationCommand> cannot run on GPU because Bloom filter write for Parquet is not yet supported on GPU. If bloom filter is not required, unset parquet.bloom.filter.enabled#id
  !Exec <WriteFilesExec> cannot run on GPU because WriteFilesExec can't run on GPU because parent can't run on GPU
```

#### Group 5
- [x] test_optimized_hive_ctas_options_fallback
- [ ] test_parquet_write_encryption_hadoopconfig_fallback
- [ ] test_parquet_write_encryption_runtimeconfig_fallback
```
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  !Output <InsertIntoHadoopFsRelationCommand> cannot run on GPU because Encryption is not yet supported on GPU. If encrypted Parquet writes are not required unset the "parquet.encryption.column.keys" and "parquet.encryption.footer.key" in Parquet options
  !Exec <WriteFilesExec> cannot run on GPU because WriteFilesExec can't run on GPU because parent can't run on GPU
```

**Steps/Code to reproduce bug**
Run integration tests for failing tests
cd  spark-rapids/integration_tests/
`./run_pyspark_from_build.sh -k <name of test>`       `//Example : ./run_pyspark_from_build.sh -k test_optimized_hive_ctas_options_fallback`

**Expected behavior**
1. Tests should pass OR 
2. XFAIL the test or fallback to CPU if there is a valid reason.

**Environment details (please complete the following information)**
local

### PR DESCRIPTION
**Pull request by razajafri**
This PR checks the appropriate fallback class for Spark 3.4 when creating a Hive table.

In Spark 3.4, the CTAS is being converted to an `ExecutedCommandExec` instead of the `DataWritingCommandExec`

fixes #8017

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Review by andygrove — APPROVED** [review]

**Comment by andygrove** [comment]
build

**Comment by gerashegalov** [comment]
@andygrove et all, databricks build is broken
```
https://github.com/NVIDIA/spark-rapids/actions/runs/4757833924/jobs/8455139615#step:2:4386
```

**Comment by andygrove** [comment]
> @andygrove et all, databricks build is broken https://github.com/NVIDIA/spark-rapids/actions/runs/4757833924/jobs/8455139615#step:2:4386
> 
> ```
> Error: 4-20T18:50:30.526Z] [ERROR] import org.apache.spark.sql.catalyst.expressions.{AnsiCast, Cast, Expression}
> Error: 4-20T18:50:30.526Z] [ERROR]        ^
> ```

I am working on this now - https://github.com/NVIDIA/spark-rapids/issues/8164

**Comment by razajafri** [comment]
build

**Review by NVnavkumar — APPROVED** [review]
LGTM

**Review by gerashegalov — APPROVED** [review]

**Comment by razajafri** [comment]
build

**Pull request merged**
