### PR TITLE
Removed the redundant test for element_at and fixed the failing one [databricks]

### PR DESCRIPTION
**Pull request by razajafri**
Test for `element_at` was added erroneously as part of #4464. 

This PR removes that test and fixes the original test. 

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Review by jlowe — DISMISSED** [review]

**Comment by jlowe** [comment]
build

**Comment by razajafri** [comment]
CI failed due to OOM Exception

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
This time I think the DB instance reached the idle timeout 
`[2022-01-13T03:30:07.202Z] ../../src/main/python/cache_test.py::test_cache_partial_load[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}-Array(String)][ALLOW_NON_GPU(CollectLimitExec)] Connection to 52.183.91.187 closed by remote host.`

**Review by jlowe — APPROVED** [review]

**Comment by jlowe** [comment]
build

**Comment by razajafri** [comment]
build

**Pull request merged**
