### PR TITLE
Merge remote-tracking branch 'origin/branch-21.08' into main [skip ci]

### PR DESCRIPTION
**Pull request by NvTimLiu**
Merge remote-tracking branch 'origin/branch-21.08' into main for spark-rapids-tools v21.08.1 release

Note: need to merge with a pull request

### CODE REVIEW

**Review by GaryShen2008 — APPROVED** [review]

**Comment by NvTimLiu** [comment]
build

**Review by pxLi — APPROVED** [review]
NOTE: this must be merged as a merge commit

**Comment by NvTimLiu** [comment]
Local build PASS

```
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /home/timl/work.d/spark-rapids/tools/target/rapids-4-spark-tools_2.12-21.08.1.jar with /home/timl/work.d/spark-rapids/tools/target/rapids-4-spark-tools_2.12-21.08.1-shaded.jar
[INFO]
[INFO] --- maven-jar-plugin:3.2.0:test-jar (default) @ rapids-4-spark-tools_2.12 ---
[INFO] Building jar: /home/timl/work.d/spark-rapids/tools/target/rapids-4-spark-tools_2.12-21.08.1-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] RAPIDS Accelerator for Apache Spark Root Project ... SUCCESS [  0.750 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin ..... SUCCESS [ 36.390 s]
[INFO] RAPIDS Accelerator for Apache Spark Shuffle Plugin . SUCCESS [  6.664 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Shims SUCCESS [  0.078 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.1 Shim SUCCESS [  7.163 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.1 EMR Shim SUCCESS [  3.059 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.2 Shim SUCCESS [  3.049 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.3 Shim SUCCESS [  3.703 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.1 Shim SUCCESS [  8.664 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.2 Shim SUCCESS [  3.182 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.1 Cloudera Shim SUCCESS [  4.919 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.4 Shim SUCCESS [  3.071 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.3 Shim SUCCESS [  3.182 s]
[INFO] RAPIDS Accelerator for Apache Spark SQL Plugin Shim Aggregator SUCCESS [  0.053 s]
[INFO] RAPIDS Accelerator for Apache Spark Scala UDF Plugin SUCCESS [ 20.603 s]
[INFO] RAPIDS Accelerator for Apache Spark Distribution ... SUCCESS [ 11.918 s]
[INFO] rapids-4-spark-api-validation ...................... SUCCESS [  4.140 s]
[INFO] RAPIDS Accelerator for Apache Spark UDF Examples ... SUCCESS [  3.774 s]
[INFO] RAPIDS Accelerator for Apache Spark Tests .......... SUCCESS [ 22.365 s]
[INFO] rapids-4-spark-integration-tests_2.12 .............. SUCCESS [ 20.075 s]
[INFO] RAPIDS Accelerator for Apache Spark tools .......... SUCCESS [ 45.957 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:33 min
[INFO] Finished at: 2021-08-31T03:55:18+00:00
[INFO] Final Memory: 216M/10546M
[INFO] ------------------------------------------------------------------------
```

**Comment by pxLi** [comment]
build

**Pull request merged**
