### PR TITLE
Fix match error in RapidsShuffleIterator.scala [scala2.13]

### PR DESCRIPTION
**Pull request by xieshuaihu**
Fix [issue-11103](https://github.com/NVIDIA/spark-rapids/issues/11103)

In scala2.13, `scala.collection.Seq` is not same with `Seq` which is `scala.collection.immutable.Seq`, so the former couldn't match the latter.

### CODE REVIEW

**Comment by xieshuaihu** [comment]
@abellina

**Review by abellina — DISMISSED** [review]
thanks for your patch @xieshuaihu !!

**Comment by abellina** [comment]
build

**Comment by pxLi** [comment]
@xieshuaihu `main` branch is our release branch, 
can you help rebase to our current development branch `branch-24.08`? thanks

**Comment by xieshuaihu** [comment]
@pxLi @abellina 
there are too many conflicts, i will create a new pr. Sorry...

**Comment by abellina** [comment]
oh woops, I didn't notice this was against main over the weekend. Thanks @pxLi

**Comment by sameerz** [comment]
One more note, please sign the commit per the contributing guide: https://github.com/NVIDIA/spark-rapids/blob/branch-24.08/CONTRIBUTING.md#sign-your-work

Regards,
Sameer

**Comment by abellina** [comment]
@sameerz here's the commit with sign off that went into branch-24.08 (https://github.com/NVIDIA/spark-rapids/pull/11115/commits/bad1a1f583137182c326faafb181bde9e6ada5db).

**Pull request closed without merging**
