### PR TITLE
README.md for auditing purposes [skip ci]

### PR DESCRIPTION
**Pull request by razajafri**
Added a README.md file which may help people with auditing commits

Signed-off-by: Raza Jafri <rjafri@nvidia.com>

### CODE REVIEW

**Review by revans2 — APPROVED** [review]

**Comment by razajafri** [comment]
build

**Comment by razajafri** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by pxLi** [comment]
adjust title [skip-ci] to [skip ci] to take effect, if require more available phrase to be added, could modify this directly https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/jenkins/Jenkinsfile-blossom.premerge#L153

**Pull request merged**
