### PR TITLE
Replicate HostColumnVector.ColumnBuilder in plugin to enable host memory oom work

### PR DESCRIPTION
**Pull request by jbrennan333**
To help enable work on host memory oom handling in `GpuRowToColumnarIterator` for feature #8887, this patch makes a copy of the `HostColumnVector.ColumnBuilder` class in the plugin and replaces plugin uses of `ColumnBuilder` with the new class `RapidsHostColumnBuilder`.

I am putting this up as a draft to get feedback and consider whether we want to put this change in, or hold off until the rest of the work on `GpuRowToColumnarIterator` is completed.

### CODE REVIEW

**Comment by jbrennan333** [comment]
build

**Comment by jbrennan333** [comment]
build

**Comment by jbrennan333** [comment]
RapidsHostColumnBuilder currently has copies of these cudf methods: `BitVectorHelper.setNullAt` and `HostColumnVectorCore.convertDecimal128FromJavaToCudf`.
If desired, I can make changes in cudf to make these accessible from the plugin.

**Comment by jlowe** [comment]
pacakge-tests-scala213 (350,false) failure is unrelated, should be fixed by #10521.

**Review by revans2 — APPROVED** [review]

**Review by abellina — APPROVED** [review]

**Pull request merged**
