### PR TITLE
Init changelog of 23.10 [skip ci]

### PR DESCRIPTION
**Pull request by pxLi**
Initiate generated changelog of 23.10 with
```
GITHUB_TOKEN=<PAT> scripts/generate-changelog --releases=23.08,23.10
```

also move 23.06 changelogs to archive as the project has been closed already, we cannot generate based on it

Please help in advance we will do final update before RC build thanks

### CODE REVIEW

**Comment by pxLi** [comment]
@sameerz @mattahrens @GaryShen2008 please help adjust the issues and PRs if needed, I will re-generate after your adjustment later thanks

**Comment by sameerz** [comment]
I updated some issues in the changelog.

**Comment by pxLi** [comment]
re-generated, we will do a final update before the RC build

**Review by NvTimLiu — APPROVED** [review]
LGTM

**Comment by pxLi** [comment]
build

**Pull request merged**
