### PR TITLE
Update 0.2 CHANGELOG

### PR DESCRIPTION
**Pull request by pxLi**
Signed-off-by: Peixin Li <pxli@nyu.edu>

as title

### CODE REVIEW

**Comment by tgravescs** [comment]
there are a few unexpected ones in here, but it looks like it picked up the new ones and the others seem to be in 0.2 so must have missed the first go around?

**Comment by tgravescs** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Review by GaryShen2008 — APPROVED** [review]

**Comment by pxLi** [comment]
> there are a few unexpected ones in here, but it looks like it picked up the new ones and the others seem to be in 0.2 so must have missed the first go around?

@tgravescs they were not missed in last PR, actually these project or label info issued have been just fixed during this week 
e.g.
https://github.com/NVIDIA/spark-rapids/issues/602
image

Added project info like ~1 hour ago

**Comment by tgravescs** [comment]
ah ok that makes sense

**Pull request merged**
