### PR TITLE
closeOnExcept -> withResources in MetaUtils

### PR DESCRIPTION
**Pull request by abellina**
Signed-off-by: Alessandro Bellina <abellina@nvidia.com>

This fixes a leak in MetaUtils. It also replaces the use of `ArrayBuffer` with `Array` such that the appropriate impl of `withResources` is picked.

Thanks to @jlowe to help triage this.

### CODE REVIEW

**Comment by abellina** [comment]
build

**Comment by abellina** [comment]
This is breaking related tests locally and in CI also. I had machine troubles so didn't run the tests beforehand until now. Please hold on reviewing until that is fixed.

**Comment by abellina** [comment]
Ok sorry for the confusion, this one looks better now. Will trigger CI again.

**Comment by abellina** [comment]
build

**Review by revans2 — APPROVED** [review]

**Review by jlowe — APPROVED** [review]

**Pull request merged**
