### PR TITLE
Remove CUDA 10.x from getting started guide [skip ci]

### PR DESCRIPTION
**Pull request by sameerz**
Signed-off-by: Sameer Raheja <sraheja@nvidia.com>

Update docs to point to CUDA 11 download, minor text changes in other parts of getting started guide.

### CODE REVIEW

**Review by viadea — APPROVED** [review]

**Comment by sameerz** [comment]
build

**Comment by pxLi** [comment]
build

**Review by tgravescs — APPROVED** [review]

**Comment by tgravescs** [comment]
@sameerz I missed this, this went into branch-21.08, assume we want 21.06

**Comment by tgravescs** [comment]
pr for 21.06 - https://github.com/NVIDIA/spark-rapids/pull/2687

**Comment by sameerz** [comment]
Yes this should have gone into 21.06, thanks for the catch.

**Pull request merged**
