### PR TITLE
Add filter in query plan for conditional nested loop and cartesian joins

### PR DESCRIPTION
**Pull request by jlowe**
This is the same type of change as in #3089 applied to broadcast nested loop and cartesian joins.  As in the other PR, the join condition parameter was left as a placeholder until the AST joins are leveraged.

### CODE REVIEW

**Comment by jlowe** [comment]
build

**Review by revans2 — APPROVED** [review]

**Comment by revans2** [comment]
The build failure is odd. It looks like a mismatch with cudf because it looks like it crashed/exited on the very first test that touched cudf.

**Comment by jlowe** [comment]
> The build failure is odd.

Agreed.  It looks like cudf somehow is not in the classpath or is missing the properties file?
```
21/07/30 18:10:38.066 ScalaTest-main-running-HashAggregatesSuite ERROR RapidsExecutorPlugin: Exception in the executor plugin
com.nvidia.spark.rapids.CudfVersionMismatchException: Could not find cudf version in rapids4spark-version-info.properties
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.$anonfun$checkCudfVersion$2(Plugin.scala:223)
	at scala.Option.getOrElse(Option.scala:138)
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.checkCudfVersion(Plugin.scala:222)
	at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:190)
	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:111)
[...]
```

**Comment by jlowe** [comment]
build

**Comment by jlowe** [comment]
> It looks like cudf somehow is not in the classpath or is missing the properties file?

Sorry, I misread the stack exception.  This is a case of the _plugin_ properties file being present but somehow not containing the `cudf_version` key.   Very bizarre.

@pxLi it looks like a unit test run and `mvn verify` were running in parallel during the build?  The unit tests require the shaded jar to be built before the tests can run.  I'm not sure if the racing builds could lead to the error I saw above in premerge build #2223, but it seems to have gotten past it in #2224.

**Comment by pxLi** [comment]
> > It looks like cudf somehow is not in the classpath or is missing the properties file?
> 
> Sorry, I misread the stack exception. This is a case of the _plugin_ properties file being present but somehow not containing the `cudf_version` key. Very bizarre.
> 
> @pxLi it looks like a unit test run and `mvn verify` were running in parallel during the build? The unit tests require the shaded jar to be built before the tests can run. I'm not sure if the racing builds could lead to the error I saw above in premerge build 2223, but it seems to have gotten past it in 2224.

hmm, this looks weird. The shaded ja should be built w/ the first mvn test run. 
Also we found some ephemeral NFS issue around that moment. I will keep monitoring this to see if this could occur again

**Comment by jlowe** [comment]
> The shaded ja should be built w/ the first mvn test run.

`mvn test` doesn't produce the shaded jar, you need to run `mvn package` to do that.

**Comment by pxLi** [comment]
> > The shaded ja should be built w/ the first mvn test run.
> 
> `mvn test` doesn't produce the shaded jar, you need to run `mvn package` to do that.

I may misunderstood, the test fail should be related to the blossom NFS issue and SRE is working on fixing it.
CMIW for the shaded jars, looks like our UTs can pass w/o the specific rapids.shade.packages. If this is required, I could enable it before the UT starts

**Pull request merged**
